const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Fade,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Plugins.Mikal_3DObject,
		C3.Behaviors.Physics,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Plugins.AJAX,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Behaviors.YellowAfterlife_FastRadialProgressBar,
		C3.Behaviors.Timer,
		C3.Behaviors.CV_BoundedDragnDrop,
		C3.Behaviors.Anchor,
		C3.Plugins.TiledBg,
		C3.Plugins.Camera3D,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Text.Acts.SetText,
		C3.JavaScriptInEvents.Gamees_Event17_Act1,
		C3.JavaScriptInEvents.Gamees_Event18_Act3,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.System.Exps.regexreplace,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Text.Acts.AddChild,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Acts.RemoveFromParent,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Exps.AnimationSpeed,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.JavaScriptInEvents.Gamees_Event221_Act1,
		C3.JavaScriptInEvents.Gamees_Event223_Act1,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Mikal_3DObject.Cnds.CompareInstanceVar,
		C3.Plugins.Mikal_3DObject.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Mikal_3DObject.Exps.ZElevation,
		C3.Plugins.Mikal_3DObject.Exps.ZAngle,
		C3.JavaScriptInEvents.Gamees_Event232_Act13,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Mikal_3DObject.Acts.SetPos,
		C3.Plugins.Mikal_3DObject.Acts.SetY,
		C3.Plugins.Mikal_3DObject.Acts.SetBoolInstanceVar,
		C3.Plugins.Mikal_3DObject.Acts.SetZElevation,
		C3.Plugins.Mikal_3DObject.Acts.SetInstanceVar,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.Mikal_3DObject.Acts.SetRotationOrdered,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Mikal_3DObject.Exps.XAngle,
		C3.Plugins.Mikal_3DObject.Exps.YAngle,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Mikal_3DObject.Cnds.IsLoaded,
		C3.Plugins.Mikal_3DObject.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.JavaScriptInEvents.Gamees_Event269_Act2,
		C3.JavaScriptInEvents.Gamees_Event270_Act1,
		C3.JavaScriptInEvents.Gamees_Event272_Act1,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.XAt,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Touch.Exps.YAt,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.JavaScriptInEvents.Gamees_Event293_Act4,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Acts.SetX,
		C3.JavaScriptInEvents.Gamees_Event348_Act5,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.JavaScriptInEvents.Gamesnacks_es_Event54_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event55_Act1,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.JavaScriptInEvents.Splashes_Event3_Act3,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.At,
		C3.JavaScriptInEvents.Mainsplashes_Event1_Act2,
		C3.JavaScriptInEvents.Mainsplashes_Event1_Act3,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.PlatformInfo.Cnds.IsOnMacOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnLinux,
		C3.Plugins.PlatformInfo.Cnds.IsOnChromeOS,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Browser.Acts.Focus,
		C3.JavaScriptInEvents.Gamesnacks_es_Event5_Act4,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.JavaScriptInEvents.Gamesnacks_es_Event42_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event44_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event45_Act2,
		C3.JavaScriptInEvents.Gamesnacks_es_Event46_Act1,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.JavaScriptInEvents.Gamesnacks_es_Event51_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event52_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event53_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event56_Act1,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.JavaScriptInEvents.Gamesnacks_es_Event59_Act2,
		C3.JavaScriptInEvents.Gamesnacks_es_Event62_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event64_Act1,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.JavaScriptInEvents.Gamesnacks_es_Event77_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event78_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event81_Act1,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Browser.Acts.Vibrate,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Particles.Exps.Rate,
		C3.Plugins.Text.Exps.FaceSize,
		C3.Plugins.Browser.Cnds.OnBackButton,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.SetMeshSize,
		C3.Plugins.Sprite.Acts.SetMeshPoint,
		C3.Plugins.Sprite.Exps.MeshRows,
		C3.Plugins.Sprite.Exps.MeshColumns,
		C3.Plugins.Browser.Acts.LockOrientation,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Behaviors.CV_BoundedDragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Behaviors.CV_BoundedDragnDrop.Acts.SetBoundY,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Behaviors.Bullet.Acts.SetSpeed
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{PlatformInfo: 0},
	{Browser: 0},
	{Touch: 0},
	{Audio: 0},
	{PlayButton: 0},
	{FullscreenButton: 0},
	{Resign: 0},
	{Type: 0},
	{HomeButton: 0},
	{SoundButton: 0},
	{rvIcon: 0},
	{SoundButton2: 0},
	{isOpen: 0},
	{Tween: 0},
	{SideMenuBG: 0},
	{sideMenuButton: 0},
	{SM_FullscreenButton: 0},
	{SM_HomeButton: 0},
	{SM_SoundButton: 0},
	{SM_HomeButton2: 0},
	{SM_FlipBoard: 0},
	{PopUpBG: 0},
	{SplashBG: 0},
	{tweenToSizeX: 0},
	{tweenToSizeY: 0},
	{Logo: 0},
	{Fade: 0},
	{BlackScreen: 0},
	{FakeSpin0: 0},
	{FakeSpin1: 0},
	{FakeSpin2: 0},
	{FakeSpin3: 0},
	{FakeSpin4: 0},
	{FakeSpin5: 0},
	{FakeSpin6: 0},
	{FakeSpin7: 0},
	{FakeSpin8: 0},
	{Pin: 0},
	{ShopCollections: 0},
	{Number: 0},
	{ShopDice0: 0},
	{ShopDice1: 0},
	{ShopDice2: 0},
	{ShopDice3: 0},
	{ShopPieces: 0},
	{ShopPieces0: 0},
	{ShopPieces1: 0},
	{ShopPieces2: 0},
	{ShopPieces3: 0},
	{ShopPieces4: 0},
	{ShopPieces5: 0},
	{ShopPieces6: 0},
	{ShopPieces7: 0},
	{ShopPieces8: 0},
	{Page: 0},
	{SinglePlayer: 0},
	{CollectionsPage: 0},
	{DiceSkin: 0},
	{PieceSkin: 0},
	{collectionsShop0: 0},
	{collectionsShop1: 0},
	{collectionsShop2: 0},
	{collectionsShop3: 0},
	{collectionsShop4: 0},
	{CollectionsShopObject: 0},
	{Tweenable: 0},
	{CollectionsTeblandscape: 0},
	{open: 0},
	{InShop_Btn: 0},
	{PiecesPage: 0},
	{UsingFrameBig: 0},
	{UsingFrameSmall: 0},
	{ID: 0},
	{Shop_Buy_txt: 0},
	{Price: 0},
	{BuyButtonLandscape: 0},
	{Coins: 0},
	{CoinsLandscape: 0},
	{CollectionPrice: 0},
	{CollectionsArray: 0},
	{CollectionsButton: 0},
	{Store: 0},
	{TabsB: 0},
	{PriceTag: 0},
	{lastX: 0},
	{lastY: 0},
	{Skin0: 0},
	{Skin1: 0},
	{Skin2: 0},
	{Skin3: 0},
	{Skin4: 0},
	{Skin5: 0},
	{Skin6: 0},
	{Skin7: 0},
	{Skin8: 0},
	{Collection0: 0},
	{Collection1: 0},
	{Collection2: 0},
	{Collection3: 0},
	{Collection4: 0},
	{Locked: 0},
	{Rolling: 0},
	{Index: 0},
	{Position: 0},
	{Skin: 0},
	{Player: 0},
	{Physics: 0},
	{Dice: 0},
	{DiceEndPosition: 0},
	{Side: 0},
	{DiceTarget: 0},
	{dice1: 0},
	{dice2: 0},
	{DiceArray: 0},
	{DiceButton: 0},
	{DicePage: 0},
	{DicePrice: 0},
	{DiceResult: 0},
	{DiceShadow: 0},
	{Solid: 0},
	{Walls: 0},
	{Explosion1: 0},
	{Explosion2: 0},
	{FireWork: 0},
	{Bullet: 0},
	{MiniFireworks: 0},
	{Difficulty: 0},
	{Diff: 0},
	{difficultyText: 0},
	{Difiiculties: 0},
	{DPin: 0},
	{isTotal: 0},
	{DefficultyBonusText: 0},
	{BackGammon: 0},
	{Coin: 0},
	{CoinsWon: 0},
	{DoubleCoinsButton: 0},
	{DoublesBonus: 0},
	{EatenCount: 0},
	{EscapesBonus: 0},
	{home: 0},
	{Fade2: 0},
	{FXCoin: 0},
	{GammonBonus: 0},
	{GammonShine: 0},
	{KingTakesBonus: 0},
	{label: 0},
	{Amount: 0},
	{CurrentAmount: 0},
	{RewardAmount: 0},
	{RewardCoins: 0},
	{TotalCoinsReward: 0},
	{RewardsScreen: 0},
	{StatsPanelLine: 0},
	{StatsTitle2: 0},
	{WinnerBanner: 0},
	{ExtraCoins_: 0},
	{LeftHalf: 0},
	{Radial: 0},
	{Radial2: 0},
	{RadialBG: 0},
	{RightHalf: 0},
	{index: 0},
	{litCol: 0},
	{NoPossibleMoves: 0},
	{PieceColor: 0},
	{TurnGlow: 0},
	{BrandImage: 0},
	{boardPosition: 0},
	{Restart: 0},
	{winnerText: 0},
	{Mouse: 0},
	{"2player": 0},
	{InX: 0},
	{Sprite: 0},
	{CloseSM: 0},
	{CnnectFour: 0},
	{Restart2: 0},
	{backGround: 0},
	{onBoard: 0},
	{OriginX: 0},
	{OriginY: 0},
	{point: 0},
	{piece: 0},
	{errorText: 0},
	{Shop_Mask: 0},
	{PiecesArray: 0},
	{AJAX: 0},
	{Undo: 0},
	{ModeSelectDifficulties: 0},
	{PlayB: 0},
	{GameBGPC: 0},
	{LogoBGLandscape: 0},
	{Sine: 0},
	{Sine2: 0},
	{LogoShineScreen: 0},
	{LogoBG: 0},
	{PiecesButton: 0},
	{Rotate: 0},
	{Shine: 0},
	{Particles: 0},
	{Particles2: 0},
	{EquipmentButtonsParticleScreen: 0},
	{SettingPopUp: 0},
	{VibrateOn: 0},
	{CloseSettings: 0},
	{Asset2: 0},
	{Asset3: 0},
	{Asset4: 0},
	{HeadlineLandscape: 0},
	{TimeModlandscape: 0},
	{TimeButton: 0},
	{InfoButtonladnscape: 0},
	{PiecesTablandscape: 0},
	{DiceTablandscape: 0},
	{CloseShopButton: 0},
	{TimeModePopUp: 0},
	{YesButtonlandscape: 0},
	{NoButtonlandscape: 0},
	{BoardPC: 0},
	{ChosenPiece: 0},
	{PlayerHolder: 0},
	{KeepPlayingPopUp: 0},
	{KeepPlayingButtonlandscape: 0},
	{ResignButtonlandscape_: 0},
	{TimeDotsHolder: 0},
	{Dotlandscape: 0},
	{Avatar: 0},
	{FastRadialProgressBar: 0},
	{Timer: 0},
	{AvatarTimer: 0},
	{hard: 0},
	{med: 0},
	{PopUpShineScreenlandscape: 0},
	{CoinsShineScreenlandscape: 0},
	{TopUIBar: 0},
	{LogoBGHome: 0},
	{PlayButtonsShine: 0},
	{BoundedDragDrop: 0},
	{Sprite2: 0},
	{GameBGMobile: 0},
	{Vibration: 0},
	{Rules: 0},
	{CloseInfo: 0},
	{Iinital_size: 0},
	{Eatting_effect: 0},
	{Eatting_effect2: 0},
	{ScrollBG: 0},
	{ScrollTab: 0},
	{MyRuller: 0},
	{Asset5: 0},
	{Asset6: 0},
	{Asset7: 0},
	{NoMoves: 0},
	{chet: 0},
	{PopUpShineScreenlandscape2: 0},
	{Untitled: 0},
	{Anchor: 0},
	{CoinExplo: 0},
	{ExtraTimeText: 0},
	{PiecesEatenRewardText: 0},
	{AteKingsBonus: 0},
	{LoadingBar: 0},
	{TiledBackground: 0},
	{TempArray: 0},
	{ButtonsSpawner: 0},
	{Restart3: 0},
	{NotEnoughCoins: 0},
	{NoWifi: 0},
	{Mask: 0},
	{Asset: 0},
	{board: 0},
	{placeholder: 0},
	{outOfBoard: 0},
	{rollDoneButton: 0},
	{turnText: 0},
	{medium: 0},
	{"3DCamera": 0},
	{UndoButton: 0},
	{black: 0},
	{PieceSideView: 0},
	{TurnIndicator: 0},
	{Fliperuni: 0},
	{Spawner: 0},
	{GlobalButtons: 0},
	{FullScreenButtons: 0},
	{HomeButtons: 0},
	{SoundButtons: 0},
	{ModeSelectTweens: 0},
	{Buttons: 0},
	{PiecesSkins: 0},
	{Settings: 0},
	{DiceShop: 0},
	{PiecesShop: 0},
	{CollectionsShop: 0},
	{ShopSpawners: 0},
	{ShopHolders: 0},
	{ShopPageSelection: 0},
	{CollectionSkins: 0},
	{Difficulties: 0},
	{VibrateButtons: 0},
	{GameBGS: 0},
	{RadialTeam: 0},
	{CanTouch: 0},
	{Tween2: 0},
	{BouncyBois: 0},
	{FadeTexts: 0},
	{FakeSpins: 0},
	{isGameOver: 0},
	{GameRunning: 0},
	{onComputerTurn: 0},
	{level: 0},
	{score: 0},
	{PlayerTurn: 0},
	{NoMoveDraw: 0},
	{playingVsComputer: 0},
	{CollectionSkin: 0},
	{BGColor: 0},
	{PlayersSwaped: 0},
	{PlayerColor: 0},
	{CurPlayerSide: 0},
	{TurnTime: 0},
	{P0Strikes: 0},
	{P1Strikes: 0},
	{P0Avatar: 0},
	{P1Avatar: 0},
	{Winner: 0},
	{P0PiecesEaten: 0},
	{P1PiecesEaten: 0},
	{BlackPlayerCollectedPieces: 0},
	{WhitePlayerCollectedPieces: 0},
	{EscapesCounter: 0},
	{PiecesEatenCounter: 0},
	{DoublesCounter: 0},
	{TripleEatsCounter: 0},
	{EatenKingsCounter: 0},
	{KingEatCounter: 0},
	{WinTime: 0},
	{MoneyFromEatenPieces: 0},
	{MoneyFromEscapes: 0},
	{MoneyFromTime: 0},
	{MoneyFromDoubles: 0},
	{MoneyFromGammon: 0},
	{MoneyFromEatenKings: 0},
	{MoneyFromKingEat: 0},
	{MoneyFromDifficulty: 0},
	{UsedDoubleCoins: 0},
	{RewardTextYOffset: 0},
	{RewardTextXOffset: 0},
	{MoneyPerEatenPiece: 0},
	{MoneyPerEscape: 0},
	{MoneyPerSecond: 0},
	{MoneyPerDouble: 0},
	{MoneyForGammon: 0},
	{MoneyPerEatenKing: 0},
	{MoneyPerKingEat: 0},
	{MaxSecForMoney: 0},
	{PC_Scale: 0},
	{PC_offset: 0},
	{Height: 0},
	{Y: 0},
	{CountRewardsForSize: 0},
	{isWin: 0},
	{computerLevel: 0},
	{rollDices: 0},
	{visible: 0},
	{PieceTweenWaitTime: 0},
	{height: 0},
	{animation: 0},
	{LastStackPoint: 0},
	{computerMove: 0},
	{Step: 0},
	{TweenTime: 0},
	{color: 0},
	{BackX: 0},
	{BackY: 0},
	{LastStack: 0},
	{step: 0},
	{StepInMove: 0},
	{ButtonAnimationSpeed: 0},
	{FloorHeight: 0},
	{DiceAnimationFinished: 0},
	{x: 0},
	{y: 0},
	{z: 0},
	{TouchedPiece: 0},
	{PlayerFinishedTurn: 0},
	{colIndex: 0},
	{pieceIndex: 0},
	{nextTurnColor: 0},
	{isGammon: 0},
	{isBackGammon: 0},
	{WinningColor: 0},
	{SOUND_ON: 0},
	{RandomMove: 0},
	{SFX_Type: 0},
	{IsFullScreenAllowed: 0},
	{IsAdsAllowed: 0},
	{IsAdmobDone: 0},
	{GoogleAd: 0},
	{GoogleAd_timeLimit: 0},
	{FreeAd: 0},
	{PiecesExists: 0},
	{DicesExists: 0},
	{CollectionsExist: 0},
	{Local_ID: 0},
	{Platform: 0},
	{ExportVersion: 0},
	{RV_type: 0},
	{first_set: 0},
	{ADS: 0},
	{RV_ready: 0},
	{RV_play: 0},
	{RV_create_attempts: 0},
	{Admob_RV: 0},
	{Admob_Interstitial: 0},
	{Interstitial_Type: 0},
	{CanAds: 0},
	{CoinsAmount: 0},
	{X: 0},
	{Layer: 0},
	{type: 0},
	{name: 0},
	{mute: 0},
	{last_score_sent: 0},
	{save_score: 0},
	{return: 0},
	{item: 0},
	{value: 0},
	{gamesnacksPause: 0},
	{Vibrate: 0},
	{destroy_fullscreen: 0},
	{ResignType: 0},
	{Frame: 0},
	{RadialMax: 0},
	{CurrentScore: 0},
	{MaxScore: 0},
	{RVCoinsCycleTime: 0},
	{RVCoinsCurrentTime: 0},
	{RVCoinsAddition: 0},
	{RowsAndColums: 0},
	{TimeMod: 0},
	{CurrentPage: 0},
	{offset: 0},
	{MenuSettingOpen: 0},
	{ShopOpen: 0},
	{IsCollection: 0},
	{DicePriceYoffset: 0},
	{DiceBuyButtonYOffset: 0},
	{PiecesPriceYoffset: 0},
	{PiecesBuyButtonYOffset: 0},
	{CollectionsPriceYoffset: 0},
	{CollectionsBuyButtonYOffset: 0},
	{msg: 0},
	{TargetX: 0},
	{TargetY: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	FullscreenButton: class extends self.ISpriteInstance {},
	HomeButton: class extends self.ISpriteInstance {},
	SoundButton: class extends self.ISpriteInstance {},
	rvIcon: class extends self.ISpriteInstance {},
	SoundButton2: class extends self.ISpriteInstance {},
	SideMenuBG: class extends self.ISpriteInstance {},
	sideMenuButton: class extends self.ISpriteInstance {},
	SM_FullscreenButton: class extends self.ISpriteInstance {},
	SM_HomeButton: class extends self.ISpriteInstance {},
	SM_SoundButton: class extends self.ISpriteInstance {},
	SM_HomeButton2: class extends self.ISpriteInstance {},
	SM_FlipBoard: class extends self.ISpriteInstance {},
	PopUpBG: class extends self.ISpriteInstance {},
	SplashBG: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	BlackScreen: class extends self.ISpriteInstance {},
	FakeSpin0: class extends self.ISpriteInstance {},
	FakeSpin1: class extends self.ISpriteInstance {},
	FakeSpin2: class extends self.ISpriteInstance {},
	FakeSpin3: class extends self.ISpriteInstance {},
	FakeSpin4: class extends self.ISpriteInstance {},
	FakeSpin5: class extends self.ISpriteInstance {},
	FakeSpin6: class extends self.ISpriteInstance {},
	FakeSpin7: class extends self.ISpriteInstance {},
	FakeSpin8: class extends self.ISpriteInstance {},
	ShopCollections: class extends self.ISpriteInstance {},
	ShopDice0: class extends self.ISpriteInstance {},
	ShopDice1: class extends self.ISpriteInstance {},
	ShopDice2: class extends self.ISpriteInstance {},
	ShopDice3: class extends self.ISpriteInstance {},
	ShopPieces: class extends self.ISpriteInstance {},
	ShopPieces0: class extends self.ISpriteInstance {},
	ShopPieces1: class extends self.ISpriteInstance {},
	ShopPieces2: class extends self.ISpriteInstance {},
	ShopPieces3: class extends self.ISpriteInstance {},
	ShopPieces4: class extends self.ISpriteInstance {},
	ShopPieces5: class extends self.ISpriteInstance {},
	ShopPieces6: class extends self.ISpriteInstance {},
	ShopPieces7: class extends self.ISpriteInstance {},
	ShopPieces8: class extends self.ISpriteInstance {},
	SinglePlayer: class extends self.ISpriteInstance {},
	CollectionsPage: class extends self.ISpriteInstance {},
	collectionsShop0: class extends self.ISpriteInstance {},
	collectionsShop1: class extends self.ISpriteInstance {},
	collectionsShop2: class extends self.ISpriteInstance {},
	collectionsShop3: class extends self.ISpriteInstance {},
	collectionsShop4: class extends self.ISpriteInstance {},
	CollectionsShopObject: class extends self.ISpriteInstance {},
	CollectionsTeblandscape: class extends self.ISpriteInstance {},
	InShop_Btn: class extends self.ISpriteInstance {},
	PiecesPage: class extends self.ISpriteInstance {},
	UsingFrameBig: class extends self.ISpriteInstance {},
	UsingFrameSmall: class extends self.ISpriteInstance {},
	Shop_Buy_txt: class extends self.ITextInstance {},
	BuyButtonLandscape: class extends self.ISpriteInstance {},
	Coins: class extends self.ITextInstance {},
	CoinsLandscape: class extends self.ISpriteInstance {},
	CollectionPrice: class extends self.ISpriteInstance {},
	CollectionsArray: class extends self.IArrayInstance {},
	CollectionsButton: class extends self.ISpriteInstance {},
	Store: class extends self.ISpriteInstance {},
	TabsB: class extends self.ISpriteInstance {},
	PriceTag: class extends self.ITextInstance {},
	Skin0: class extends self.ISpriteInstance {},
	Skin1: class extends self.ISpriteInstance {},
	Skin2: class extends self.ISpriteInstance {},
	Skin3: class extends self.ISpriteInstance {},
	Skin4: class extends self.ISpriteInstance {},
	Skin5: class extends self.ISpriteInstance {},
	Skin6: class extends self.ISpriteInstance {},
	Skin7: class extends self.ISpriteInstance {},
	Skin8: class extends self.ISpriteInstance {},
	Collection0: class extends self.ISpriteInstance {},
	Collection1: class extends self.ISpriteInstance {},
	Collection2: class extends self.ISpriteInstance {},
	Collection3: class extends self.ISpriteInstance {},
	Collection4: class extends self.ISpriteInstance {},
	Dice: class extends self.IWorldInstance {},
	DiceEndPosition: class extends self.ISpriteInstance {},
	DiceTarget: class extends self.ISpriteInstance {},
	dice1: class extends self.ITextInstance {},
	dice2: class extends self.ITextInstance {},
	DiceArray: class extends self.IArrayInstance {},
	DiceButton: class extends self.ISpriteInstance {},
	DicePage: class extends self.ISpriteInstance {},
	DicePrice: class extends self.ISpriteInstance {},
	DiceResult: class extends self.ISpriteInstance {},
	DiceShadow: class extends self.ISpriteInstance {},
	Walls: class extends self.ISpriteInstance {},
	Explosion1: class extends self.ISpriteInstance {},
	Explosion2: class extends self.ISpriteInstance {},
	FireWork: class extends self.ISpriteInstance {},
	MiniFireworks: class extends self.ISpriteInstance {},
	Diff: class extends self.ISpriteInstance {},
	difficultyText: class extends self.ITextInstance {},
	Difiiculties: class extends self.ISpriteInstance {},
	DPin: class extends self.ISpriteInstance {},
	DefficultyBonusText: class extends self.ITextInstance {},
	BackGammon: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	CoinsWon: class extends self.ISpriteInstance {},
	DoubleCoinsButton: class extends self.ISpriteInstance {},
	DoublesBonus: class extends self.ITextInstance {},
	EatenCount: class extends self.ITextInstance {},
	EscapesBonus: class extends self.ITextInstance {},
	FXCoin: class extends self.ISpriteInstance {},
	GammonBonus: class extends self.ITextInstance {},
	GammonShine: class extends self.ISpriteInstance {},
	KingTakesBonus: class extends self.ITextInstance {},
	label: class extends self.ITextInstance {},
	RewardAmount: class extends self.ITextInstance {},
	RewardCoins: class extends self.ITextInstance {},
	TotalCoinsReward: class extends self.ITextInstance {},
	RewardsScreen: class extends self.ISpriteInstance {},
	StatsPanelLine: class extends self.ISpriteInstance {},
	StatsTitle2: class extends self.ISpriteInstance {},
	WinnerBanner: class extends self.ISpriteInstance {},
	ExtraCoins_: class extends self.ISpriteInstance {},
	LeftHalf: class extends self.ISpriteInstance {},
	Radial: class extends self.ISpriteInstance {},
	Radial2: class extends self.ISpriteInstance {},
	RadialBG: class extends self.ISpriteInstance {},
	RightHalf: class extends self.ISpriteInstance {},
	litCol: class extends self.ISpriteInstance {},
	NoPossibleMoves: class extends self.ISpriteInstance {},
	PieceColor: class extends self.ISpriteInstance {},
	TurnGlow: class extends self.ISpriteInstance {},
	BrandImage: class extends self.ISpriteInstance {},
	boardPosition: class extends self.ISpriteInstance {},
	Restart: class extends self.ISpriteInstance {},
	winnerText: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	_2player: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	CloseSM: class extends self.ISpriteInstance {},
	CnnectFour: class extends self.ISpriteInstance {},
	Restart2: class extends self.ISpriteInstance {},
	backGround: class extends self.ISpriteInstance {},
	piece: class extends self.ISpriteInstance {},
	errorText: class extends self.ITextInstance {},
	Shop_Mask: class extends self.ISpriteInstance {},
	PiecesArray: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	Undo: class extends self.ISpriteInstance {},
	ModeSelectDifficulties: class extends self.ISpriteInstance {},
	PlayB: class extends self.ISpriteInstance {},
	GameBGPC: class extends self.ISpriteInstance {},
	LogoBGLandscape: class extends self.ISpriteInstance {},
	LogoShineScreen: class extends self.ISpriteInstance {},
	LogoBG: class extends self.ISpriteInstance {},
	PiecesButton: class extends self.ISpriteInstance {},
	Shine: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	EquipmentButtonsParticleScreen: class extends self.ISpriteInstance {},
	SettingPopUp: class extends self.ISpriteInstance {},
	VibrateOn: class extends self.ISpriteInstance {},
	CloseSettings: class extends self.ISpriteInstance {},
	Asset2: class extends self.ISpriteInstance {},
	Asset3: class extends self.ISpriteInstance {},
	Asset4: class extends self.ISpriteInstance {},
	HeadlineLandscape: class extends self.ISpriteInstance {},
	TimeModlandscape: class extends self.ISpriteInstance {},
	TimeButton: class extends self.ISpriteInstance {},
	InfoButtonladnscape: class extends self.ISpriteInstance {},
	PiecesTablandscape: class extends self.ISpriteInstance {},
	DiceTablandscape: class extends self.ISpriteInstance {},
	CloseShopButton: class extends self.ISpriteInstance {},
	TimeModePopUp: class extends self.ISpriteInstance {},
	YesButtonlandscape: class extends self.ISpriteInstance {},
	NoButtonlandscape: class extends self.ISpriteInstance {},
	BoardPC: class extends self.ISpriteInstance {},
	ChosenPiece: class extends self.ISpriteInstance {},
	PlayerHolder: class extends self.ISpriteInstance {},
	KeepPlayingPopUp: class extends self.ISpriteInstance {},
	KeepPlayingButtonlandscape: class extends self.ISpriteInstance {},
	ResignButtonlandscape_: class extends self.ISpriteInstance {},
	TimeDotsHolder: class extends self.ISpriteInstance {},
	Dotlandscape: class extends self.ISpriteInstance {},
	Avatar: class extends self.ISpriteInstance {},
	AvatarTimer: class extends self.ISpriteInstance {},
	hard: class extends self.ISpriteInstance {},
	med: class extends self.ISpriteInstance {},
	PopUpShineScreenlandscape: class extends self.ISpriteInstance {},
	CoinsShineScreenlandscape: class extends self.ISpriteInstance {},
	TopUIBar: class extends self.ISpriteInstance {},
	LogoBGHome: class extends self.ISpriteInstance {},
	PlayButtonsShine: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	GameBGMobile: class extends self.ISpriteInstance {},
	Vibration: class extends self.ISpriteInstance {},
	Rules: class extends self.ISpriteInstance {},
	CloseInfo: class extends self.ISpriteInstance {},
	Eatting_effect: class extends self.ISpriteInstance {},
	Eatting_effect2: class extends self.ISpriteInstance {},
	ScrollBG: class extends self.ISpriteInstance {},
	ScrollTab: class extends self.ISpriteInstance {},
	MyRuller: class extends self.ISpriteInstance {},
	Asset5: class extends self.ISpriteInstance {},
	Asset6: class extends self.ISpriteInstance {},
	Asset7: class extends self.ISpriteInstance {},
	NoMoves: class extends self.ITextInstance {},
	chet: class extends self.ISpriteInstance {},
	PopUpShineScreenlandscape2: class extends self.ISpriteInstance {},
	Untitled: class extends self.ISpriteInstance {},
	Anchor: class extends self.ISpriteInstance {},
	CoinExplo: class extends self.IParticlesInstance {},
	ExtraTimeText: class extends self.ITextInstance {},
	PiecesEatenRewardText: class extends self.ITextInstance {},
	AteKingsBonus: class extends self.ITextInstance {},
	LoadingBar: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TempArray: class extends self.IArrayInstance {},
	ButtonsSpawner: class extends self.ISpriteInstance {},
	Restart3: class extends self.ISpriteInstance {},
	NotEnoughCoins: class extends self.ISpriteInstance {},
	NoWifi: class extends self.ISpriteInstance {},
	Mask: class extends self.ISpriteInstance {},
	Asset: class extends self.ISpriteInstance {},
	board: class extends self.ISpriteInstance {},
	placeholder: class extends self.ISpriteInstance {},
	outOfBoard: class extends self.ISpriteInstance {},
	rollDoneButton: class extends self.ISpriteInstance {},
	turnText: class extends self.ITextInstance {},
	medium: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	UndoButton: class extends self.ISpriteInstance {},
	black: class extends self.ISpriteInstance {},
	PieceSideView: class extends self.ISpriteInstance {},
	TurnIndicator: class extends self.ISpriteInstance {},
	Fliperuni: class extends self.ISpriteInstance {},
	Spawner: class extends self.ISpriteInstance {},
	GlobalButtons: class extends self.ISpriteInstance {},
	FullScreenButtons: class extends self.ISpriteInstance {},
	HomeButtons: class extends self.ISpriteInstance {},
	SoundButtons: class extends self.ISpriteInstance {},
	ModeSelectTweens: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	PiecesSkins: class extends self.ISpriteInstance {},
	Settings: class extends self.ISpriteInstance {},
	DiceShop: class extends self.ISpriteInstance {},
	PiecesShop: class extends self.ISpriteInstance {},
	CollectionsShop: class extends self.ISpriteInstance {},
	ShopSpawners: class extends self.ISpriteInstance {},
	ShopHolders: class extends self.ISpriteInstance {},
	ShopPageSelection: class extends self.ISpriteInstance {},
	CollectionSkins: class extends self.ISpriteInstance {},
	Difficulties: class extends self.ISpriteInstance {},
	VibrateButtons: class extends self.ISpriteInstance {},
	GameBGS: class extends self.ISpriteInstance {},
	RadialTeam: class extends self.ISpriteInstance {},
	CanTouch: class extends self.ISpriteInstance {},
	BouncyBois: class extends self.ISpriteInstance {},
	FadeTexts: class extends self.ITextInstance {},
	FakeSpins: class extends self.ISpriteInstance {}
}