const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Touch,
		C3.Behaviors.Sin,
		C3.Behaviors.NoSave,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.OnLoadFailed,
		C3.Plugins.System.Cnds.OnSaveComplete,
		C3.Plugins.System.Cnds.OnSaveFailed,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Text.Acts.MoveAtAngle,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.IsBetweenAngles,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.Focus,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.System.Exps.rgb,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.PlatformInfo.Cnds.IsOnLinux,
		C3.Plugins.PlatformInfo.Cnds.IsOnMacOS,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Exps.projectversion,
		C3.ScriptsInEvents.Splash_es_Event7_Act2,
		C3.Plugins.System.Acts.SetTimescale,
		C3.ScriptsInEvents.Ads_sounds_Event23_Act4,
		C3.ScriptsInEvents.Ads_sounds_Event34_Act1,
		C3.ScriptsInEvents.Ads_sounds_Event35_Act1,
		C3.ScriptsInEvents.Ads_sounds_Event36_Act2,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.ScriptsInEvents.Ads_sounds_Event60_Act1,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.ScriptsInEvents.Ads_sounds_Event69_Act2,
		C3.ScriptsInEvents.Ads_sounds_Event70_Act2,
		C3.ScriptsInEvents.Ads_sounds_Event71_Act2,
		C3.ScriptsInEvents.Ads_sounds_Event72_Act2,
		C3.ScriptsInEvents.Ads_sounds_Event73_Act2,
		C3.ScriptsInEvents.Ads_sounds_Event74_Act2,
		C3.ScriptsInEvents.Ads_sounds_Event78_Act2,
		C3.ScriptsInEvents.Ads_sounds_Event81_Act1,
		C3.ScriptsInEvents.Ads_sounds_Event83_Act1,
		C3.ScriptsInEvents.Ads_sounds_Event87_Act1,
		C3.ScriptsInEvents.Ads_sounds_Event88_Act1
	];
};
self.C3_JsPropNameTable = [
	{BestScore_txt: 0},
	{BestScore_value_txt: 0},
	{Score_txt: 0},
	{Score_value_txt: 0},
	{Time_value_txt: 0},
	{Time_txt: 0},
	{New_Game_txt: 0},
	{Sound_txt: 0},
	{Full_Screen_txt: 0},
	{Tween: 0},
	{LosePop: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Original_W: 0},
	{Original_H: 0},
	{WinPop: 0},
	{Close_settings: 0},
	{Game_Menu_Button: 0},
	{Game_Undo_Button: 0},
	{Timer: 0},
	{NewGame_button2: 0},
	{NewGame_button3: 0},
	{Show_Numbers_Button: 0},
	{Rv_icon_undo: 0},
	{Rv_icon_show_numbers: 0},
	{Sprite2: 0},
	{V3: 0},
	{Colors: 0},
	{Particles: 0},
	{Settings_bg2: 0},
	{Shadow: 0},
	{blackscreen: 0},
	{GameBoard: 0},
	{xx: 0},
	{yy: 0},
	{HostBlock: 0},
	{Spot: 0},
	{moved: 0},
	{del: 0},
	{lastX: 0},
	{lastY: 0},
	{FrameNumber: 0},
	{Block: 0},
	{GridStartSpawn: 0},
	{UIZone: 0},
	{Block2: 0},
	{Fullscreen_button: 0},
	{Settings_bg: 0},
	{Sound_button: 0},
	{NewGame_button: 0},
	{Restart_button: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{PlatformInfo: 0},
	{Touch: 0},
	{Sine: 0},
	{confetti1: 0},
	{confetti2: 0},
	{NoSave: 0},
	{particle_drag: 0},
	{particle_explode: 0},
	{Particles2: 0},
	{Particles3: 0},
	{confettiLeft: 0},
	{confettiRight: 0},
	{Particles4: 0},
	{GameBG_PC: 0},
	{MobileGameScreen: 0},
	{MobileSplash: 0},
	{DesktopSplash: 0},
	{Sprite11: 0},
	{l: 0},
	{l2: 0},
	{l3: 0},
	{Sine2: 0},
	{l4: 0},
	{l5_: 0},
	{light: 0},
	{light2: 0},
	{r: 0},
	{r10: 0},
	{r1_: 0},
	{r2: 0},
	{r2_: 0},
	{r3: 0},
	{r3_: 0},
	{r4: 0},
	{r4_: 0},
	{r5: 0},
	{r5_: 0},
	{r6: 0},
	{r7: 0},
	{r8: 0},
	{r9: 0},
	{smoke: 0},
	{v: 0},
	{v10: 0},
	{v6: 0},
	{v7: 0},
	{v8: 0},
	{v9: 0},
	{buttons_txt: 0},
	{Debug_txt: 0},
	{Interstitial_button: 0},
	{Reawrd_button: 0},
	{Reward_ready: 0},
	{Audio_state: 0},
	{tnewgame: 0},
	{tscound: 0},
	{shadowbuttons: 0},
	{shadowbuttons2: 0},
	{shadowbuttons3: 0},
	{tfscreen: 0},
	{btnstart: 0},
	{logo2: 0},
	{logotext: 0},
	{logopizza: 0},
	{Particles5: 0},
	{logotext2: 0},
	{logopizza2: 0},
	{Text: 0},
	{tfscreen2: 0},
	{tscound2: 0},
	{tnewgame2: 0},
	{GamePause_BG: 0},
	{GamePause_txt: 0},
	{PAUSED: 0},
	{FSpot: 0},
	{FBlock: 0},
	{Texts: 0},
	{MovingArt: 0},
	{SwipeDir: 0},
	{SwipeMaxDistance: 0},
	{StartTouchX: 0},
	{StartTouchY: 0},
	{BlocksMoving: 0},
	{GameOver: 0},
	{Win: 0},
	{Settings: 0},
	{Undo_count: 0},
	{Score: 0},
	{BestScore: 0},
	{firstMove: 0},
	{LastCreatedBlockUID: 0},
	{NumbersVisble: 0},
	{NumbersReveal: 0},
	{LocalStorage_ID: 0},
	{UndoCD: 0},
	{Pizza_Sound: 0},
	{SaveCD: 0},
	{LocalStorage_BestScore: 0},
	{sound_load: 0},
	{PC: 0},
	{pc: 0},
	{spaceX: 0},
	{spaceY: 0},
	{BlockID: 0},
	{SpotID: 0},
	{Tag: 0},
	{ThereIsChance: 0},
	{Score_thousands: 0},
	{Score_millions: 0},
	{seconds: 0},
	{minutes: 0},
	{num: 0},
	{cnt: 0},
	{Block_UID: 0},
	{Device: 0},
	{animals_count: 0},
	{random_animals: 0},
	{IsAdsAllowed: 0},
	{gameSnacksAudioAllowed: 0},
	{IsFullscreenAllowed: 0},
	{random_move_sound: 0},
	{random_collapse_sound: 0},
	{random_food_sound: 0},
	{Rv_type: 0},
	{RV_ready: 0},
	{RV_play: 0},
	{RV_create_attempts: 0},
	{ADSPlay: 0},
	{firstTime: 0},
	{RandomSong: 0},
	{IsAudioAllowed: 0},
	{isGamePaused: 0},
	{IsDone: 0},
	{playmusicafterad: 0},
	{type: 0},
	{name: 0},
	{Kind: 0},
	{mute: 0},
	{save_score: 0},
	{return_score: 0},
	{item: 0},
	{value: 0}
];

self.InstanceType = {
	BestScore_txt: class extends self.ITextInstance {},
	BestScore_value_txt: class extends self.ITextInstance {},
	Score_txt: class extends self.ITextInstance {},
	Score_value_txt: class extends self.ITextInstance {},
	Time_value_txt: class extends self.ITextInstance {},
	Time_txt: class extends self.ITextInstance {},
	New_Game_txt: class extends self.ITextInstance {},
	Sound_txt: class extends self.ITextInstance {},
	Full_Screen_txt: class extends self.ITextInstance {},
	LosePop: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	WinPop: class extends self.ISpriteInstance {},
	Close_settings: class extends self.ISpriteInstance {},
	Game_Menu_Button: class extends self.ISpriteInstance {},
	Game_Undo_Button: class extends self.ISpriteInstance {},
	NewGame_button2: class extends self.ISpriteInstance {},
	NewGame_button3: class extends self.ISpriteInstance {},
	Show_Numbers_Button: class extends self.ISpriteInstance {},
	Rv_icon_undo: class extends self.ISpriteInstance {},
	Rv_icon_show_numbers: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	V3: class extends self.ISpriteInstance {},
	Colors: class extends self.ITextInstance {},
	Particles: class extends self.IParticlesInstance {},
	Settings_bg2: class extends self.ISpriteInstance {},
	Shadow: class extends self.ISpriteInstance {},
	blackscreen: class extends self.ISpriteInstance {},
	GameBoard: class extends self.ISpriteInstance {},
	Spot: class extends self.ISpriteInstance {},
	Block: class extends self.ISpriteInstance {},
	GridStartSpawn: class extends self.ISpriteInstance {},
	UIZone: class extends self.ISpriteInstance {},
	Block2: class extends self.ISpriteInstance {},
	Fullscreen_button: class extends self.ISpriteInstance {},
	Settings_bg: class extends self.ISpriteInstance {},
	Sound_button: class extends self.ISpriteInstance {},
	NewGame_button: class extends self.ISpriteInstance {},
	Restart_button: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	confetti1: class extends self.ISpriteInstance {},
	confetti2: class extends self.ISpriteInstance {},
	particle_drag: class extends self.IParticlesInstance {},
	particle_explode: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Particles3: class extends self.IParticlesInstance {},
	confettiLeft: class extends self.ISpriteInstance {},
	confettiRight: class extends self.ISpriteInstance {},
	Particles4: class extends self.IParticlesInstance {},
	GameBG_PC: class extends self.ISpriteInstance {},
	MobileGameScreen: class extends self.ISpriteInstance {},
	MobileSplash: class extends self.ISpriteInstance {},
	DesktopSplash: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	l: class extends self.ISpriteInstance {},
	l2: class extends self.ISpriteInstance {},
	l3: class extends self.ISpriteInstance {},
	l4: class extends self.ISpriteInstance {},
	l5_: class extends self.ISpriteInstance {},
	light: class extends self.ISpriteInstance {},
	light2: class extends self.ISpriteInstance {},
	r: class extends self.ISpriteInstance {},
	r10: class extends self.ISpriteInstance {},
	r1_: class extends self.ISpriteInstance {},
	r2: class extends self.ISpriteInstance {},
	r2_: class extends self.ISpriteInstance {},
	r3: class extends self.ISpriteInstance {},
	r3_: class extends self.ISpriteInstance {},
	r4: class extends self.ISpriteInstance {},
	r4_: class extends self.ISpriteInstance {},
	r5: class extends self.ISpriteInstance {},
	r5_: class extends self.ISpriteInstance {},
	r6: class extends self.ISpriteInstance {},
	r7: class extends self.ISpriteInstance {},
	r8: class extends self.ISpriteInstance {},
	r9: class extends self.ISpriteInstance {},
	smoke: class extends self.ISpriteInstance {},
	v: class extends self.ISpriteInstance {},
	v10: class extends self.ISpriteInstance {},
	v6: class extends self.ISpriteInstance {},
	v7: class extends self.ISpriteInstance {},
	v8: class extends self.ISpriteInstance {},
	v9: class extends self.ISpriteInstance {},
	buttons_txt: class extends self.ITextInstance {},
	Debug_txt: class extends self.ITextInstance {},
	Interstitial_button: class extends self.ISpriteInstance {},
	Reawrd_button: class extends self.ISpriteInstance {},
	Reward_ready: class extends self.ISpriteInstance {},
	Audio_state: class extends self.ISpriteInstance {},
	tnewgame: class extends self.ISpriteInstance {},
	tscound: class extends self.ISpriteInstance {},
	shadowbuttons: class extends self.ISpriteInstance {},
	shadowbuttons2: class extends self.ISpriteInstance {},
	shadowbuttons3: class extends self.ISpriteInstance {},
	tfscreen: class extends self.ISpriteInstance {},
	btnstart: class extends self.ISpriteInstance {},
	logo2: class extends self.ISpriteInstance {},
	logotext: class extends self.ISpriteInstance {},
	logopizza: class extends self.ISpriteInstance {},
	Particles5: class extends self.IParticlesInstance {},
	logotext2: class extends self.ISpriteInstance {},
	logopizza2: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	tfscreen2: class extends self.ISpriteInstance {},
	tscound2: class extends self.ISpriteInstance {},
	tnewgame2: class extends self.ISpriteInstance {},
	GamePause_BG: class extends self.ISpriteInstance {},
	GamePause_txt: class extends self.ITextInstance {},
	PAUSED: class extends self.ISpriteInstance {},
	FSpot: class extends self.ISpriteInstance {},
	FBlock: class extends self.ISpriteInstance {},
	Texts: class extends self.ITextInstance {},
	MovingArt: class extends self.ISpriteInstance {}
}