const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Rotate,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Plugins.NinePatch,
		C3.Plugins.Text,
		C3.Behaviors.LOS,
		C3.Behaviors.Orbit,
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Behaviors.Anchor,
		C3.Plugins.Keyboard,
		C3.Plugins.Arr,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Behaviors.Physics,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.PlatformInfo.Cnds.IsOnMacOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnLinux,
		C3.Plugins.PlatformInfo.Cnds.IsOnChromeOS,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.JavaScriptInEvents.Splash_es_Event8_Act2,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Browser.Acts.Focus,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.Width,
		C3.JavaScriptInEvents.Game_es_Event9_Act5,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.JavaScriptInEvents.Game_es_Event15_Act2,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Cnds.PickParent,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Particles.Acts.MoveToBottom,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.JavaScriptInEvents.Ads_es_Event8_Act4,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.JavaScriptInEvents.Ads_es_Event30_Act1,
		C3.JavaScriptInEvents.Ads_es_Event32_Act1,
		C3.JavaScriptInEvents.Ads_es_Event33_Act2,
		C3.JavaScriptInEvents.Ads_es_Event34_Act1,
		C3.JavaScriptInEvents.Ads_es_Event39_Act1,
		C3.JavaScriptInEvents.Ads_es_Event40_Act1,
		C3.JavaScriptInEvents.Ads_es_Event41_Act1,
		C3.JavaScriptInEvents.Ads_es_Event42_Act1,
		C3.JavaScriptInEvents.Ads_es_Event43_Act1,
		C3.JavaScriptInEvents.Ads_es_Event44_Act1,
		C3.JavaScriptInEvents.Ads_es_Event46_Act1,
		C3.JavaScriptInEvents.Ads_es_Event49_Act1,
		C3.JavaScriptInEvents.Ads_es_Event51_Act1,
		C3.Plugins.System.Exps.find,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.JavaScriptInEvents.Ads_es_Event60_Act1,
		C3.JavaScriptInEvents.Ads_es_Event61_Act1,
		C3.JavaScriptInEvents.Ads_es_Event64_Act1,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.Sprite.Exps.LayerName
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{Chest: 0},
	{Chest_light_1: 0},
	{Chest_light_2: 0},
	{Chest_light_3: 0},
	{Coin_1: 0},
	{Coin_2: 0},
	{Coin_3: 0},
	{Coin_4: 0},
	{Coin_5: 0},
	{Coin_6: 0},
	{gem_1: 0},
	{Gem_2: 0},
	{Rotate: 0},
	{Fade: 0},
	{Glow_effect3: 0},
	{Particles: 0},
	{Sine: 0},
	{Sine2: 0},
	{shine: 0},
	{Target_width: 0},
	{Target_height: 0},
	{Target_X: 0},
	{Target_Y: 0},
	{clean_Board_Icon_Chest: 0},
	{coin2: 0},
	{Hint_icon_Chest: 0},
	{Shuffle_icon_Chest: 0},
	{Axe2: 0},
	{Inital_size_X: 0},
	{Inital_size_Y: 0},
	{Inital_location_X: 0},
	{Inital_location_Y: 0},
	{Axe_popUp_items: 0},
	{Axe_world_popup: 0},
	{AllTheKitchenToolsAreFoundTimeToWhipUpARoyalFeast: 0},
	{ClaimBTN: 0},
	{Continue_BTN: 0},
	{COINS_BTN: 0},
	{COINS_BTN2: 0},
	{End_world_text_0: 0},
	{End_world_text_1: 0},
	{End_world_text_2: 0},
	{End_world_text_3: 0},
	{End_world_text_4: 0},
	{EveryHiddenItemIsFoundTheGroundsAreReadyForARoyalStroll: 0},
	{"EveryScrollAndBookIsBackInPlaceTheKing’sKnowledgeBankIsRestored": 0},
	{GET200COINS: 0},
	{Get30SecPink: 0},
	{Get_BTN: 0},
	{GreenFrame: 0},
	{Group: 0},
	{Group_world_popup: 0},
	{happyHappyKing: 0},
	{Jump: 0},
	{HappyKing: 0},
	{Hint_pop: 0},
	{Jumping_King: 0},
	{Knife: 0},
	{Knife2: 0},
	{Knife2_world_popup: 0},
	{Knife_popUp_items: 0},
	{LosePop_0: 0},
	{LosePop_1: 0},
	{LosePop_2: 0},
	{LosePop_3: 0},
	{LosePop_4: 0},
	{mortarAndPestle: 0},
	{mortarAndPestle2: 0},
	{mortarAndPestle2_world_popup: 0},
	{mortarAndPestle_popUp_items: 0},
	{Next_BTN: 0},
	{NextBTN_Worlds: 0},
	{NORVItemsPopUP: 0},
	{NORVPopUpBoardClean: 0},
	{NoRVShuffleBoosterBackPopup: 0},
	{NotEnoughCoins_Popup: 0},
	{outOfTimeTitle: 0},
	{popupTitle: 0},
	{ShieldSwords: 0},
	{ShieldSwords2: 0},
	{ShieldSwords2_world_popup: 0},
	{ShieldSwords_popUp_items: 0},
	{Shuffle_Pop: 0},
	{Sweep_pop: 0},
	{"TheEnchantedItemsAreGatheredTheKing’sSpellsAreReadyToCast": 0},
	{"TheEnchantedItemsAreGatheredTheKing’sSpellsAreReadyToCast2": 0},
	{TITLEPOPUP: 0},
	{TITLEPOPUP2: 0},
	{Trophy: 0},
	{Trumpet: 0},
	{Trumpet2: 0},
	{Trumpet2_popUp_items: 0},
	{Trumpet3: 0},
	{Trumpet3_world_popup: 0},
	{Trumpet4: 0},
	{Trumpet4_world_popup: 0},
	{Trumpet5: 0},
	{Trumpet_popUp_items: 0},
	{V: 0},
	{WinPop_0: 0},
	{WinPop_1: 0},
	{WinPop_2: 0},
	{WinPop_3: 0},
	{WinPop_4: 0},
	{WorldWinParent_0: 0},
	{WorldWinParent_1: 0},
	{WorldWinParent_2: 0},
	{WorldWinParent_3: 0},
	{WorldWinParent_4: 0},
	{X3FOR: 0},
	{X9FOR: 0},
	{xButton: 0},
	{xButton_2ndPop: 0},
	{"You’veUncoveredAllTheTreasuresTheKing’sThroneRoomHasNeverLookedBetter": 0},
	{WinPop_5: 0},
	{Axe_popUp_items2: 0},
	{WinPop_6: 0},
	{Axe_popUp_items3: 0},
	{WinPop_8: 0},
	{Axe_popUp_items4: 0},
	{WinPop_9: 0},
	{Axe_popUp_items5: 0},
	{LosePop_5: 0},
	{LosePop_6: 0},
	{LosePop_7: 0},
	{LosePop_8: 0},
	{LosePop_9: 0},
	{Axe_popUp_items8: 0},
	{WorldWinParent_5: 0},
	{Axe_world_popup2: 0},
	{End_world_text_5: 0},
	{WorldWinParent_6: 0},
	{End_world_text_6: 0},
	{Axe_world_popup3: 0},
	{WorldWinParent_80: 0},
	{Axe_world_popup4: 0},
	{End_world_text_7: 0},
	{WorldWinParent_8: 0},
	{End_world_text_8: 0},
	{Axe_world_popup5: 0},
	{WorldWinParent_7: 0},
	{End_world_text_9: 0},
	{Axe_world_popup6: 0},
	{Axe_world_popup7: 0},
	{WorldWinParent_9: 0},
	{End_world_text_10: 0},
	{Axe_world_popup8: 0},
	{NextWorldStart_1: 0},
	{NextWorldStart_2: 0},
	{NextWorldStart_3: 0},
	{NextWorldStart_4: 0},
	{NextWorldStart_5: 0},
	{NextWorldStart_6: 0},
	{NextWorldStart_7: 0},
	{NextWorldStart_8: 0},
	{NextWorldStart_9: 0},
	{NextWorldStart_10: 0},
	{NextWorldStart_11: 0},
	{WinPop_7: 0},
	{Axe_popUp_items9: 0},
	{Trumpet_popUp_items2: 0},
	{Trumpet4_world_popup2: 0},
	{GreenFrame2: 0},
	{V2: 0},
	{Axe_world_popup9: 0},
	{Axe_world_popup10: 0},
	{BG: 0},
	{BG2: 0},
	{BG3: 0},
	{BG4: 0},
	{BG5: 0},
	{BGCourtyard: 0},
	{BGEnchanters: 0},
	{BGKitchen: 0},
	{BGLibrary: 0},
	{BGPortrait: 0},
	{BGThroneRoom: 0},
	{Game_BG0: 0},
	{Game_BG0_P: 0},
	{Game_BG1: 0},
	{Game_BG1_P: 0},
	{Game_BG2: 0},
	{Game_BG2_P: 0},
	{Game_BG3: 0},
	{Game_BG3_P: 0},
	{Game_BG4: 0},
	{Game_BG4_P: 0},
	{Game_BGSpalsh: 0},
	{Game_BG5: 0},
	{Game_BG5_P: 0},
	{Game_BG6: 0},
	{Game_BG6_P: 0},
	{Game_BG7: 0},
	{Game_BG7_P: 0},
	{Game_BG8_P: 0},
	{Game_BG8: 0},
	{Game_BG9: 0},
	{Game_BG9_P: 0},
	{backgroundOfPortrait: 0},
	{BackMobileLevelSelect: 0},
	{backWall: 0},
	{BelltowerLevelSelector: 0},
	{BG6: 0},
	{BG7: 0},
	{BG8: 0},
	{BG9: 0},
	{BGWATCHTOWERLevelSelectorPortraite: 0},
	{chapelBG: 0},
	{Game_BGSpalsh2: 0},
	{Air_particales: 0},
	{"9patch": 0},
	{boosterNum2: 0},
	{BlackScreen: 0},
	{BorderPortrait: 0},
	{Axe: 0},
	{boosterNum: 0},
	{clean_Board_Icon: 0},
	{CloseMenuBTN: 0},
	{backOfBoosters: 0},
	{backOfHintsPortrait: 0},
	{Coins_TXT: 0},
	{Exit_BTN: 0},
	{EndLevel_TXT: 0},
	{FINDINGBAR: 0},
	{padding: 0},
	{Frame: 0},
	{FullScreen_BTN: 0},
	{GameEndTitle_TXT: 0},
	{greenButton: 0},
	{Highlight: 0},
	{LineOfSight: 0},
	{Highlight2: 0},
	{Highlight3: 0},
	{amount: 0},
	{Hint_Button: 0},
	{Hint_icon: 0},
	{index: 0},
	{ItemsLeft_TXT: 0},
	{LEVEL2: 0},
	{Level_TXT: 0},
	{levelNum_TXT: 0},
	{Logo: 0},
	{Light_particles: 0},
	{ogY: 0},
	{Menu: 0},
	{Menu_BTN: 0},
	{Music_BTN: 0},
	{play_Button: 0},
	{PlayAgain_BTN: 0},
	{playAgainBTN: 0},
	{PressEffectGETMultiply: 0},
	{PressEffectLevelMultiply: 0},
	{PressEffectMoneyMultiply: 0},
	{Restart_TXT: 0},
	{Ring: 0},
	{Rope: 0},
	{SCORE: 0},
	{shine1: 0},
	{shine2: 0},
	{Shine3: 0},
	{Shuffle_Button: 0},
	{Shuffle_icon: 0},
	{Sound_BTN: 0},
	{Sprite10: 0},
	{Sprite12: 0},
	{Sprite2: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sweep_Button: 0},
	{Time_TXT: 0},
	{YellowButton: 0},
	{YellowButton2: 0},
	{TitleLose: 0},
	{TitleLose2: 0},
	{Text: 0},
	{worldNum: 0},
	{levelOffset: 0},
	{worlds_icon: 0},
	{worlds_Targets: 0},
	{EndLevel_TXT2: 0},
	{EndLevel_TXT3: 0},
	{EndLevel_TXT4: 0},
	{EndLevel_TXT5: 0},
	{EndLevel_TXT6: 0},
	{EndLevel_TXT7: 0},
	{EndLevel_TXT8: 0},
	{EndLevel_TXT9: 0},
	{EndLevel_TXT10: 0},
	{EndLevel_TXT11: 0},
	{Menu2: 0},
	{BOTTOM: 0},
	{BOTTOM2: 0},
	{BOTTOM3: 0},
	{BOTTOM4: 0},
	{Bottom5: 0},
	{Cannon: 0},
	{Cannon2: 0},
	{Cannon2_world_popup: 0},
	{Cannon_popUp_items: 0},
	{Carpet: 0},
	{Carpet2: 0},
	{Castle: 0},
	{Castle2: 0},
	{Castle2_world_popup: 0},
	{Castle_popUp_items: 0},
	{Ceiling: 0},
	{chandelier: 0},
	{Cherries: 0},
	{Cherries2: 0},
	{Cherries2_popUp_items: 0},
	{Cherries_popUp_items: 0},
	{Couldron: 0},
	{Couldron2: 0},
	{Couldron2_world_popup: 0},
	{Couldron_popUp_items: 0},
	{Curtains: 0},
	{Curtains2: 0},
	{Flowers: 0},
	{Flowers2: 0},
	{Flowers3: 0},
	{Fork: 0},
	{Fork2: 0},
	{Fork2_world_popup: 0},
	{Fork_popUp_items: 0},
	{FountainPen: 0},
	{FountainPen2: 0},
	{FountainPen2_world_popup: 0},
	{FountainPen_popUp_items: 0},
	{FRAME2: 0},
	{Glow_effect2: 0},
	{levelIndex: 0},
	{PC_size_x: 0},
	{PC_size_y: 0},
	{open: 0},
	{Level_BTN: 0},
	{Level_BTN2: 0},
	{LockedLevel: 0},
	{LOWERCHAIR: 0},
	{Mist: 0},
	{OpenBook: 0},
	{OpenBook2: 0},
	{OpenBook2_world_popup: 0},
	{OpenBook_popUp_items: 0},
	{Pan: 0},
	{Pan2: 0},
	{Pan2_world_popup: 0},
	{Pan_popUp_items: 0},
	{Orbit: 0},
	{Particles2: 0},
	{Pot: 0},
	{Pot2: 0},
	{Pot_popUp_items: 0},
	{Potion: 0},
	{Potion2: 0},
	{Potion2_world_popup: 0},
	{Potion_popUp_items: 0},
	{pots: 0},
	{QuillAndInk: 0},
	{QuillAndInk2: 0},
	{QuillAndInk2_world_popup: 0},
	{QuillAndInk_popUp_items: 0},
	{ROOF: 0},
	{roof2: 0},
	{Sad_King: 0},
	{ScreenLightFromWindow: 0},
	{Stairs: 0},
	{Stairs2: 0},
	{Throne: 0},
	{TOP: 0},
	{TOP2: 0},
	{TopShelf: 0},
	{TOPSHLEF: 0},
	{UPPERLEAFS: 0},
	{WOODENLEFT: 0},
	{WorldIcons0: 0},
	{WorldIcons1: 0},
	{WorldIcons2: 0},
	{WorldIcons3: 0},
	{WorldIcons4: 0},
	{Castle_popUp_items2: 0},
	{Cannon_popUp_items2: 0},
	{Cannon_popUp_items3: 0},
	{Castle_popUp_items3: 0},
	{Castle_popUp_items4: 0},
	{Cannon_popUp_items4: 0},
	{Castle_popUp_items5: 0},
	{Cannon_popUp_items5: 0},
	{Cannon_popUp_items9: 0},
	{Cannon_popUp_items10: 0},
	{Cannon_popUp_items11: 0},
	{Castle2_world_popup2: 0},
	{Cannon2_world_popup2: 0},
	{Castle2_world_popup3: 0},
	{Cannon2_world_popup3: 0},
	{Cannon2_world_popup4: 0},
	{Castle2_world_popup4: 0},
	{Cannon2_world_popup5: 0},
	{Castle2_world_popup5: 0},
	{Cannon2_world_popup6: 0},
	{Castle2_world_popup6: 0},
	{Cannon2_world_popup7: 0},
	{Castle2_world_popup7: 0},
	{Cannon2_world_popup8: 0},
	{Armchair: 0},
	{ArmchairBack: 0},
	{ArmorL: 0},
	{ArmorL2: 0},
	{ArmorR: 0},
	{ArmorR2: 0},
	{Bed: 0},
	{Bed2: 0},
	{chapelFrame: 0},
	{chapelFrame2: 0},
	{comcom: 0},
	{Curtains3: 0},
	{Curtains4: 0},
	{Fireplace: 0},
	{Fireplace2: 0},
	{front: 0},
	{FrontMobileLevelSelect: 0},
	{metalGear: 0},
	{metalGear2: 0},
	{navel: 0},
	{pump: 0},
	{pump2: 0},
	{"Scholar’sChamber": 0},
	{StatueR: 0},
	{StatueRCopy: 0},
	{theNavePortrat: 0},
	{Cannon_popUp_items6: 0},
	{Cannon_popUp_items7: 0},
	{Castle_popUp_items6: 0},
	{Castle_popUp_items7: 0},
	{Cannon2_world_popup9: 0},
	{Cannon2_world_popup10: 0},
	{Cannon2_world_popup11: 0},
	{AJAX: 0},
	{Audio: 0},
	{Browser: 0},
	{ChestPoint: 0},
	{Coin_spawner: 0},
	{Coin_spawner2: 0},
	{Confetti: 0},
	{Confetti2: 0},
	{Destroyer: 0},
	{ItemUI: 0},
	{ItemUI2: 0},
	{ItemUI_Lose: 0},
	{King_spawner: 0},
	{Anchor: 0},
	{King_spawner_Mobile: 0},
	{Keyboard: 0},
	{levelsArray: 0},
	{LevelsParent0: 0},
	{LevelsParent0_P: 0},
	{LevelsParent1: 0},
	{LevelsParent1_P: 0},
	{LevelsParent2: 0},
	{LevelsParent2_P: 0},
	{LevelsParent3: 0},
	{LevelsParent3_P: 0},
	{LevelsParent4: 0},
	{LevelsParent4_P: 0},
	{LevelsParent5: 0},
	{LevelsParent5_P: 0},
	{LevelsParent6: 0},
	{LevelsParent6_P: 0},
	{LevelsParent7: 0},
	{LevelsParent7_P: 0},
	{LevelsParent8: 0},
	{LevelsParent8_P: 0},
	{LevelsParent9: 0},
	{LevelsParent9_P: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{NewWorldsLevels_Array: 0},
	{NumTextHolder: 0},
	{Particles_confetti: 0},
	{Particles_Dust: 0},
	{Particles_Shine: 0},
	{Physics: 0},
	{PhysicsManager: 0},
	{Placement_Array: 0},
	{PlatformInfo: 0},
	{Reset_Button: 0},
	{Touch: 0},
	{Trumpet_spawner: 0},
	{WorldsParent0: 0},
	{WorldsParent0_P: 0},
	{WorldsParent1: 0},
	{WorldsParent1_P: 0},
	{WorldsParent2: 0},
	{WorldsParent2_P: 0},
	{WorldsParent3: 0},
	{WorldsParent3_P: 0},
	{WorldsParent4: 0},
	{WorldsParent4_P: 0},
	{LevelsParent10_P: 0},
	{LevelsParent11_P: 0},
	{LevelsParent12_P: 0},
	{LevelsParent13_P: 0},
	{LevelsParent14_P: 0},
	{LevelsParent15_P: 0},
	{LevelsParent16_P: 0},
	{LevelsParent17_P: 0},
	{LevelsParent18_P: 0},
	{LevelsParent19_P: 0},
	{WorldsParent5: 0},
	{WorldsParent5_P: 0},
	{WorldsParent6: 0},
	{WorldsParent6_P: 0},
	{WorldsParent7: 0},
	{WorldsParent7_P: 0},
	{WorldsParent8: 0},
	{WorldsParent8_P: 0},
	{WorldsParent9: 0},
	{WorldsParent9_P: 0},
	{LevelsParent10: 0},
	{LevelsParent11: 0},
	{LevelsParent12: 0},
	{LevelsParent13: 0},
	{LevelsParent14: 0},
	{LevelsParent15: 0},
	{LevelsParent16: 0},
	{LevelsParent17: 0},
	{LevelsParent18: 0},
	{LevelsParent19: 0},
	{UI_Opacity: 0},
	{playerstats: 0},
	{findable: 0},
	{ui: 0},
	{items_0: 0},
	{items_1: 0},
	{items_2: 0},
	{items_3: 0},
	{items_4: 0},
	{items_5: 0},
	{items_6: 0},
	{items_7: 0},
	{items_8: 0},
	{items_9: 0},
	{Cheat: 0},
	{codeNumber: 0},
	{cheat1: 0},
	{cheat2: 0},
	{cheat3: 0},
	{cheat4: 0},
	{cheat5: 0},
	{Door_landscape: 0},
	{Door_spawner: 0},
	{Door_spawner_P: 0},
	{DoorPort: 0},
	{anchor: 0},
	{Blackscreen_Rotate: 0},
	{RotateScreen: 0},
	{Text2: 0},
	{Message: 0},
	{WinPopParent_0: 0},
	{WinPopParent_1: 0},
	{WinPopParent_2: 0},
	{WinPopParent_3: 0},
	{WinPopParent_4: 0},
	{WinPopParent_5: 0},
	{WinPopParent_6: 0},
	{WinPopParent_7: 0},
	{WinPopParent_8: 0},
	{WinPopParent_9: 0},
	{WinPopParentP_0: 0},
	{WinPopParentP_1: 0},
	{WinPopParentP_2: 0},
	{WinPopParentP_3: 0},
	{WinPopParentP_4: 0},
	{WinPopParentP_5: 0},
	{WinPopParentP_6: 0},
	{WinPopParentP_7: 0},
	{WinPopParentP_8: 0},
	{WinPopParentP_9: 0},
	{LosePopParentP_0: 0},
	{LosePopParentP_1: 0},
	{LosePopParentP_2: 0},
	{LosePopParentP_3: 0},
	{LosePopParentP_4: 0},
	{LosePopParentP_5: 0},
	{LosePopParentP_6: 0},
	{LosePopParentP_7: 0},
	{LosePopParentP_8: 0},
	{LosePopParentP_9: 0},
	{LosePopParent_0: 0},
	{LosePopParent_1: 0},
	{LosePopParent_2: 0},
	{LosePopParent_3: 0},
	{LosePopParent_4: 0},
	{LosePopParent_5: 0},
	{LosePopParent_6: 0},
	{LosePopParent_7: 0},
	{LosePopParent_8: 0},
	{LosePopParent_9: 0},
	{sizeOverlaper: 0},
	{sizeOverlaper2: 0},
	{yForMenu: 0},
	{vingette: 0},
	{PressEffectCircle: 0},
	{WoodenPlank: 0},
	{WoodenPlankCopy: 0},
	{Sprite4: 0},
	{rope2: 0},
	{Items: 0},
	{BGs_LS: 0},
	{LevelsParents: 0},
	{WorldsIcons: 0},
	{Worldsparents: 0},
	{RV_Buttons: 0},
	{Pops: 0},
	{WinPops: 0},
	{LosePops: 0},
	{KIngs: 0},
	{PopUp_items: 0},
	{Treasue_lights: 0},
	{Treasure: 0},
	{End_world_texts: 0},
	{Buttons: 0},
	{BoostersIcons: 0},
	{NextWorlds: 0},
	{cheating: 0},
	{AllBGS: 0},
	{Trumpets: 0},
	{mobile: 0},
	{platform: 0},
	{Local_ID: 0},
	{IsFullScreenAllowed: 0},
	{IsAdsAllowed: 0},
	{localID: 0},
	{GoogleAd_timeLimit: 0},
	{jsonFinished: 0},
	{itemToFind: 0},
	{itemToFind2: 0},
	{itemToFind3: 0},
	{amountToFind: 0},
	{amountToFind2: 0},
	{amountToFind3: 0},
	{itemsToFindCount: 0},
	{itemsToFindCount2: 0},
	{itemsToFindCount3: 0},
	{sweepAmount: 0},
	{hintAmount: 0},
	{shuffleAmount: 0},
	{maxItemsLevel: 0},
	{Level: 0},
	{levelTime: 0},
	{coins: 0},
	{gameOver: 0},
	{popOpen: 0},
	{shouldKing: 0},
	{shuffeling: 0},
	{allItemsFound: 0},
	{allItemsFound2: 0},
	{allItemsFound3: 0},
	{kingsFrame: 0},
	{popUpSizeAdder: 0},
	{justRVed: 0},
	{shouldSequance: 0},
	{gameCompleted: 0},
	{CurrScale: 0},
	{xOffset: 0},
	{yOffset: 0},
	{loopIndexFA: 0},
	{width: 0},
	{height: 0},
	{points: 0},
	{pointX: 0},
	{pointY: 0},
	{loop_index: 0},
	{checkAgain: 0},
	{shouldCreate: 0},
	{popKind: 0},
	{price: 0},
	{lastOfWorld: 0},
	{on: 0},
	{dist: 0},
	{boostersTargetY: 0},
	{RV_type: 0},
	{RV_create_attempts: 0},
	{ads: 0},
	{RV_ready: 0},
	{RV_play: 0},
	{Interstitial_Type: 0},
	{DidUseRv: 0},
	{rvAttempts: 0},
	{CanAds: 0},
	{IsDone: 0},
	{Type: 0},
	{type: 0},
	{name: 0},
	{mute: 0},
	{save_score: 0},
	{score: 0},
	{return: 0},
	{item: 0},
	{value: 0},
	{SFX: 0},
	{music: 0},
	{Sound: 0},
	{kind: 0},
	{world: 0},
	{opendLevel: 0},
	{worldCount: 0},
	{maxLevel: 0},
	{lastWorld: 0},
	{rightArrow: 0},
	{totalWidth: 0},
	{remainder: 0},
	{space: 0},
	{lastPlacedX: 0},
	{marker_coordinates: 0},
	{menuOpen: 0},
	{ENABLE_CHEATS: 0},
	{ItemsToPlaceOverride: 0},
	{UnlockedLevels: 0},
	{ClearCacheOnLoad: 0},
	{InfiniteHints: 0},
	{InfiniteTime: 0},
	{cheatCode: 0},
	{cheat_open_levels: 0}
];

self.InstanceType = {
	Chest: class extends self.ISpriteInstance {},
	Chest_light_1: class extends self.ISpriteInstance {},
	Chest_light_2: class extends self.ISpriteInstance {},
	Chest_light_3: class extends self.ISpriteInstance {},
	Coin_1: class extends self.ISpriteInstance {},
	Coin_2: class extends self.ISpriteInstance {},
	Coin_3: class extends self.ISpriteInstance {},
	Coin_4: class extends self.ISpriteInstance {},
	Coin_5: class extends self.ISpriteInstance {},
	Coin_6: class extends self.ISpriteInstance {},
	gem_1: class extends self.ISpriteInstance {},
	Gem_2: class extends self.ISpriteInstance {},
	Glow_effect3: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	shine: class extends self.ISpriteInstance {},
	clean_Board_Icon_Chest: class extends self.ISpriteInstance {},
	coin2: class extends self.ISpriteInstance {},
	Hint_icon_Chest: class extends self.ISpriteInstance {},
	Shuffle_icon_Chest: class extends self.ISpriteInstance {},
	Axe2: class extends self.ISpriteInstance {},
	Axe_popUp_items: class extends self.ISpriteInstance {},
	Axe_world_popup: class extends self.ISpriteInstance {},
	AllTheKitchenToolsAreFoundTimeToWhipUpARoyalFeast: class extends self.ISpriteInstance {},
	ClaimBTN: class extends self.ISpriteInstance {},
	Continue_BTN: class extends self.ISpriteInstance {},
	COINS_BTN: class extends self.ISpriteInstance {},
	COINS_BTN2: class extends self.ISpriteInstance {},
	End_world_text_0: class extends self.ISpriteInstance {},
	End_world_text_1: class extends self.ISpriteInstance {},
	End_world_text_2: class extends self.ISpriteInstance {},
	End_world_text_3: class extends self.ISpriteInstance {},
	End_world_text_4: class extends self.ISpriteInstance {},
	EveryHiddenItemIsFoundTheGroundsAreReadyForARoyalStroll: class extends self.ISpriteInstance {},
	__InvalidName0__: class extends self.ISpriteInstance {},
	GET200COINS: class extends self.ISpriteInstance {},
	Get30SecPink: class extends self.ISpriteInstance {},
	Get_BTN: class extends self.ISpriteInstance {},
	GreenFrame: class extends self.ISpriteInstance {},
	Group: class extends self.ISpriteInstance {},
	Group_world_popup: class extends self.ISpriteInstance {},
	happyHappyKing: class extends self.ISpriteInstance {},
	HappyKing: class extends self.ISpriteInstance {},
	Hint_pop: class extends self.ISpriteInstance {},
	Jumping_King: class extends self.ISpriteInstance {},
	Knife: class extends self.ISpriteInstance {},
	Knife2: class extends self.ISpriteInstance {},
	Knife2_world_popup: class extends self.ISpriteInstance {},
	Knife_popUp_items: class extends self.ISpriteInstance {},
	LosePop_0: class extends self.ISpriteInstance {},
	LosePop_1: class extends self.ISpriteInstance {},
	LosePop_2: class extends self.ISpriteInstance {},
	LosePop_3: class extends self.ISpriteInstance {},
	LosePop_4: class extends self.ISpriteInstance {},
	mortarAndPestle: class extends self.ISpriteInstance {},
	mortarAndPestle2: class extends self.ISpriteInstance {},
	mortarAndPestle2_world_popup: class extends self.ISpriteInstance {},
	mortarAndPestle_popUp_items: class extends self.ISpriteInstance {},
	Next_BTN: class extends self.ISpriteInstance {},
	NextBTN_Worlds: class extends self.ISpriteInstance {},
	NORVItemsPopUP: class extends self.ISpriteInstance {},
	NORVPopUpBoardClean: class extends self.ISpriteInstance {},
	NoRVShuffleBoosterBackPopup: class extends self.ISpriteInstance {},
	NotEnoughCoins_Popup: class extends self.ISpriteInstance {},
	outOfTimeTitle: class extends self.ISpriteInstance {},
	popupTitle: class extends self.ISpriteInstance {},
	ShieldSwords: class extends self.ISpriteInstance {},
	ShieldSwords2: class extends self.ISpriteInstance {},
	ShieldSwords2_world_popup: class extends self.ISpriteInstance {},
	ShieldSwords_popUp_items: class extends self.ISpriteInstance {},
	Shuffle_Pop: class extends self.ISpriteInstance {},
	Sweep_pop: class extends self.ISpriteInstance {},
	__InvalidName1__: class extends self.ISpriteInstance {},
	__InvalidName2__: class extends self.ISpriteInstance {},
	TITLEPOPUP: class extends self.ISpriteInstance {},
	TITLEPOPUP2: class extends self.ISpriteInstance {},
	Trophy: class extends self.ISpriteInstance {},
	Trumpet: class extends self.ISpriteInstance {},
	Trumpet2: class extends self.ISpriteInstance {},
	Trumpet2_popUp_items: class extends self.ISpriteInstance {},
	Trumpet3: class extends self.ISpriteInstance {},
	Trumpet3_world_popup: class extends self.ISpriteInstance {},
	Trumpet4: class extends self.ISpriteInstance {},
	Trumpet4_world_popup: class extends self.ISpriteInstance {},
	Trumpet5: class extends self.ISpriteInstance {},
	Trumpet_popUp_items: class extends self.ISpriteInstance {},
	V: class extends self.ISpriteInstance {},
	WinPop_0: class extends self.ISpriteInstance {},
	WinPop_1: class extends self.ISpriteInstance {},
	WinPop_2: class extends self.ISpriteInstance {},
	WinPop_3: class extends self.ISpriteInstance {},
	WinPop_4: class extends self.ISpriteInstance {},
	WorldWinParent_0: class extends self.ISpriteInstance {},
	WorldWinParent_1: class extends self.ISpriteInstance {},
	WorldWinParent_2: class extends self.ISpriteInstance {},
	WorldWinParent_3: class extends self.ISpriteInstance {},
	WorldWinParent_4: class extends self.ISpriteInstance {},
	X3FOR: class extends self.ISpriteInstance {},
	X9FOR: class extends self.ISpriteInstance {},
	xButton: class extends self.ISpriteInstance {},
	xButton_2ndPop: class extends self.ISpriteInstance {},
	__InvalidName3__: class extends self.ISpriteInstance {},
	WinPop_5: class extends self.ISpriteInstance {},
	Axe_popUp_items2: class extends self.ISpriteInstance {},
	WinPop_6: class extends self.ISpriteInstance {},
	Axe_popUp_items3: class extends self.ISpriteInstance {},
	WinPop_8: class extends self.ISpriteInstance {},
	Axe_popUp_items4: class extends self.ISpriteInstance {},
	WinPop_9: class extends self.ISpriteInstance {},
	Axe_popUp_items5: class extends self.ISpriteInstance {},
	LosePop_5: class extends self.ISpriteInstance {},
	LosePop_6: class extends self.ISpriteInstance {},
	LosePop_7: class extends self.ISpriteInstance {},
	LosePop_8: class extends self.ISpriteInstance {},
	LosePop_9: class extends self.ISpriteInstance {},
	Axe_popUp_items8: class extends self.ISpriteInstance {},
	WorldWinParent_5: class extends self.ISpriteInstance {},
	Axe_world_popup2: class extends self.ISpriteInstance {},
	End_world_text_5: class extends self.ISpriteInstance {},
	WorldWinParent_6: class extends self.ISpriteInstance {},
	End_world_text_6: class extends self.ISpriteInstance {},
	Axe_world_popup3: class extends self.ISpriteInstance {},
	WorldWinParent_80: class extends self.ISpriteInstance {},
	Axe_world_popup4: class extends self.ISpriteInstance {},
	End_world_text_7: class extends self.ISpriteInstance {},
	WorldWinParent_8: class extends self.ISpriteInstance {},
	End_world_text_8: class extends self.ISpriteInstance {},
	Axe_world_popup5: class extends self.ISpriteInstance {},
	WorldWinParent_7: class extends self.ISpriteInstance {},
	End_world_text_9: class extends self.ISpriteInstance {},
	Axe_world_popup6: class extends self.ISpriteInstance {},
	Axe_world_popup7: class extends self.ISpriteInstance {},
	WorldWinParent_9: class extends self.ISpriteInstance {},
	End_world_text_10: class extends self.ISpriteInstance {},
	Axe_world_popup8: class extends self.ISpriteInstance {},
	NextWorldStart_1: class extends self.ISpriteInstance {},
	NextWorldStart_2: class extends self.ISpriteInstance {},
	NextWorldStart_3: class extends self.ISpriteInstance {},
	NextWorldStart_4: class extends self.ISpriteInstance {},
	NextWorldStart_5: class extends self.ISpriteInstance {},
	NextWorldStart_6: class extends self.ISpriteInstance {},
	NextWorldStart_7: class extends self.ISpriteInstance {},
	NextWorldStart_8: class extends self.ISpriteInstance {},
	NextWorldStart_9: class extends self.ISpriteInstance {},
	NextWorldStart_10: class extends self.ISpriteInstance {},
	NextWorldStart_11: class extends self.ISpriteInstance {},
	WinPop_7: class extends self.ISpriteInstance {},
	Axe_popUp_items9: class extends self.ISpriteInstance {},
	Trumpet_popUp_items2: class extends self.ISpriteInstance {},
	Trumpet4_world_popup2: class extends self.ISpriteInstance {},
	GreenFrame2: class extends self.ISpriteInstance {},
	V2: class extends self.ISpriteInstance {},
	Axe_world_popup9: class extends self.ISpriteInstance {},
	Axe_world_popup10: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	BG2: class extends self.ISpriteInstance {},
	BG3: class extends self.ISpriteInstance {},
	BG4: class extends self.ISpriteInstance {},
	BG5: class extends self.ISpriteInstance {},
	BGCourtyard: class extends self.ISpriteInstance {},
	BGEnchanters: class extends self.ISpriteInstance {},
	BGKitchen: class extends self.ISpriteInstance {},
	BGLibrary: class extends self.ISpriteInstance {},
	BGPortrait: class extends self.ISpriteInstance {},
	BGThroneRoom: class extends self.ISpriteInstance {},
	Game_BG0: class extends self.ISpriteInstance {},
	Game_BG0_P: class extends self.ISpriteInstance {},
	Game_BG1: class extends self.ISpriteInstance {},
	Game_BG1_P: class extends self.ISpriteInstance {},
	Game_BG2: class extends self.ISpriteInstance {},
	Game_BG2_P: class extends self.ISpriteInstance {},
	Game_BG3: class extends self.ISpriteInstance {},
	Game_BG3_P: class extends self.ISpriteInstance {},
	Game_BG4: class extends self.ISpriteInstance {},
	Game_BG4_P: class extends self.ISpriteInstance {},
	Game_BGSpalsh: class extends self.ISpriteInstance {},
	Game_BG5: class extends self.ISpriteInstance {},
	Game_BG5_P: class extends self.ISpriteInstance {},
	Game_BG6: class extends self.ISpriteInstance {},
	Game_BG6_P: class extends self.ISpriteInstance {},
	Game_BG7: class extends self.ISpriteInstance {},
	Game_BG7_P: class extends self.ISpriteInstance {},
	Game_BG8_P: class extends self.ISpriteInstance {},
	Game_BG8: class extends self.ISpriteInstance {},
	Game_BG9: class extends self.ISpriteInstance {},
	Game_BG9_P: class extends self.ISpriteInstance {},
	backgroundOfPortrait: class extends self.ISpriteInstance {},
	BackMobileLevelSelect: class extends self.ISpriteInstance {},
	backWall: class extends self.ISpriteInstance {},
	BelltowerLevelSelector: class extends self.ISpriteInstance {},
	BG6: class extends self.ISpriteInstance {},
	BG7: class extends self.ISpriteInstance {},
	BG8: class extends self.ISpriteInstance {},
	BG9: class extends self.ISpriteInstance {},
	BGWATCHTOWERLevelSelectorPortraite: class extends self.ISpriteInstance {},
	chapelBG: class extends self.ISpriteInstance {},
	Game_BGSpalsh2: class extends self.ISpriteInstance {},
	Air_particales: class extends self.IParticlesInstance {},
	_9patch: class extends self.IWorldInstance {},
	boosterNum2: class extends self.ISpriteInstance {},
	BlackScreen: class extends self.ISpriteInstance {},
	BorderPortrait: class extends self.ISpriteInstance {},
	Axe: class extends self.ISpriteInstance {},
	boosterNum: class extends self.ISpriteInstance {},
	clean_Board_Icon: class extends self.ISpriteInstance {},
	CloseMenuBTN: class extends self.ISpriteInstance {},
	backOfBoosters: class extends self.ISpriteInstance {},
	backOfHintsPortrait: class extends self.ISpriteInstance {},
	Coins_TXT: class extends self.ITextInstance {},
	Exit_BTN: class extends self.ISpriteInstance {},
	EndLevel_TXT: class extends self.ITextInstance {},
	FINDINGBAR: class extends self.ISpriteInstance {},
	Frame: class extends self.ISpriteInstance {},
	FullScreen_BTN: class extends self.ISpriteInstance {},
	GameEndTitle_TXT: class extends self.ITextInstance {},
	greenButton: class extends self.ISpriteInstance {},
	Highlight: class extends self.ISpriteInstance {},
	Highlight2: class extends self.ISpriteInstance {},
	Highlight3: class extends self.ISpriteInstance {},
	Hint_Button: class extends self.ISpriteInstance {},
	Hint_icon: class extends self.ISpriteInstance {},
	ItemsLeft_TXT: class extends self.ITextInstance {},
	LEVEL2: class extends self.ISpriteInstance {},
	Level_TXT: class extends self.ITextInstance {},
	levelNum_TXT: class extends self.ITextInstance {},
	Logo: class extends self.ISpriteInstance {},
	Light_particles: class extends self.IParticlesInstance {},
	Menu: class extends self.ISpriteInstance {},
	Menu_BTN: class extends self.ISpriteInstance {},
	Music_BTN: class extends self.ISpriteInstance {},
	play_Button: class extends self.ISpriteInstance {},
	PlayAgain_BTN: class extends self.ISpriteInstance {},
	playAgainBTN: class extends self.ISpriteInstance {},
	PressEffectGETMultiply: class extends self.ISpriteInstance {},
	PressEffectLevelMultiply: class extends self.ISpriteInstance {},
	PressEffectMoneyMultiply: class extends self.ISpriteInstance {},
	Restart_TXT: class extends self.ITextInstance {},
	Ring: class extends self.ISpriteInstance {},
	Rope: class extends self.ISpriteInstance {},
	SCORE: class extends self.ISpriteInstance {},
	shine1: class extends self.ISpriteInstance {},
	shine2: class extends self.ISpriteInstance {},
	Shine3: class extends self.ISpriteInstance {},
	Shuffle_Button: class extends self.ISpriteInstance {},
	Shuffle_icon: class extends self.ISpriteInstance {},
	Sound_BTN: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sweep_Button: class extends self.ISpriteInstance {},
	Time_TXT: class extends self.ITextInstance {},
	YellowButton: class extends self.ISpriteInstance {},
	YellowButton2: class extends self.ISpriteInstance {},
	TitleLose: class extends self.ISpriteInstance {},
	TitleLose2: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	worlds_icon: class extends self.ISpriteInstance {},
	worlds_Targets: class extends self.ISpriteInstance {},
	EndLevel_TXT2: class extends self.ITextInstance {},
	EndLevel_TXT3: class extends self.ITextInstance {},
	EndLevel_TXT4: class extends self.ITextInstance {},
	EndLevel_TXT5: class extends self.ITextInstance {},
	EndLevel_TXT6: class extends self.ITextInstance {},
	EndLevel_TXT7: class extends self.ITextInstance {},
	EndLevel_TXT8: class extends self.ITextInstance {},
	EndLevel_TXT9: class extends self.ITextInstance {},
	EndLevel_TXT10: class extends self.ITextInstance {},
	EndLevel_TXT11: class extends self.ITextInstance {},
	Menu2: class extends self.ISpriteInstance {},
	BOTTOM: class extends self.ISpriteInstance {},
	BOTTOM2: class extends self.ISpriteInstance {},
	BOTTOM3: class extends self.ISpriteInstance {},
	BOTTOM4: class extends self.ISpriteInstance {},
	Bottom5: class extends self.ISpriteInstance {},
	Cannon: class extends self.ISpriteInstance {},
	Cannon2: class extends self.ISpriteInstance {},
	Cannon2_world_popup: class extends self.ISpriteInstance {},
	Cannon_popUp_items: class extends self.ISpriteInstance {},
	Carpet: class extends self.ISpriteInstance {},
	Carpet2: class extends self.ISpriteInstance {},
	Castle: class extends self.ISpriteInstance {},
	Castle2: class extends self.ISpriteInstance {},
	Castle2_world_popup: class extends self.ISpriteInstance {},
	Castle_popUp_items: class extends self.ISpriteInstance {},
	Ceiling: class extends self.ISpriteInstance {},
	chandelier: class extends self.ISpriteInstance {},
	Cherries: class extends self.ISpriteInstance {},
	Cherries2: class extends self.ISpriteInstance {},
	Cherries2_popUp_items: class extends self.ISpriteInstance {},
	Cherries_popUp_items: class extends self.ISpriteInstance {},
	Couldron: class extends self.ISpriteInstance {},
	Couldron2: class extends self.ISpriteInstance {},
	Couldron2_world_popup: class extends self.ISpriteInstance {},
	Couldron_popUp_items: class extends self.ISpriteInstance {},
	Curtains: class extends self.ISpriteInstance {},
	Curtains2: class extends self.ISpriteInstance {},
	Flowers: class extends self.ISpriteInstance {},
	Flowers2: class extends self.ISpriteInstance {},
	Flowers3: class extends self.ISpriteInstance {},
	Fork: class extends self.ISpriteInstance {},
	Fork2: class extends self.ISpriteInstance {},
	Fork2_world_popup: class extends self.ISpriteInstance {},
	Fork_popUp_items: class extends self.ISpriteInstance {},
	FountainPen: class extends self.ISpriteInstance {},
	FountainPen2: class extends self.ISpriteInstance {},
	FountainPen2_world_popup: class extends self.ISpriteInstance {},
	FountainPen_popUp_items: class extends self.ISpriteInstance {},
	FRAME2: class extends self.ISpriteInstance {},
	Glow_effect2: class extends self.ISpriteInstance {},
	Level_BTN: class extends self.ISpriteInstance {},
	Level_BTN2: class extends self.ISpriteInstance {},
	LockedLevel: class extends self.ISpriteInstance {},
	LOWERCHAIR: class extends self.ISpriteInstance {},
	Mist: class extends self.IParticlesInstance {},
	OpenBook: class extends self.ISpriteInstance {},
	OpenBook2: class extends self.ISpriteInstance {},
	OpenBook2_world_popup: class extends self.ISpriteInstance {},
	OpenBook_popUp_items: class extends self.ISpriteInstance {},
	Pan: class extends self.ISpriteInstance {},
	Pan2: class extends self.ISpriteInstance {},
	Pan2_world_popup: class extends self.ISpriteInstance {},
	Pan_popUp_items: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Pot: class extends self.ISpriteInstance {},
	Pot2: class extends self.ISpriteInstance {},
	Pot_popUp_items: class extends self.ISpriteInstance {},
	Potion: class extends self.ISpriteInstance {},
	Potion2: class extends self.ISpriteInstance {},
	Potion2_world_popup: class extends self.ISpriteInstance {},
	Potion_popUp_items: class extends self.ISpriteInstance {},
	pots: class extends self.ISpriteInstance {},
	QuillAndInk: class extends self.ISpriteInstance {},
	QuillAndInk2: class extends self.ISpriteInstance {},
	QuillAndInk2_world_popup: class extends self.ISpriteInstance {},
	QuillAndInk_popUp_items: class extends self.ISpriteInstance {},
	ROOF: class extends self.ISpriteInstance {},
	roof2: class extends self.ISpriteInstance {},
	Sad_King: class extends self.ISpriteInstance {},
	ScreenLightFromWindow: class extends self.ISpriteInstance {},
	Stairs: class extends self.ISpriteInstance {},
	Stairs2: class extends self.ISpriteInstance {},
	Throne: class extends self.ISpriteInstance {},
	TOP: class extends self.ISpriteInstance {},
	TOP2: class extends self.ISpriteInstance {},
	TopShelf: class extends self.ISpriteInstance {},
	TOPSHLEF: class extends self.ISpriteInstance {},
	UPPERLEAFS: class extends self.ISpriteInstance {},
	WOODENLEFT: class extends self.ISpriteInstance {},
	WorldIcons0: class extends self.ISpriteInstance {},
	WorldIcons1: class extends self.ISpriteInstance {},
	WorldIcons2: class extends self.ISpriteInstance {},
	WorldIcons3: class extends self.ISpriteInstance {},
	WorldIcons4: class extends self.ISpriteInstance {},
	Castle_popUp_items2: class extends self.ISpriteInstance {},
	Cannon_popUp_items2: class extends self.ISpriteInstance {},
	Cannon_popUp_items3: class extends self.ISpriteInstance {},
	Castle_popUp_items3: class extends self.ISpriteInstance {},
	Castle_popUp_items4: class extends self.ISpriteInstance {},
	Cannon_popUp_items4: class extends self.ISpriteInstance {},
	Castle_popUp_items5: class extends self.ISpriteInstance {},
	Cannon_popUp_items5: class extends self.ISpriteInstance {},
	Cannon_popUp_items9: class extends self.ISpriteInstance {},
	Cannon_popUp_items10: class extends self.ISpriteInstance {},
	Cannon_popUp_items11: class extends self.ISpriteInstance {},
	Castle2_world_popup2: class extends self.ISpriteInstance {},
	Cannon2_world_popup2: class extends self.ISpriteInstance {},
	Castle2_world_popup3: class extends self.ISpriteInstance {},
	Cannon2_world_popup3: class extends self.ISpriteInstance {},
	Cannon2_world_popup4: class extends self.ISpriteInstance {},
	Castle2_world_popup4: class extends self.ISpriteInstance {},
	Cannon2_world_popup5: class extends self.ISpriteInstance {},
	Castle2_world_popup5: class extends self.ISpriteInstance {},
	Cannon2_world_popup6: class extends self.ISpriteInstance {},
	Castle2_world_popup6: class extends self.ISpriteInstance {},
	Cannon2_world_popup7: class extends self.ISpriteInstance {},
	Castle2_world_popup7: class extends self.ISpriteInstance {},
	Cannon2_world_popup8: class extends self.ISpriteInstance {},
	Armchair: class extends self.ISpriteInstance {},
	ArmchairBack: class extends self.ISpriteInstance {},
	ArmorL: class extends self.ISpriteInstance {},
	ArmorL2: class extends self.ISpriteInstance {},
	ArmorR: class extends self.ISpriteInstance {},
	ArmorR2: class extends self.ISpriteInstance {},
	Bed: class extends self.ISpriteInstance {},
	Bed2: class extends self.ISpriteInstance {},
	chapelFrame: class extends self.ISpriteInstance {},
	chapelFrame2: class extends self.ISpriteInstance {},
	comcom: class extends self.ISpriteInstance {},
	Curtains3: class extends self.ISpriteInstance {},
	Curtains4: class extends self.ISpriteInstance {},
	Fireplace: class extends self.ISpriteInstance {},
	Fireplace2: class extends self.ISpriteInstance {},
	front: class extends self.ISpriteInstance {},
	FrontMobileLevelSelect: class extends self.ISpriteInstance {},
	metalGear: class extends self.ISpriteInstance {},
	metalGear2: class extends self.ISpriteInstance {},
	navel: class extends self.ISpriteInstance {},
	pump: class extends self.ISpriteInstance {},
	pump2: class extends self.ISpriteInstance {},
	__InvalidName4__: class extends self.ISpriteInstance {},
	StatueR: class extends self.ISpriteInstance {},
	StatueRCopy: class extends self.ISpriteInstance {},
	theNavePortrat: class extends self.ISpriteInstance {},
	Cannon_popUp_items6: class extends self.ISpriteInstance {},
	Cannon_popUp_items7: class extends self.ISpriteInstance {},
	Castle_popUp_items6: class extends self.ISpriteInstance {},
	Castle_popUp_items7: class extends self.ISpriteInstance {},
	Cannon2_world_popup9: class extends self.ISpriteInstance {},
	Cannon2_world_popup10: class extends self.ISpriteInstance {},
	Cannon2_world_popup11: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	ChestPoint: class extends self.ISpriteInstance {},
	Coin_spawner: class extends self.ISpriteInstance {},
	Coin_spawner2: class extends self.ISpriteInstance {},
	Confetti: class extends self.ISpriteInstance {},
	Confetti2: class extends self.ISpriteInstance {},
	Destroyer: class extends self.ISpriteInstance {},
	ItemUI: class extends self.ISpriteInstance {},
	ItemUI2: class extends self.ISpriteInstance {},
	ItemUI_Lose: class extends self.ISpriteInstance {},
	King_spawner: class extends self.ISpriteInstance {},
	King_spawner_Mobile: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	levelsArray: class extends self.IArrayInstance {},
	LevelsParent0: class extends self.ISpriteInstance {},
	LevelsParent0_P: class extends self.ISpriteInstance {},
	LevelsParent1: class extends self.ISpriteInstance {},
	LevelsParent1_P: class extends self.ISpriteInstance {},
	LevelsParent2: class extends self.ISpriteInstance {},
	LevelsParent2_P: class extends self.ISpriteInstance {},
	LevelsParent3: class extends self.ISpriteInstance {},
	LevelsParent3_P: class extends self.ISpriteInstance {},
	LevelsParent4: class extends self.ISpriteInstance {},
	LevelsParent4_P: class extends self.ISpriteInstance {},
	LevelsParent5: class extends self.ISpriteInstance {},
	LevelsParent5_P: class extends self.ISpriteInstance {},
	LevelsParent6: class extends self.ISpriteInstance {},
	LevelsParent6_P: class extends self.ISpriteInstance {},
	LevelsParent7: class extends self.ISpriteInstance {},
	LevelsParent7_P: class extends self.ISpriteInstance {},
	LevelsParent8: class extends self.ISpriteInstance {},
	LevelsParent8_P: class extends self.ISpriteInstance {},
	LevelsParent9: class extends self.ISpriteInstance {},
	LevelsParent9_P: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	NewWorldsLevels_Array: class extends self.IArrayInstance {},
	NumTextHolder: class extends self.ISpriteInstance {},
	Particles_confetti: class extends self.IParticlesInstance {},
	Particles_Dust: class extends self.IParticlesInstance {},
	Particles_Shine: class extends self.IParticlesInstance {},
	PhysicsManager: class extends self.ISpriteInstance {},
	Placement_Array: class extends self.IArrayInstance {},
	PlatformInfo: class extends self.IInstance {},
	Reset_Button: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Trumpet_spawner: class extends self.ISpriteInstance {},
	WorldsParent0: class extends self.ISpriteInstance {},
	WorldsParent0_P: class extends self.ISpriteInstance {},
	WorldsParent1: class extends self.ISpriteInstance {},
	WorldsParent1_P: class extends self.ISpriteInstance {},
	WorldsParent2: class extends self.ISpriteInstance {},
	WorldsParent2_P: class extends self.ISpriteInstance {},
	WorldsParent3: class extends self.ISpriteInstance {},
	WorldsParent3_P: class extends self.ISpriteInstance {},
	WorldsParent4: class extends self.ISpriteInstance {},
	WorldsParent4_P: class extends self.ISpriteInstance {},
	LevelsParent10_P: class extends self.ISpriteInstance {},
	LevelsParent11_P: class extends self.ISpriteInstance {},
	LevelsParent12_P: class extends self.ISpriteInstance {},
	LevelsParent13_P: class extends self.ISpriteInstance {},
	LevelsParent14_P: class extends self.ISpriteInstance {},
	LevelsParent15_P: class extends self.ISpriteInstance {},
	LevelsParent16_P: class extends self.ISpriteInstance {},
	LevelsParent17_P: class extends self.ISpriteInstance {},
	LevelsParent18_P: class extends self.ISpriteInstance {},
	LevelsParent19_P: class extends self.ISpriteInstance {},
	WorldsParent5: class extends self.ISpriteInstance {},
	WorldsParent5_P: class extends self.ISpriteInstance {},
	WorldsParent6: class extends self.ISpriteInstance {},
	WorldsParent6_P: class extends self.ISpriteInstance {},
	WorldsParent7: class extends self.ISpriteInstance {},
	WorldsParent7_P: class extends self.ISpriteInstance {},
	WorldsParent8: class extends self.ISpriteInstance {},
	WorldsParent8_P: class extends self.ISpriteInstance {},
	WorldsParent9: class extends self.ISpriteInstance {},
	WorldsParent9_P: class extends self.ISpriteInstance {},
	LevelsParent10: class extends self.ISpriteInstance {},
	LevelsParent11: class extends self.ISpriteInstance {},
	LevelsParent12: class extends self.ISpriteInstance {},
	LevelsParent13: class extends self.ISpriteInstance {},
	LevelsParent14: class extends self.ISpriteInstance {},
	LevelsParent15: class extends self.ISpriteInstance {},
	LevelsParent16: class extends self.ISpriteInstance {},
	LevelsParent17: class extends self.ISpriteInstance {},
	LevelsParent18: class extends self.ISpriteInstance {},
	LevelsParent19: class extends self.ISpriteInstance {},
	UI_Opacity: class extends self.ISpriteInstance {},
	playerstats: class extends self.IArrayInstance {},
	items_0: class extends self.ISpriteInstance {},
	items_1: class extends self.ISpriteInstance {},
	items_2: class extends self.ISpriteInstance {},
	items_3: class extends self.ISpriteInstance {},
	items_4: class extends self.ISpriteInstance {},
	items_5: class extends self.ISpriteInstance {},
	items_6: class extends self.ISpriteInstance {},
	items_7: class extends self.ISpriteInstance {},
	items_8: class extends self.ISpriteInstance {},
	items_9: class extends self.ISpriteInstance {},
	Cheat: class extends self.ISpriteInstance {},
	cheat1: class extends self.ISpriteInstance {},
	cheat2: class extends self.ISpriteInstance {},
	cheat3: class extends self.ISpriteInstance {},
	cheat4: class extends self.ISpriteInstance {},
	cheat5: class extends self.ISpriteInstance {},
	Door_landscape: class extends self.ISpriteInstance {},
	Door_spawner: class extends self.ISpriteInstance {},
	Door_spawner_P: class extends self.ISpriteInstance {},
	DoorPort: class extends self.ISpriteInstance {},
	anchor: class extends self.ISpriteInstance {},
	Blackscreen_Rotate: class extends self.ISpriteInstance {},
	RotateScreen: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Message: class extends self.ISpriteInstance {},
	WinPopParent_0: class extends self.ISpriteInstance {},
	WinPopParent_1: class extends self.ISpriteInstance {},
	WinPopParent_2: class extends self.ISpriteInstance {},
	WinPopParent_3: class extends self.ISpriteInstance {},
	WinPopParent_4: class extends self.ISpriteInstance {},
	WinPopParent_5: class extends self.ISpriteInstance {},
	WinPopParent_6: class extends self.ISpriteInstance {},
	WinPopParent_7: class extends self.ISpriteInstance {},
	WinPopParent_8: class extends self.ISpriteInstance {},
	WinPopParent_9: class extends self.ISpriteInstance {},
	WinPopParentP_0: class extends self.ISpriteInstance {},
	WinPopParentP_1: class extends self.ISpriteInstance {},
	WinPopParentP_2: class extends self.ISpriteInstance {},
	WinPopParentP_3: class extends self.ISpriteInstance {},
	WinPopParentP_4: class extends self.ISpriteInstance {},
	WinPopParentP_5: class extends self.ISpriteInstance {},
	WinPopParentP_6: class extends self.ISpriteInstance {},
	WinPopParentP_7: class extends self.ISpriteInstance {},
	WinPopParentP_8: class extends self.ISpriteInstance {},
	WinPopParentP_9: class extends self.ISpriteInstance {},
	LosePopParentP_0: class extends self.ISpriteInstance {},
	LosePopParentP_1: class extends self.ISpriteInstance {},
	LosePopParentP_2: class extends self.ISpriteInstance {},
	LosePopParentP_3: class extends self.ISpriteInstance {},
	LosePopParentP_4: class extends self.ISpriteInstance {},
	LosePopParentP_5: class extends self.ISpriteInstance {},
	LosePopParentP_6: class extends self.ISpriteInstance {},
	LosePopParentP_7: class extends self.ISpriteInstance {},
	LosePopParentP_8: class extends self.ISpriteInstance {},
	LosePopParentP_9: class extends self.ISpriteInstance {},
	LosePopParent_0: class extends self.ISpriteInstance {},
	LosePopParent_1: class extends self.ISpriteInstance {},
	LosePopParent_2: class extends self.ISpriteInstance {},
	LosePopParent_3: class extends self.ISpriteInstance {},
	LosePopParent_4: class extends self.ISpriteInstance {},
	LosePopParent_5: class extends self.ISpriteInstance {},
	LosePopParent_6: class extends self.ISpriteInstance {},
	LosePopParent_7: class extends self.ISpriteInstance {},
	LosePopParent_8: class extends self.ISpriteInstance {},
	LosePopParent_9: class extends self.ISpriteInstance {},
	sizeOverlaper: class extends self.ISpriteInstance {},
	sizeOverlaper2: class extends self.ISpriteInstance {},
	yForMenu: class extends self.ISpriteInstance {},
	vingette: class extends self.ISpriteInstance {},
	PressEffectCircle: class extends self.ISpriteInstance {},
	WoodenPlank: class extends self.ISpriteInstance {},
	WoodenPlankCopy: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	rope2: class extends self.ISpriteInstance {},
	Items: class extends self.ISpriteInstance {},
	BGs_LS: class extends self.ISpriteInstance {},
	LevelsParents: class extends self.ISpriteInstance {},
	WorldsIcons: class extends self.ISpriteInstance {},
	Worldsparents: class extends self.ISpriteInstance {},
	RV_Buttons: class extends self.ISpriteInstance {},
	Pops: class extends self.ISpriteInstance {},
	WinPops: class extends self.ISpriteInstance {},
	LosePops: class extends self.ISpriteInstance {},
	KIngs: class extends self.ISpriteInstance {},
	PopUp_items: class extends self.ISpriteInstance {},
	Treasue_lights: class extends self.ISpriteInstance {},
	Treasure: class extends self.ISpriteInstance {},
	End_world_texts: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	BoostersIcons: class extends self.ISpriteInstance {},
	NextWorlds: class extends self.ISpriteInstance {},
	cheating: class extends self.ISpriteInstance {},
	AllBGS: class extends self.ISpriteInstance {},
	Trumpets: class extends self.ISpriteInstance {}
}