const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite,
		C3.Plugins.Particles,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Tween,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Behaviors.Fade,
		C3.Behaviors.Pin,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Spritefont2,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Text,
		C3.Plugins.Json,
		C3.Plugins.Keyboard,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.PickAll,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Bullet.Cnds.OnStep,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Bullet.Acts.Bounce,
		C3.Behaviors.Bullet.Acts.StopStepping,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Physics.Acts.CreateLimitedRevoluteJoint,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.OnResume,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.TiledBg.Exps.Count,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Browser.Acts.LoadStyleSheet,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Spritefont2.Acts.SetX,
		C3.Plugins.Spritefont2.Exps.X,
		C3.JavaScriptInEvents.Esglobal_Event3_Act1,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.JavaScriptInEvents.Esglobal_Event12_Act2,
		C3.JavaScriptInEvents.Esglobal_Event13_Act2,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.JavaScriptInEvents.Esglobal_Event17_Act1,
		C3.JavaScriptInEvents.Esglobal_Event18_Act1,
		C3.JavaScriptInEvents.Esglobal_Event19_Act1,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.JavaScriptInEvents.Esglobal_Event20_Act2,
		C3.JavaScriptInEvents.Esglobal_Event21_Act1,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.Browser.Exps.Language,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Exps.AnimationFrame
	];
};
self.C3_JsPropNameTable = [
	{Anchor: 0},
	{Background: 0},
	{BackRock: 0},
	{BackRock2: 0},
	{BloodParticles: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{BulletDesk: 0},
	{BulletNumber: 0},
	{BulletUI: 0},
	{Tween: 0},
	{ButtonEffect: 0},
	{blood: 0},
	{EnemyBody: 0},
	{EnemyBody2: 0},
	{EnemyBody3: 0},
	{EnemyBody4: 0},
	{EnemyFootLeft: 0},
	{EnemyFootLeft2: 0},
	{EnemyFootLeft3: 0},
	{EnemyFootLeft4: 0},
	{EnemyFootRight: 0},
	{EnemyFootRight2: 0},
	{EnemyFootRight3: 0},
	{EnemyFootRight4: 0},
	{EnemyGun: 0},
	{EnemyGun2: 0},
	{EnemyGun3: 0},
	{EnemyGun4: 0},
	{EnemyHead: 0},
	{EnemyHead2: 0},
	{EnemyHead3: 0},
	{EnemyHead4: 0},
	{EnemyLegLeft: 0},
	{EnemyLegLeft2: 0},
	{EnemyLegLeft3: 0},
	{EnemyLegLeft4: 0},
	{EnemyLegLeftDown: 0},
	{EnemyLegLeftDown2: 0},
	{EnemyLegLeftDown3: 0},
	{EnemyLegLeftDown4: 0},
	{EnemyLegRight: 0},
	{EnemyLegRight2: 0},
	{EnemyLegRight3: 0},
	{EnemyLegRight4: 0},
	{EnemyLegRightDown: 0},
	{EnemyLegRightDown2: 0},
	{EnemyLegRightDown3: 0},
	{EnemyLegRightDown4: 0},
	{Solid: 0},
	{Physics: 0},
	{Ground: 0},
	{HeroBody: 0},
	{HeroFootLeft: 0},
	{HeroFootRight: 0},
	{HeroGun: 0},
	{HeroHead: 0},
	{HeroLegLeft: 0},
	{HeroLegLeftDown: 0},
	{HeroLegLeftDown2: 0},
	{HeroLegRight: 0},
	{HeroLegRightDown: 0},
	{Sine: 0},
	{HeroMark: 0},
	{HomeButton: 0},
	{LevelDesk: 0},
	{LoseText: 0},
	{MenuButton: 0},
	{MissionCompletePlace: 0},
	{MissionLosePlace: 0},
	{OverBloodDrop: 0},
	{OverBloodLine: 0},
	{Rotate: 0},
	{OverGun: 0},
	{OverLoseAgent: 0},
	{OverLoseRedAgent: 0},
	{OverMenuButton: 0},
	{OverNextButton: 0},
	{OverRestartButton: 0},
	{OverWinAgent: 0},
	{RestartButton: 0},
	{Rock1: 0},
	{Rock10: 0},
	{Rock11: 0},
	{Rock12: 0},
	{Rock13: 0},
	{Rock14: 0},
	{Rock15: 0},
	{Rock16: 0},
	{Rock17: 0},
	{Rock2: 0},
	{Rock3: 0},
	{Rock4: 0},
	{Rock5: 0},
	{Rock6: 0},
	{Rock7: 0},
	{Rock8: 0},
	{Rock9: 0},
	{ShotLight: 0},
	{SparkParticles: 0},
	{StartFade: 0},
	{Fade: 0},
	{TotalBloodEffect: 0},
	{Trace: 0},
	{WhiteMoon: 0},
	{YellowMoon: 0},
	{LoseWinFade: 0},
	{OverButtonEffect: 0},
	{OverHomeButton: 0},
	{Target: 0},
	{TargetRoute: 0},
	{bloodSplah: 0},
	{OverHomeButton2: 0},
	{adButton: 0},
	{Gear: 0},
	{Play: 0},
	{PlayParticles: 0},
	{StartExplosion: 0},
	{Level: 0},
	{LevelPlace: 0},
	{LockParticles: 0},
	{PlaceEffect: 0},
	{bginfo: 0},
	{Pin: 0},
	{btnClose: 0},
	{btnInfo: 0},
	{btnLanguage: 0},
	{btnPause: 0},
	{Active: 0},
	{btnSettings: 0},
	{Orientation: 0},
	{SecretAgentLogo: 0},
	{SplashFin: 0},
	{Audio: 0},
	{Browser: 0},
	{Completed: 0},
	{LevelNumber: 0},
	{LevelText: 0},
	{StartLevelText: 0},
	{TextLevelUnlocked: 0},
	{Touch: 0},
	{Sprite: 0},
	{PlatformInfo: 0},
	{TXT_Congratulations: 0},
	{TXT_LevelsUnlocked: 0},
	{TXT_Level: 0},
	{TXT_Levels: 0},
	{TXT_ResetLevels: 0},
	{TXT_No: 0},
	{TXT_Yes: 0},
	{TXT_CurLevel: 0},
	{TXT_StartLevel: 0},
	{TXT_MissionFailed: 0},
	{JSON: 0},
	{TXT_MissionFailed2: 0},
	{Keyboard: 0},
	{Grounds: 0},
	{Enemy: 0},
	{Enemy2: 0},
	{Enemy3: 0},
	{Enemy4: 0},
	{GUI: 0},
	{CheckEnemy: 0},
	{TXT_ResetLevel: 0},
	{Levels: 0},
	{CompletedLevels: 0},
	{Win: 0},
	{RewardUse: 0},
	{Lose: 0},
	{Bullets: 0},
	{EnemyCount: 0},
	{sound: 0},
	{Music: 0},
	{load: 0},
	{mute: 0},
	{param: 0},
	{rewardAd: 0},
	{reward: 0},
	{Score: 0},
	{DataJson: 0},
	{keyName: 0},
	{Key: 0},
	{Language: 0},
	{TXT_LevelCompleted: 0},
	{TXT_MissionsCompleted: 0},
	{TXT_Get3patrons: 0}
];

self.InstanceType = {
	Background: class extends self.ITiledBackgroundInstance {},
	BackRock: class extends self.ISpriteInstance {},
	BackRock2: class extends self.ISpriteInstance {},
	BloodParticles: class extends self.IParticlesInstance {},
	Bullet: class extends self.ISpriteInstance {},
	BulletDesk: class extends self.ISpriteInstance {},
	BulletUI: class extends self.ISpriteInstance {},
	ButtonEffect: class extends self.ISpriteInstance {},
	EnemyBody: class extends self.ISpriteInstance {},
	EnemyBody2: class extends self.ISpriteInstance {},
	EnemyBody3: class extends self.ISpriteInstance {},
	EnemyBody4: class extends self.ISpriteInstance {},
	EnemyFootLeft: class extends self.ISpriteInstance {},
	EnemyFootLeft2: class extends self.ISpriteInstance {},
	EnemyFootLeft3: class extends self.ISpriteInstance {},
	EnemyFootLeft4: class extends self.ISpriteInstance {},
	EnemyFootRight: class extends self.ISpriteInstance {},
	EnemyFootRight2: class extends self.ISpriteInstance {},
	EnemyFootRight3: class extends self.ISpriteInstance {},
	EnemyFootRight4: class extends self.ISpriteInstance {},
	EnemyGun: class extends self.ISpriteInstance {},
	EnemyGun2: class extends self.ISpriteInstance {},
	EnemyGun3: class extends self.ISpriteInstance {},
	EnemyGun4: class extends self.ISpriteInstance {},
	EnemyHead: class extends self.ISpriteInstance {},
	EnemyHead2: class extends self.ISpriteInstance {},
	EnemyHead3: class extends self.ISpriteInstance {},
	EnemyHead4: class extends self.ISpriteInstance {},
	EnemyLegLeft: class extends self.ISpriteInstance {},
	EnemyLegLeft2: class extends self.ISpriteInstance {},
	EnemyLegLeft3: class extends self.ISpriteInstance {},
	EnemyLegLeft4: class extends self.ISpriteInstance {},
	EnemyLegLeftDown: class extends self.ISpriteInstance {},
	EnemyLegLeftDown2: class extends self.ISpriteInstance {},
	EnemyLegLeftDown3: class extends self.ISpriteInstance {},
	EnemyLegLeftDown4: class extends self.ISpriteInstance {},
	EnemyLegRight: class extends self.ISpriteInstance {},
	EnemyLegRight2: class extends self.ISpriteInstance {},
	EnemyLegRight3: class extends self.ISpriteInstance {},
	EnemyLegRight4: class extends self.ISpriteInstance {},
	EnemyLegRightDown: class extends self.ISpriteInstance {},
	EnemyLegRightDown2: class extends self.ISpriteInstance {},
	EnemyLegRightDown3: class extends self.ISpriteInstance {},
	EnemyLegRightDown4: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	HeroBody: class extends self.ISpriteInstance {},
	HeroFootLeft: class extends self.ISpriteInstance {},
	HeroFootRight: class extends self.ISpriteInstance {},
	HeroGun: class extends self.ISpriteInstance {},
	HeroHead: class extends self.ISpriteInstance {},
	HeroLegLeft: class extends self.ISpriteInstance {},
	HeroLegLeftDown: class extends self.ISpriteInstance {},
	HeroLegLeftDown2: class extends self.ISpriteInstance {},
	HeroLegRight: class extends self.ISpriteInstance {},
	HeroLegRightDown: class extends self.ISpriteInstance {},
	HeroMark: class extends self.ISpriteInstance {},
	HomeButton: class extends self.ISpriteInstance {},
	LevelDesk: class extends self.ISpriteInstance {},
	LoseText: class extends self.ISpriteInstance {},
	MenuButton: class extends self.ISpriteInstance {},
	MissionCompletePlace: class extends self.ISpriteInstance {},
	MissionLosePlace: class extends self.ISpriteInstance {},
	OverBloodDrop: class extends self.ISpriteInstance {},
	OverBloodLine: class extends self.ISpriteInstance {},
	OverGun: class extends self.ISpriteInstance {},
	OverLoseAgent: class extends self.ISpriteInstance {},
	OverLoseRedAgent: class extends self.ISpriteInstance {},
	OverMenuButton: class extends self.ISpriteInstance {},
	OverNextButton: class extends self.ISpriteInstance {},
	OverRestartButton: class extends self.ISpriteInstance {},
	OverWinAgent: class extends self.ISpriteInstance {},
	RestartButton: class extends self.ISpriteInstance {},
	Rock1: class extends self.ISpriteInstance {},
	Rock10: class extends self.ISpriteInstance {},
	Rock11: class extends self.ISpriteInstance {},
	Rock12: class extends self.ISpriteInstance {},
	Rock13: class extends self.ISpriteInstance {},
	Rock14: class extends self.ISpriteInstance {},
	Rock15: class extends self.ISpriteInstance {},
	Rock16: class extends self.ISpriteInstance {},
	Rock17: class extends self.ISpriteInstance {},
	Rock2: class extends self.ISpriteInstance {},
	Rock3: class extends self.ISpriteInstance {},
	Rock4: class extends self.ISpriteInstance {},
	Rock5: class extends self.ISpriteInstance {},
	Rock6: class extends self.ISpriteInstance {},
	Rock7: class extends self.ISpriteInstance {},
	Rock8: class extends self.ISpriteInstance {},
	Rock9: class extends self.ISpriteInstance {},
	ShotLight: class extends self.ISpriteInstance {},
	SparkParticles: class extends self.IParticlesInstance {},
	StartFade: class extends self.ITiledBackgroundInstance {},
	TotalBloodEffect: class extends self.ITiledBackgroundInstance {},
	Trace: class extends self.ISpriteInstance {},
	WhiteMoon: class extends self.ISpriteInstance {},
	YellowMoon: class extends self.ISpriteInstance {},
	LoseWinFade: class extends self.ITiledBackgroundInstance {},
	OverButtonEffect: class extends self.ISpriteInstance {},
	OverHomeButton: class extends self.ISpriteInstance {},
	Target: class extends self.ISpriteInstance {},
	TargetRoute: class extends self.ISpriteInstance {},
	bloodSplah: class extends self.ISpriteInstance {},
	OverHomeButton2: class extends self.ISpriteInstance {},
	adButton: class extends self.ISpriteInstance {},
	Gear: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	PlayParticles: class extends self.IParticlesInstance {},
	StartExplosion: class extends self.ISpriteInstance {},
	LevelPlace: class extends self.ISpriteInstance {},
	LockParticles: class extends self.IParticlesInstance {},
	PlaceEffect: class extends self.ISpriteInstance {},
	bginfo: class extends self.ISpriteInstance {},
	btnClose: class extends self.ISpriteInstance {},
	btnInfo: class extends self.ISpriteInstance {},
	btnLanguage: class extends self.ISpriteInstance {},
	btnPause: class extends self.ISpriteInstance {},
	btnSettings: class extends self.ISpriteInstance {},
	Orientation: class extends self.ISpriteInstance {},
	SecretAgentLogo: class extends self.ISpriteInstance {},
	SplashFin: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Completed: class extends self.ISpriteFontInstance {},
	LevelNumber: class extends self.ISpriteFontInstance {},
	LevelText: class extends self.ISpriteFontInstance {},
	StartLevelText: class extends self.ISpriteFontInstance {},
	TextLevelUnlocked: class extends self.ISpriteFontInstance {},
	Touch: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	TXT_Congratulations: class extends self.ITextInstance {},
	TXT_LevelsUnlocked: class extends self.ITextInstance {},
	TXT_Level: class extends self.ITextInstance {},
	TXT_Levels: class extends self.ITextInstance {},
	TXT_ResetLevels: class extends self.ITextInstance {},
	TXT_No: class extends self.ITextInstance {},
	TXT_Yes: class extends self.ITextInstance {},
	TXT_CurLevel: class extends self.ITextInstance {},
	TXT_StartLevel: class extends self.ITextInstance {},
	TXT_MissionFailed: class extends self.ITextInstance {},
	JSON: class extends self.IJSONInstance {},
	TXT_MissionFailed2: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	Grounds: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Enemy2: class extends self.ISpriteInstance {},
	Enemy3: class extends self.ISpriteInstance {},
	Enemy4: class extends self.ISpriteInstance {},
	GUI: class extends self.ISpriteInstance {},
	CheckEnemy: class extends self.ISpriteInstance {},
	TXT_ResetLevel: class extends self.ITextInstance {}
}