const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.List,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Behaviors.Anchor,
		C3.Plugins.TextBox,
		C3.Behaviors.Pin,
		C3.Plugins.Button,
		C3.Plugins.Browser,
		C3.Plugins.PlatformInfo,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Json,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.find,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.replace,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SortZOrderByInstVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.List.Exps.SelectedIndex,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.List.Acts.SetCSSStyle,
		C3.Plugins.List.Acts.Select,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.List.Cnds.OnClicked,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Exps.ZIndex,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.JavaScriptInEvents.GeneralEvent_Event13_Act1,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.JavaScriptInEvents.GeneralEvent_Event21_Act2,
		C3.JavaScriptInEvents.GeneralEvent_Event22_Act2,
		C3.JavaScriptInEvents.GeneralEvent_Event25_Act1,
		C3.JavaScriptInEvents.GeneralEvent_Event26_Act1,
		C3.JavaScriptInEvents.GeneralEvent_Event27_Act1,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.JavaScriptInEvents.GeneralEvent_Event28_Act2,
		C3.JavaScriptInEvents.GeneralEvent_Event29_Act1,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.Browser.Exps.Language,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{LocalStorage: 0},
	{Lst: 0},
	{LstColor: 0},
	{Touch: 0},
	{Sine: 0},
	{Title: 0},
	{bg: 0},
	{tx_open_lvl: 0},
	{Tween: 0},
	{panel_reset_progress: 0},
	{Anchor: 0},
	{btnLanguage: 0},
	{bavkground: 0},
	{overText: 0},
	{Board: 0},
	{Parent: 0},
	{Group: 0},
	{z_indx: 0},
	{Line: 0},
	{TbxGenerate: 0},
	{TextBox: 0},
	{Cam: 0},
	{xx: 0},
	{yy: 0},
	{List: 0},
	{Input: 0},
	{Output: 0},
	{Tail: 0},
	{A: 0},
	{LINES: 0},
	{zinx: 0},
	{TargetX: 0},
	{TargetY: 0},
	{OnTarget: 0},
	{Hexa: 0},
	{Pin: 0},
	{Border: 0},
	{Arrow: 0},
	{hexa_part: 0},
	{tx_lvl: 0},
	{tx_hint: 0},
	{b_apply_generate: 0},
	{b_generate: 0},
	{b_menu: 0},
	{b_next: 0},
	{b_start: 0},
	{b_reset_progress: 0},
	{b_y_n: 0},
	{btnHome: 0},
	{Button: 0},
	{TextInput: 0},
	{tx_reset_progress: 0},
	{Browser: 0},
	{PlatformInfo: 0},
	{AJAX: 0},
	{Language: 0},
	{JSON: 0},
	{FHexa: 0},
	{FLine: 0},
	{bgs: 0},
	{HexaList: 0},
	{ShuffledHexas: 0},
	{CurHexa: 0},
	{Res: 0},
	{HexaPosList: 0},
	{Ready: 0},
	{FirstSelect: 0},
	{SecondSelect: 0},
	{Code: 0},
	{GetCode: 0},
	{Sound_: 0},
	{param_0: 0},
	{param_1: 0},
	{level: 0},
	{VList: 0},
	{VListCheck: 0},
	{CurX: 0},
	{CurY: 0},
	{DirList: 0},
	{Size: 0},
	{CurGroup: 0},
	{S0: 0},
	{S1: 0},
	{S2: 0},
	{S4: 0},
	{StartX: 0},
	{StartY: 0},
	{L: 0},
	{R: 0},
	{T: 0},
	{B: 0},
	{sound: 0},
	{music: 0},
	{lvl: 0},
	{max_lvl: 0},
	{SaveLvl: 0},
	{SaveLang: 0},
	{mute: 0},
	{param: 0},
	{rewardAd: 0},
	{reward: 0},
	{Score: 0},
	{Level: 0},
	{DataJson: 0},
	{keyName: 0},
	{Key: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Lst: class extends self.IListInstance {},
	LstColor: class extends self.IListInstance {},
	Touch: class extends self.IInstance {},
	Title: class extends self.ISpriteInstance {},
	bg: class extends self.ITiledBackgroundInstance {},
	tx_open_lvl: class extends self.ITextInstance {},
	panel_reset_progress: class extends self.ISpriteInstance {},
	btnLanguage: class extends self.ISpriteInstance {},
	bavkground: class extends self.ISpriteInstance {},
	overText: class extends self.ISpriteInstance {},
	Board: class extends self.ISpriteInstance {},
	Line: class extends self.ISpriteInstance {},
	TbxGenerate: class extends self.ITextInputInstance {},
	TextBox: class extends self.ITextInputInstance {},
	Cam: class extends self.ISpriteInstance {},
	Hexa: class extends self.ISpriteInstance {},
	Border: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	hexa_part: class extends self.ISpriteInstance {},
	tx_lvl: class extends self.ITextInstance {},
	tx_hint: class extends self.ITextInstance {},
	b_apply_generate: class extends self.IButtonInstance {},
	b_generate: class extends self.IButtonInstance {},
	b_menu: class extends self.ISpriteInstance {},
	b_next: class extends self.ISpriteInstance {},
	b_start: class extends self.ISpriteInstance {},
	b_reset_progress: class extends self.ISpriteInstance {},
	b_y_n: class extends self.ISpriteInstance {},
	btnHome: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	TextInput: class extends self.ITextInputInstance {},
	tx_reset_progress: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Language: class extends self.IArrayInstance {},
	JSON: class extends self.IJSONInstance {},
	FHexa: class extends self.ISpriteInstance {},
	FLine: class extends self.ISpriteInstance {},
	bgs: class extends self.ISpriteInstance {}
}