const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Arr,
		C3.Behaviors.Tween,
		C3.Behaviors.scrollto,
		C3.Behaviors.Fade,
		C3.Behaviors.Physics,
		C3.Behaviors.solid,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Overboy_Utils,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.NinePatch,
		C3.Behaviors.Timer,
		C3.Behaviors.Anchor,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Acts.SetText,
		C3.ScriptsInEvents.Gamees_Event5_Act15,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Tween.Acts.SetTweensTime,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.HasParent,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.System.Cnds.Repeat,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.Sprite.Exps.IID,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.ScriptsInEvents.Gamees_Event88,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.HasChildren,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Plugins.Particles.Acts.SetYRandomiser,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.ScriptsInEvents.Gamees_Event134_Act2,
		C3.ScriptsInEvents.Gamees_Event135_Act5,
		C3.ScriptsInEvents.Gamees_Event137_Act4,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Text.Exps.Y,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Touch.Exps.XAt,
		C3.Plugins.Touch.Exps.YAt,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Exps.FaceSize,
		C3.Plugins.Text.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetTimescale,
		C3.ScriptsInEvents.Commones_Event51_Act1,
		C3.ScriptsInEvents.Commones_Event52_Act1,
		C3.ScriptsInEvents.Commones_Event53_Act1,
		C3.ScriptsInEvents.Splashes_Event2_Act3,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Browser.Acts.Focus,
		C3.ScriptsInEvents.Commones_Event16_Act4,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.ScriptsInEvents.Commones_Event44_Act1,
		C3.ScriptsInEvents.Commones_Event46_Act1,
		C3.ScriptsInEvents.Commones_Event47_Act2,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Audio.Exps.Volume,
		C3.ScriptsInEvents.Commones_Event117_Act1,
		C3.ScriptsInEvents.Commones_Event125_Act1,
		C3.ScriptsInEvents.Commones_Event126_Act1,
		C3.ScriptsInEvents.Commones_Event127_Act1,
		C3.ScriptsInEvents.Commones_Event128_Act1,
		C3.ScriptsInEvents.Commones_Event129_Act1,
		C3.ScriptsInEvents.Commones_Event130_Act1,
		C3.ScriptsInEvents.Commones_Event132_Act1,
		C3.ScriptsInEvents.Commones_Event135_Act1,
		C3.ScriptsInEvents.Commones_Event137_Act1,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.ScriptsInEvents.Commones_Event140_Act1,
		C3.ScriptsInEvents.Commones_Event141_Act1
	];
};
self.C3_JsPropNameTable = [
	{preview: 0},
	{size: 0},
	{destroyFx: 0},
	{pieceArt_1: 0},
	{pieceArt_2: 0},
	{pieceArt_3: 0},
	{pieceArt_4: 0},
	{Bk: 0},
	{Bk2: 0},
	{Bk3: 0},
	{Bk4: 0},
	{Chain1: 0},
	{Chain2: 0},
	{Chain3: 0},
	{Chain4: 0},
	{ChainOvr: 0},
	{ChainOvr2: 0},
	{ChainOvr3: 0},
	{ChainOvr4: 0},
	{F: 0},
	{F2: 0},
	{F3: 0},
	{F4: 0},
	{Line: 0},
	{Line2: 0},
	{Line3: 0},
	{Line4: 0},
	{shine1: 0},
	{shine2: 0},
	{shine3: 0},
	{shine4: 0},
	{ice1: 0},
	{ice2: 0},
	{ice3: 0},
	{ice4: 0},
	{Back: 0},
	{Back2: 0},
	{Back3: 0},
	{Back4: 0},
	{back5: 0},
	{Chain5: 0},
	{Chain6: 0},
	{Chain7: 0},
	{Chain8: 0},
	{arr_x: 0},
	{arr_y: 0},
	{slot: 0},
	{gridCenter: 0},
	{gridArray: 0},
	{ice: 0},
	{locked: 0},
	{piece_1: 0},
	{piece_2: 0},
	{piece_3: 0},
	{piece_4: 0},
	{tempArray: 0},
	{Tween: 0},
	{moveTarget: 0},
	{movePlaceholder: 0},
	{timer: 0},
	{ScrollTo: 0},
	{cam: 0},
	{highlightVer: 0},
	{highlightHor: 0},
	{exploHitbox: 0},
	{temp2Array: 0},
	{mascotSayArray: 0},
	{Fade: 0},
	{slotShine: 0},
	{follow: 0},
	{bomb: 0},
	{Physics: 0},
	{Solid: 0},
	{collider: 0},
	{moveChecker: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Touch: 0},
	{PlatformInfo: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{playerstats: 0},
	{Utils: 0},
	{exploParticles: 0},
	{exploParticles2: 0},
	{Rotate: 0},
	{iceShard: 0},
	{exploParticles3: 0},
	{Air_particales: 0},
	{bombSparki: 0},
	{Sine: 0},
	{Sine2: 0},
	{Butterfly: 0},
	{Bullet: 0},
	{cherryPetal: 0},
	{coinFX: 0},
	{explo: 0},
	{exploCircle: 0},
	{Knight_light: 0},
	{Roll_button_Particles: 0},
	{shine: 0},
	{warning: 0},
	{slice: 0},
	{fullscreen_btn: 0},
	{music_btn: 0},
	{sound_btn: 0},
	{settings_panel: 0},
	{settings_txt: 0},
	{settings_btn: 0},
	{gameover_panel: 0},
	{gameover_txt: 0},
	{replay_btn: 0},
	{start_btn: 0},
	{level_txt: 0},
	{xp_txt: 0},
	{xpBar_bg: 0},
	{xpBar_frame: 0},
	{xpPop: 0},
	{xpBar_obj: 0},
	{score_txt: 0},
	{best_txt: 0},
	{coins_txt: 0},
	{powerup_txt: 0},
	{price_txt: 0},
	{mascot_txt: 0},
	{levelup_txt: 0},
	{bg: 0},
	{bgshadow: 0},
	{blackScreen: 0},
	{board: 0},
	{boardmask: 0},
	{powerup: 0},
	{c: 0},
	{bombBtn: 0},
	{bombPanel: 0},
	{buyBtn: 0},
	{coin: 0},
	{colorBtn: 0},
	{colorPanel: 0},
	{continueBtn: 0},
	{contRvIcon: 0},
	{highscore: 0},
	{levelup: 0},
	{LightColorDodge2: 0},
	{LightColorDodge3: 0},
	{LightColorDodgeMain: 0},
	{LightColorDodge: 0},
	{lvl: 0},
	{Logo: 0},
	{emotion: 0},
	{happiness: 0},
	{boredom: 0},
	{MascotAnimation: 0},
	{money: 0},
	{rvBtn: 0},
	{RvIcon: 0},
	{score: 0},
	{splitBtn: 0},
	{splitPanel: 0},
	{tutorialPanel: 0},
	{txtBbl: 0},
	{blackScreen2: 0},
	{blackScreen3: 0},
	{replay_btn2: 0},
	{gameOverText: 0},
	{Sprite: 0},
	{Booster_btn_shine: 0},
	{Setting_panel: 0},
	{Logo_shine: 0},
	{Target_height: 0},
	{PopUp_anime_1: 0},
	{PopUp_anime: 0},
	{PopUp_anime2: 0},
	{Target_x: 0},
	{Target_y: 0},
	{PopUp_anime3: 0},
	{PopUp_anime7: 0},
	{PopUp_anime5: 0},
	{PopUp_anime6: 0},
	{PopUp_anime8: 0},
	{Text: 0},
	{Asset: 0},
	{Text2: 0},
	{Asset2: 0},
	{Asset3: 0},
	{Timer: 0},
	{Timers_manager: 0},
	{posForNade: 0},
	{Anchor: 0},
	{Asset4: 0},
	{rvLoading: 0},
	{pieces: 0},
	{otherPiece: 0},
	{piecesArt: 0},
	{settingsBtns: 0},
	{iceBk: 0},
	{Chain: 0},
	{powerupBtns: 0},
	{chainBk: 0},
	{powerupPanels: 0},
	{miscBtns: 0},
	{gridWidth: 0},
	{gridHeight: 0},
	{slotSize: 0},
	{level: 0},
	{xp: 0},
	{xpTxt: 0},
	{xpCap: 0},
	{xpCapTxt: 0},
	{bestscore: 0},
	{bestscoreTxt: 0},
	{scoreTxt: 0},
	{bombPowerup: 0},
	{splitPowerup: 0},
	{colorPowerup: 0},
	{coins: 0},
	{gameOver: 0},
	{popUp: 0},
	{splitRV: 0},
	{colorRV: 0},
	{bombRV: 0},
	{contRV: 0},
	{Game_over: 0},
	{width: 0},
	{height: 0},
	{loop: 0},
	{fall: 0},
	{wait: 0},
	{randEmpty: 0},
	{pieceW: 0},
	{set: 0},
	{i: 0},
	{legal: 0},
	{break: 0},
	{push: 0},
	{clear: 0},
	{pw: 0},
	{pax: 0},
	{pay: 0},
	{isLegal: 0},
	{x: 0},
	{y: 0},
	{amount: 0},
	{color: 0},
	{px: 0},
	{py: 0},
	{refundC: 0},
	{c2: 0},
	{Type: 0},
	{PopUpOpen: 0},
	{selectedRow: 0},
	{moveCount: 0},
	{movesPush: 0},
	{selectedPiece: 0},
	{arrY: 0},
	{arrx: 0},
	{IID1: 0},
	{IID2: 0},
	{slotUID: 0},
	{tutorial: 0},
	{txt: 0},
	{panik: 0},
	{cherry: 0},
	{loadAndShow: 0},
	{IsLoadAndShow: 0},
	{type: 0},
	{IsFullScreenAllowed: 0},
	{IsAdsAllowed: 0},
	{Mobile: 0},
	{Local_ID: 0},
	{gameSnacksAudioAllowed: 0},
	{IsInMicrosoft: 0},
	{Microsoft_Interstital_Complete_String: 0},
	{Microsoft_Reward_Complete_string: 0},
	{instanceRewardID_string: 0},
	{instanceID_string: 0},
	{RV_type: 0},
	{RV_ready: 0},
	{RV_play: 0},
	{ADS: 0},
	{Interstitial_Type: 0},
	{DidUseRv: 0},
	{rvAttempts: 0},
	{CanAds: 0},
	{IsDone: 0},
	{name: 0},
	{BGM: 0},
	{bgmVol: 0},
	{enableMusic: 0},
	{enableSound: 0},
	{Sound: 0},
	{Vol: 0},
	{Playback: 0},
	{Music: 0},
	{masterSound: 0},
	{mute: 0},
	{save_score: 0},
	{return: 0},
	{item: 0},
	{value: 0}
];

self.InstanceType = {
	pieceArt_1: class extends self.ISpriteInstance {},
	pieceArt_2: class extends self.ISpriteInstance {},
	pieceArt_3: class extends self.ISpriteInstance {},
	pieceArt_4: class extends self.ISpriteInstance {},
	Bk: class extends self.ISpriteInstance {},
	Bk2: class extends self.ISpriteInstance {},
	Bk3: class extends self.ISpriteInstance {},
	Bk4: class extends self.ISpriteInstance {},
	Chain1: class extends self.ISpriteInstance {},
	Chain2: class extends self.ISpriteInstance {},
	Chain3: class extends self.ISpriteInstance {},
	Chain4: class extends self.ISpriteInstance {},
	ChainOvr: class extends self.ISpriteInstance {},
	ChainOvr2: class extends self.ISpriteInstance {},
	ChainOvr3: class extends self.ISpriteInstance {},
	ChainOvr4: class extends self.ISpriteInstance {},
	F: class extends self.ISpriteInstance {},
	F2: class extends self.ISpriteInstance {},
	F3: class extends self.ISpriteInstance {},
	F4: class extends self.ISpriteInstance {},
	Line: class extends self.ISpriteInstance {},
	Line2: class extends self.ISpriteInstance {},
	Line3: class extends self.ISpriteInstance {},
	Line4: class extends self.ISpriteInstance {},
	shine1: class extends self.ISpriteInstance {},
	shine2: class extends self.ISpriteInstance {},
	shine3: class extends self.ISpriteInstance {},
	shine4: class extends self.ISpriteInstance {},
	ice1: class extends self.ISpriteInstance {},
	ice2: class extends self.ISpriteInstance {},
	ice3: class extends self.ISpriteInstance {},
	ice4: class extends self.ISpriteInstance {},
	Back: class extends self.ISpriteInstance {},
	Back2: class extends self.ISpriteInstance {},
	Back3: class extends self.ISpriteInstance {},
	Back4: class extends self.ISpriteInstance {},
	back5: class extends self.ISpriteInstance {},
	Chain5: class extends self.ISpriteInstance {},
	Chain6: class extends self.ISpriteInstance {},
	Chain7: class extends self.ISpriteInstance {},
	Chain8: class extends self.ISpriteInstance {},
	slot: class extends self.ISpriteInstance {},
	gridCenter: class extends self.ISpriteInstance {},
	gridArray: class extends self.IArrayInstance {},
	piece_1: class extends self.ISpriteInstance {},
	piece_2: class extends self.ISpriteInstance {},
	piece_3: class extends self.ISpriteInstance {},
	piece_4: class extends self.ISpriteInstance {},
	tempArray: class extends self.IArrayInstance {},
	moveTarget: class extends self.ISpriteInstance {},
	movePlaceholder: class extends self.ISpriteInstance {},
	timer: class extends self.ISpriteInstance {},
	cam: class extends self.ISpriteInstance {},
	highlightVer: class extends self.ISpriteInstance {},
	highlightHor: class extends self.ISpriteInstance {},
	exploHitbox: class extends self.ISpriteInstance {},
	temp2Array: class extends self.IArrayInstance {},
	mascotSayArray: class extends self.IArrayInstance {},
	slotShine: class extends self.ISpriteInstance {},
	bomb: class extends self.ISpriteInstance {},
	collider: class extends self.ISpriteInstance {},
	moveChecker: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	playerstats: class extends self.IArrayInstance {},
	Utils: class extends self.IInstance {},
	exploParticles: class extends self.IParticlesInstance {},
	exploParticles2: class extends self.IParticlesInstance {},
	iceShard: class extends self.ISpriteInstance {},
	exploParticles3: class extends self.IParticlesInstance {},
	Air_particales: class extends self.IParticlesInstance {},
	bombSparki: class extends self.ISpriteInstance {},
	Butterfly: class extends self.ISpriteInstance {},
	cherryPetal: class extends self.ISpriteInstance {},
	coinFX: class extends self.ISpriteInstance {},
	explo: class extends self.ISpriteInstance {},
	exploCircle: class extends self.ISpriteInstance {},
	Knight_light: class extends self.ISpriteInstance {},
	Roll_button_Particles: class extends self.IParticlesInstance {},
	shine: class extends self.ISpriteInstance {},
	warning: class extends self.ISpriteInstance {},
	slice: class extends self.ISpriteInstance {},
	fullscreen_btn: class extends self.ISpriteInstance {},
	music_btn: class extends self.ISpriteInstance {},
	sound_btn: class extends self.ISpriteInstance {},
	settings_panel: class extends self.ISpriteInstance {},
	settings_txt: class extends self.ITextInstance {},
	settings_btn: class extends self.ISpriteInstance {},
	gameover_panel: class extends self.ISpriteInstance {},
	gameover_txt: class extends self.ITextInstance {},
	replay_btn: class extends self.ISpriteInstance {},
	start_btn: class extends self.ISpriteInstance {},
	level_txt: class extends self.ITextInstance {},
	xp_txt: class extends self.ITextInstance {},
	xpBar_bg: class extends self.ISpriteInstance {},
	xpBar_frame: class extends self.IWorldInstance {},
	xpPop: class extends self.ITextInstance {},
	xpBar_obj: class extends self.ISpriteInstance {},
	score_txt: class extends self.ITextInstance {},
	best_txt: class extends self.ITextInstance {},
	coins_txt: class extends self.ITextInstance {},
	powerup_txt: class extends self.ITextInstance {},
	price_txt: class extends self.ITextInstance {},
	mascot_txt: class extends self.ITextInstance {},
	levelup_txt: class extends self.ITextInstance {},
	bg: class extends self.ISpriteInstance {},
	bgshadow: class extends self.ISpriteInstance {},
	blackScreen: class extends self.ISpriteInstance {},
	board: class extends self.ISpriteInstance {},
	boardmask: class extends self.ISpriteInstance {},
	bombBtn: class extends self.ISpriteInstance {},
	bombPanel: class extends self.ISpriteInstance {},
	buyBtn: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	colorBtn: class extends self.ISpriteInstance {},
	colorPanel: class extends self.ISpriteInstance {},
	continueBtn: class extends self.ISpriteInstance {},
	contRvIcon: class extends self.ISpriteInstance {},
	highscore: class extends self.ISpriteInstance {},
	levelup: class extends self.ISpriteInstance {},
	LightColorDodge2: class extends self.ISpriteInstance {},
	LightColorDodge3: class extends self.ISpriteInstance {},
	LightColorDodgeMain: class extends self.ISpriteInstance {},
	LightColorDodge: class extends self.ISpriteInstance {},
	lvl: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	MascotAnimation: class extends self.ISpriteInstance {},
	money: class extends self.ISpriteInstance {},
	rvBtn: class extends self.ISpriteInstance {},
	RvIcon: class extends self.ISpriteInstance {},
	score: class extends self.ISpriteInstance {},
	splitBtn: class extends self.ISpriteInstance {},
	splitPanel: class extends self.ISpriteInstance {},
	tutorialPanel: class extends self.ISpriteInstance {},
	txtBbl: class extends self.ISpriteInstance {},
	blackScreen2: class extends self.ISpriteInstance {},
	blackScreen3: class extends self.ISpriteInstance {},
	replay_btn2: class extends self.ISpriteInstance {},
	gameOverText: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Booster_btn_shine: class extends self.ISpriteInstance {},
	Setting_panel: class extends self.ISpriteInstance {},
	Logo_shine: class extends self.ISpriteInstance {},
	PopUp_anime_1: class extends self.ISpriteInstance {},
	PopUp_anime: class extends self.ISpriteInstance {},
	PopUp_anime2: class extends self.ISpriteInstance {},
	PopUp_anime3: class extends self.ISpriteInstance {},
	PopUp_anime7: class extends self.ISpriteInstance {},
	PopUp_anime5: class extends self.ISpriteInstance {},
	PopUp_anime6: class extends self.ISpriteInstance {},
	PopUp_anime8: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Asset: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Asset2: class extends self.ISpriteInstance {},
	Asset3: class extends self.ISpriteInstance {},
	Timers_manager: class extends self.ISpriteInstance {},
	posForNade: class extends self.ISpriteInstance {},
	Anchor: class extends self.ISpriteInstance {},
	Asset4: class extends self.ISpriteInstance {},
	rvLoading: class extends self.ISpriteInstance {},
	pieces: class extends self.ISpriteInstance {},
	otherPiece: class extends self.ISpriteInstance {},
	piecesArt: class extends self.ISpriteInstance {},
	settingsBtns: class extends self.ISpriteInstance {},
	iceBk: class extends self.ISpriteInstance {},
	ice: class extends self.ISpriteInstance {},
	Chain: class extends self.ISpriteInstance {},
	powerupBtns: class extends self.ISpriteInstance {},
	chainBk: class extends self.ISpriteInstance {},
	powerupPanels: class extends self.ISpriteInstance {},
	miscBtns: class extends self.ISpriteInstance {}
}