const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.frvrsdk,
		C3.Plugins.advert,
		C3.Plugins.GameSnacks_SDK,
		C3.Plugins.Keyboard,
		C3.Plugins.Arr,
		C3.Plugins.Dictionary,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Behaviors.Timer,
		C3.Plugins.Date,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.JavaScriptInEvents.Sdk_crazygames_Event2_Act5,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Date.Exps.Now,
		C3.JavaScriptInEvents.Sdk_crazygames_Event4_Act6,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.JavaScriptInEvents.Sdk_crazygames_Event12_Act1,
		C3.JavaScriptInEvents.Sdk_crazygames_Event13_Act1,
		C3.JavaScriptInEvents.Sdk_crazygames_Event14_Act1,
		C3.JavaScriptInEvents.Sdk_crazygames_Event15_Act1,
		C3.Plugins.System.Acts.Wait,
		C3.JavaScriptInEvents.Sdk_crazygames_Event16_Act1,
		C3.JavaScriptInEvents.Sdk_crazygames_Event16_Act2,
		C3.JavaScriptInEvents.Sdk_crazygames_Event16_Act3,
		C3.JavaScriptInEvents.Sdk_crazygames_Event17_Act1,
		C3.JavaScriptInEvents.Sdk_crazygames_Event17_Act2,
		C3.JavaScriptInEvents.Sdk_crazygames_Event17_Act3,
		C3.JavaScriptInEvents.Sdk_crazygames_Event18_Act1,
		C3.JavaScriptInEvents.Sdk_crazygames_Event19_Act1,
		C3.JavaScriptInEvents.Sdk_crazygames_Event20_Act1,
		C3.JavaScriptInEvents.Sdk_crazygames_Event20_Act2,
		C3.JavaScriptInEvents.Sdk_crazygames_Event20_Act3,
		C3.JavaScriptInEvents.Sdk_crazygames_Event20_Act4,
		C3.JavaScriptInEvents.Sdk_crazygames_Event20_Act5,
		C3.JavaScriptInEvents.Sdk_crazygames_Event20_Act6,
		C3.JavaScriptInEvents.Sdk_crazygames_Event21_Act1,
		C3.JavaScriptInEvents.Sdk_crazygames_Event21_Act2,
		C3.JavaScriptInEvents.Sdk_crazygames_Event21_Act3,
		C3.JavaScriptInEvents.Sdk_crazygames_Event21_Act4,
		C3.JavaScriptInEvents.Sdk_crazygames_Event21_Act5,
		C3.JavaScriptInEvents.Sdk_crazygames_Event21_Act6,
		C3.JavaScriptInEvents.Sdk_crazygames_Event22_Act1,
		C3.JavaScriptInEvents.Sdk_crazygames_Event23_Act1,
		C3.JavaScriptInEvents.Sdk_crazygames_Event24_Act1,
		C3.JavaScriptInEvents.Sdk_crazygames_Event25_Act1,
		C3.JavaScriptInEvents.Sdk_crazygames_Event26_Act3,
		C3.JavaScriptInEvents.Sdk_crazygames_Event27_Act1,
		C3.JavaScriptInEvents.Sdk_crazygames_Event28_Act1,
		C3.JavaScriptInEvents.Sdk_crazygames_Event29_Act1,
		C3.JavaScriptInEvents.Sdk_crazygames_Event30_Act1,
		C3.JavaScriptInEvents.Sdk_crazygames_Event31_Act1,
		C3.JavaScriptInEvents.Sdk_crazygames_Event31_Act2,
		C3.JavaScriptInEvents.Sdk_crazygames_Event31_Act3,
		C3.JavaScriptInEvents.Sdk_crazygames_Event31_Act4,
		C3.JavaScriptInEvents.Sdk_crazygames_Event31_Act5,
		C3.JavaScriptInEvents.Sdk_crazygames_Event31_Act6,
		C3.JavaScriptInEvents.Sdk_crazygames_Event31_Act7,
		C3.JavaScriptInEvents.Sdk_crazygames_Event31_Act8,
		C3.JavaScriptInEvents.Sdk_crazygames_Event31_Act9,
		C3.JavaScriptInEvents.Sdk_crazygames_Event31_Act10,
		C3.JavaScriptInEvents.Sdk_crazygames_Event31_Act11,
		C3.JavaScriptInEvents.Sdk_crazygames_Event31_Act12,
		C3.JavaScriptInEvents.Sdk_crazygames_Event32_Act1,
		C3.JavaScriptInEvents.Sdk_crazygames_Event32_Act2,
		C3.JavaScriptInEvents.Sdk_crazygames_Event32_Act3,
		C3.JavaScriptInEvents.Sdk_crazygames_Event32_Act4,
		C3.JavaScriptInEvents.Sdk_crazygames_Event32_Act5,
		C3.JavaScriptInEvents.Sdk_crazygames_Event32_Act6,
		C3.JavaScriptInEvents.Sdk_crazygames_Event32_Act7,
		C3.JavaScriptInEvents.Sdk_crazygames_Event32_Act8,
		C3.JavaScriptInEvents.Sdk_crazygames_Event32_Act9,
		C3.JavaScriptInEvents.Sdk_crazygames_Event32_Act10,
		C3.JavaScriptInEvents.Sdk_crazygames_Event32_Act11,
		C3.JavaScriptInEvents.Sdk_crazygames_Event32_Act12,
		C3.JavaScriptInEvents.Sdk_crazygames_Event33_Act1,
		C3.JavaScriptInEvents.Sdk_crazygames_Event33_Act2,
		C3.JavaScriptInEvents.Sdk_crazygames_Event33_Act3,
		C3.JavaScriptInEvents.Sdk_crazygames_Event33_Act4,
		C3.JavaScriptInEvents.Sdk_crazygames_Event33_Act5,
		C3.JavaScriptInEvents.Sdk_crazygames_Event33_Act6,
		C3.JavaScriptInEvents.Sdk_crazygames_Event34_Act1,
		C3.JavaScriptInEvents.Sdk_crazygames_Event34_Act2,
		C3.JavaScriptInEvents.Sdk_crazygames_Event34_Act3,
		C3.JavaScriptInEvents.Sdk_crazygames_Event34_Act4,
		C3.JavaScriptInEvents.Sdk_crazygames_Event34_Act5,
		C3.JavaScriptInEvents.Sdk_crazygames_Event34_Act6,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Exps.int,
		C3.Plugins.advert.Acts.ShowInterstitial,
		C3.Plugins.advert.Acts.ShowRewarded,
		C3.Plugins.advert.Cnds.IsInterstitialLoaded,
		C3.Plugins.advert.Acts.CreateInterstitial,
		C3.Plugins.advert.Cnds.IsRewardedLoaded,
		C3.Plugins.advert.Acts.CreateRewarded,
		C3.Plugins.advert.Cnds.OnRewardedComplete,
		C3.Plugins.frvrsdk.Acts.ShowRewarded,
		C3.Plugins.frvrsdk.Acts.ShowInterstitial,
		C3.Plugins.frvrsdk.Cnds.OnRewardGranted,
		C3.Plugins.frvrsdk.Cnds.OnAdFinished,
		C3.Plugins.GameSnacks_SDK.Acts.FirstFrameReady,
		C3.Plugins.GameSnacks_SDK.Acts.GameReady,
		C3.Plugins.GameSnacks_SDK.Acts.GameOver,
		C3.Plugins.GameSnacks_SDK.Acts.UpdateScore,
		C3.Plugins.GameSnacks_SDK.Cnds.IsAudioEnabled,
		C3.Plugins.GameSnacks_SDK.Cnds.OnAudioChanged,
		C3.Plugins.GameSnacks_SDK.Cnds.OnGamePaused,
		C3.Plugins.GameSnacks_SDK.Acts.PauseGame,
		C3.Plugins.GameSnacks_SDK.Cnds.OnGameResumed,
		C3.Plugins.GameSnacks_SDK.Acts.ResumeGame,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.GameSnacks_SDK.Acts.SetStorage,
		C3.Plugins.GameSnacks_SDK.Acts.GetStorage,
		C3.Plugins.GameSnacks_SDK.Cnds.OnStorageItemLoaded,
		C3.Plugins.GameSnacks_SDK.Exps.LoadedStorageKey,
		C3.Plugins.GameSnacks_SDK.Exps.LoadedStorageValue,
		C3.Plugins.GameSnacks_SDK.Acts.ShowInterstitial,
		C3.Plugins.GameSnacks_SDK.Acts.ShowRewarded,
		C3.Plugins.GameSnacks_SDK.Cnds.OnAdDismissed,
		C3.Plugins.GameSnacks_SDK.Cnds.OnAdShown,
		C3.Plugins.GameSnacks_SDK.Cnds.OnAdFailed,
		C3.Plugins.GameSnacks_SDK.Cnds.OnAdViewed,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.Browser.Exps.Language,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Arr.Cnds.CompareXYZ,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SortZOrderByInstVar,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Text.Acts.AddChild,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Arr.Exps.LastIndexOf,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.JavaScriptInEvents.Sh_game_es_Event546,
		C3.Plugins.Dictionary.Exps.KeyCount,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.JavaScriptInEvents.Sh_game_es_Event888,
		C3.JavaScriptInEvents.Sh_game_es_Event891,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Text.Cnds.PickDistance,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.PickByComparison
	];
};
self.C3_JsPropNameTable = [
	{Inv: 0},
	{Inv2: 0},
	{Inv3: 0},
	{InventorySlotId: 0},
	{Tween: 0},
	{InventoryPanel: 0},
	{Inv4: 0},
	{FRVRSDK: 0},
	{MobileAdvert: 0},
	{GameSnacksSDK: 0},
	{BG: 0},
	{GridX: 0},
	{GridY: 0},
	{TileNo: 0},
	{Tile: 0},
	{ZValue: 0},
	{Hero: 0},
	{Keyboard: 0},
	{Board: 0},
	{Inventory: 0},
	{Might: 0},
	{Type: 0},
	{Target: 0},
	{Item: 0},
	{Items: 0},
	{ZOrder: 0},
	{Enemy: 0},
	{Enemies: 0},
	{EnemiesConfig: 0},
	{StatsPanel: 0},
	{StatTxt: 0},
	{Config_Weapons: 0},
	{HPPanel: 0},
	{HPTxt: 0},
	{Config_Shields: 0},
	{DrawPile: 0},
	{DungeonDoors: 0},
	{CoinPanel: 0},
	{CoinsTxt: 0},
	{Coin: 0},
	{Config_Consumable: 0},
	{EnemyTile: 0},
	{Dust: 0},
	{TitlePanel: 0},
	{Btn_Play: 0},
	{CoverHero: 0},
	{Torch: 0},
	{TorchLight: 0},
	{TorchFire: 0},
	{Touch: 0},
	{Mouse: 0},
	{DarkMagicProjectile: 0},
	{Kurtyna: 0},
	{Btn_Continue: 0},
	{VFX_ShieldDefense: 0},
	{VFX_HitAnimations: 0},
	{IconBoughtInStore: 0},
	{StatusIcon: 0},
	{VFX_Poison: 0},
	{TreasurePanel: 0},
	{TreasureTxt: 0},
	{GameOverCzacha: 0},
	{LocalStorage: 0},
	{ThrowingKnife: 0},
	{StatusList: 0},
	{LowHPIndicator: 0},
	{Fireball: 0},
	{VFX_MagicHit: 0},
	{PreloaderIcon: 0},
	{Audio: 0},
	{Soundlist: 0},
	{VFX_Heal: 0},
	{VFX_Explosion01: 0},
	{VFX_LevelUpSwirl: 0},
	{ItemType: 0},
	{Price: 0},
	{SkinType: 0},
	{ItemTypeLoc: 0},
	{StorePanel: 0},
	{Btn_Buy: 0},
	{Price_Txt: 0},
	{QuantityText: 0},
	{Btn_Pause: 0},
	{Btn_Mute: 0},
	{BigPauseIcon: 0},
	{PlaceToPutBoughtUpgrades: 0},
	{Point: 0},
	{Point2: 0},
	{Point3: 0},
	{Btn_GiveUp: 0},
	{DragonPart: 0},
	{Reward: 0},
	{Btn_WatchAds: 0},
	{HowMuchForAnAd: 0},
	{Arrow: 0},
	{TrashID: 0},
	{Btn_Trash: 0},
	{PlaceForUpgrades: 0},
	{TooltipPanel: 0},
	{Tooltip_Head: 0},
	{Tooltip_Content: 0},
	{TXT_EN_TooltipHead: 0},
	{TXT_EN_TooltipContent: 0},
	{DebugTxt: 0},
	{HTP_Panel: 0},
	{HTP_Head: 0},
	{HTP_Content: 0},
	{Hero_VictoryPose: 0},
	{HandPointingToSwipe: 0},
	{HandPointingToTap: 0},
	{HTP_ArrowKeys: 0},
	{TXT_PL_TooltipContent: 0},
	{TXT_PL_TooltipHead: 0},
	{Btn_Prev: 0},
	{Btn_Next: 0},
	{LangTxt: 0},
	{LangList: 0},
	{Browser: 0},
	{TXT_FR_TooltipContent: 0},
	{TXT_FR_TooltipHead: 0},
	{TXT_ES_TooltipContent: 0},
	{TXT_ES_TooltipHead: 0},
	{Timer: 0},
	{TooltipTimer: 0},
	{Btn_Back: 0},
	{Btn_Store: 0},
	{BtnStore_Label: 0},
	{Label_Upgrades: 0},
	{Label_Skins: 0},
	{Btn_BuySkin: 0},
	{PriceSkin_Txt: 0},
	{Price_Coin: 0},
	{ChosenSkinFrame: 0},
	{SkinPrices: 0},
	{Date: 0},
	{BossLevelIcon: 0},
	{RadialLight: 0},
	{DailyMissions: 0},
	{DailyMissionPanel: 0},
	{DailyMissionText: 0},
	{DailyMissionDone: 0},
	{HowMuchForDaily: 0},
	{Artifacts: 0},
	{Direction: 0},
	{CtrlBtn: 0},
	{Label_DailyQuest: 0},
	{Label_Unlock: 0},
	{TooltipStore_Head: 0},
	{TooltipStore_Content: 0},
	{TooltipStorePanel: 0},
	{Btn_Yes: 0},
	{Btn_No: 0},
	{ConfirmationPopup: 0},
	{ConfirmationPopup_Txt: 0},
	{Label_Revive: 0},
	{DailyRewardPanel: 0},
	{DailyReward_Label: 0},
	{Btn_Thropies: 0},
	{BtnThropies_Label: 0},
	{TrophyId: 0},
	{Trophy: 0},
	{TrophyPanel: 0},
	{Label_Trophies: 0},
	{Label_TrophyName: 0},
	{Progress_Txt: 0},
	{BoardElements: 0},
	{SDK: 0},
	{Highscore: 0},
	{gameWasMutedBeforePause: 0},
	{rootY: 0},
	{HeroGridX: 0},
	{HeroGridY: 0},
	{HeroIsMoving: 0},
	{firstFreeInventorySpace: 0},
	{MaxHP: 0},
	{CurrentHP: 0},
	{NoMoreEnemiesOnTheBoard: 0},
	{Coins: 0},
	{BoardPiecesDropped: 0},
	{GameIsRunning: 0},
	{HeroJustWalkThroughTheDoor: 0},
	{TouchStartX: 0},
	{TouchStartY: 0},
	{TouchDistanceX: 0},
	{TouchDistanceY: 0},
	{DmgOverflow: 0},
	{HeroIsDefendingWithShield: 0},
	{ShieldInvIndex: 0},
	{HeroStatus_Poisoned: 0},
	{PickedCoin: 0},
	{Treasure: 0},
	{InventoryPanelsAreBumping: 0},
	{Hero_MeleePower: 0},
	{Hero_ValorPower: 0},
	{GameIsPaused: 0},
	{Store_Leveled_Price: 0},
	{Store_Armored_Price: 0},
	{Store_PoweredUp_Price: 0},
	{useLocalStorage: 0},
	{GameIsMuted: 0},
	{numberOfItemsBoughtInStore: 0},
	{boughtItem1: 0},
	{boughtItem2: 0},
	{boughtItem3: 0},
	{CurrentLevel: 0},
	{HeroHasARing: 0},
	{BossFlipFlop: 0},
	{HowToPlayPassed_Step1: 0},
	{HowToPlayPassed_Step2: 0},
	{HowToPlayPassed_Step3: 0},
	{HowToPlayPassed_Step4: 0},
	{HowToPlayPassed_Step5: 0},
	{HowToPlayPassed_Step6: 0},
	{HowToPlayPassed_Step7: 0},
	{WaitingForHTP_Step1: 0},
	{WaitingForHTP_Step2: 0},
	{WaitingForHTP_Step3: 0},
	{WaitingForHTP_Step4: 0},
	{WaitingForHTP_Step5: 0},
	{WaitingForHTP_Step6: 0},
	{WaitingForHTP_Step7: 0},
	{SH_Language: 0},
	{BrowserLanguage: 0},
	{touchTime: 0},
	{currentSkin: 0},
	{boughtSkin_Hero: 0},
	{boughtSkin_Barbarian: 0},
	{boughtSkin_Jester: 0},
	{boughtSkin_King: 0},
	{boughtSkin_Mage: 0},
	{boughtSkin_Artificier: 0},
	{LastRewardAdTime: 0},
	{MinutesPassedFromLastRewardedAd: 0},
	{CurrentTheme: 0},
	{DailyMissionNo: 0},
	{DailyMissionId: 0},
	{LastDoneDailyMission: 0},
	{DailyMissionAlreadyDoneForToday: 0},
	{coverScreenShown: 0},
	{RewardedAdsEnabled: 0},
	{FirstTreasureLoad: 0},
	{IsThisFirstTime: 0},
	{InventorySpace: 0},
	{NumberOfRevives: 0},
	{wasGameMutedBeforeTheAd: 0},
	{TodayDayNumber: 0},
	{LastDailyRewardDayNumber: 0},
	{Trophy_DragonSkull_Claimed: 0},
	{Trophy_TrollsTooth_Claimed: 0},
	{Trophy_BrokenHelmet_Claimed: 0},
	{Trophy_NecromancersPalm_Claimed: 0},
	{Trophy_Belt_Claimed: 0},
	{Trophy_Medal_Claimed: 0},
	{Trophy_Cup_Claimed: 0},
	{Trophy_TopHat_Claimed: 0},
	{Trophy_Certificate_Claimed: 0},
	{Trophy_SlayersScythe_Claimed: 0},
	{Trophy_Firestarter_Claimed: 0},
	{Trophy_HawkEye_Claimed: 0},
	{Trophy_Firestarter_Progress: 0},
	{Trophy_Medal_Progress: 0},
	{Trophy_Cup_Progress: 0},
	{Trophy_Certificate_Progress: 0},
	{Trophy_SlayersScythe_Progress: 0},
	{Trophy_HawkEye_Progress: 0},
	{HeroAttack: 0},
	{FirstAttack: 0},
	{HeroHasShield: 0},
	{FirstShieldDefense: 0},
	{BumpedEnemyUID: 0},
	{fItemFinalX: 0},
	{fItemFinalY: 0},
	{fGridX: 0},
	{fGridY: 0},
	{fDirection: 0},
	{tilerotation: 0},
	{customShapeChance: 0},
	{animPeriod: 0},
	{elementsPlaced: 0},
	{coinChance: 0},
	{BossName: 0},
	{tmpNoMoreEnemiesOnTheBoard: 0},
	{doorsPlaced: 0},
	{fX: 0},
	{fY: 0},
	{upgradeCubePlaced: 0},
	{cubeX: 0},
	{cubeY: 0},
	{randomCube: 0},
	{sortingZ: 0},
	{margin: 0},
	{odstep: 0},
	{tmpItemType: 0},
	{fItem: 0},
	{invNumber: 0},
	{MinotaurAttack: 0},
	{minotaurDeltaX: 0},
	{minotaurDeltaY: 0},
	{firstShieldDefense: 0},
	{rndAnim: 0},
	{canChangePauseState: 0},
	{canChangeMuteState: 0},
	{langNo: 0},
	{randomX: 0},
	{randomY: 0},
	{itemToSpawn: 0},
	{enemyToSpawn: 0},
	{HealingEnabled: 0},
	{HealPower: 0},
	{fMight: 0},
	{EnemyType: 0},
	{AxeMight: 0},
	{coinSpeed: 0},
	{fNumberOfCoins: 0},
	{fXprime: 0},
	{fYprime: 0},
	{fXsec: 0},
	{fYsec: 0},
	{ReportedDailyMissionId: 0},
	{htpID: 0},
	{animPeriod2: 0},
	{numberOfTreasures: 0},
	{fTarget: 0},
	{lootDraw: 0},
	{lootChance: 0},
	{loot: 0},
	{gameoveradchance: 0},
	{revivechance: 0},
	{tooltipX: 0},
	{tooltipY: 0},
	{tooltipId: 0},
	{rndSnd: 0},
	{enemyType: 0},
	{fdebug: 0},
	{Melee_Dagger: 0},
	{Melee_Sword: 0},
	{Enemy_Goblin: 0},
	{fLevel: 0},
	{storeCount: 0},
	{skinStoreStartX: 0},
	{skinStoreStartY: 0},
	{rozstawX: 0},
	{rozstawY: 0},
	{skinStoreRow: 0},
	{skinStoreColumn: 0},
	{StorePanelUID: 0},
	{tmpFrame: 0},
	{storeTooltipX: 0},
	{storeTooltipY: 0},
	{HowMany: 0},
	{WhereX: 0},
	{WhereY: 0},
	{ShowTrophyTooltips: 0},
	{TrophyId_int: 0},
	{trno: 0}
];

self.InstanceType = {
	Inv: class extends self.ISpriteInstance {},
	Inv2: class extends self.ISpriteInstance {},
	Inv3: class extends self.ISpriteInstance {},
	InventoryPanel: class extends self.ISpriteInstance {},
	Inv4: class extends self.ISpriteInstance {},
	FRVRSDK: class extends self.IInstance {},
	MobileAdvert: class extends self.IInstance {},
	GameSnacksSDK: class extends C3.Plugins.GameSnacks_SDK.Instance {},
	BG: class extends self.ISpriteInstance {},
	Tile: class extends self.ISpriteInstance {},
	Hero: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Board: class extends self.IArrayInstance {},
	Inventory: class extends self.IArrayInstance {},
	Item: class extends self.ISpriteInstance {},
	Items: class extends self.IArrayInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Enemies: class extends self.IArrayInstance {},
	EnemiesConfig: class extends self.IDictionaryInstance {},
	StatsPanel: class extends self.ISpriteInstance {},
	StatTxt: class extends self.ITextInstance {},
	Config_Weapons: class extends self.IDictionaryInstance {},
	HPPanel: class extends self.ISpriteInstance {},
	HPTxt: class extends self.ITextInstance {},
	Config_Shields: class extends self.IDictionaryInstance {},
	DrawPile: class extends self.IArrayInstance {},
	DungeonDoors: class extends self.ISpriteInstance {},
	CoinPanel: class extends self.ISpriteInstance {},
	CoinsTxt: class extends self.ITextInstance {},
	Coin: class extends self.ISpriteInstance {},
	Config_Consumable: class extends self.IDictionaryInstance {},
	EnemyTile: class extends self.ISpriteInstance {},
	Dust: class extends self.ISpriteInstance {},
	TitlePanel: class extends self.ISpriteInstance {},
	Btn_Play: class extends self.ISpriteInstance {},
	CoverHero: class extends self.ISpriteInstance {},
	Torch: class extends self.ISpriteInstance {},
	TorchLight: class extends self.ISpriteInstance {},
	TorchFire: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	DarkMagicProjectile: class extends self.ISpriteInstance {},
	Kurtyna: class extends self.ISpriteInstance {},
	Btn_Continue: class extends self.ISpriteInstance {},
	VFX_ShieldDefense: class extends self.ISpriteInstance {},
	VFX_HitAnimations: class extends self.ISpriteInstance {},
	StatusIcon: class extends self.ISpriteInstance {},
	VFX_Poison: class extends self.ISpriteInstance {},
	TreasurePanel: class extends self.ISpriteInstance {},
	TreasureTxt: class extends self.ITextInstance {},
	GameOverCzacha: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	ThrowingKnife: class extends self.ISpriteInstance {},
	StatusList: class extends self.IArrayInstance {},
	LowHPIndicator: class extends self.ISpriteInstance {},
	Fireball: class extends self.ISpriteInstance {},
	VFX_MagicHit: class extends self.ISpriteInstance {},
	PreloaderIcon: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Soundlist: class extends self.IDictionaryInstance {},
	VFX_Heal: class extends self.ISpriteInstance {},
	VFX_Explosion01: class extends self.ISpriteInstance {},
	VFX_LevelUpSwirl: class extends self.ISpriteInstance {},
	StorePanel: class extends self.ISpriteInstance {},
	Btn_Buy: class extends self.ISpriteInstance {},
	Price_Txt: class extends self.ITextInstance {},
	QuantityText: class extends self.ITextInstance {},
	Btn_Pause: class extends self.ISpriteInstance {},
	Btn_Mute: class extends self.ISpriteInstance {},
	BigPauseIcon: class extends self.ISpriteInstance {},
	PlaceToPutBoughtUpgrades: class extends self.ISpriteInstance {},
	Point: class extends self.ISpriteInstance {},
	Point2: class extends self.ISpriteInstance {},
	Point3: class extends self.ISpriteInstance {},
	Btn_GiveUp: class extends self.ISpriteInstance {},
	DragonPart: class extends self.ISpriteInstance {},
	Btn_WatchAds: class extends self.ISpriteInstance {},
	HowMuchForAnAd: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	Btn_Trash: class extends self.ISpriteInstance {},
	PlaceForUpgrades: class extends self.ISpriteInstance {},
	TooltipPanel: class extends self.ISpriteInstance {},
	Tooltip_Head: class extends self.ITextInstance {},
	Tooltip_Content: class extends self.ITextInstance {},
	TXT_EN_TooltipHead: class extends self.IDictionaryInstance {},
	TXT_EN_TooltipContent: class extends self.IDictionaryInstance {},
	DebugTxt: class extends self.ITextInstance {},
	HTP_Panel: class extends self.ISpriteInstance {},
	HTP_Head: class extends self.ITextInstance {},
	HTP_Content: class extends self.ITextInstance {},
	Hero_VictoryPose: class extends self.ISpriteInstance {},
	HandPointingToSwipe: class extends self.ISpriteInstance {},
	HandPointingToTap: class extends self.ISpriteInstance {},
	HTP_ArrowKeys: class extends self.ISpriteInstance {},
	TXT_PL_TooltipContent: class extends self.IDictionaryInstance {},
	TXT_PL_TooltipHead: class extends self.IDictionaryInstance {},
	Btn_Prev: class extends self.ISpriteInstance {},
	Btn_Next: class extends self.ISpriteInstance {},
	LangTxt: class extends self.ITextInstance {},
	LangList: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	TXT_FR_TooltipContent: class extends self.IDictionaryInstance {},
	TXT_FR_TooltipHead: class extends self.IDictionaryInstance {},
	TXT_ES_TooltipContent: class extends self.IDictionaryInstance {},
	TXT_ES_TooltipHead: class extends self.IDictionaryInstance {},
	TooltipTimer: class extends self.ISpriteInstance {},
	Btn_Back: class extends self.ISpriteInstance {},
	Btn_Store: class extends self.ISpriteInstance {},
	BtnStore_Label: class extends self.ITextInstance {},
	Label_Upgrades: class extends self.ITextInstance {},
	Label_Skins: class extends self.ITextInstance {},
	Btn_BuySkin: class extends self.ISpriteInstance {},
	PriceSkin_Txt: class extends self.ITextInstance {},
	Price_Coin: class extends self.ISpriteInstance {},
	ChosenSkinFrame: class extends self.ISpriteInstance {},
	SkinPrices: class extends self.IDictionaryInstance {},
	Date: class extends self.IInstance {},
	BossLevelIcon: class extends self.ISpriteInstance {},
	RadialLight: class extends self.ISpriteInstance {},
	DailyMissions: class extends self.IDictionaryInstance {},
	DailyMissionPanel: class extends self.ISpriteInstance {},
	DailyMissionText: class extends self.ITextInstance {},
	DailyMissionDone: class extends self.ISpriteInstance {},
	HowMuchForDaily: class extends self.ISpriteInstance {},
	Artifacts: class extends self.IDictionaryInstance {},
	CtrlBtn: class extends self.ISpriteInstance {},
	Label_DailyQuest: class extends self.ITextInstance {},
	Label_Unlock: class extends self.ITextInstance {},
	TooltipStore_Head: class extends self.ITextInstance {},
	TooltipStore_Content: class extends self.ITextInstance {},
	TooltipStorePanel: class extends self.ISpriteInstance {},
	Btn_Yes: class extends self.ISpriteInstance {},
	Btn_No: class extends self.ISpriteInstance {},
	ConfirmationPopup: class extends self.ISpriteInstance {},
	ConfirmationPopup_Txt: class extends self.ITextInstance {},
	Label_Revive: class extends self.ITextInstance {},
	DailyRewardPanel: class extends self.ISpriteInstance {},
	DailyReward_Label: class extends self.ITextInstance {},
	Btn_Thropies: class extends self.ISpriteInstance {},
	BtnThropies_Label: class extends self.ITextInstance {},
	Trophy: class extends self.ISpriteInstance {},
	TrophyPanel: class extends self.ISpriteInstance {},
	Label_Trophies: class extends self.ITextInstance {},
	Label_TrophyName: class extends self.ITextInstance {},
	Progress_Txt: class extends self.ITextInstance {},
	BoardElements: class extends self.ISpriteInstance {}
}