function m(b,a,c,d){b.j.qb(b.tb,a,c,d)}function n(b,a,c,d){b.j.ea?m(b,a,c,d):b.j.Xe()._OnMessageFromDOM({type:"event",component:b.tb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function p(b,a,c){b.j.B(b.tb,a,c)}function v(b,a){for(const [c,d]of a)p(b,c,d)}function w(b){b.Zb||(b.j.Ec(b.ne),b.Zb=!0)}window.qa=class{constructor(b,a){this.j=b;this.tb=a;this.Zb=!1;this.ne=()=>this.Ha()}vd(){}Ha(){}};
window.If=class{constructor(){this.qd=-1}l(){-1!==this.qd&&(self.clearTimeout(this.qd),this.qd=-1)}};"use strict";class aa{constructor(b){this.wb=b;this.Wc=!1;this.dd=!0;this.yb=this.ta=this.rd=-1}}
function ba(b,a){const c=a.elementId,d=b.zd(c,a),e=new aa(d);b.Na.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.dd=!!a.isVisible;d.addEventListener("focus",()=>{x(b,"elem-focused",c)});d.addEventListener("blur",()=>{x(b,"elem-blurred",c)});const f=a.htmlIndex;e.rd=f;e.yb=a.htmlZIndex;b.Wa&&(a=b.j.vc(f),e.ta=a,b.j.Nb(a).appendChild(d))}function ca(b,a,c){p(b,a,d=>{const e=y(b,d.elementId);return c(e,d)})}
function y(b,a){b=b.Na.get(a);if(!b)throw Error(`no element with id ${a}`);return b.wb}function x(b,a,c,d){d||(d={});d.elementId=c;m(b,a,d)}function da(b,a,c){var d;d||(d={});d.elementId=c;n(b,a,d)}
window.uc=class extends self.qa{constructor(b){super(b,"text-input");this.Na=new Map;this.Wa=!0;v(this,[["create",a=>ba(this,a)],["destroy",a=>{a=a.elementId;const c=y(this,a);this.Wa&&c.parentElement.removeChild(c);this.Na.delete(a)}],["set-visible",a=>{if(this.Wa){var c=this.Na.get(a.elementId),d=c.wb;c.Wc?d.style.display=a.isVisible?"":"none":c.dd=!!a.isVisible}}],["update-position",a=>{if(this.Wa){var c=this.Na.get(a.elementId),d=c.wb,e=this.j;d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=
a.width+"px";d.style.height=a.height+"px";var f=a.fontSize;null!==f&&(d.style.fontSize=f+"em");f=a.htmlIndex;c.rd=f;f=e.vc(f);f!==c.ta&&(d.remove(),e.Nb(f).appendChild(d),c.ta=f,e.Qc());a=a.htmlZIndex;a!==c.yb&&(c.yb=a,e.Qc());c.Wc||(c.Wc=!0,c.dd&&(d.style.display=""))}}],["update-state",a=>{const c=y(this,a.elementId);this.Dc(c,a)}],["focus",a=>this.Nc(a)],["set-css-style",a=>{const c=y(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",
a=>{y(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{y(this,a.elementId).removeAttribute(a.name)}]]);ca(this,"get-element",a=>a)}zd(){throw Error("required override");}Dc(){throw Error("required override");}Nc(b){var a=y(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const ea=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),z=/android/i.test(navigator.userAgent);let fa=0;
function ha(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.yf?new Promise(c=>{const d="c3_resolve_"+fa;++fa;self[d]=c;a.textContent=b.Cf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function ia(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let A=new Audio;
const ja={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ka(b){b=await la(b);return(new TextDecoder("utf-8")).decode(b)}
function la(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const ma=[];let C=0;window.RealFile=window.File;const D=[],na=new Map,oa=new Map;let pa=0;const ta=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ta.push(b)};const ua=new Set(["cordova","playable-ad","instant-games"]);let va=!1;
window.Z=class b{constructor(a){this.ea=a.Ef;this.Ba=null;this.ba="";this.gb=a.Bf;this.Lb={};this.$a=this.ya=null;this.Ya=[];this.na=null;this.$d=!0;this.M=[];this.kd=[];this.ld=!1;this.oe=()=>this.Ve();this.$c=!1;this.Ud=0;this.Ab=null;this.fb=-1;this.uf=()=>this.ff();this.Ib=new Set;this.sd=null;this.pe=[];this.u=a.qe;this.$b="file"===location.protocol.substr(0,4);if("playable-ad"===this.u||"instant-games"===this.u)this.ea=!1;if("cordova"===this.u&&this.ea&&z){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.ea=!1)}this.ra()?self.chrome.webview.addEventListener("message",c=>this.Kd(c.data)):"macos-wkwebview"===this.u&&(self.C3WrapperOnMessage=c=>this.Kd(c));this.cc=this.va=null;"html5"!==this.u||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.kf(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.af());this.B("runtime","cordova-fetch-local-file",c=>this.bf(c));this.B("runtime","create-job-worker",()=>this.cf());this.B("runtime","send-wrapper-extension-message",c=>this.jf(c));"cordova"===this.u?document.addEventListener("deviceready",()=>this.Rb(a)):this.Rb(a)}l(){this.Fc();this.Ba&&(this.Ba=this.Ba.onmessage=null);this.ya&&(this.ya.terminate(),this.ya=null);this.$a&&(this.$a.l(),this.$a=null);for(const {canvas:a,
jb:c}of this.M)a.remove(),c.remove();this.M.length=0}Bd(){return this.M[0].canvas}vc(a){return Math.min(a,this.M.length-1)}Nb(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].jb}Le(){return ea&&"cordova"===this.u}ob(){const a=navigator.userAgent;return ea&&ua.has(this.u)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Je(){return z}Cd(){return z&&ua.has(this.u)}Ed(){return"windows-webview2"===this.u||!!("preview"===this.u&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}ra(){return this.Ed()||"xbox-uwp-webview2"===this.u}async Rb(a){this.ea&&!await ia()&&(this.ea=!1);"macos-wkwebview"===this.u?this.Ja({type:"ready"}):this.ra()&&(this.mf(),this.pe=(await this.$e()).registeredComponentIds);if("playable-ad"===this.u){this.va=self.c3_base64files;this.cc={};await this.Se();for(let d=0,e=a.ib.length;d<e;++d){var c=a.ib[d];this.cc.hasOwnProperty(c)?a.ib[d]={yf:!0,Cf:this.cc[c]}:this.va.hasOwnProperty(c)&&(a.ib[d]=URL.createObjectURL(this.va[c]))}a.rc=
[]}if("nwjs"===this.u&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Ec(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.Af?this.ba=a.Af:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.Gf&&(this.Lb=a.Gf);c=new MessageChannel;this.Ba=c.port1;this.Ba.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.ef(d));this.Ab=
new self.Me(this);await wa(this.Ab);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ea?await this.Ze(a,c.port2):await this.Ye(a,c.port2)}Hc(a){a=this.Lb.hasOwnProperty(a)?this.Lb[a]:a.endsWith("/workermain.js")&&this.Lb.hasOwnProperty("workermain.js")?this.Lb["workermain.js"]:"playable-ad"===
this.u&&this.va.hasOwnProperty(a)?this.va[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async tc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.u&&this.$b)return a=await this.Mb(d.xf?a:this.gb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}sa(){return Math.max(window.innerWidth,1)}ha(){return Math.max(window.innerHeight,1)}Id(a){var c=this.ba,d=location.href,e=this.sa(),f=this.ha(),g=window.devicePixelRatio,h=b.nb(),k=a.Mf,l=window.cr_previewImageBlobs||this.va,q=window.cr_previewProjectFileBlobs,r=window.cr_previewProjectFiles,t=window.cr_swClientId||"";a=a.qe;var u=(new URLSearchParams(self.location.search)).has("debug"),B=this.Ab;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,
projectData:k,previewImageBlobs:l,previewProjectFileBlobs:q,previewProjectFileSWUrls:r,swClientId:t,exportType:a,isDebug:u,ife:!!self.Lf,jobScheduler:{inputPort:B.Zc,outputPort:B.jd,maxNumWorkers:B.rf},supportedAudioFormats:ja,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.gb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.gb+"opus.wasm.wasm",isFileProtocol:this.$b,isiOSCordova:this.Le(),isiOSWebView:this.ob(),isWindowsWebView2:this.Ed(),isAnyWebView2Wrapper:this.ra(),wrapperComponentIds:this.pe,
isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ze(a,c){const d=this.Hc(a.Ff);"preview"===this.u?(this.ya=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,q)=>{const r=t=>{this.ya.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():q()};this.ya.addEventListener("message",r);this.ya.postMessage({type:"construct-worker-init","import":(new URL(d,this.ba)).toString()})})):this.ya=await this.tc(d,this.ba,{type:"module",name:"Runtime",xf:!0});
const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,jb:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.rc||[],k=a.ib;h=await Promise.all(h.map(l=>this.Ua(l)));k=await Promise.all(k.map(l=>this.Ua(l)));if("cordova"===this.u)for(let l=0,q=a.qc.length;l<q;++l){const r=
a.qc[l],t=r[0];if(t===a.td||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Ua(t)}this.ya.postMessage(Object.assign(this.Id(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.qc,mainProjectScript:a.td,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...xa(this.Ab)]);this.Ya=D.map(l=>new l(this));this.Hd();ya(e);za(g);Aa(this.na);self.c3_callFunction=(l,q)=>{var r=this.na;return r.j.Fd(r.tb,"js-invoke-function",
{name:l,params:q})};"preview"===this.u&&(self.goToLastErrorScript=()=>this.qb("runtime","go-to-last-error-script"))}async Ye(a,c){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,jb:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Ya=D.map(h=>new h(this));this.Hd();ya(d);za(e);e=a.ib.map(h=>"string"===
typeof h?(new URL(h,this.ba)).toString():h);if(Array.isArray(a.rc)){var f=[...a.rc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=await Promise.all(e.map(h=>this.Ua(h)));await Promise.all(e.map(h=>ha(h)));e=self.C3_ProjectScriptsStatus;f=a.td;const g=a.qc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Ua(k),await ha(k),"preview"!==this.u||e[h]||this.Md(h,"main script did not run to completion")}catch(l){this.Md(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=
await this.Ua(k),await ha(k);"preview"===this.u&&"object"!==typeof self.Hf.Jf?(this.Tb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Id(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:ta}),Aa(this.na),this.Jd(),this.$a=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.$a,
a))}Md(a,c){this.Tb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Jd(){this.Tb()}Tb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async cf(){const a=await Ba(this.Ab);return{outputPort:a,transferables:[a]}}kf(a){if(!this.$c){var c=a.styleWidth+"px",d=a.styleHeight+
"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,jb:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.$d&&(g.style.display="",h.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.$d=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";
a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,jb:q}=this.M.pop();q.remove();this.ea&&!d?this.kd.push(l):l.remove()}else if(c>this.M.length)for(let l=0,q=c-this.M.length;l<q;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),this.ea?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=
f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,ya(c),za(d),this.M.push({canvas:c,jb:d});for(const l of this.Ya)if(l instanceof window.uc&&l.Wa)for(const q of l.Na.values())e=l.j.vc(q.rd),f=q.ta,-1!==e&&-1!==f&&e!==f&&(f=q.wb,f.remove(),l.j.Nb(e).appendChild(f),q.ta=e);this.Qc();return{addedCanvases:a,transferables:k}}af(){for(const a of this.kd)a.remove();this.kd.length=0}Qc(){this.ld||(this.ld=!0,this.Ec(this.oe))}Ve(){this.Ld(this.oe);
this.ld=!1;let a=[];for(var c of this.Ya)if(c instanceof window.uc){var d=c.Wa?[...c.Na.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.ta,l=h.ta;return k!==l?k-l:g.yb-h.yb});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.ta!==c&&(this.Gd(c,a.slice(d,e)),c=g.ta,d=e)}d<e&&this.Gd(c,a.slice(d,e))}Gd(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.wb);var d=new Set(c);a=this.Nb(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);
for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Xe(){if(this.ea)throw Error("not available in worker mode");return this.$a}qb(a,c,d,e,f){this.Ba.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}Fd(a,c,d,e,f){const g=pa++,h=new Promise((k,l)=>{oa.set(g,{resolve:k,reject:l})});this.Ba.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===
c)return this.df(a);if("result"===c)this.gf(a);else if("runtime-ready"===c)this.hf();else if("alert-error"===c)this.Tb(),alert(a.message);else if("creating-runtime"===c)this.Jd();else throw Error(`unknown message '${c}'`);}df(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=na.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Sb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Sb(f,!0,h)).catch(h=>
{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Sb(f,!1,""+h)}):this.Sb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Sb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.Ba.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}gf(a){const c=a.responseId,d=a.isOk;a=a.result;const e=oa.get(c);d?e.resolve(a):e.reject(a);oa.delete(c)}B(a,c,d){let e=na.get(a);e||(e=new Map,na.set(a,
e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static pa(a){if(D.includes(a))throw Error("DOM handler already added");D.push(a)}Hd(){for(const a of this.Ya)if("runtime"===a.tb){this.na=a;return}throw Error("cannot find runtime DOM handler");}ef(a){this.qb("debugger","message",a)}hf(){for(const a of this.Ya)a.vd()}static nb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||va)}static Ub(a){va=!!a}Ec(a){this.Ib.add(a);
this.Pc()}Ld(a){this.Ib.delete(a);0===this.Ib.size&&this.Fc()}Pc(){-1===this.fb&&0<this.Ib.size&&(this.fb=requestAnimationFrame(this.uf))}Fc(){-1!==this.fb&&(cancelAnimationFrame(this.fb),this.fb=-1)}ff(){this.fb=-1;for(const a of this.Ib)a();this.Pc()}Ia(a){this.na.Ia(a)}Ta(a){this.na.Ta(a)}Oc(){this.na.Oc()}Qb(a){this.na.Qb(a)}Ke(){return!!ja["audio/webm; codecs=opus"]}async nf(a){a=await this.Fd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Oe(a){this.$c=!0;this.Ud=
a}Ie(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}Dd(a){return!this.Ie(a)}async Ua(a){return"cordova"===this.u&&(a.startsWith("file:")||this.$b&&this.Dd(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Mb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async bf(a){const c=a.filename;switch(a.as){case "text":return await this.He(c);case "buffer":return await this.Mb(c);default:throw Error("unsupported type");
}}yd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async He(a){a=await this.yd(a);return await ka(a)}Gc(){if(ma.length&&!(8<=C)){C++;var a=ma.shift();this.Te(a.filename,a.Df,a.wf)}}Mb(a){return new Promise((c,d)=>{ma.push({filename:a,Df:e=>{C--;this.Gc();c(e)},wf:e=>{C--;this.Gc();d(e)}});this.Gc()})}async Te(a,c,d){try{const e=await this.yd(a),f=await la(e);c(f)}catch(e){d(e)}}Kd(a){if("entered-fullscreen"===
a)b.Ub(!0),F(this.na);else if("exited-fullscreen"===a)b.Ub(!1),F(this.na);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.sd(a),this.sd=null):"extension-message"===c?this.qb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}jf(a){this.Ja({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}Ja(a){this.ra()?window.chrome.webview.postMessage(JSON.stringify(a)):
"macos-wkwebview"===this.u&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}mf(){window.moveTo=(a,c)=>{this.Ja({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.Ja({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}$e(){return this.ra()?new Promise(a=>{this.sd=a;this.Ja({type:"wrapper-init"})}):Promise.resolve()}async Se(){const a=[];for(const [c,d]of Object.entries(this.va))a.push(this.Re(c,d));
await Promise.all(a)}async Re(a,c){if("object"===typeof c)this.va[a]=new Blob([c.str],{type:c.type}),this.cc[a]=c.str;else{let d=await this.We(c);d||(d=this.Ue(c));this.va[a]=d}}async We(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Ue(a){a=this.lf(a);return this.Qe(a.data,
a.zf)}lf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{zf:a,data:d}}Qe(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],
{type:c})}};"use strict";const G=self.Z,Ca=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),H={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Da={dispatchUserScriptEvent:!0},Ea={dispatchRuntimeEvent:!0};function Fa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ga(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}
async function I(b){b=URL.createObjectURL(b);try{return await Ga(b)}finally{URL.revokeObjectURL(b)}}function Ha(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ia(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await I(b);var d=await Ha(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await I(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await I(b)}
function Ja(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ka=new Set(["input","textarea","datalist","select"]),La=new Set(["canvas","body","html"]);function J(b){b.target.tagName&&La.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ma(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Na(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await I(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ia(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Oa=!1;document.addEventListener("pause",()=>Oa=!0);document.addEventListener("resume",()=>Oa=!1);function ya(b){b.addEventListener("selectstart",J);b.addEventListener("gesturehold",J);b.addEventListener("pointerdown",J)}function za(b){b.addEventListener("selectstart",Ma);b.addEventListener("gesturehold",Ma);b.addEventListener("touchstart",Ma)}function Aa(b){b.Td=!0;b.ed=b.j.sa();b.Bb=b.j.ha()}
function F(b){if(!b.la){var a=G.nb();a&&"any"!==b.od&&Pa(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.sa(),innerHeight:b.ha()})}}async function Qa(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ra(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Sa(b){return await self.C3_GetSvgImageSize(b.blob)}function Ta(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ua(b){self.setTimeout(()=>{b.Sd=!0},1E3);"cordova"===b.j.u?(document.addEventListener("pause",()=>Va(b,!0)),document.addEventListener("resume",()=>Va(b,!1))):document.addEventListener("visibilitychange",()=>Va(b,"hidden"===document.visibilityState));b.hc=!("hidden"!==document.visibilityState&&!Oa);return{isSuspended:b.hc}}
function Wa(b){b.Od||(b.Od=!0,window.addEventListener("deviceorientation",a=>{b.la||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},H)}),window.addEventListener("deviceorientationabsolute",a=>{b.la||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},H)}))}
function Xa(b){b.Nd||(b.Nd=!0,window.addEventListener("devicemotion",a=>{if(!b.la){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},H)}}))}async function Ya(b){await Fa(b.url)}
function Za(b,a){b.Vd=a.message;-1===b.Uc&&(b.Uc=setTimeout(()=>{b.Uc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Vd)},250))}function $a(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:G.nb(),innerWidth:b.sa(),innerHeight:b.ha()})}
function Va(b,a){b.hc!==a&&((b.hc=a)?b.j.Fc():b.j.Pc(),m(b,"visibilitychange",{hidden:a}),!a&&b.j.ob()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function ab(b,a,c){"Backspace"===c.key&&J(c);if(b.j.ra()){var d=["r","p","f","g","u"];(["F3","F5","F7"].includes(c.key)||c.ctrlKey&&d.includes(c.key))&&c.preventDefault()}b.la||(d=Ca.get(c.code)||c.code,n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},H))}
function K(b,a,c,d){b.la||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Ea,pageX:c.pageX,pageY:c.pageY+b.Ea,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function L(b,a,c){if(!b.la){var d=0;"mouse"===c.pointerType&&(d=b.gd);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Ea,pageX:c.pageX,pageY:c.pageY+b.Ea,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},H);"mouse"===c.pointerType&&
(b.gd=c.buttons)}}function bb(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Ea=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Ea=a))}}
function cb(b,a,c,d){const e=b.sa(),f=b.ha();b.hb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:G.nb()}):10>d&&db(b,e,f,d+1)}function db(b,a,c,d){-1!==b.hb&&clearTimeout(b.hb);b.hb=setTimeout(()=>cb(b,a,c,d),48)}
function Pa(b){b=b.od;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function eb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
G.pa(class extends self.qa{constructor(b){super(b,"runtime");this.Td=!1;this.hb=-1;this.od="any";this.hc=this.Nd=this.Od=!1;this.nc=document.createElement("div");this.nc.className="c3-screen-reader-text";this.nc.setAttribute("aria-live","polite");document.body.appendChild(this.nc);this.Ma=null;this.la=!1;this.Vd="";this.Uc=-1;this.Sd=!1;this.ed=b.sa();this.Bb=b.ha();this.Ea=this.Kb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Qa(c));b.B("runtime","raster-svg-image",c=>Ra(c));b.B("runtime","get-svg-image-size",c=>Sa(c));b.B("runtime","set-target-orientation",c=>{this.od=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Ta(c));b.B("runtime","go-to-script",c=>Ta(c));b.B("runtime","before-start-ticking",()=>Ua(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Ma||(this.Ma=document.createElement("div"),this.Ma.id="inspectOutline",document.body.appendChild(this.Ma));var d=this.Ma;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ma&&(this.Ma.style.display="none")});b.B("runtime","enable-device-orientation",()=>Wa(this));b.B("runtime","enable-device-motion",()=>Xa(this));b.B("runtime","add-stylesheet",c=>Ya(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>this.Kc(c));b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.nc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===d?
(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.la=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.j.Bd().style.display="";this.j.Oe(c.duration)});b.B("runtime","export-to-video-progress",c=>Za(this,c));b.B("runtime","exported-to-video",c=>{window.vf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.vf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Ja(d)||c.preventDefault()});window.addEventListener("selectstart",J);window.addEventListener("gesturehold",J);window.addEventListener("touchstart",J,{passive:!1});window.addEventListener("pointerdown",J,{passive:!1});this.gd=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Na,{passive:!1});window.addEventListener("wheel",Na,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.la&&this.Td){var c=this.sa();var d=this.ha();if(this.j.Cd()){if(this.Sd){if(this.ed===
c&&d<this.Bb){this.Kb=this.Bb-d;bb(this,this.Bb,this.Kb);c=void 0;break a}0<this.Kb&&(this.Kb=0,bb(this,d,this.Kb))}this.ed=c;this.Bb=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:G.nb()});this.j.ob()&&(-1!==this.hb&&clearTimeout(this.hb),cb(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>F(this));window.addEventListener("webkitfullscreenchange",()=>F(this));window.addEventListener("mozfullscreenchange",()=>
F(this));window.addEventListener("fullscreenerror",c=>$a(this,c));window.addEventListener("webkitfullscreenerror",c=>$a(this,c));window.addEventListener("mozfullscreenerror",c=>$a(this,c));if(b.ob()){if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d})}else window.addEventListener("focusout",()=>{{const e=document.activeElement;if(e){var c=
e.tagName.toLowerCase();var d=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?d.has(e.type.toLowerCase()||"text"):Ja(e)}else c=!1}c||(document.scrollingElement.scrollTop=0)});document.documentElement.setAttribute("ioswebview","")}this.ab=new Set;this.ec=new WeakSet;this.Aa=!1}vd(){window.addEventListener("focus",()=>{m(this,"window-focus",null,Ea)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}m(this,"window-blur",{parentHasFocus:a},Ea);this.gd=0});window.addEventListener("focusin",a=>{a=a.target;(Ka.has(a.tagName.toLowerCase())||Ja(a))&&m(this,"keyboard-blur",null,Ea)});window.addEventListener("keydown",a=>ab(this,"keydown",a));window.addEventListener("keyup",a=>ab(this,"keyup",a));window.addEventListener("mousedown",a=>K(this,"mousedown",a,Da));window.addEventListener("mousemove",a=>K(this,"mousemove",a,Da));window.addEventListener("mouseup",a=>K(this,"mouseup",a,Da));window.addEventListener("dblclick",
a=>K(this,"dblclick",a,H));window.addEventListener("wheel",a=>{this.la||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Ea,pageX:a.pageX,pageY:a.pageY+this.Ea,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},H)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();eb(a.target)&&document.activeElement&&!eb(document.activeElement)&&document.activeElement.blur();L(this,"pointerdown",a)});this.j.ea&&"undefined"!==typeof window.onpointerrawupdate&&
self===self.top?window.addEventListener("pointerrawupdate",a=>{L(this,"pointermove",a)}):window.addEventListener("pointermove",a=>L(this,"pointermove",a));window.addEventListener("pointerup",a=>L(this,"pointerup",a));window.addEventListener("pointercancel",a=>L(this,"pointercancel",a));const b=()=>this.Oc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",
b,!0);this.j.Je()&&!this.j.Cd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{bb(this,this.ha(),navigator.virtualKeyboard.boundingRect.height)}));this.j.ob()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}sa(){return this.j.sa()}ha(){return this.j.ha()}Oc(){var b=[...this.ab];this.ab.clear();if(!this.Aa)for(const a of b)(b=a.play())&&b.catch(()=>{this.ec.has(a)||this.ab.add(a)})}Ia(b){if("function"!==
typeof b.play)throw Error("missing play function");this.ec.delete(b);let a;try{a=b.play()}catch(c){this.ab.add(b);return}a&&a.catch(()=>{this.ec.has(b)||this.ab.add(b)})}Ta(b){this.ab.delete(b);this.ec.add(b)}Qb(b){this.Aa=!!b}Kc(b){alert(b.message)}});"use strict";
async function wa(b){if(b.pf)throw Error("already initialised");b.pf=!0;var a=b.Ca.Hc(("playable-ad"===b.Ca.u?b.Ca.gb:"")+"dispatchworker.js");b.Tc=await b.Ca.tc(a,b.sb,{name:"DispatchWorker"});a=new MessageChannel;b.Zc=a.port1;b.Tc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.jd=await Ba(b)}function xa(b){return[b.Zc,b.jd]}
async function Ba(b){const a=b.be.length;var c=b.Ca.Hc(("playable-ad"===b.Ca.u?b.Ca.gb:"")+"jobworker.js");c=await b.Ca.tc(c,b.sb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Tc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.be.push(c);return e.port1}
self.Me=class{constructor(b){this.Ca=b;this.sb=b.ba;this.sb="preview"===b.u?this.sb+"workers/":this.sb+b.gb;this.rf=Math.min(navigator.hardwareConcurrency||2,16);this.Tc=null;this.be=[];this.jd=this.Zc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.Z({Ef:!1,Ff:"workermain.js",ib:["scripts/c3runtime.js"],qc:[],td:"",Bf:"scripts/",rc:[],qe:"html5"}));"use strict";function fb(){}
function gb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>m(b,"sw-message",a.data))}
function hb(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.Z.pa(class extends self.qa{constructor(b){super(b,"browser");this.u="";v(this,[["get-initial-state",a=>this.Mc(a)],["ready-for-sw-messages",()=>gb(this)],["alert",a=>this.Kc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Nc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>hb(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===
c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):"preview"===a||this.j.ra()?window.open(c,"_blank"):this.Kf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.j.ra()||"macos-wkwebview"===this.u)self.Z.Ub(!0),this.j.Ja({type:"set-fullscreen",
fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(fb)}}],["exit-fullscreen",
()=>{if(this.j.ra()||"macos-wkwebview"===this.u)self.Z.Ub(!1),this.j.Ja({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(fb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;
a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",
e),c={isOk:!1}}}return c}],["set-window-size",a=>{window.resizeTo(a.windowWidth,a.windowHeight)}],["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}]]);window.addEventListener("online",()=>{m(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{m(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{m(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{m(this,"backbutton")})}Mc(b){this.u=b.exportType;
return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}Kc(b){alert(b.message)}Nc(b){b=b.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});
"use strict";let ib=!1;async function jb(b){var a=lb(b.index);if(a&&(a=a.vibrationActuator)&&a.playEffect)try{await a.playEffect("dual-rumble",{duration:b.duration,startDelay:0,weakMagnitude:b.weakMag,strongMagnitude:b.strongMag})}catch(c){console.warn("[Gamepad] Failed to vibrate gamepad: ",c)}}function M(){try{return Array.from(navigator.getGamepads()).filter(b=>b&&b.connected)}catch(b){return ib||(console.warn("[Construct] Failed to access gamepads: ",b),ib=!0),[]}}
function lb(b){for(const a of M())if(a.index===b)return a;return null}
self.Z.pa(class extends self.qa{constructor(b){super(b,"gamepad");this.ae=!!navigator.getGamepads;this.bd=!1;p(this,"is-supported",()=>this.ae);p(this,"ready",()=>{this.bd=!0;for(const a of M())m(this,"gamepad-connected",{index:a.index,id:a.id});this.ae&&w(this)});p(this,"vibrate",a=>jb(a));p(this,"reset-vibrate",a=>{(a=lb(a.index))&&(a=a.vibrationActuator)&&a.reset&&a.reset()});window.addEventListener("gamepadconnected",a=>{this.bd&&(a=a.gamepad,m(this,"gamepad-connected",{index:a.index,id:a.id}))});
window.addEventListener("gamepaddisconnected",a=>{this.bd&&m(this,"gamepad-disconnected",{index:a.gamepad.index})});window.addEventListener("unload",()=>{for(const a of M()){const c=a.vibrationActuator;c&&c.reset&&c.reset()}})}Ha(){var b=M();b.length&&(b=b.map(a=>({index:a.index,id:a.id,buttons:a.buttons.map(c=>({pressed:c.pressed,value:c.value})),axes:a.axes})),m(this,"input-update",b))}});"use strict";function mb(b){return new Promise((a,c)=>{b.getInsetTop(a,c)})}
function nb(b){return new Promise((a,c)=>{b.getInsetRight(a,c)})}function ob(b){return new Promise((a,c)=>{b.getInsetBottom(a,c)})}function pb(b){return new Promise((a,c)=>{b.getInsetLeft(a,c)})}
async function qb(b){if(!b.Pa)try{b.Pa=await navigator.wakeLock.request("screen"),b.Pa.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.Pa=null;m(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),m(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),m(b,"wake-lock-error")}}
async function rb(b){const a=await sb();m(b,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:a})}
async function sb(){var b=self.AndroidNotch;if(b)try{return await Promise.all([mb(b),nb(b),ob(b),pb(b)])}catch(c){return console.error("[Construct] Failed to get Android safe area inset: ",c),[0,0,0,0]}else{var a=document.body;b=a.style;b.setProperty("--temp-sai-top","env(safe-area-inset-top)");b.setProperty("--temp-sai-right","env(safe-area-inset-right)");b.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");b.setProperty("--temp-sai-left","env(safe-area-inset-left)");a=getComputedStyle(a);
a=[a.getPropertyValue("--temp-sai-top"),a.getPropertyValue("--temp-sai-right"),a.getPropertyValue("--temp-sai-bottom"),a.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);return isFinite(c)?c:0});b.removeProperty("--temp-sai-top");b.removeProperty("--temp-sai-right");b.removeProperty("--temp-sai-bottom");b.removeProperty("--temp-sai-left");return a}}
self.Z.pa(class extends self.qa{constructor(b){super(b,"platform-info");v(this,[["get-initial-state",()=>this.Mc()],["request-wake-lock",()=>qb(this)],["release-wake-lock",()=>{this.Pa&&(this.Pa.release(),this.Pa=null)}]]);window.addEventListener("resize",()=>rb(this));this.Pa=null}async Mc(){const b=await sb();return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:b,supportsWakeLock:!!navigator.wakeLock,isNwjs:"undefined"!==
typeof nw}}});"use strict";async function tb(b,a){a=a.type;let c=!0;0===a?c=await ub():1===a&&(c=await vb());m(b,"permission-result",{type:a,result:c})}async function ub(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function vb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.Z.pa(class extends self.qa{constructor(b){super(b,"touch");p(this,"request-permission",a=>tb(this,a))}});"use strict";const wb=180/Math.PI;
async function xb(b,a){if(a.isiOSCordova||a.isSafari)b.jc=!0;b.pd=a.timeScaleMode;b.ge=["equalpower","HRTF","soundfield"][a.panningModel];b.Rd=["linear","inverse","exponential"][a.distanceModel];b.he=a.refDistance;b.fe=a.maxDistance;b.je=a.rolloffFactor;if(b.j.$c)b.jc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.j.Ud)});else{var c={latencyHint:a.latencyHint};b.me||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");yb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&yb(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Xa=b.g.createGain();b.Xa.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ca);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
N(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function zb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,q=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.ce=g.slice(0);Ab(b,g);try{b.R=await Bb(b,c,d,e,g,f);if(q){O(b.R,!0);var u=b.R,B=q.innerAngle,ra=q.outerAngle,sa=q.outerGain;if(u.zb){Cb(u,q.x,q.y,q.z,q.angle);var E=self.kb.Pe;u.wa[0]!==E(B)&&
(u.wa[0]=E(B),u.F.coneInnerAngle=E(B));u.wa[1]!==E(ra)&&(u.wa[1]=E(ra),u.F.coneOuterAngle=E(ra));u.wa[2]!==sa&&(u.wa[2]=sa,u.F.coneOuterGain=sa)}q.hasOwnProperty("uid")&&(b.R.ua=q.uid)}else"number"===typeof r&&0!==r?(P(b.R,!0),Db(b.R,r)):(O(b.R,!1),P(b.R,!1));b.R.Play(h,k,l,t)}catch(Qb){console.error("[Construct] Audio: error starting playback: ",Qb);return}finally{c=g.join(" ");d=b.Hb.get(c);if(!d)throw Error("expected pending tag");d.ud--;0===d.ud&&(d.resolve(),b.Hb.delete(c))}w(b)}
async function Eb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await Fb(b,c);for(const h of Q(b,c))if(!h.za){c=h.G.gain;c.cancelScheduledValues(0);var f=h.v.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ra=d;h.Za=g;h.le=a}R(b)}async function Gb(b,a){const c=a.tags;a=a.rate;await Fb(b,c);for(const d of Q(b,c))d.ma!==a&&(d.ma=a,d.Ka())}async function Hb(b,a){const c=a.tags;a=a.pos;await Fb(b,c);for(const d of Q(b,c))d.Ac(a)}
async function Ib(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await Bb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function Jb(b,a){if(a=await N(b,"",a.url,a.type,a.isMusic,!0))a.l(),a=b.ja.indexOf(a),-1!==a&&b.ja.splice(a,1)}
async function Kb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await N(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.we(b,...e);else if("delay"===c)d=new self.ue(b,...e);else if("convolution"===c){var g=d=new self.te(b,f.ia,...e),h=a.bufferType;g.Pd=a.bufferOriginalUrl;g.Qd=h}else if("flanger"===c)d=
new self.xe(b,...e);else if("phaser"===c)d=new self.ze(b,...e);else if("gain"===c)d=new self.ye(b,...e);else if("stereopan"===c)d=new self.Be(b,...e);else if("tremolo"===c)d=new self.Ce(b,...e);else if("ringmod"===c)d=new self.Ae(b,...e);else if("distortion"===c)d=new self.ve(b,...e);else if("compressor"===c)d=new self.se(b,...e);else if("analyser"===c)d=new self.re(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ka.get(h);l||(l=[],g.ka.set(h,l));d.Zd=l.length;d.nd=
h;l.push(d);Lb(g,h)}Mb(b)}
async function Nb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Fa()&&1===c||!e.Fa()&&2===c?d.push(e):e.l();b.H=d}for(const f of b.ka.values())for(const g of f)g.l();b.ka.clear();b.oc=a.timeScale;b.Vc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ca[e]=d[e];b.g.listener.setOrientation(...b.ca)}b.Aa=a.isSilent;b.j.Qb(b.Aa);b.dc=a.masterVolume;b.Xa.gain.value=
b.dc;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>Kb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Ob(b,f,c)));R(b)}
async function Pb(b,a){try{const c=b.g.suspend(a.time);b.Yd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.j.qb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Rb(d)),b.Yd=!0);await c}catch(c){Rb(c)}}
function yb(b){b.Yb||(b.Yc=!1,window.addEventListener("pointerup",b.Da,!0),window.addEventListener("touchend",b.Da,!0),window.addEventListener("click",b.Da,!0),window.addEventListener("keydown",b.Da,!0),b.Yb=!0)}
async function N(b,a,c,d,e,f){for(var g of b.ja)if(g.mb()===c)return await Sb(g),g;if(f)return null;if(e&&(b.jc||b.Xd)){f=0;for(let h=0,k=b.ja.length;h<k;++h)g=b.ja[h],b.ja[f]=g,g.Fa()?g.l():++f;b.ja.length=f}f="audio/webm; codecs=opus"===d&&!b.me;e&&f&&(b.Xd=!0);c=!e||b.jc||f?new self.Fe(b,a,c,d,e,f):new self.De(b,a,c,d,e);b.ja.push(c);await Sb(c);b.ee.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.ga()}),b.ee.add(a));return c}
function Tb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Ub(b,a){return(a=b.ka.get(a.toLowerCase()))?a[0].N():b.fa()}function Lb(b,a){a=a.toLowerCase();let c=b.fa();var d=b.ka.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.fa()):e.U(d[f+1].N())}}for(const f of Vb(b,a))d=c,e=f.da||f.F||f.G,e.disconnect(),e.connect(d);b.Oa&&b.fd===a&&(b.Oa.disconnect(),b.Oa.connect(c))}
function*Vb(b,a){if(a)for(const c of b.H)Tb(0<c.oa.length?c.oa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Wb(b,a,c){return c?b.j.nf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Xb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.l():++c}b.H.length=c}
function*Q(b,a){if(0<a.length)for(const d of b.H){a:{b=d.oa;var c=a;for(const e of c){c=!1;for(const f of b)if(Tb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function Bb(b,a,c,d,e,f){for(const g of b.H)if(g.mb()===c&&(g.sc()||f))return g.oa=e,g;a=await N(b,a,c,d,f);e="html5"===a.Rc?new self.Ee(a.v,a,e):new self.Ge(a.v,a,e);b.H.push(e);return e}
function Ab(b,a){a=a.join(" ");let c=b.Hb.get(a);if(!c){let d=null;c={ud:0,promise:new Promise(e=>d=e),resolve:d};b.Hb.set(a,c)}c.ud++}function Fb(b,a){return(b=b.Hb.get((0===a.length?b.ce:a).join(" ")))?b.promise:Promise.resolve()}function R(b){if(0<b.Va.size)w(b);else for(const a of b.H)if(!a.I&&!a.O()){w(b);break}}function Yb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function Mb(b){b.ad||(b.ad=!0,Promise.resolve().then(()=>Zb(b)))}
function Zb(b){const a={};for(const [c,d]of b.ka)a[c]=d.map(e=>e.lb());m(b,"fxstate",{fxstate:a});b.ad=!1}
async function Ob(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await Bb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(O(b,!0),e=b.F,f=d.pos,b.cb[0]=f[0],b.cb[1]=f[1],b.cb[2]=f[2],f=d.orient,b.bb[0]=f[0],b.bb[1]=f[1],b.bb[2]=f[2],e.setPosition(...b.cb),e.setOrientation(...b.bb),b.wa[0]=d.cia,b.wa[1]=d.coa,b.wa[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.ua=d.uid):O(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?P(b,!1):(P(b,!0),Db(b,d));c.Play(k,l,q,0);a.isPlaying||c.pb();c.Jc(a)}}}function Rb(b){console.error("[Audio] Offline rendering error: ",b)}
self.kb=class extends self.qa{constructor(b){super(b,"audio");this.Xa=this.g=null;this.Yb=this.Yc=!1;this.Da=()=>{if(!this.Yc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Yb&&(this.Yc=!0,window.removeEventListener("pointerup",this.Da,!0),window.removeEventListener("touchend",this.Da,!0),window.removeEventListener("click",this.Da,!0),window.removeEventListener("keydown",
this.Da,!0),this.Yb=!1)}};this.ja=[];this.H=[];this.R=null;this.ce=[];this.ee=new Set;this.de=-1;this.Hb=new Map;this.dc=1;this.Aa=!1;this.pd=0;this.oc=1;this.Vc=0;this.ge="HRTF";this.Rd="inverse";this.he=600;this.fe=1E4;this.je=1;this.aa=[0,0,0];this.ca=[0,0,-1,0,1,0];this.Xd=this.jc=!1;this.me=this.j.Ke();this.ka=new Map;this.Va=new Set;this.Yd=this.ad=!1;this.fd="";this.Oa=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Oa&&this.Oa.disconnect();this.fd=c.toLowerCase();this.Oa=this.g.createMediaStreamSource(a);
this.Oa.connect(Ub(this,this.fd))};this.Xb=null;self.C3Audio_GetOutputStream=()=>{this.Xb||(this.Xb=this.g.createMediaStreamDestination(),this.Xa.connect(this.Xb));return this.Xb.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>xb(this,a)],["play",a=>zb(this,a)],["stop",a=>{a=a.tags;for(const c of Q(this,a))c.Ga()}],["stop-all",()=>{for(const a of this.H)a.Ga()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of Q(this,c))a?d.pb():d.Pb();R(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of Q(this,c))S(d,a)}],["fade-volume",a=>Eb(this,a)],["set-master-volume",a=>{this.dc=a.vol;this.Xa.gain.value=this.dc}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of Q(this,c))$b(d,a)}],["set-silent",a=>{this.Aa=a.isSilent;this.j.Qb(this.Aa);for(const c of this.H)c.Vb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of Q(this,c))d.Bc(a)}],["set-playback-rate",a=>Gb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of Q(this,
c))P(d,!0),Db(d,a)}],["seek",a=>Hb(this,a)],["preload",a=>Ib(this,a)],["unload",a=>Jb(this,a)],["unload-all",()=>{for(const a of this.ja)a.l();this.ja.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.Cc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>Kb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ka.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].$(e,
f,g,a);Mb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ka.get(a);if(!d||!d.length)break;for(const e of d)e.l();this.ka.delete(a);Lb(this,a)}}],["tick",a=>{this.oc=a.timeScale;this.Vc=a.gameTime;this.de=a.tickCount;if(0!==this.pd)for(var c of this.H)c.Ka();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ca[0]!==
c[0]||this.ca[1]!==c[1]||this.ca[2]!==c[2]||this.ca[3]!==c[3]||this.ca[4]!==c[4]||this.ca[5]!==c[5])){for(let d=0;6>d;++d)this.ca[d]=c[d];this.g.listener.setOrientation(...this.ca)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.ua===a&&Cb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Nb(this,a)],["offline-render-audio",a=>Pb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}fa(){return this.Xa}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.fa()}Ob(){return this.Aa}Ia(b){this.j.Ia(b)}Ta(b){this.j.Ta(b)}Ha(){for(var b of this.Va)b.Ha();
b=this.g.currentTime;for(var a of this.H)a.Ha(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.lb());m(this,"state",{tickCount:this.de,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Va].map(c=>({tag:c.nd,index:c.Zd,peak:c.eb,rms:c.ie,binCount:c.m.frequencyBinCount,freqBins:c.Wd}))});0===a.length&&0===this.Va.size&&this.Zb&&(this.j.Ld(this.ne),this.Zb=!1)}static Pe(b){return b*wb}static Ad(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Ne(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.Z.pa(self.kb);"use strict";function Sb(b){b.bc||(b.bc=b.Ic());return b.bc}self.wd=class{constructor(b,a,c,d,e){this.v=b;this.tf=a;this.Qa=c;this.T=d;this.qf=e;this.Rc="";this.bc=null}l(){this.bc=this.v=null}Ic(){}V(){return this.v.V()}xc(){return this.tf}mb(){return this.Qa}wc(){return this.T}Fa(){return this.qf}ga(){}};"use strict";
self.De=class extends self.wd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Rc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.Cb=this.Db=null;this.L.addEventListener("canplaythrough",()=>!0);this.Gb=this.V().createGain();this.Fb=null;this.L.addEventListener("canplay",()=>{this.Db&&(this.Db(),this.Cb=this.Db=null);!this.Fb&&this.L&&(this.Fb=this.V().createMediaElementSource(this.L),this.Fb.connect(this.Gb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Qa}' error: `,f);this.Cb&&(this.Cb(f),this.Cb=this.Db=null)})}l(){Xb(this.v,this);this.Gb.disconnect();this.Gb=null;this.Fb.disconnect();this.Fb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.l()}Ic(){return new Promise((b,a)=>{this.Db=b;this.Cb=a;this.L.src=this.Qa})}W(){return this.L}ga(){return this.L.duration}};"use strict";
async function ac(b){if(b.La)return b.La;var a=b.v.j;if("cordova"===a.u&&a.Dd(b.Qa)&&a.$b)b.La=await a.Mb(b.Qa);else{a=await fetch(b.Qa);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.La=await a.arrayBuffer()}}async function bc(b){if(b.ia)return b.ia;b.ia=await Wb(b.v,b.La,b.sf);b.La=null}
self.Fe=class extends self.wd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Rc="webaudio";this.ia=this.La=null;this.sf=!!f}l(){Xb(this.v,this);this.ia=this.La=null;super.l()}async Ic(){try{await ac(this),await bc(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Qa}': `,b)}}ga(){return this.ia?this.ia.duration:0}};"use strict";let cc=0;
function O(b,a){a=!!a;b.zb!==a&&(b.zb=a,b.zb?(P(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.v.ge,b.F.distanceModel=b.v.Rd,b.F.refDistance=b.v.he,b.F.maxDistance=b.v.fe,b.F.rolloffFactor=b.v.je),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.fa())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.fa())))}
function P(b,a){a=!!a;b.ac!==a&&(b.ac=a,b.ac?(O(b,!1),b.da=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.da),b.da.connect(b.fa())):(b.da.disconnect(),b.da=null,b.G.disconnect(),b.G.connect(b.fa())))}function Db(b,a){b.ac&&b.md!==a&&(b.da.pan.value=a,b.md=a)}function S(b,a){b.Ra=a;b.G.gain.cancelScheduledValues(0);b.Za=-1;b.G.gain.value=b.yc()}function $b(b,a){a=!!a;b.za!==a&&(b.za=a,b.Vb())}
function Cb(b,a,c,d,e){if(b.zb){var f=b.cb,g=b.bb,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function T(b){return b.cd?b.v.Vc:performance.now()/1E3}
self.xd=class{constructor(b,a,c){this.v=b;this.P=a;this.oa=c;this.Wb=cc++;this.G=this.V().createGain();this.G.connect(this.fa());this.F=null;this.zb=!1;this.cb=[0,0,0];this.bb=[0,0,0];this.wa=[0,0,0];this.da=null;this.ac=!1;this.md=0;this.I=!0;this.Y=this.xa=this.J=!1;this.Ra=1;this.za=!1;this.ma=1;b=this.v.pd;this.cd=1===b&&!this.Fa()||2===b;this.Za=this.ua=-1;this.le=!1}l(){this.P=this.v=null;this.F&&(this.F.disconnect(),this.F=null);this.da&&(this.da.disconnect(),this.da=null);this.G.disconnect();
this.G=null}V(){return this.v.V()}fa(){return Ub(this.v,0<this.oa.length?this.oa[0]:"")}xc(){return this.P.xc()}mb(){return this.P.mb()}wc(){return this.P.wc()}Fa(){return this.P.Fa()}O(){}sc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Sa(){}ga(){return this.P.ga()}Play(){}Ga(){}pb(){}Pb(){}Ha(b){-1!==this.Za&&b>=this.Za&&(this.Za=-1,this.le&&this.Ga(),Yb(this.v,"fade-ended",this.oa,this.Wb))}yc(){const b=this.Ra;return isFinite(b)?b:0}Ob(){return this.v.Ob()}Vb(){}Bc(){}Ka(){}Ac(){}Cc(){}zc(){}lb(){var b=
this.Wb,a=this.oa,c=this.ga(),d=-1===this.Za?this.Ra:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.cb,orient:this.bb,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ua}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Sa(),playbackRate:this.ma,uid:this.ua,bufferOriginalUrl:this.xc(),bufferUrl:"",bufferType:this.wc(),isMusic:this.Fa(),isLooping:this.Y,isMuted:this.za,resumePosition:this.zc(),pan:f,stereoPan:this.da?
this.md:null}}Jc(b){var a=b.playbackRate;this.ma!==a&&(this.ma=a,this.Ka());$b(this,b.isMuted)}};"use strict";
self.Ee=class extends self.xd{constructor(b,a,c){super(b,a,c);this.P.Gb.connect(this.G);this.P.onended=()=>this.Lc()}l(){this.Ga();this.P.Gb.disconnect();super.l()}W(){return this.P.W()}Lc(){this.I=!0;this.ua=-1;Yb(this.v,"ended",this.oa,this.Wb)}O(){return this.W().ended}sc(){return this.I?!0:this.O()}Sa(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.ga()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);S(this,a);this.za=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.mb()}' to position '${c}': `,e)}this.v.Ia(d);this.J=this.I=!1;this.Y=b;this.ma=1}Ga(){const b=this.W();b.paused||b.pause();this.v.Ta(b);this.I=!0;this.J=!1;this.ua=-1}pb(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.v.Ta(b);this.J=!0}}Pb(){!this.J||this.I||this.O()||(this.v.Ia(this.W()),this.J=!1)}Vb(){this.W().muted=this.za||this.Ob()}Bc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ka(){let b=this.ma;this.cd&&(b*=this.v.oc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}Ac(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}zc(){return this.Sa()}Cc(b){b?this.IsPlaying()?(this.W().pause(),this.xa=!0):this.xa=!1:this.xa&&(this.v.Ia(this.W()),this.xa=!1)}};"use strict";
function U(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.rb=null}
self.Ge=class extends self.xd{constructor(b,a,c){super(b,a,c);this.s=null;this.fc=d=>this.Lc(d);this.Xc=!0;this.rb=null;this.S=this.ic=this.kc=0;this.hd=1}l(){this.Ga();U(this);this.fc=null;super.l()}Lc(b){this.J||this.xa||b.target!==this.rb||(this.I=this.Xc=!0,this.ua=-1,U(this),Yb(this.v,"ended",this.oa,this.Wb))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Xc}sc(){return!this.s||this.I?!0:this.O()}Sa(){let b;b=this.J?this.S:this.ic+(T(this)-this.kc)*this.ma;this.Y||(b=Math.min(b,this.ga()));
return b}Play(b,a,c,d){this.za=!1;this.hd=1;S(this,a);U(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ia;this.s.connect(this.G);this.rb=this.s;this.s.onended=this.fc;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Xc=!1;this.Y=b;this.ma=1;this.kc=T(this);this.ic=c}Ga(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.ua=-1}pb(){this.J||this.I||this.O()||(this.S=this.Sa(),this.Y&&(this.S%=this.ga()),this.J=!0,this.s.stop(0))}Pb(){!this.J||this.I||this.O()||(U(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ia,this.s.connect(this.G),this.rb=this.s,this.s.onended=this.fc,this.s.loop=this.Y,S(this,this.Ra),this.Ka(),this.s.start(0,this.S),this.kc=T(this),this.ic=this.S,this.J=!1)}yc(){return super.yc()*this.hd}Vb(){this.hd=this.za||this.Ob()?0:1;S(this,this.Ra)}Bc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ka(){let b=this.ma;this.cd&&(b*=this.v.oc);this.s&&(this.s.playbackRate.value=b)}Ac(b){this.I||this.O()||(this.J?this.S=b:(this.pb(),
this.S=b,this.Pb()))}zc(){return this.S}Cc(b){b?this.IsPlaying()?(this.xa=!0,this.S=this.Sa(),this.Y&&(this.S%=this.ga()),this.s.stop(0)):this.xa=!1:this.xa&&(U(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ia,this.s.connect(this.G),this.rb=this.s,this.s.onended=this.fc,this.s.loop=this.Y,S(this,this.Ra),this.Ka(),this.s.start(0,this.S),this.kc=T(this),this.ic=this.S,this.xa=!1)}Jc(b){super.Jc(b);this.S=b.resumePosition}};"use strict";function V(b){return b.g.createGain()}
function W(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class X{constructor(b){this.v=b;this.g=b.V();this.Zd=-1;this.T=this.nd="";this.o=null}l(){this.g=null}N(){}U(){}lb(){return{type:this.T,tag:this.nd,params:this.o}}}
self.we=class extends X{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.A=V(this);this.i=V(this);this.i.gain.value=g;this.h=V(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}l(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;W(this,this.i.gain,a,c,d);W(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;W(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;W(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;W(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,W(this,this.D.gain,a,c,d)}}};
self.ue=class extends X{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.A=V(this);this.i=V(this);this.i.gain.value=d;this.h=V(this);this.h.gain.value=1-d;this.Eb=V(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.vb=V(this);this.vb.gain.value=c;this.A.connect(this.Eb);this.A.connect(this.h);this.Eb.connect(this.i);this.Eb.connect(this.X);this.X.connect(this.vb);this.vb.connect(this.Eb)}l(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.Eb.disconnect();
this.X.disconnect();this.vb.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}$(b,a,c,d){const e=self.kb.Ad;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;W(this,this.i.gain,a,c,d);W(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);W(this,this.vb.gain,e(a),c,d);break;case 5:this.o[0]=a,W(this,this.X.delayTime,a,c,d)}}};
self.te=class extends X{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Qd=this.Pd="";this.A=V(this);this.i=V(this);this.i.gain.value=d;this.h=V(this);this.h.gain.value=1-d;this.ub=this.g.createConvolver();this.ub.normalize=c;this.ub.buffer=a;this.A.connect(this.ub);this.A.connect(this.h);this.ub.connect(this.i)}l(){this.A.disconnect();this.ub.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}$(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,W(this,this.i.gain,a,c,d),W(this,this.h.gain,1-a,c,d)}}lb(){const b=super.lb();b.bufferOriginalUrl=this.Pd;b.bufferUrl="";b.bufferType=this.Qd;return b}};
self.xe=class extends X{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.A=V(this);this.h=V(this);this.h.gain.value=1-f/2;this.i=V(this);this.i.gain.value=f/2;this.xb=V(this);this.xb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=V(this);this.K.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.i);this.X.connect(this.xb);this.xb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.xb.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;W(this,this.i.gain,a/2,c,d);W(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;W(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;W(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,W(this,this.xb.gain,a/100,c,d)}}};
self.ze=class extends X{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.A=V(this);this.h=V(this);this.h.gain.value=1-g/2;this.i=V(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=V(this);this.K.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;W(this,this.i.gain,a/2,c,d);W(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;W(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;W(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;W(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;W(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,W(this,this.C.frequency,a,c,d)}}};self.ye=class extends X{constructor(b,a){super(b);this.T="gain";this.o=[a];this.m=V(this);this.m.gain.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}$(b,a,c,d){const e=self.kb.Ad;switch(b){case 4:this.o[0]=e(a),W(this,this.m.gain,e(a),c,d)}}};
self.Be=class extends X{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.m=this.g.createStereoPanner();this.m.pan.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}$(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,W(this,this.m.pan,a,c,d)}}};
self.Ce=class extends X{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.m=V(this);this.m.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=V(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.m.gain);this.C.start(0)}l(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;W(this,this.m.gain,1-a/2,c,d);W(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,W(this,this.C.frequency,a,c,d)}}};
self.Ae=class extends X{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.A=V(this);this.i=V(this);this.i.gain.value=c;this.h=V(this);this.h.gain.value=1-c;this.Jb=V(this);this.Jb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Jb.gain);this.C.start(0);this.A.connect(this.Jb);this.A.connect(this.h);this.Jb.connect(this.i)}l(){this.C.stop(0);this.C.disconnect();this.Jb.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;W(this,this.i.gain,a,c,d);W(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,W(this,this.C.frequency,a,c,d)}}};
self.ve=class extends X{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.A=V(this);this.mc=V(this);this.lc=V(this);b=d;.01>b&&(b=.01);this.mc.gain.value=b;this.lc.gain.value=Math.pow(1/b,.6)*e;this.i=V(this);this.i.gain.value=f;this.h=V(this);this.h.gain.value=1-f;this.pc=this.g.createWaveShaper();this.Sc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Sc[32768+e]=f,this.Sc[32768-
e-1]=-f;this.pc.curve=this.Sc;this.A.connect(this.mc);this.A.connect(this.h);this.mc.connect(this.pc);this.pc.connect(this.lc);this.lc.connect(this.i)}l(){this.A.disconnect();this.mc.disconnect();this.pc.disconnect();this.lc.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,W(this,this.i.gain,a,c,d),W(this,this.h.gain,
1-a,c,d)}}};self.se=class extends X{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.m=this.g.createDynamicsCompressor();this.m.threshold.value=a;this.m.knee.value=c;this.m.ratio.value=d;this.m.attack.value=e;this.m.release.value=f}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}$(){}};
self.re=class extends X{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.m=this.g.createAnalyser();this.m.fftSize=a;this.m.smoothingTimeConstant=c;this.Wd=new Float32Array(this.m.frequencyBinCount);this.ke=new Uint8Array(a);this.ie=this.eb=0;b=this.v;b.Va.add(this);R(b)}l(){this.v.Va.delete(this);this.m.disconnect();super.l()}Ha(){this.m.getFloatFrequencyData(this.Wd);this.m.getByteTimeDomainData(this.ke);const b=this.m.fftSize;let a=this.eb=0;for(var c=0;c<b;++c){let d=(this.ke[c]-
128)/128;0>d&&(d=-d);this.eb<d&&(this.eb=d);a+=d*d}c=self.kb.Ne;this.eb=c(this.eb);this.ie=c(Math.sqrt(a/b))}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}$(){}};"use strict";
self.Z.pa(class extends self.qa{constructor(b){super(b,"mouse");v(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.j.Bd().requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{m(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{m(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";function Y(b){b.stopPropagation()}function dc(b){13!==b.which&&27!==b.which&&b.stopPropagation()}
self.Z.pa(class extends self.uc{constructor(b){super(b);ca(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}zd(b,a){let c;const d=a.type;"textarea"===d?(c=document.createElement("textarea"),c.style.resize="none"):(c=document.createElement("input"),c.type=d);c.style.position="absolute";c.autocomplete="off";c.addEventListener("pointerdown",Y);c.addEventListener("pointermove",Y);c.addEventListener("pointerrawupdate",Y);c.addEventListener("pointerup",Y);c.addEventListener("mousedown",Y);c.addEventListener("mouseup",
Y);c.addEventListener("keydown",dc);c.addEventListener("keyup",dc);c.addEventListener("click",e=>{e.stopPropagation();da(this,"click",b)});c.addEventListener("dblclick",e=>{e.stopPropagation();da(this,"dblclick",b)});c.addEventListener("input",()=>x(this,"change",b,{text:c.value}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.Dc(c,a);return c}Dc(b,a){b.value=a.text;b.placeholder=a.placeholder;b.title=a.title;b.disabled=!a.isEnabled;b.readOnly=a.isReadOnly;b.spellcheck=a.spellCheck;
a=a.maxLength;0>a?b.removeAttribute("maxlength"):b.setAttribute("maxlength",a)}});"use strict";async function ec(){try{return{isOk:!0,isPersistent:await navigator.storage.persist()}}catch(b){return console.error("[Construct] Error requesting persistent storage: ",b),{isOk:!1}}}
self.Z.pa(class extends self.qa{constructor(b){super(b,"localstorage");v(this,[["init",()=>this.Rb()],["request-persistent",()=>ec()]])}async Rb(){let b=!1;try{b=await navigator.storage.persisted()}catch(a){b=!1,console.warn("[Construct] Error checking storage persisted state: ",a)}return{isPersistent:b}}});
