const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.AJAX,
		C3.Plugins.Mouse,
		C3.Plugins.Json,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Behaviors.Fade,
		C3.Plugins.Arr,
		C3.Plugins.TiledBg,
		C3.Plugins.SVGPicture,
		C3.Behaviors.Tween,
		C3.Behaviors.Follow,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Car,
		C3.Behaviors.scrollto,
		C3.Behaviors.Timer,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Sin,
		C3.Plugins.TextBox,
		C3.Behaviors.aekiroWater,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnDoubleTapGesture,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Arr.Exps.CurX,
		C3.JavaScriptInEvents.Common_Event76_Act1,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.RemoveAllDynamicLayers,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.AddLayer,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Plugins.System.Acts.SetLayerTransparent,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Text.Cnds.HasTags,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Car.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Json.Acts.AddTo,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Browser.Acts.Focus,
		C3.Plugins.System.Acts.SetVar,
		C3.JavaScriptInEvents.Gamesnacks_es_Event16_Act4,
		C3.JavaScriptInEvents.Gamesnacks_es_Event37_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event39_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event40_Act2,
		C3.JavaScriptInEvents.Gamesnacks_es_Event41_Act1,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.JavaScriptInEvents.Gamesnacks_es_Event46_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event47_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event48_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event49_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event52_Act2,
		C3.JavaScriptInEvents.Gamesnacks_es_Event55_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event57_Act1,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.JavaScriptInEvents.Gamesnacks_es_Event61_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event62_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event65_Act1,
		C3.Plugins.Browser.Acts.Vibrate,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Car.Acts.SetSpeed,
		C3.Plugins.System.Acts.UnloadUnusedTextures,
		C3.JavaScriptInEvents.Gamees_Event14_Act7,
		C3.Plugins.System.Acts.LoadLayoutTexturesByName,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.SVGPicture.Acts.SetSize,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgb,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Exps.TouchCount,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Follow.Acts.SetDelay,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.Touch.Exps.XAt,
		C3.Plugins.Touch.Exps.YAt,
		C3.Plugins.System.Exps.anglelerp,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Exps.layerscale,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Cnds.IsCollisionEnabled,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Arr.Acts.Delete,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Cnds.PickChildren,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.Car.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Exps.projectversion,
		C3.JavaScriptInEvents.Splashes_Event1_Act4,
		C3.Plugins.Audio.Exps.MasterVolume,
		C3.Plugins.TextBox.Acts.Destroy,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Browser.Acts.LockOrientation,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.JavaScriptInEvents.Splashes_Event18_Act8,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Exps.len,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.Json.Exps.CurrentValue,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.JavaScriptInEvents.Mainsplashes_Event2_Act1,
		C3.JavaScriptInEvents.Mainsplashes_Event2_Act2,
		C3.JavaScriptInEvents.Mainsplashes_Event4_Act2,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.PlatformInfo.Cnds.IsOnMacOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnLinux,
		C3.Plugins.PlatformInfo.Cnds.IsOnChromeOS,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Sprite.Exps.AnimationFrameTag,
		C3.JavaScriptInEvents.Store_es_Event20_Act2,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.Json.Acts.PushValue,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.CompareFrame
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{PlatformInfo: 0},
	{Browser: 0},
	{Touch: 0},
	{Audio: 0},
	{AJAX: 0},
	{Mouse: 0},
	{JSON_Inventory: 0},
	{FullscreenText: 0},
	{HomeText: 0},
	{SondText: 0},
	{PlayButton: 0},
	{FullscreenButton: 0},
	{HomeButton: 0},
	{SoundButton: 0},
	{RetryLevelButton: 0},
	{rvIcon: 0},
	{btn_Shop: 0},
	{btn_ScrollStore: 0},
	{InDirection: 0},
	{InTime: 0},
	{TweenToWidth: 0},
	{TweenToHeight: 0},
	{OutDirection: 0},
	{OutTime: 0},
	{OnFinish: 0},
	{Kind: 0},
	{TweenToX: 0},
	{TweenToY: 0},
	{Anchor: 0},
	{Menu: 0},
	{MenuButton: 0},
	{SM_FullscreenButton: 0},
	{SM_HomeButton: 0},
	{SM_SoundButton: 0},
	{CloseMenu: 0},
	{SM_SoundButton2: 0},
	{SM_SoundButton3: 0},
	{CloseMenuPopup: 0},
	{PopUpBG: 0},
	{Logo: 0},
	{Fade: 0},
	{BlackScreen: 0},
	{ShopArray: 0},
	{BG_Candy: 0},
	{ExtraSIze: 0},
	{Border_Candy: 0},
	{Food_Candy: 0},
	{Body_Candy: 0},
	{Head_Candy: 0},
	{Tail_Candy: 0},
	{Body_Farm: 0},
	{Head_Farm: 0},
	{Tail_Farm: 0},
	{BG_Farm: 0},
	{Border_Farm: 0},
	{Food_Farm: 0},
	{Body_Vikings: 0},
	{Head_Vikings: 0},
	{Tail_Vikings: 0},
	{BG_Vikings: 0},
	{Border_Vikings: 0},
	{Food_Vikings: 0},
	{Body_Fantasy: 0},
	{Head_Fantasy: 0},
	{Tail_Fantasy: 0},
	{BG_Fantasy: 0},
	{Border_Fantasy: 0},
	{Food_Fantasy: 0},
	{Body_Aliens: 0},
	{Head_Aliens: 0},
	{Tail_Aliens: 0},
	{BG_Aliens: 0},
	{Border_Aliens: 0},
	{Food_Aliens: 0},
	{Body_Cyberpunk: 0},
	{Head_Cyberpunk: 0},
	{Tail_Cyberpunk: 0},
	{BG_Cyberpunk: 0},
	{Border_Cyberpunk: 0},
	{Food_Cyberpunk: 0},
	{Body_Monsters: 0},
	{Head_Monsters: 0},
	{Tail_Monsters: 0},
	{BG_Monsters: 0},
	{Border_Monsters: 0},
	{Food_Monsters: 0},
	{Body_Basic: 0},
	{Head_Basic: 0},
	{Tail_Basic: 0},
	{BG_Basic: 0},
	{Border_Basic: 0},
	{Food_Basic: 0},
	{item: 0},
	{price: 0},
	{btn_buy: 0},
	{VisibleX: 0},
	{HiddenX: 0},
	{Price: 0},
	{LightColor: 0},
	{Tween: 0},
	{Shop_Icon: 0},
	{txt_Money: 0},
	{txt_Price: 0},
	{BrandImage: 0},
	{LayersStatus: 0},
	{ID: 0},
	{Snake_Num: 0},
	{Index: 0},
	{Follow: 0},
	{Snake_BodyPart: 0},
	{eye: 0},
	{Points: 0},
	{Points_Max: 0},
	{Level: 0},
	{ReactionSpeed: 0},
	{ScoreCountForSpeed: 0},
	{Name: 0},
	{R: 0},
	{G: 0},
	{B: 0},
	{currentScale: 0},
	{InitDone: 0},
	{MoveTo: 0},
	{Car: 0},
	{ScrollTo: 0},
	{Timer: 0},
	{Pathfinding: 0},
	{Snake_Head: 0},
	{Food: 0},
	{FoodColector: 0},
	{Spots: 0},
	{Vision: 0},
	{FoodVision: 0},
	{Bot_Direction: 0},
	{startingX: 0},
	{startingY: 0},
	{SixTagon: 0},
	{EnemyVision: 0},
	{Position: 0},
	{ScoreBoardRankText: 0},
	{ScoreBoard: 0},
	{JSON: 0},
	{NamesArray: 0},
	{PickedNames: 0},
	{ContinueButton: 0},
	{GameOverTitle: 0},
	{Sine: 0},
	{Food_Snake: 0},
	{ScoreBoardBg: 0},
	{Food_Snake2: 0},
	{EnterNameBox: 0},
	{Player_Direction: 0},
	{TouchControl: 0},
	{PlayerDirectionRotator: 0},
	{Water: 0},
	{TiledLogo: 0},
	{DirectionArrow: 0},
	{PlayerCurrentScoreText: 0},
	{PlayerTopScoreText: 0},
	{ScoreBoardScoreText: 0},
	{Boost: 0},
	{Sprite: 0},
	{Snake_NameText: 0},
	{SpotsGlow: 0},
	{Spots2: 0},
	{Store_Blackscreen: 0},
	{Store_Close: 0},
	{description: 0},
	{BG_Store: 0},
	{Asset3: 0},
	{PriceTag: 0},
	{Asset4: 0},
	{UNderGlow: 0},
	{txt_coins: 0},
	{GameOver_Decoration: 0},
	{FullscreenAllowed: 0},
	{VibrationAlowed: 0},
	{Paused_Parent: 0},
	{Asset: 0},
	{Asset5: 0},
	{Farm: 0},
	{Cyberpunk: 0},
	{Basic: 0},
	{Candy: 0},
	{Aliens: 0},
	{Vikings: 0},
	{Monsters: 0},
	{Fantasy: 0},
	{JSON_Scales: 0},
	{Squish: 0},
	{UI_Anchor: 0},
	{Anchor_LevelSelector: 0},
	{Settings_Anchor: 0},
	{Anchor_Splash: 0},
	{Anchor_SplashMaster: 0},
	{Sprite2: 0},
	{RotateScreen: 0},
	{txt_rotate: 0},
	{Message: 0},
	{SVGPicture: 0},
	{extrasize: 0},
	{newBorder: 0},
	{FFoodSkin: 0},
	{FBodySkin: 0},
	{FHeadSkin: 0},
	{FtailSkin: 0},
	{FBG: 0},
	{FBorder: 0},
	{GlobalButtons: 0},
	{FullScreenButtons: 0},
	{HomeButtons: 0},
	{SoundButtons: 0},
	{Tweenables: 0},
	{VibrateButtons: 0},
	{Snake: 0},
	{Foods: 0},
	{FTexts: 0},
	{MusicButtons: 0},
	{ScoreBoardTexts: 0},
	{FAnchors: 0},
	{Volume: 0},
	{bMusic: 0},
	{bSound: 0},
	{SFX_Type: 0},
	{DB: 0},
	{Playback: 0},
	{destroy_fullscreen: 0},
	{Vibrate: 0},
	{MenuOpen: 0},
	{PopUpOpen: 0},
	{LeaveActive: 0},
	{NumberOfLayers: 0},
	{returnValue: 0},
	{num: 0},
	{bLandscape: 0},
	{RV_type: 0},
	{first_set: 0},
	{ADS: 0},
	{RV_ready: 0},
	{RV_play: 0},
	{RV_create_attempts: 0},
	{PlayerContinued: 0},
	{isAdPlaying: 0},
	{Interstitial_Ready: 0},
	{IsInMicrosoft: 0},
	{music: 0},
	{Sound: 0},
	{CanAds: 0},
	{Interstitial_Type: 0},
	{ReturnBackFromBorderDistance: 0},
	{Type: 0},
	{type: 0},
	{name: 0},
	{mute: 0},
	{last_score_sent: 0},
	{save_score: 0},
	{return: 0},
	{value: 0},
	{gamesnacksPause: 0},
	{VibrationsTime: 0},
	{EquippedSkin: 0},
	{SkinScale: 0},
	{color: 0},
	{self_ID: 0},
	{NormalSpeed: 0},
	{FollowDelay: 0},
	{BoostedSpeed: 0},
	{MaxPointsMultiplier: 0},
	{CoinsEarned: 0},
	{DirectionTouchIndex: 0},
	{ArrowDistanceFromHead: 0},
	{MoveInPixels: 0},
	{curretnLayerScale: 0},
	{currentTweenValue: 0},
	{Needed_ID: 0},
	{SnakeNum: 0},
	{PointToReturnTo: 0},
	{NormalFoodScore: 0},
	{SnakeFoodScore: 0},
	{SnakeNumbersCounter: 0},
	{Number: 0},
	{EnemyFound: 0},
	{WallFound: 0},
	{RandomDirection: 0},
	{ValidDirectionFound: 0},
	{BestFoodScore: 0},
	{FoodScore: 0},
	{GameRadius: 0},
	{DistanceFromCore: 0},
	{PlayerScore: 0},
	{PlayerTopScore: 0},
	{LastPositionInBoard: 0},
	{BodyParts: 0},
	{SnakeUID: 0},
	{id: 0},
	{ang: 0},
	{Scale: 0},
	{Amont: 0},
	{IsStart: 0},
	{FatAmount: 0},
	{IsFullScreenAllowed: 0},
	{IsAdsAllowed: 0},
	{GoogleAd: 0},
	{GoogleAd_timeLimit: 0},
	{IsBranded: 0},
	{BrandUrl: 0},
	{PlayerName: 0},
	{gameSnacksAudioAllowed: 0},
	{Local_ID: 0},
	{masterSound: 0},
	{Platform: 0},
	{midAnimation: 0},
	{canBuy: 0},
	{AudoEquip: 0},
	{originalSkin: 0},
	{b: 0},
	{itemToCheck: 0},
	{duration: 0},
	{TargetOpacity: 0},
	{TimesClicked: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	JSON_Inventory: class extends self.IJSONInstance {},
	FullscreenText: class extends self.ITextInstance {},
	HomeText: class extends self.ITextInstance {},
	SondText: class extends self.ITextInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	FullscreenButton: class extends self.ISpriteInstance {},
	HomeButton: class extends self.ISpriteInstance {},
	SoundButton: class extends self.ISpriteInstance {},
	RetryLevelButton: class extends self.ISpriteInstance {},
	rvIcon: class extends self.ISpriteInstance {},
	btn_Shop: class extends self.ISpriteInstance {},
	btn_ScrollStore: class extends self.ISpriteInstance {},
	Menu: class extends self.ISpriteInstance {},
	MenuButton: class extends self.ISpriteInstance {},
	SM_FullscreenButton: class extends self.ISpriteInstance {},
	SM_HomeButton: class extends self.ISpriteInstance {},
	SM_SoundButton: class extends self.ISpriteInstance {},
	CloseMenu: class extends self.ISpriteInstance {},
	SM_SoundButton2: class extends self.ISpriteInstance {},
	SM_SoundButton3: class extends self.ISpriteInstance {},
	CloseMenuPopup: class extends self.ISpriteInstance {},
	PopUpBG: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	BlackScreen: class extends self.ISpriteInstance {},
	ShopArray: class extends self.IArrayInstance {},
	BG_Candy: class extends self.ITiledBackgroundInstance {},
	Border_Candy: class extends self.ISVGPictureInstance {},
	Food_Candy: class extends self.ISpriteInstance {},
	Body_Candy: class extends self.ISpriteInstance {},
	Head_Candy: class extends self.ISpriteInstance {},
	Tail_Candy: class extends self.ISpriteInstance {},
	Body_Farm: class extends self.ISpriteInstance {},
	Head_Farm: class extends self.ISpriteInstance {},
	Tail_Farm: class extends self.ISpriteInstance {},
	BG_Farm: class extends self.ITiledBackgroundInstance {},
	Border_Farm: class extends self.ISVGPictureInstance {},
	Food_Farm: class extends self.ISpriteInstance {},
	Body_Vikings: class extends self.ISpriteInstance {},
	Head_Vikings: class extends self.ISpriteInstance {},
	Tail_Vikings: class extends self.ISpriteInstance {},
	BG_Vikings: class extends self.ITiledBackgroundInstance {},
	Border_Vikings: class extends self.ISVGPictureInstance {},
	Food_Vikings: class extends self.ISpriteInstance {},
	Body_Fantasy: class extends self.ISpriteInstance {},
	Head_Fantasy: class extends self.ISpriteInstance {},
	Tail_Fantasy: class extends self.ISpriteInstance {},
	BG_Fantasy: class extends self.ITiledBackgroundInstance {},
	Border_Fantasy: class extends self.ISVGPictureInstance {},
	Food_Fantasy: class extends self.ISpriteInstance {},
	Body_Aliens: class extends self.ISpriteInstance {},
	Head_Aliens: class extends self.ISpriteInstance {},
	Tail_Aliens: class extends self.ISpriteInstance {},
	BG_Aliens: class extends self.ITiledBackgroundInstance {},
	Border_Aliens: class extends self.ISVGPictureInstance {},
	Food_Aliens: class extends self.ISpriteInstance {},
	Body_Cyberpunk: class extends self.ISpriteInstance {},
	Head_Cyberpunk: class extends self.ISpriteInstance {},
	Tail_Cyberpunk: class extends self.ISpriteInstance {},
	BG_Cyberpunk: class extends self.ITiledBackgroundInstance {},
	Border_Cyberpunk: class extends self.ISVGPictureInstance {},
	Food_Cyberpunk: class extends self.ISpriteInstance {},
	Body_Monsters: class extends self.ISpriteInstance {},
	Head_Monsters: class extends self.ISpriteInstance {},
	Tail_Monsters: class extends self.ISpriteInstance {},
	BG_Monsters: class extends self.ITiledBackgroundInstance {},
	Border_Monsters: class extends self.ISVGPictureInstance {},
	Food_Monsters: class extends self.ISpriteInstance {},
	Body_Basic: class extends self.ISpriteInstance {},
	Head_Basic: class extends self.ISpriteInstance {},
	Tail_Basic: class extends self.ISpriteInstance {},
	BG_Basic: class extends self.ITiledBackgroundInstance {},
	Border_Basic: class extends self.ISVGPictureInstance {},
	Food_Basic: class extends self.ISpriteInstance {},
	btn_buy: class extends self.ISpriteInstance {},
	Shop_Icon: class extends self.ISpriteInstance {},
	txt_Money: class extends self.ITextInstance {},
	txt_Price: class extends self.ITextInstance {},
	BrandImage: class extends self.ISpriteInstance {},
	LayersStatus: class extends self.IArrayInstance {},
	Snake_BodyPart: class extends self.ISpriteInstance {},
	eye: class extends self.ISpriteInstance {},
	Snake_Head: class extends self.ISpriteInstance {},
	Food: class extends self.ISpriteInstance {},
	FoodColector: class extends self.ISpriteInstance {},
	Spots: class extends self.ISpriteInstance {},
	Vision: class extends self.ISpriteInstance {},
	FoodVision: class extends self.ISpriteInstance {},
	Bot_Direction: class extends self.ISpriteInstance {},
	SixTagon: class extends self.ISpriteInstance {},
	EnemyVision: class extends self.ISpriteInstance {},
	ScoreBoardRankText: class extends self.ITextInstance {},
	ScoreBoard: class extends self.IArrayInstance {},
	JSON: class extends self.IJSONInstance {},
	NamesArray: class extends self.IArrayInstance {},
	PickedNames: class extends self.IArrayInstance {},
	ContinueButton: class extends self.ISpriteInstance {},
	GameOverTitle: class extends self.ISpriteInstance {},
	Food_Snake: class extends self.ISpriteInstance {},
	ScoreBoardBg: class extends self.ISpriteInstance {},
	Food_Snake2: class extends self.ISpriteInstance {},
	EnterNameBox: class extends self.ITextInputInstance {},
	Player_Direction: class extends self.ISpriteInstance {},
	TouchControl: class extends self.ISpriteInstance {},
	PlayerDirectionRotator: class extends self.ISpriteInstance {},
	TiledLogo: class extends self.ITiledBackgroundInstance {},
	DirectionArrow: class extends self.ISpriteInstance {},
	PlayerCurrentScoreText: class extends self.ITextInstance {},
	PlayerTopScoreText: class extends self.ITextInstance {},
	ScoreBoardScoreText: class extends self.ITextInstance {},
	Boost: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Snake_NameText: class extends self.ITextInstance {},
	SpotsGlow: class extends self.ISpriteInstance {},
	Spots2: class extends self.ISpriteInstance {},
	Store_Blackscreen: class extends self.ISpriteInstance {},
	Store_Close: class extends self.ISpriteInstance {},
	description: class extends self.ISpriteInstance {},
	BG_Store: class extends self.ISpriteInstance {},
	Asset3: class extends self.ISpriteInstance {},
	PriceTag: class extends self.ISpriteInstance {},
	Asset4: class extends self.ISpriteInstance {},
	UNderGlow: class extends self.ISpriteInstance {},
	txt_coins: class extends self.ITextInstance {},
	GameOver_Decoration: class extends self.ISpriteInstance {},
	Paused_Parent: class extends self.ISpriteInstance {},
	Asset: class extends self.ISpriteInstance {},
	Asset5: class extends self.ISpriteInstance {},
	JSON_Scales: class extends self.IJSONInstance {},
	Squish: class extends self.IParticlesInstance {},
	UI_Anchor: class extends self.ISpriteInstance {},
	Anchor_LevelSelector: class extends self.ISpriteInstance {},
	Anchor: class extends self.ISpriteInstance {},
	Settings_Anchor: class extends self.ISpriteInstance {},
	Anchor_Splash: class extends self.ISpriteInstance {},
	Anchor_SplashMaster: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	RotateScreen: class extends self.ISpriteInstance {},
	txt_rotate: class extends self.ITextInstance {},
	Message: class extends self.ISpriteInstance {},
	SVGPicture: class extends self.ISVGPictureInstance {},
	newBorder: class extends self.ISpriteInstance {},
	FFoodSkin: class extends self.ISpriteInstance {},
	FBodySkin: class extends self.ISpriteInstance {},
	FHeadSkin: class extends self.ISpriteInstance {},
	FtailSkin: class extends self.ISpriteInstance {},
	FBG: class extends self.ITiledBackgroundInstance {},
	FBorder: class extends self.ISVGPictureInstance {},
	GlobalButtons: class extends self.ISpriteInstance {},
	FullScreenButtons: class extends self.ISpriteInstance {},
	HomeButtons: class extends self.ISpriteInstance {},
	SoundButtons: class extends self.ISpriteInstance {},
	Tweenables: class extends self.ISpriteInstance {},
	VibrateButtons: class extends self.ISpriteInstance {},
	Snake: class extends self.ISpriteInstance {},
	Foods: class extends self.ISpriteInstance {},
	FTexts: class extends self.ITextInstance {},
	MusicButtons: class extends self.ISpriteInstance {},
	ScoreBoardTexts: class extends self.ITextInstance {},
	FAnchors: class extends self.ISpriteInstance {}
}