const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Dictionary,
		C3.Plugins.Arr,
		C3.Plugins.PlatformInfo,
		C3.Plugins.BinaryData,
		C3.Plugins.Json,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Behaviors.scrollto,
		C3.Behaviors.Pin,
		C3.Behaviors.bound,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Particles,
		C3.Behaviors.Physics,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.TiledBg.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.UnloadObjectTextures,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Spritefont2.Acts.SetPosToObject,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Text.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.LayerName,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Exps.LayerName,
		C3.Plugins.Text.Exps.Height,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Exps.X,
		C3.Behaviors.Physics.Acts.CreateDistanceJoint,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Behaviors.Physics.Acts.CreateLimitedRevoluteJoint,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.originalwindowwidth,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.BinaryData.Acts.SetFromText,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.BinaryData.Acts.Compress,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.BinaryData.Exps.GetBase64,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Behaviors.Physics.Acts.SetFriction,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Physics.Acts.ApplyTorque,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Particles.Acts.SetSpeedRandomiser,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Physics.Acts.RemoveJoints,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Cnds.OnSuspend,
		C3.Plugins.System.Exps.windowwidth,
		C3.Plugins.System.Exps.windowheight,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Spritefont2.Exps.LayerName,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetPosToObject,
		C3.Plugins.System.Exps.originalwindowheight,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Spritefont2.Acts.SetBoolInstanceVar,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.Signal,
		C3.Behaviors.Physics.Acts.SetSteppingMode,
		C3.JavaScriptInEvents.Global_event_Event195_Act1,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.JavaScriptInEvents.Global_event_Event203_Act2,
		C3.JavaScriptInEvents.Global_event_Event204_Act2,
		C3.JavaScriptInEvents.Global_event_Event207_Act1,
		C3.JavaScriptInEvents.Global_event_Event208_Act1,
		C3.JavaScriptInEvents.Global_event_Event209_Act1,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.JavaScriptInEvents.Global_event_Event210_Act2,
		C3.JavaScriptInEvents.Global_event_Event211_Act1,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.Browser.Exps.Language,
		C3.Plugins.BinaryData.Acts.SetFromBase64,
		C3.Plugins.BinaryData.Acts.Decompress,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.BinaryData.Exps.GetAllText,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Spritefont2.Exps.IID,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Exps.Height,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Width,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Touch.Cnds.OnTapGestureObject
	];
};
self.C3_JsPropNameTable = [
	{Cursor_Pressed: 0},
	{Cursor: 0},
	{Frame_Paused: 0},
	{Progress_Frame: 0},
	{Progress_Indicator: 0},
	{Progress_Line: 0},
	{Name: 0},
	{Frame_Icon: 0},
	{Icon_Time: 0},
	{Icon_Total_Score: 0},
	{Icon_Star: 0},
	{Icon_Coin: 0},
	{Frame_Button: 0},
	{Loading_Bar: 0},
	{Width_Size: 0},
	{Loading_Bar_Line: 0},
	{Loading_Bar_Top: 0},
	{Loading_Bar_Frame: 0},
	{Red_Flag: 0},
	{White_Flag: 0},
	{Fade: 0},
	{Frame_Instruction: 0},
	{Frame_Results: 0},
	{Star_1: 0},
	{Star_2: 0},
	{Star_3: 0},
	{Icon_Target: 0},
	{Frame_Score: 0},
	{Frame_Coins: 0},
	{ID: 0},
	{Level_Closed: 0},
	{Icon_Level: 0},
	{Page_Indicator: 0},
	{Orientation: 0},
	{Anchor: 0},
	{Black_Screen2: 0},
	{Active: 0},
	{Height_Size: 0},
	{Button_Ad: 0},
	{Button_Ad2: 0},
	{Icon_Coin2: 0},
	{Icon_Coin3: 0},
	{Background_Mine: 0},
	{Sky: 0},
	{Index: 0},
	{Background_Game0: 0},
	{Background_Game1: 0},
	{Background_Game2: 0},
	{Background_Game3: 0},
	{Background_Game4: 0},
	{Background_Game5: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{Dictionary: 0},
	{Level_Stars: 0},
	{Tractors: 0},
	{Trailers: 0},
	{PlatformInfo: 0},
	{BinaryData_Level_Stars: 0},
	{JSON: 0},
	{BinaryData_Tractors: 0},
	{BinaryData_Trailers: 0},
	{BinaryData_Dictionary: 0},
	{Fire: 0},
	{Box_Explosion: 0},
	{Score_Font: 0},
	{Time_Font: 0},
	{Loading_Font: 0},
	{Game_Score_Font: 0},
	{Orientation_Font: 0},
	{Item: 0},
	{Price_Font: 0},
	{Distance_Font: 0},
	{Stars_Font: 0},
	{Coins_Font: 0},
	{Button_Level_Font: 0},
	{Target_Font: 0},
	{Level_Font: 0},
	{Total_Score_Font: 0},
	{Button_Exit: 0},
	{Button_Facebook: 0},
	{Button_Fullscreen: 0},
	{Button_Play: 0},
	{Button_Info: 0},
	{Button_Garage: 0},
	{Button_More_Games: 0},
	{Button_Music: 0},
	{Button_Pause: 0},
	{Button_Return: 0},
	{Button_Sound: 0},
	{Button_Start: 0},
	{Button_Twitter: 0},
	{Button_Go: 0},
	{Button_Restart: 0},
	{Button_Vehicles: 0},
	{Button_Buy: 0},
	{Button_Reverse: 0},
	{Button_Acceleration: 0},
	{Button_Up: 0},
	{Button_Down: 0},
	{Button_Language: 0},
	{Button_Level: 0},
	{Button_Back: 0},
	{Button_Menu: 0},
	{Button_Handbrake: 0},
	{Button_Nitro: 0},
	{Button_Next: 0},
	{Button_Clear: 0},
	{Button_Left: 0},
	{Button_Right: 0},
	{Button_Restart2: 0},
	{Game_Icon: 0},
	{Sine: 0},
	{Game_Logo: 0},
	{Black_Screen: 0},
	{Sun_Rays: 0},
	{Sun_Shine: 0},
	{btn_CloseNo: 0},
	{btn_CloseYes: 0},
	{CloseText: 0},
	{info: 0},
	{InfoBg: 0},
	{Logo: 0},
	{Qplaze: 0},
	{Spash_Fin: 0},
	{TeXT_Paused: 0},
	{Text_You_Won: 0},
	{Text_You_Score: 0},
	{Text_New_Score: 0},
	{Text_Levels: 0},
	{Text_Out_Of_Fuel: 0},
	{Text_Description: 0},
	{Text_Game_Description: 0},
	{Text_Instruction: 0},
	{Text_Level_Completed: 0},
	{Text_Level_Failed: 0},
	{Text_Driver_Suffered: 0},
	{Text_Time_Over: 0},
	{Text_Out_Of_Fuel_Results: 0},
	{Text_Tap_To_Play: 0},
	{Text_Product_Not_Delivered: 0},
	{Tween: 0},
	{NotEnoughCoins: 0},
	{Start_Point: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{Finish_Point: 0},
	{Field: 0},
	{Flower: 0},
	{Building: 0},
	{Citrus_Tree: 0},
	{Bush_Midground: 0},
	{Bush_Foreground: 0},
	{Tree_Midground: 0},
	{Tree_Foreground: 0},
	{Powerline_Post: 0},
	{Top_Edge: 0},
	{Light_Slope_To_Left_Part_3: 0},
	{Inner_Corner_Bottom_Right: 0},
	{Center_Of_Floating_Platform: 0},
	{Inner_Corner_Bottom_Left: 0},
	{Inner_Corner_Top_Left: 0},
	{Inner_Corner_Top_Right: 0},
	{Left_Edge_Vertical_Grass_Top: 0},
	{Light_Slope_To_Left_Part_1: 0},
	{Top_Edge_Left: 0},
	{Top_Edge_Right: 0},
	{Left_Edge_Floating_Platform: 0},
	{Light_Slope_To_Right_Part_1: 0},
	{Light_Slope_To_Right_Part_2: 0},
	{Right_Edge_Floating_Platform: 0},
	{Light_Slope_To_Right_Part_3: 0},
	{One_Edge_Platform_Rock: 0},
	{Light_Slope_To_Left_Part_2: 0},
	{Outer_Corner_Bottom_Left: 0},
	{Outer_Corner_Bottom_Right: 0},
	{Outer_Corner_Top_Right: 0},
	{Outer_Corner_Top_Left: 0},
	{Right_Edge_Vertical_Grass_Top: 0},
	{Steep_Slope_To_Left_Part_1: 0},
	{Steep_Slope_To_Left_Part_2: 0},
	{Top_Edge_One_Tile_Platform: 0},
	{Steep_Slope_To_Right_Part_1: 0},
	{Steep_Slope_To_Right_Part_2: 0},
	{Top_To_Left_Edge_Join: 0},
	{Top_To_Right_Edge_Join: 0},
	{Upper_Straight_Edge: 0},
	{Flat_Color_Inner_Fill: 0},
	{Right_Edge_Rock: 0},
	{Left_Edge_Rock: 0},
	{Danger_Sign: 0},
	{Moved: 0},
	{Red_Barn: 0},
	{Silo: 0},
	{Windmill: 0},
	{Windmill_UID: 0},
	{Speed: 0},
	{Windmill_Fan: 0},
	{Chicken_Coop_Wooden: 0},
	{Chicken_Coop_Red: 0},
	{Scarecrow: 0},
	{Haypile: 0},
	{Wood_Fence_Repeating_Panel: 0},
	{Stone_Wall_Center: 0},
	{Stone_Wall: 0},
	{Stone_Wall_Left: 0},
	{Stone_Wall_Right: 0},
	{Wood_Fence_Post: 0},
	{Wood_Fence_Panel: 0},
	{Wood_Gate_Closed: 0},
	{Wood_Gate_Open: 0},
	{Wood_Gate_Complete: 0},
	{Wood_Gate_Post: 0},
	{Mesh_Fence: 0},
	{Wood_Fence: 0},
	{Bush: 0},
	{Bush_1: 0},
	{Bush_2: 0},
	{Bush_3: 0},
	{Tree_1: 0},
	{Tree_2: 0},
	{Tree_3: 0},
	{Tree_4: 0},
	{Tree_5: 0},
	{Sweetcorn_Group: 0},
	{Sunflowers_Group2: 0},
	{Sweetcorn_1: 0},
	{Sweetcorn_2: 0},
	{Sunflower_1: 0},
	{Sunflower_2: 0},
	{Lettuce_1: 0},
	{Lettuce_2: 0},
	{Carrot_1: 0},
	{Carrot_2: 0},
	{Leaf: 0},
	{Line: 0},
	{Curved_Cable: 0},
	{Bridge_Tile_1: 0},
	{Left_Stake: 0},
	{Right_Stake: 0},
	{Bridge_ID: 0},
	{Tile_ID: 0},
	{Pin: 0},
	{Rope: 0},
	{Bridge_Tile_2: 0},
	{Bridge_Tile_3: 0},
	{Bridge_Tile_4: 0},
	{Bridge_Tile_5: 0},
	{Bridge_Tile_6: 0},
	{Bridge_Tile_7: 0},
	{Coin: 0},
	{Garage_Bottom: 0},
	{Upgrade_Frame: 0},
	{Text_Engine: 0},
	{Text_Transmission: 0},
	{Text_Tyres: 0},
	{Text_Boost: 0},
	{Text_Fuel: 0},
	{Upgrade_Levels: 0},
	{Garage_Tractors: 0},
	{Garage_Trailers: 0},
	{Text_Tractor: 0},
	{Text_Trailer: 0},
	{Lock: 0},
	{Text_Garage: 0},
	{Ladder: 0},
	{Lamp: 0},
	{Window: 0},
	{Garage_Background: 0},
	{Rack_Centr: 0},
	{Board_Center: 0},
	{Board_Left_1: 0},
	{Bucket: 0},
	{Sack_1: 0},
	{Sack_2: 0},
	{Sign_Board: 0},
	{Board_Left_2: 0},
	{Board_Left_3: 0},
	{Board_Right_1: 0},
	{Board_Right_2: 0},
	{Board_Right_3: 0},
	{Garage_Floor: 0},
	{Rack_Right: 0},
	{Sign_Open: 0},
	{BoundToLayout: 0},
	{Trailer_Frame: 0},
	{Trailer_Wheel_Front: 0},
	{Trailer_Wheel_Middle: 0},
	{Trailer_Wheel_Rear: 0},
	{Trailer_Lever_Wheel_F_Front: 0},
	{Trailer_Lever_Wheel_F_Rear: 0},
	{Trailer_Lever_Wheel_R_Front: 0},
	{Trailer_Lever_Wheel_R_Rear: 0},
	{Trailer_Lever_Wheel_M_Front: 0},
	{Trailer_Lever_Wheel_M_Rear: 0},
	{Tow_Hitch: 0},
	{Tractor_Frame: 0},
	{Tractor_Lever_Wheel_F_Front: 0},
	{Tractor_Lever_Wheel_F_Rear: 0},
	{Tractor_Lever_Wheel_R_Front: 0},
	{Tractor_Lever_Wheel_R_Rear: 0},
	{Tractor_Wheel_Front: 0},
	{Tractor_Wheel_Rear: 0},
	{Tractor_Wing: 0},
	{Arm_Bottom: 0},
	{Arm_Top: 0},
	{DragDrop: 0},
	{Body: 0},
	{Hand_Bottom: 0},
	{Hand_Top: 0},
	{Tractor: 0},
	{Head: 0},
	{Leg_Bottom: 0},
	{Leg_Top: 0},
	{Fuel_Gauge: 0},
	{Fuel_Gauge_Arrow: 0},
	{Fuel_Gauge_Lamp: 0},
	{Fuel_Gauge_Lamp_Light: 0},
	{Nitro_Gauge: 0},
	{Nitro_Gauge_Arrow: 0},
	{Speedometer_Gauge: 0},
	{Start_Angle: 0},
	{Speedometer_Gauge_Arrow: 0},
	{Brake_Light: 0},
	{Nitro: 0},
	{Reverse_Light: 0},
	{Smoke: 0},
	{Sound: 0},
	{Delivered: 0},
	{Reward: 0},
	{Apple: 0},
	{Banana: 0},
	{Cherry: 0},
	{Coconut: 0},
	{Grape: 0},
	{Lemon: 0},
	{Lime: 0},
	{Orange: 0},
	{Peach: 0},
	{Pear: 0},
	{Plum: 0},
	{Raspberry: 0},
	{Starfruit: 0},
	{Strawberry: 0},
	{Watermelon: 0},
	{Mushroom: 0},
	{Aubergine: 0},
	{Cabbage: 0},
	{Carrot: 0},
	{Courgette: 0},
	{Onion: 0},
	{Tomato: 0},
	{Pepper: 0},
	{Potato: 0},
	{Broccoli: 0},
	{Cauliflower: 0},
	{Lettuce: 0},
	{Sweetcorn: 0},
	{Pumpkin: 0},
	{Beetroot: 0},
	{Chili_Pepper: 0},
	{Garlic: 0},
	{Parsnip: 0},
	{Blackberry: 0},
	{Conveyer_Center: 0},
	{Conveyer_Right: 0},
	{Loader: 0},
	{Loader_Light: 0},
	{Traffic_Light: 0},
	{Crane_Gantry: 0},
	{Loader_Switch: 0},
	{Stop_Sign: 0},
	{Barricade: 0},
	{Watchtower: 0},
	{Farm_Background: 0},
	{Farm_Object_Center: 0},
	{Farm_Object_Left: 0},
	{Farm_Object_Right: 0},
	{Farm_Sky: 0},
	{Sun: 0},
	{TXT_Description: 0},
	{TXT_GameDescription: 0},
	{TXT_TractorMania: 0},
	{TXT_Garage: 0},
	{TXT_Trailer: 0},
	{TXT_Tractor: 0},
	{TXT_Engine: 0},
	{TXT_Gearbox: 0},
	{TXT_Tires: 0},
	{TXT_Boost: 0},
	{TXT_Fuel: 0},
	{TXT_levels: 0},
	{TXT_Reach: 0},
	{TXT_LVl: 0},
	{TXT_Paused: 0},
	{TXT_Instruction: 0},
	{TXT_OutOfFuel: 0},
	{TXT_TapToPlay: 0},
	{TXT_LevelFailed: 0},
	{TXT_OutOfFuel2: 0},
	{TXT_TimeOver: 0},
	{TXT_ProductNotDelivered: 0},
	{TXT_Suffered: 0},
	{TXT_LevelCompleted: 0},
	{TXT_YouWon: 0},
	{Buttons: 0},
	{Texts: 0},
	{Physics: 0},
	{Road: 0},
	{Trailer: 0},
	{Objects: 0},
	{Products: 0},
	{Driver: 0},
	{Trees: 0},
	{Bushes: 0},
	{Buildings: 0},
	{Bridge: 0},
	{BG: 0},
	{Bridge_Count: 0},
	{Building_Position: 0},
	{Building_Width: 0},
	{Field_Area_Start: 0},
	{Field_Area_Finish: 0},
	{Garden_Area_Start: 0},
	{Garden_Area_Finish: 0},
	{Load_Area: 0},
	{Unload_Area: 0},
	{Loader_Command: 0},
	{Game_Status: 0},
	{Control: 0},
	{Command: 0},
	{Stars: 0},
	{Level_Total_Products: 0},
	{Spawn_Products: 0},
	{Delivery_Products: 0},
	{Delivered_Products: 0},
	{Speed_Coefficient: 0},
	{Speed_Limit: 0},
	{Scale: 0},
	{Coins: 0},
	{Score: 0},
	{Seconds: 0},
	{Minutes: 0},
	{Count_Score: 0},
	{Count_Coins: 0},
	{Count_Seconds: 0},
	{Tile_Size: 0},
	{Powerline_Posts: 0},
	{Powerline_Post_Road_ID: 0},
	{Powerline_Post_Position: 0},
	{Powerline_Post_Distance: 0},
	{Road_Difficulty: 0},
	{Level_Max_Tiles: 0},
	{Level_Tiles: 0},
	{Current_Y: 0},
	{Current_Tile: 0},
	{Road_Top: 0},
	{Road_Bottom: 0},
	{Road_Part_Type: 0},
	{Road_Part_Width: 0},
	{Current_Part_Width: 0},
	{Product: 0},
	{Audio_Layout: 0},
	{Language: 0},
	{Sound_Status: 0},
	{Music: 0},
	{Music_Status: 0},
	{Size_Difference: 0},
	{Current_Distance: 0},
	{DISTANCE_BETWEEN_OBJECTS: 0},
	{cheat: 0},
	{TXT_NotEnoughCoins: 0},
	{TXT_Lvl: 0},
	{TXT_M: 0},
	{TEXT_youWantToExit: 0},
	{mute: 0},
	{param: 0},
	{rewardAd: 0},
	{reward: 0},
	{Score2: 0},
	{Level2: 0},
	{DataJson: 0},
	{keyName: 0},
	{Key: 0},
	{Info: 0},
	{Page_Indicator_Width: 0},
	{Page_Indicator_Margin_Left: 0},
	{Level: 0},
	{CompleteLevels: 0},
	{Total_Stars: 0},
	{Level_Number: 0},
	{Total_Buttons: 0},
	{Total_Levels: 0},
	{Total_Pages: 0},
	{Levels_Page: 0},
	{Button_Rows: 0},
	{Button_Columns: 0},
	{Button_Space_Between: 0},
	{Button_Width: 0},
	{Button_Height: 0},
	{Margin_Top: 0},
	{Margin_Left: 0},
	{Current_Button_Created: 0},
	{Current_Column: 0},
	{Current_Row: 0},
	{Page_Indicator_Created: 0},
	{DESCRIPTION: 0},
	{REDIRECT_URL: 0},
	{IMAGE: 0},
	{Tractor_Price: 0},
	{Trailer_Price: 0},
	{Frequency_Tractor_Front: 0},
	{Frequency_Tractor_Rear: 0},
	{Frequency_Trailer: 0},
	{Friction: 0},
	{Torque: 0},
	{Garage_Tractor: 0},
	{Garage_Trailer: 0},
	{Weigh: 0},
	{Gravity: 0},
	{Suspension_Height: 0},
	{Engine_Price: 0},
	{Engine_Level: 0},
	{Engine_Max_Level: 0},
	{Transmission_Price: 0},
	{Transmission_Level: 0},
	{Transmission_Max_Level: 0},
	{Transmission_Coefficient: 0},
	{Tires_Price: 0},
	{Tires_Level: 0},
	{Tires_Max_Level: 0},
	{Nitro_Price: 0},
	{Nitro_Level: 0},
	{Nitro_Max_Level: 0},
	{Nitro_Coefficient: 0},
	{Fuel: 0},
	{Fuel_Price: 0},
	{Fuel_Level: 0},
	{Fuel_Max_Level: 0},
	{Total_Coins: 0},
	{Total_Score: 0},
	{Global_Score: 0},
	{CountAds: 0}
];

self.InstanceType = {
	Cursor_Pressed: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	Frame_Paused: class extends self.ISpriteInstance {},
	Progress_Frame: class extends self.ISpriteInstance {},
	Progress_Indicator: class extends self.ISpriteInstance {},
	Progress_Line: class extends self.ITiledBackgroundInstance {},
	Frame_Icon: class extends self.ISpriteInstance {},
	Icon_Time: class extends self.ISpriteInstance {},
	Icon_Total_Score: class extends self.ISpriteInstance {},
	Icon_Star: class extends self.ISpriteInstance {},
	Icon_Coin: class extends self.ISpriteInstance {},
	Frame_Button: class extends self.ISpriteInstance {},
	Loading_Bar: class extends self.ISpriteInstance {},
	Loading_Bar_Line: class extends self.ITiledBackgroundInstance {},
	Loading_Bar_Top: class extends self.ISpriteInstance {},
	Loading_Bar_Frame: class extends self.ISpriteInstance {},
	Red_Flag: class extends self.ISpriteInstance {},
	White_Flag: class extends self.ISpriteInstance {},
	Frame_Instruction: class extends self.ISpriteInstance {},
	Frame_Results: class extends self.ISpriteInstance {},
	Star_1: class extends self.ISpriteInstance {},
	Star_2: class extends self.ISpriteInstance {},
	Star_3: class extends self.ISpriteInstance {},
	Icon_Target: class extends self.ISpriteInstance {},
	Frame_Score: class extends self.ISpriteInstance {},
	Frame_Coins: class extends self.ISpriteInstance {},
	Level_Closed: class extends self.ISpriteInstance {},
	Icon_Level: class extends self.ISpriteInstance {},
	Page_Indicator: class extends self.ISpriteInstance {},
	Orientation: class extends self.ISpriteInstance {},
	Black_Screen2: class extends self.ISpriteInstance {},
	Button_Ad: class extends self.ISpriteInstance {},
	Button_Ad2: class extends self.ISpriteInstance {},
	Icon_Coin2: class extends self.ISpriteInstance {},
	Icon_Coin3: class extends self.ISpriteInstance {},
	Background_Mine: class extends self.ITiledBackgroundInstance {},
	Sky: class extends self.ITiledBackgroundInstance {},
	Background_Game0: class extends self.ITiledBackgroundInstance {},
	Background_Game1: class extends self.ITiledBackgroundInstance {},
	Background_Game2: class extends self.ITiledBackgroundInstance {},
	Background_Game3: class extends self.ITiledBackgroundInstance {},
	Background_Game4: class extends self.ITiledBackgroundInstance {},
	Background_Game5: class extends self.ITiledBackgroundInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	Level_Stars: class extends self.IArrayInstance {},
	Tractors: class extends self.IArrayInstance {},
	Trailers: class extends self.IArrayInstance {},
	PlatformInfo: class extends self.IInstance {},
	BinaryData_Level_Stars: class extends self.IBinaryDataInstance {},
	JSON: class extends self.IJSONInstance {},
	BinaryData_Tractors: class extends self.IBinaryDataInstance {},
	BinaryData_Trailers: class extends self.IBinaryDataInstance {},
	BinaryData_Dictionary: class extends self.IBinaryDataInstance {},
	Fire: class extends self.ISpriteInstance {},
	Box_Explosion: class extends self.ISpriteInstance {},
	Score_Font: class extends self.ISpriteFontInstance {},
	Time_Font: class extends self.ISpriteFontInstance {},
	Loading_Font: class extends self.ISpriteFontInstance {},
	Game_Score_Font: class extends self.ISpriteFontInstance {},
	Orientation_Font: class extends self.ISpriteFontInstance {},
	Price_Font: class extends self.ISpriteFontInstance {},
	Distance_Font: class extends self.ISpriteFontInstance {},
	Stars_Font: class extends self.ISpriteFontInstance {},
	Coins_Font: class extends self.ISpriteFontInstance {},
	Button_Level_Font: class extends self.ISpriteFontInstance {},
	Target_Font: class extends self.ISpriteFontInstance {},
	Level_Font: class extends self.ISpriteFontInstance {},
	Total_Score_Font: class extends self.ISpriteFontInstance {},
	Button_Exit: class extends self.ISpriteInstance {},
	Button_Facebook: class extends self.ISpriteInstance {},
	Button_Fullscreen: class extends self.ISpriteInstance {},
	Button_Play: class extends self.ISpriteInstance {},
	Button_Info: class extends self.ISpriteInstance {},
	Button_Garage: class extends self.ISpriteInstance {},
	Button_More_Games: class extends self.ISpriteInstance {},
	Button_Music: class extends self.ISpriteInstance {},
	Button_Pause: class extends self.ISpriteInstance {},
	Button_Return: class extends self.ISpriteInstance {},
	Button_Sound: class extends self.ISpriteInstance {},
	Button_Start: class extends self.ISpriteInstance {},
	Button_Twitter: class extends self.ISpriteInstance {},
	Button_Go: class extends self.ISpriteInstance {},
	Button_Restart: class extends self.ISpriteInstance {},
	Button_Vehicles: class extends self.ISpriteInstance {},
	Button_Buy: class extends self.ISpriteInstance {},
	Button_Reverse: class extends self.ISpriteInstance {},
	Button_Acceleration: class extends self.ISpriteInstance {},
	Button_Up: class extends self.ISpriteInstance {},
	Button_Down: class extends self.ISpriteInstance {},
	Button_Language: class extends self.ISpriteInstance {},
	Button_Level: class extends self.ISpriteInstance {},
	Button_Back: class extends self.ISpriteInstance {},
	Button_Menu: class extends self.ISpriteInstance {},
	Button_Handbrake: class extends self.ISpriteInstance {},
	Button_Nitro: class extends self.ISpriteInstance {},
	Button_Next: class extends self.ISpriteInstance {},
	Button_Clear: class extends self.ISpriteInstance {},
	Button_Left: class extends self.ISpriteInstance {},
	Button_Right: class extends self.ISpriteInstance {},
	Button_Restart2: class extends self.ISpriteInstance {},
	Game_Icon: class extends self.ISpriteInstance {},
	Game_Logo: class extends self.ISpriteInstance {},
	Black_Screen: class extends self.ISpriteInstance {},
	Sun_Rays: class extends self.ISpriteInstance {},
	Sun_Shine: class extends self.ISpriteInstance {},
	btn_CloseNo: class extends self.ISpriteInstance {},
	btn_CloseYes: class extends self.ISpriteInstance {},
	CloseText: class extends self.ITextInstance {},
	info: class extends self.ISpriteInstance {},
	InfoBg: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	Qplaze: class extends self.ISpriteInstance {},
	Spash_Fin: class extends self.ISpriteInstance {},
	TeXT_Paused: class extends self.ISpriteInstance {},
	Text_You_Won: class extends self.ISpriteInstance {},
	Text_You_Score: class extends self.ISpriteInstance {},
	Text_New_Score: class extends self.ISpriteInstance {},
	Text_Levels: class extends self.ISpriteInstance {},
	Text_Out_Of_Fuel: class extends self.ISpriteInstance {},
	Text_Description: class extends self.ISpriteInstance {},
	Text_Game_Description: class extends self.ISpriteInstance {},
	Text_Instruction: class extends self.ISpriteInstance {},
	Text_Level_Completed: class extends self.ISpriteInstance {},
	Text_Level_Failed: class extends self.ISpriteInstance {},
	Text_Driver_Suffered: class extends self.ISpriteInstance {},
	Text_Time_Over: class extends self.ISpriteInstance {},
	Text_Out_Of_Fuel_Results: class extends self.ISpriteInstance {},
	Text_Tap_To_Play: class extends self.ISpriteInstance {},
	Text_Product_Not_Delivered: class extends self.ISpriteInstance {},
	NotEnoughCoins: class extends self.ITextInstance {},
	Start_Point: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	Finish_Point: class extends self.ISpriteInstance {},
	Top_Edge: class extends self.ISpriteInstance {},
	Light_Slope_To_Left_Part_3: class extends self.ISpriteInstance {},
	Inner_Corner_Bottom_Right: class extends self.ISpriteInstance {},
	Center_Of_Floating_Platform: class extends self.ISpriteInstance {},
	Inner_Corner_Bottom_Left: class extends self.ISpriteInstance {},
	Inner_Corner_Top_Left: class extends self.ISpriteInstance {},
	Inner_Corner_Top_Right: class extends self.ISpriteInstance {},
	Left_Edge_Vertical_Grass_Top: class extends self.ISpriteInstance {},
	Light_Slope_To_Left_Part_1: class extends self.ISpriteInstance {},
	Top_Edge_Left: class extends self.ISpriteInstance {},
	Top_Edge_Right: class extends self.ISpriteInstance {},
	Left_Edge_Floating_Platform: class extends self.ISpriteInstance {},
	Light_Slope_To_Right_Part_1: class extends self.ISpriteInstance {},
	Light_Slope_To_Right_Part_2: class extends self.ISpriteInstance {},
	Right_Edge_Floating_Platform: class extends self.ISpriteInstance {},
	Light_Slope_To_Right_Part_3: class extends self.ISpriteInstance {},
	One_Edge_Platform_Rock: class extends self.ISpriteInstance {},
	Light_Slope_To_Left_Part_2: class extends self.ISpriteInstance {},
	Outer_Corner_Bottom_Left: class extends self.ISpriteInstance {},
	Outer_Corner_Bottom_Right: class extends self.ISpriteInstance {},
	Outer_Corner_Top_Right: class extends self.ISpriteInstance {},
	Outer_Corner_Top_Left: class extends self.ISpriteInstance {},
	Right_Edge_Vertical_Grass_Top: class extends self.ISpriteInstance {},
	Steep_Slope_To_Left_Part_1: class extends self.ISpriteInstance {},
	Steep_Slope_To_Left_Part_2: class extends self.ISpriteInstance {},
	Top_Edge_One_Tile_Platform: class extends self.ISpriteInstance {},
	Steep_Slope_To_Right_Part_1: class extends self.ISpriteInstance {},
	Steep_Slope_To_Right_Part_2: class extends self.ISpriteInstance {},
	Top_To_Left_Edge_Join: class extends self.ISpriteInstance {},
	Top_To_Right_Edge_Join: class extends self.ISpriteInstance {},
	Upper_Straight_Edge: class extends self.ISpriteInstance {},
	Flat_Color_Inner_Fill: class extends self.ITiledBackgroundInstance {},
	Right_Edge_Rock: class extends self.ITiledBackgroundInstance {},
	Left_Edge_Rock: class extends self.ITiledBackgroundInstance {},
	Danger_Sign: class extends self.ISpriteInstance {},
	Red_Barn: class extends self.ISpriteInstance {},
	Silo: class extends self.ISpriteInstance {},
	Windmill: class extends self.ISpriteInstance {},
	Windmill_Fan: class extends self.ISpriteInstance {},
	Chicken_Coop_Wooden: class extends self.ISpriteInstance {},
	Chicken_Coop_Red: class extends self.ISpriteInstance {},
	Scarecrow: class extends self.ISpriteInstance {},
	Haypile: class extends self.ISpriteInstance {},
	Wood_Fence_Repeating_Panel: class extends self.ISpriteInstance {},
	Stone_Wall_Center: class extends self.ISpriteInstance {},
	Stone_Wall: class extends self.ISpriteInstance {},
	Stone_Wall_Left: class extends self.ISpriteInstance {},
	Stone_Wall_Right: class extends self.ISpriteInstance {},
	Wood_Fence_Post: class extends self.ISpriteInstance {},
	Wood_Fence_Panel: class extends self.ISpriteInstance {},
	Wood_Gate_Closed: class extends self.ISpriteInstance {},
	Wood_Gate_Open: class extends self.ISpriteInstance {},
	Wood_Gate_Complete: class extends self.ISpriteInstance {},
	Wood_Gate_Post: class extends self.ISpriteInstance {},
	Mesh_Fence: class extends self.ITiledBackgroundInstance {},
	Wood_Fence: class extends self.ITiledBackgroundInstance {},
	Bush: class extends self.ISpriteInstance {},
	Citrus_Tree: class extends self.ISpriteInstance {},
	Bush_1: class extends self.ISpriteInstance {},
	Bush_2: class extends self.ISpriteInstance {},
	Bush_3: class extends self.ISpriteInstance {},
	Tree_1: class extends self.ISpriteInstance {},
	Tree_2: class extends self.ISpriteInstance {},
	Tree_3: class extends self.ISpriteInstance {},
	Tree_4: class extends self.ISpriteInstance {},
	Tree_5: class extends self.ISpriteInstance {},
	Sweetcorn_Group: class extends self.ISpriteInstance {},
	Sunflowers_Group2: class extends self.ISpriteInstance {},
	Sweetcorn_1: class extends self.ISpriteInstance {},
	Sweetcorn_2: class extends self.ISpriteInstance {},
	Sunflower_1: class extends self.ISpriteInstance {},
	Sunflower_2: class extends self.ISpriteInstance {},
	Lettuce_1: class extends self.ISpriteInstance {},
	Lettuce_2: class extends self.ISpriteInstance {},
	Carrot_1: class extends self.ISpriteInstance {},
	Carrot_2: class extends self.ISpriteInstance {},
	Flower: class extends self.ISpriteInstance {},
	Leaf: class extends self.ISpriteInstance {},
	Curved_Cable: class extends self.ISpriteInstance {},
	Powerline_Post: class extends self.ISpriteInstance {},
	Bridge_Tile_1: class extends self.ISpriteInstance {},
	Left_Stake: class extends self.ISpriteInstance {},
	Right_Stake: class extends self.ISpriteInstance {},
	Rope: class extends self.ITiledBackgroundInstance {},
	Bridge_Tile_2: class extends self.ISpriteInstance {},
	Bridge_Tile_3: class extends self.ISpriteInstance {},
	Bridge_Tile_4: class extends self.ISpriteInstance {},
	Bridge_Tile_5: class extends self.ISpriteInstance {},
	Bridge_Tile_6: class extends self.ISpriteInstance {},
	Bridge_Tile_7: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	Garage_Bottom: class extends self.ITiledBackgroundInstance {},
	Upgrade_Frame: class extends self.ISpriteInstance {},
	Text_Engine: class extends self.ISpriteInstance {},
	Text_Transmission: class extends self.ISpriteInstance {},
	Text_Tyres: class extends self.ISpriteInstance {},
	Text_Boost: class extends self.ISpriteInstance {},
	Text_Fuel: class extends self.ISpriteInstance {},
	Upgrade_Levels: class extends self.ISpriteInstance {},
	Garage_Tractors: class extends self.ISpriteInstance {},
	Garage_Trailers: class extends self.ISpriteInstance {},
	Text_Tractor: class extends self.ISpriteInstance {},
	Text_Trailer: class extends self.ISpriteInstance {},
	Lock: class extends self.ISpriteInstance {},
	Text_Garage: class extends self.ISpriteInstance {},
	Ladder: class extends self.ISpriteInstance {},
	Lamp: class extends self.ISpriteInstance {},
	Window: class extends self.ISpriteInstance {},
	Garage_Background: class extends self.ITiledBackgroundInstance {},
	Rack_Centr: class extends self.ISpriteInstance {},
	Board_Center: class extends self.ISpriteInstance {},
	Board_Left_1: class extends self.ISpriteInstance {},
	Bucket: class extends self.ISpriteInstance {},
	Sack_1: class extends self.ISpriteInstance {},
	Sack_2: class extends self.ISpriteInstance {},
	Sign_Board: class extends self.ISpriteInstance {},
	Board_Left_2: class extends self.ISpriteInstance {},
	Board_Left_3: class extends self.ISpriteInstance {},
	Board_Right_1: class extends self.ISpriteInstance {},
	Board_Right_2: class extends self.ISpriteInstance {},
	Board_Right_3: class extends self.ISpriteInstance {},
	Garage_Floor: class extends self.ITiledBackgroundInstance {},
	Rack_Right: class extends self.ISpriteInstance {},
	Sign_Open: class extends self.ISpriteInstance {},
	Trailer_Frame: class extends self.ISpriteInstance {},
	Trailer_Wheel_Front: class extends self.ISpriteInstance {},
	Trailer_Wheel_Middle: class extends self.ISpriteInstance {},
	Trailer_Wheel_Rear: class extends self.ISpriteInstance {},
	Trailer_Lever_Wheel_F_Front: class extends self.ISpriteInstance {},
	Trailer_Lever_Wheel_F_Rear: class extends self.ISpriteInstance {},
	Trailer_Lever_Wheel_R_Front: class extends self.ISpriteInstance {},
	Trailer_Lever_Wheel_R_Rear: class extends self.ISpriteInstance {},
	Trailer_Lever_Wheel_M_Front: class extends self.ISpriteInstance {},
	Trailer_Lever_Wheel_M_Rear: class extends self.ISpriteInstance {},
	Tow_Hitch: class extends self.ISpriteInstance {},
	Tractor_Frame: class extends self.ISpriteInstance {},
	Tractor_Lever_Wheel_F_Front: class extends self.ISpriteInstance {},
	Tractor_Lever_Wheel_F_Rear: class extends self.ISpriteInstance {},
	Tractor_Lever_Wheel_R_Front: class extends self.ISpriteInstance {},
	Tractor_Lever_Wheel_R_Rear: class extends self.ISpriteInstance {},
	Tractor_Wheel_Front: class extends self.ISpriteInstance {},
	Tractor_Wheel_Rear: class extends self.ISpriteInstance {},
	Tractor_Wing: class extends self.ISpriteInstance {},
	Arm_Bottom: class extends self.ISpriteInstance {},
	Arm_Top: class extends self.ISpriteInstance {},
	Body: class extends self.ISpriteInstance {},
	Hand_Bottom: class extends self.ISpriteInstance {},
	Hand_Top: class extends self.ISpriteInstance {},
	Head: class extends self.ISpriteInstance {},
	Leg_Bottom: class extends self.ISpriteInstance {},
	Leg_Top: class extends self.ISpriteInstance {},
	Fuel_Gauge: class extends self.ISpriteInstance {},
	Fuel_Gauge_Arrow: class extends self.ISpriteInstance {},
	Fuel_Gauge_Lamp: class extends self.ISpriteInstance {},
	Fuel_Gauge_Lamp_Light: class extends self.ISpriteInstance {},
	Nitro_Gauge: class extends self.ISpriteInstance {},
	Nitro_Gauge_Arrow: class extends self.ISpriteInstance {},
	Speedometer_Gauge: class extends self.ISpriteInstance {},
	Speedometer_Gauge_Arrow: class extends self.ISpriteInstance {},
	Brake_Light: class extends self.ISpriteInstance {},
	Nitro: class extends self.ISpriteInstance {},
	Reverse_Light: class extends self.ISpriteInstance {},
	Smoke: class extends self.IParticlesInstance {},
	Apple: class extends self.ISpriteInstance {},
	Banana: class extends self.ISpriteInstance {},
	Cherry: class extends self.ISpriteInstance {},
	Coconut: class extends self.ISpriteInstance {},
	Grape: class extends self.ISpriteInstance {},
	Lemon: class extends self.ISpriteInstance {},
	Lime: class extends self.ISpriteInstance {},
	Orange: class extends self.ISpriteInstance {},
	Peach: class extends self.ISpriteInstance {},
	Pear: class extends self.ISpriteInstance {},
	Plum: class extends self.ISpriteInstance {},
	Raspberry: class extends self.ISpriteInstance {},
	Starfruit: class extends self.ISpriteInstance {},
	Strawberry: class extends self.ISpriteInstance {},
	Watermelon: class extends self.ISpriteInstance {},
	Mushroom: class extends self.ISpriteInstance {},
	Aubergine: class extends self.ISpriteInstance {},
	Cabbage: class extends self.ISpriteInstance {},
	Carrot: class extends self.ISpriteInstance {},
	Courgette: class extends self.ISpriteInstance {},
	Onion: class extends self.ISpriteInstance {},
	Tomato: class extends self.ISpriteInstance {},
	Pepper: class extends self.ISpriteInstance {},
	Potato: class extends self.ISpriteInstance {},
	Broccoli: class extends self.ISpriteInstance {},
	Cauliflower: class extends self.ISpriteInstance {},
	Lettuce: class extends self.ISpriteInstance {},
	Sweetcorn: class extends self.ISpriteInstance {},
	Pumpkin: class extends self.ISpriteInstance {},
	Beetroot: class extends self.ISpriteInstance {},
	Chili_Pepper: class extends self.ISpriteInstance {},
	Garlic: class extends self.ISpriteInstance {},
	Parsnip: class extends self.ISpriteInstance {},
	Blackberry: class extends self.ISpriteInstance {},
	Conveyer_Center: class extends self.ISpriteInstance {},
	Conveyer_Right: class extends self.ISpriteInstance {},
	Loader: class extends self.ISpriteInstance {},
	Loader_Light: class extends self.ISpriteInstance {},
	Traffic_Light: class extends self.ISpriteInstance {},
	Crane_Gantry: class extends self.ISpriteInstance {},
	Loader_Switch: class extends self.ISpriteInstance {},
	Stop_Sign: class extends self.ISpriteInstance {},
	Barricade: class extends self.ISpriteInstance {},
	Watchtower: class extends self.ISpriteInstance {},
	Farm_Background: class extends self.ITiledBackgroundInstance {},
	Farm_Object_Center: class extends self.ISpriteInstance {},
	Farm_Object_Left: class extends self.ISpriteInstance {},
	Farm_Object_Right: class extends self.ISpriteInstance {},
	Farm_Sky: class extends self.ITiledBackgroundInstance {},
	Sun: class extends self.ISpriteInstance {},
	TXT_Description: class extends self.ITextInstance {},
	TXT_GameDescription: class extends self.ITextInstance {},
	TXT_TractorMania: class extends self.ITextInstance {},
	TXT_Garage: class extends self.ITextInstance {},
	TXT_Trailer: class extends self.ITextInstance {},
	TXT_Tractor: class extends self.ITextInstance {},
	TXT_Engine: class extends self.ITextInstance {},
	TXT_Gearbox: class extends self.ITextInstance {},
	TXT_Tires: class extends self.ITextInstance {},
	TXT_Boost: class extends self.ITextInstance {},
	TXT_Fuel: class extends self.ITextInstance {},
	TXT_levels: class extends self.ITextInstance {},
	TXT_Reach: class extends self.ITextInstance {},
	TXT_LVl: class extends self.ITextInstance {},
	TXT_Paused: class extends self.ITextInstance {},
	TXT_Instruction: class extends self.ITextInstance {},
	TXT_OutOfFuel: class extends self.ITextInstance {},
	TXT_TapToPlay: class extends self.ITextInstance {},
	TXT_LevelFailed: class extends self.ITextInstance {},
	TXT_OutOfFuel2: class extends self.ITextInstance {},
	TXT_TimeOver: class extends self.ITextInstance {},
	TXT_ProductNotDelivered: class extends self.ITextInstance {},
	TXT_Suffered: class extends self.ITextInstance {},
	TXT_LevelCompleted: class extends self.ITextInstance {},
	TXT_YouWon: class extends self.ITextInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Texts: class extends self.ISpriteInstance {},
	Tractor: class extends self.ISpriteInstance {},
	Road: class extends self.ISpriteInstance {},
	Trailer: class extends self.ISpriteInstance {},
	Objects: class extends self.ISpriteInstance {},
	Products: class extends self.ISpriteInstance {},
	Driver: class extends self.ISpriteInstance {},
	Trees: class extends self.ISpriteInstance {},
	Bushes: class extends self.ISpriteInstance {},
	Buildings: class extends self.ISpriteInstance {},
	Field: class extends self.ISpriteInstance {},
	Bridge: class extends self.ISpriteInstance {},
	BG: class extends self.ITiledBackgroundInstance {}
}