const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Behaviors.Fade,
		C3.Behaviors.Physics,
		C3.Behaviors.Flash,
		C3.Behaviors.MoveTo,
		C3.Plugins.TiledBg,
		C3.Behaviors.scrollto,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.Focus,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Acts.PauseAllTweens,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Sin.Exps.Value,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Behaviors.Rotate.Cnds.IsEnabled,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Rotate.Exps.Speed,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Exps.projectversion,
		C3.JavaScriptInEvents.Splashes_Event1_Act4,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsPreview,
		C3.JavaScriptInEvents.Mainsplashes_Event2_Act2,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.PlatformInfo.Cnds.IsOnMacOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnLinux,
		C3.Plugins.PlatformInfo.Cnds.IsOnChromeOS,
		C3.Behaviors.Flash.Acts.Flash,
		C3.JavaScriptInEvents.Gamesnacks_es_Event6_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event8_Act4,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.JavaScriptInEvents.Gamesnacks_es_Event38_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event39_Act2,
		C3.JavaScriptInEvents.Gamesnacks_es_Event40_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event48_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event49_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event50_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event51_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event52_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event53_Act1,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.JavaScriptInEvents.Gamesnacks_es_Event56_Act2,
		C3.JavaScriptInEvents.Gamesnacks_es_Event59_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event61_Act1,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.JavaScriptInEvents.Gamesnacks_es_Event64_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event65_Act1,
		C3.JavaScriptInEvents.Gamesnacks_es_Event68_Act1,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Exps.viewporttop
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{PlatformInfo: 0},
	{Browser: 0},
	{Touch: 0},
	{Audio: 0},
	{PlayButton: 0},
	{FullscreenButton: 0},
	{HomeButton: 0},
	{SoundButton: 0},
	{Sine: 0},
	{RetryLevelButton: 0},
	{rvIcon: 0},
	{isOpen: 0},
	{Tween: 0},
	{SideMenuBG: 0},
	{Fade: 0},
	{sideMenuButton: 0},
	{SM_FullscreenButton: 0},
	{SM_HomeButton: 0},
	{SM_SoundButton: 0},
	{PopUpBG: 0},
	{tweenToSizeX: 0},
	{tweenToSizeY: 0},
	{Logo: 0},
	{BlackScreen: 0},
	{BrandImage: 0},
	{Physics: 0},
	{Ground: 0},
	{Flash: 0},
	{PlayerBall: 0},
	{Colors: 0},
	{ChangeColor: 0},
	{RotationSpeed: 0},
	{Shape1: 0},
	{Color: 0},
	{Collider: 0},
	{Shape2: 0},
	{Shape3: 0},
	{MoveTo: 0},
	{Shape4: 0},
	{TiledBackground: 0},
	{ScrollTo: 0},
	{Cam: 0},
	{ShapeSpawner3: 0},
	{ShapeSpawner1: 0},
	{ShapeSpawner2: 0},
	{DistanceFromGround: 0},
	{ShapeSpawnerCollider: 0},
	{ShapeSpawner5: 0},
	{Shape5: 0},
	{ShapeSpawner6: 0},
	{ShapeSpawner7: 0},
	{ShapeSpawner8: 0},
	{Particles: 0},
	{DestroyedBall: 0},
	{Wall: 0},
	{PlayerBall2: 0},
	{Rotate: 0},
	{ColorJump: 0},
	{ContinueButton: 0},
	{FADE: 0},
	{Fade2: 0},
	{ScoreTXT: 0},
	{BestScoreTXT: 0},
	{Sprite2: 0},
	{Label: 0},
	{start: 0},
	{Star: 0},
	{Particles2: 0},
	{Point: 0},
	{ResumeButton: 0},
	{PauseTXT: 0},
	{ShapeSpawner4: 0},
	{AddScoreTXT: 0},
	{DeathCollider: 0},
	{ShapeSpawner9: 0},
	{Shape6: 0},
	{ShapeSpawner10: 0},
	{ShapeSpawner11: 0},
	{Shape7: 0},
	{ShapeSpawner12: 0},
	{ShapeSpawner13: 0},
	{Shape8: 0},
	{Shape9: 0},
	{Shape10: 0},
	{Shape11: 0},
	{ShapeSpawner14: 0},
	{ShapeSpawner15: 0},
	{ShapeSpawner16: 0},
	{DestroyerOfAll: 0},
	{Star2: 0},
	{Sprite: 0},
	{HighScoreLine: 0},
	{HighScoreLineTXT: 0},
	{UI_Anchor: 0},
	{Anchor: 0},
	{bg: 0},
	{GlobalButtons: 0},
	{FullScreenButtons: 0},
	{HomeButtons: 0},
	{SoundButtons: 0},
	{Shapes: 0},
	{ShapeSpawner: 0},
	{PopUp: 0},
	{FAnchors: 0},
	{ShapeChooser: 0},
	{LastSpawnerY: 0},
	{Score: 0},
	{HighScore: 0},
	{GamePaused: 0},
	{UsedContinue: 0},
	{DeathYPosition: 0},
	{Gravity: 0},
	{PlayerHighestY: 0},
	{StarsCreated: 0},
	{HighScoreLineCreated: 0},
	{OriginalHighScore: 0},
	{LastColor: 0},
	{JumpStrengh: 0},
	{CurrentColor: 0},
	{RotationSpeedAdder: 0},
	{SOUND_ON: 0},
	{SFX_Type: 0},
	{IsFullScreenAllowed: 0},
	{IsAdsAllowed: 0},
	{GoogleAd_timeLimit: 0},
	{IsBranded: 0},
	{BrandUrl: 0},
	{Local_id: 0},
	{FirstTime: 0},
	{gameSnacksAudioAllowed: 0},
	{mobile: 0},
	{RV_type: 0},
	{first_set: 0},
	{ADS: 0},
	{RV_ready: 0},
	{RV_play: 0},
	{RV_create_attempts: 0},
	{Interstitial_Type: 0},
	{DidUseRv: 0},
	{rvAttempts: 0},
	{CanAds: 0},
	{IsDone: 0},
	{Type: 0},
	{type: 0},
	{name: 0},
	{masterSound: 0},
	{mute: 0},
	{LastSent: 0},
	{save_score: 0},
	{return: 0},
	{item: 0},
	{value: 0},
	{clickable: 0},
	{destroy_fullscreen: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	FullscreenButton: class extends self.ISpriteInstance {},
	HomeButton: class extends self.ISpriteInstance {},
	SoundButton: class extends self.ISpriteInstance {},
	RetryLevelButton: class extends self.ISpriteInstance {},
	rvIcon: class extends self.ISpriteInstance {},
	SideMenuBG: class extends self.ISpriteInstance {},
	sideMenuButton: class extends self.ISpriteInstance {},
	SM_FullscreenButton: class extends self.ISpriteInstance {},
	SM_HomeButton: class extends self.ISpriteInstance {},
	SM_SoundButton: class extends self.ISpriteInstance {},
	PopUpBG: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	BlackScreen: class extends self.ISpriteInstance {},
	BrandImage: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	PlayerBall: class extends self.ISpriteInstance {},
	ChangeColor: class extends self.ISpriteInstance {},
	Shape1: class extends self.ISpriteInstance {},
	Collider: class extends self.ISpriteInstance {},
	Shape2: class extends self.ISpriteInstance {},
	Shape3: class extends self.ISpriteInstance {},
	Shape4: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Cam: class extends self.ISpriteInstance {},
	ShapeSpawner3: class extends self.ISpriteInstance {},
	ShapeSpawner1: class extends self.ISpriteInstance {},
	ShapeSpawner2: class extends self.ISpriteInstance {},
	DistanceFromGround: class extends self.ITextInstance {},
	ShapeSpawnerCollider: class extends self.ISpriteInstance {},
	ShapeSpawner5: class extends self.ISpriteInstance {},
	Shape5: class extends self.ISpriteInstance {},
	ShapeSpawner6: class extends self.ISpriteInstance {},
	ShapeSpawner7: class extends self.ISpriteInstance {},
	ShapeSpawner8: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	DestroyedBall: class extends self.ISpriteInstance {},
	Wall: class extends self.ISpriteInstance {},
	PlayerBall2: class extends self.ISpriteInstance {},
	ColorJump: class extends self.ISpriteInstance {},
	ContinueButton: class extends self.ISpriteInstance {},
	ScoreTXT: class extends self.ITextInstance {},
	BestScoreTXT: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Label: class extends self.ITextInstance {},
	Star: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Point: class extends self.ISpriteInstance {},
	ResumeButton: class extends self.ISpriteInstance {},
	PauseTXT: class extends self.ITextInstance {},
	ShapeSpawner4: class extends self.ISpriteInstance {},
	AddScoreTXT: class extends self.ITextInstance {},
	DeathCollider: class extends self.ISpriteInstance {},
	ShapeSpawner9: class extends self.ISpriteInstance {},
	Shape6: class extends self.ISpriteInstance {},
	ShapeSpawner10: class extends self.ISpriteInstance {},
	ShapeSpawner11: class extends self.ISpriteInstance {},
	Shape7: class extends self.ISpriteInstance {},
	ShapeSpawner12: class extends self.ISpriteInstance {},
	ShapeSpawner13: class extends self.ISpriteInstance {},
	Shape8: class extends self.ISpriteInstance {},
	Shape9: class extends self.ISpriteInstance {},
	Shape10: class extends self.ISpriteInstance {},
	Shape11: class extends self.ISpriteInstance {},
	ShapeSpawner14: class extends self.ISpriteInstance {},
	ShapeSpawner15: class extends self.ISpriteInstance {},
	ShapeSpawner16: class extends self.ISpriteInstance {},
	DestroyerOfAll: class extends self.ISpriteInstance {},
	Star2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	HighScoreLine: class extends self.ITiledBackgroundInstance {},
	HighScoreLineTXT: class extends self.ITextInstance {},
	UI_Anchor: class extends self.ISpriteInstance {},
	Anchor: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	GlobalButtons: class extends self.ISpriteInstance {},
	FullScreenButtons: class extends self.ISpriteInstance {},
	HomeButtons: class extends self.ISpriteInstance {},
	SoundButtons: class extends self.ISpriteInstance {},
	Shapes: class extends self.ISpriteInstance {},
	ShapeSpawner: class extends self.ISpriteInstance {},
	PopUp: class extends self.ISpriteInstance {},
	FAnchors: class extends self.ISpriteInstance {}
}