var g = g || {};

g = {
    savedatalevelscompleted: 'ThrulineDataLevelsCompleted',
    savedatalevelprogress: 'ThrulineDataLevelProgress', // the progress of current level
    testingGameSnacks: true, // set to TRUE to enable GameSnacks testing
    mute: false,
    mutemusic: false,
    mutesfx: false,
    pauseandmute: true,
    drawhitzone: false,
    foxaniscaleratio: 1,
    makeshowlogbutton: true,
    onlyshowlogforlocaltesting: true,
    defaultframerate: 60,
    hitmapscale: 0.125, // hitmap scale for pixel-perfect hitTest
    autoplay: false,
    inputenabled: true,
    buttonmargin: 60,
    log: '',
    talking: null,
    scene: null,
    scenename: null,
    pausescr: null,
    continuescr: null,
    transitioning: false,
    ticker: null,
    ticker2: null,
    pressing: false,
    tapping: false,
    gamestart: false,
    startpresstime: null,
    startpressx: null,
    startpressy: null,
    mousex: null,
    mousey: null,
    showFPStext: null,
    delayactions: {},
    repeatactions: {},
    SATpolydrawings: {},
    delayactionID: 0,
    repeatactionID: 0,
    gameframenow: 0,
    sfxvolume: 1,
    easing: PIXI.tween.Easing,
    ismobile: false,
    isphone: false,
    istablet: false,
    localtesting: false,
    rainbowcolors: [0xFFFFFF,0xFFFF00,0xFFCC00,0xFF9900,0xFF6600,0xFF3300,0xCCCC00,0x99CC00,0x66CC00,0x33CC00,0x72FD35],
    foxclip: {},
    foxani: {},
    foxpic: {},
    // fonts
    fonts: ['neu','neubold','avenir'],
    titlefont: 'neubold',
    titlefillcolor: '#03AF2F',
    titlestrokecolor: '#FFFFFF',
    copyfont: 'neu',
    copyfillcolor: '#FFFFFF',
    copystrokecolor: '#000000',
    altcolor1: '#1F1F20', // color-gray-darkest
    altcolor2: '#66FF00',
    altcolor3: '#FF6600',
    // atlas
    atlasnames: ['foxpic','foxani','foxclip','foxbg','foxjpg'],
    foxpic_atlas: ['foxpic'],
    foxbg_atlas: [],
    foxjpg_atlas: [],
    foxclip_atlas: [],
    foxani_atlas: [],
    // non-looping foxanimation
    nonloopingfoxani: [],
    // non-looping foxclip (Pixi.AnimatedSprite)
    nonloopingfoxclip: [],
    // foxclip anchors
    foxclip_anchors: {},
    // audioO
    audiosfx: [], // use this to load audio files manually instead of using z_audio.js
    // bitmap fonts
    bitmapfonts: [],
    foxuniqueID: 1000000,
    foxcliparrays: {},
    foxclipframecount: {},
    randomlisting: {},
    foxfloating: {},
    foxpool: {},
    allspawned: [],
    activeitems: [],
    particles: [],
    sfx: {},
    bgmusicname: '',
    fontsloadedcount: 0,
    ratio: 2,
    gameresolution: 1,
    textresolution: 1,
    highscore: 0,
    locallysavedhighscore: 0,
    udatutorial: false,
    playgame: true,
    // vars
    levelscompleted: 0,
    levelnow: 1,
    levelwords: null,
    columns: null,
    answer: null,
    middlerow: null,
    stage: 1,
    stageanswerfiller: ['THRULINE','THRULINE','THRULINE','THRULINE','THRULINE','THRULINE','THRULINE'],
    stagetimecompletion: [],
    color_green: 0x03AF2F,
    color_red: 0xE03927,
    color_yellow: 0xECBE0B,
    color_timer_yellow: 0xDBAA22,
    color_timer_red: 0xAF1D03,
    force_levelwords: null,
    gamemode: 2,
    totaltime: 0,
    totalstageswon: 0,
    timeleft: 0,
    continuetimeleft: 0,
    stageboxspacing: 70,
    timeractionID: null,
    stagestatus: null,
    ingamepaused: false,
    // width we use to make bottom bar & word background box
    maxbgwid: 2800,
    bottombarhei: 100,
    complimented: false,
    encouraged: false,
    textforclipboard : '',
    clickongame: false,
    configURL: 'json/config.json?'+Date.now(),
    // AMU
    skipAMU: false,
    // AMU default state and data
    AMUdefaultState: {
        snapshot: {
            level: 0,
            stageanswer:[],
            stagetimecompletion:[],
            timeleft:0,
        },
        isCompleted: false,
        madeMistakes: false,
        earnedPerfectScore: false,
        resetLevel: false,
        clearedBoard: false,
        totalPlayTime: 0,
        wordsSolved: 0,
        orderSolved: [],
    },
    // AMU default settings
    AMUdefaultSettings: {
        snapshot: {
            sound: true,
        },
    },
    AMUonEvent: [],
};