const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.lgshake,
		C3.Plugins.Arr,
		C3.Plugins.Dictionary,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.AJAX,
		C3.Plugins.Browser,
		C3.Plugins.BHT_Smart_Random,
		C3.Plugins.Keyboard,
		C3.Plugins.PlatformInfo,
		C3.Plugins.LocalStorage,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.NinePatch,
		C3.Plugins.Spritefont2,
		C3.Plugins.Touch,
		C3.Plugins.Timeline,
		C3.Behaviors.Rex_MoveTo,
		C3.Plugins.Audio,
		C3.Plugins.Cache_Client_Error,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnMacOS,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.ScriptsInEvents.Emain_Event4_Act1,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Text.Cnds.PickParent,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Text.Cnds.OnTypewriterTextFinished,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Timeline.Acts.SetInstance,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Particles.Cnds.OnDestroyed,
		C3.ScriptsInEvents.Emain_Event113_Act4,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.ScriptsInEvents.Emain_Event153_Act6,
		C3.ScriptsInEvents.Emain_Event153_Act12,
		C3.ScriptsInEvents.Emain_Event153_Act22,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.ScriptsInEvents.Emain_Event157_Act1,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.ScriptsInEvents.Emain_Event160_Act7,
		C3.ScriptsInEvents.Emain_Event160_Act11,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.ScriptsInEvents.Emain_Event170_Act4,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.ScriptsInEvents.Emain_Event174_Act1,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.BHT_Smart_Random.Exps.Next,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Arr.Exps.Width,
		C3.ScriptsInEvents.Emain_Event206_Act4,
		C3.ScriptsInEvents.Emain_Event211_Act1,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.ScriptsInEvents.Emain_Event216_Act1,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.Destroy,
		C3.ScriptsInEvents.Emain_Event313_Act4,
		C3.ScriptsInEvents.Emain_Event316_Act4,
		C3.ScriptsInEvents.Emain_Event319_Act4,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.ScriptsInEvents.Emain_Event372_Act1,
		C3.ScriptsInEvents.Emain_Event373_Act1,
		C3.ScriptsInEvents.Emain_Event380_Act2,
		C3.ScriptsInEvents.Emain_Event387_Act2,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.TiledBg.Acts.MoveToLayer,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.lgshake.Acts.Shake,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.ScriptsInEvents.Emain_Event511_Act1,
		C3.ScriptsInEvents.Emain_Event512_Act1,
		C3.ScriptsInEvents.Emain_Event514_Act1,
		C3.ScriptsInEvents.Emain_Event514_Act5,
		C3.ScriptsInEvents.Emain_Event516_Act1,
		C3.ScriptsInEvents.Emain_Event517_Act1,
		C3.ScriptsInEvents.Emain_Event518_Act1,
		C3.ScriptsInEvents.Emain_Event519_Act1,
		C3.ScriptsInEvents.Emain_Event519_Act4,
		C3.ScriptsInEvents.Emain_Event519_Act8,
		C3.ScriptsInEvents.Emain_Event520_Act1,
		C3.ScriptsInEvents.Emain_Event521_Act1,
		C3.ScriptsInEvents.Emain_Event521_Act2,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Behaviors.Tween.Exps.Value,
		C3.ScriptsInEvents.Esplash_Event11_Act1,
		C3.ScriptsInEvents.Esplash_Event11_Act4,
		C3.ScriptsInEvents.Esplash_Event11_Act5,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.System.Exps.lowercase,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.BHT_Smart_Random.Acts.New,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Text.Acts.TypewriterFinish,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetLineHeight,
		C3.Plugins.Timeline.Cnds.OnTimelineFinishedByTags,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Text.Exps.PlainText,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Browser.Exps.Referrer,
		C3.Plugins.Browser.Exps.Domain,
		C3.ScriptsInEvents.Sitelock_Event3_Act8,
		C3.ScriptsInEvents.Sitelock_Event7_Act8,
		C3.ScriptsInEvents.Elogo_Event1_Act1,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.ScriptsInEvents.Elogo_Event2_Act4,
		C3.Plugins.Text.Cnds.IsOnScreen,
		C3.Plugins.System.Exps.loadingprogress,
		C3.ScriptsInEvents.Elogo_Event5_Act1
	];
};
self.C3_JsPropNameTable = [
	{row: 0},
	{col: 0},
	{letter: 0},
	{pos: 0},
	{myX: 0},
	{destroy: 0},
	{lg_Shake: 0},
	{grid: 0},
	{alphabet: 0},
	{used: 0},
	{green: 0},
	{yellow: 0},
	{inWord: 0},
	{key: 0},
	{found: 0},
	{hint_grid: 0},
	{key_holder: 0},
	{array_easy: 0},
	{array_hard: 0},
	{array_medium: 0},
	{array_correct_words: 0},
	{array_level: 0},
	{Dictionary: 0},
	{array_saveGame: 0},
	{colors: 0},
	{canTouch: 0},
	{soundoff: 0},
	{home: 0},
	{type: 0},
	{features: 0},
	{info: 0},
	{scoreBG: 0},
	{skip: 0},
	{ok: 0},
	{Rotate: 0},
	{particles: 0},
	{star: 0},
	{ScrollTo: 0},
	{camera: 0},
	{bgPattern: 0},
	{color: 0},
	{Tween: 0},
	{bg: 0},
	{dimmer: 0},
	{play: 0},
	{shine: 0},
	{shine_ray: 0},
	{guess: 0},
	{word: 0},
	{ceiling: 0},
	{pathway: 0},
	{myY: 0},
	{time: 0},
	{flat_letters: 0},
	{orange_box: 0},
	{purple_box: 0},
	{rays: 0},
	{AJAX: 0},
	{Browser: 0},
	{randomWords: 0},
	{sRandomDart: 0},
	{Keyboard: 0},
	{PlatformInfo: 0},
	{LocalStorage: 0},
	{rShineReward: 0},
	{sRandomReward: 0},
	{sRandomBgColor: 0},
	{tut_popBoard: 0},
	{tut_boardTxt: 0},
	{tut_board: 0},
	{tut_popBoardTxt: 0},
	{tutorialtext: 0},
	{rulesBoard: 0},
	{find_result: 0},
	{GREEN: 0},
	{grids: 0},
	{show_word: 0},
	{YELLOW: 0},
	{debugText: 0},
	{debug_green: 0},
	{debug_greenYellow: 0},
	{debug_yellow: 0},
	{"9patch": 0},
	{debug_notMatching: 0},
	{scoreboard: 0},
	{revealed: 0},
	{taptoreveal: 0},
	{TheWordWas: 0},
	{game: 0},
	{over: 0},
	{playAgain: 0},
	{shining: 0},
	{rewardstext: 0},
	{rewards_rays: 0},
	{reward_icon: 0},
	{playtutorial: 0},
	{crossButton: 0},
	{claim: 0},
	{score: 0},
	{debug_Text: 0},
	{feature_text: 0},
	{scoreSTATUS: 0},
	{reveal_Text: 0},
	{hint_txt: 0},
	{grid_txt: 0},
	{keys_txt: 0},
	{adboard: 0},
	{msg: 0},
	{no: 0},
	{yes: 0},
	{Touch: 0},
	{TimelineController: 0},
	{rotate: 0},
	{hand: 0},
	{glow: 0},
	{done: 0},
	{MoveTo: 0},
	{cpl_conf: 0},
	{confetti: 0},
	{Audio: 0},
	{hand2: 0},
	{level_txt: 0},
	{fxlogo: 0},
	{bar: 0},
	{loadingtext: 0},
	{camm: 0},
	{Textlicense: 0},
	{Client_Error: 0},
	{adicon: 0},
	{flying_boxes: 0},
	{ui_buttons: 0},
	{TWEEN_SPRITE: 0},
	{TWEEN_TXT: 0},
	{disable: 0},
	{all_images: 0},
	{EASY: 0},
	{current_word: 0},
	{word_index: 0},
	{skip_limit: 0},
	{hint_limit: 0},
	{starting_msg_shown: 0},
	{dart_limit: 0},
	{ROWS: 0},
	{SIZE: 0},
	{MARGIN: 0},
	{key_presed: 0},
	{key_combo: 0},
	{matching_letters: 0},
	{current_col: 0},
	{current_row: 0},
	{STEP: 0},
	{game_status: 0},
	{REWARD_DART: 0},
	{REWARD_HINT: 0},
	{REWARD_SKIP: 0},
	{NEXT: 0},
	{PLAY_AGAIN: 0},
	{overshoot: 0},
	{f1: 0},
	{f2: 0},
	{f3: 0},
	{s35: 0},
	{f4: 0},
	{f0: 0},
	{overError: 0},
	{temp_score: 0},
	{i: 0},
	{Parameter0: 0},
	{level: 0},
	{waiting: 0},
	{duration: 0},
	{status: 0},
	{match: 0},
	{a: 0},
	{b: 0},
	{currentLetter: 0},
	{unused_letter: 0},
	{hint: 0},
	{SKIP_WORD: 0},
	{WATCH_AD_TO_REVEAL: 0},
	{WATCH_AD_TO_SKIP: 0},
	{WATCH_AD_FOR_DART: 0},
	{WATCH_AD_FOR_HINT: 0},
	{QUIT_GAME: 0},
	{SKIP_TUTORIAL: 0},
	{RewardAvail: 0},
	{ad_reward_is: 0},
	{checkover: 0},
	{msg_type: 0},
	{KEY_DEFAULT: 0},
	{KEY_GRAY: 0},
	{KEY_YELLOW: 0},
	{KEY_GREEN: 0},
	{KEY_BACK: 0},
	{KEY_SUBMIT_GRAY: 0},
	{KEY_SUBMIT_GREEN: 0},
	{KEY_NOT_A_WORD: 0},
	{EMPTY_BOX: 0},
	{GRAY_TILES: 0},
	{YELLOW_TILES: 0},
	{GREEN_TILES: 0},
	{onGameOver: 0},
	{SAVE_DART: 0},
	{SAVE_HINT: 0},
	{SAVE_SKIP: 0},
	{SAVE_KEYBOARD: 0},
	{SAVE_HINT_KEYS: 0},
	{SAVE_GRID_LETTERS: 0},
	{SAVE_CURRENT_WORD: 0},
	{SAVE_CURRENT_ROW: 0},
	{SAVE_UNUSED_LETTERS: 0},
	{SAVE_SCORE: 0},
	{SAVE_HISCORE: 0},
	{SAVE_TUTORIAL_STATUS: 0},
	{SAVE_GAME_STATUS: 0},
	{SAVE_WORD_INDEX: 0},
	{SAVE_STARTING_MSG: 0},
	{SAVE_LEVELS: 0},
	{SAVE_DIFFICULTY: 0},
	{SAVE_COUNT_WORDS: 0},
	{keyBoard: 0},
	{used_hints: 0},
	{found_hints: 0},
	{grids_letters: 0},
	{sound: 0},
	{DART: 0},
	{DART_AD: 0},
	{DART_GRAY: 0},
	{HINT: 0},
	{HINT_AD: 0},
	{HINT_GRAY: 0},
	{SKIP: 0},
	{SKIP_AD: 0},
	{SKIP_GRAY: 0},
	{MUTE: 0},
	{UNMUTE: 0},
	{timer: 0},
	{TIME_LIMIT: 0},
	{checkstart: 0},
	{s1: 0},
	{s2: 0},
	{s3: 0},
	{hi_score: 0},
	{allover: 0},
	{st: 0},
	{sc: 0},
	{val: 0},
	{value: 0},
	{soundextra: 0},
	{tutorial: 0},
	{unFinished_available: 0},
	{lastLetter: 0},
	{pickedWord: 0},
	{checkarray: 0},
	{load: 0},
	{itemName: 0},
	{itemData: 0},
	{count_words: 0},
	{difficulty: 0},
	{gameError: 0},
	{ADDITIONALl_TEXT_WAIT: 0},
	{TEXT_DURATION: 0},
	{WAIT_TIME: 0},
	{tut_FSM: 0},
	{gray_tut_shown: 0},
	{yellow_tut_shown: 0},
	{green_tut_shown: 0},
	{found_letters: 0},
	{features_shown: 0},
	{board_tween_time: 0},
	{onRow: 0},
	{count_shown_features: 0},
	{message: 0},
	{show_tutorials_of: 0},
	{temp_msg: 0},
	{showing_hand: 0},
	{FOR_TIME: 0},
	{frame: 0},
	{current_tut_color: 0},
	{index: 0},
	{default: 0},
	{offsetY: 0},
	{AllOk: 0},
	{FsLock: 0},
	{loadDomain: 0},
	{whiteURL2: 0},
	{A: 0},
	{B: 0},
	{C: 0},
	{D: 0},
	{D2: 0},
	{D3: 0},
	{E: 0},
	{E2: 0},
	{E3: 0},
	{E4: 0},
	{E5: 0},
	{E6: 0},
	{F: 0},
	{Check: 0},
	{cmplg: 0},
	{loadError: 0}
];

self.InstanceType = {
	grid: class extends self.ISpriteInstance {},
	key: class extends self.ISpriteInstance {},
	hint_grid: class extends self.ISpriteInstance {},
	key_holder: class extends self.ISpriteInstance {},
	array_easy: class extends self.IArrayInstance {},
	array_hard: class extends self.IArrayInstance {},
	array_medium: class extends self.IArrayInstance {},
	array_correct_words: class extends self.IArrayInstance {},
	array_level: class extends self.IArrayInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	array_saveGame: class extends self.IArrayInstance {},
	colors: class extends self.IDictionaryInstance {},
	soundoff: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	features: class extends self.ISpriteInstance {},
	info: class extends self.ISpriteInstance {},
	scoreBG: class extends self.ISpriteInstance {},
	skip: class extends self.ISpriteInstance {},
	ok: class extends self.ISpriteInstance {},
	particles: class extends self.IParticlesInstance {},
	star: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	bgPattern: class extends self.ITiledBackgroundInstance {},
	bg: class extends self.ITiledBackgroundInstance {},
	dimmer: class extends self.ITiledBackgroundInstance {},
	play: class extends self.ISpriteInstance {},
	shine: class extends self.ISpriteInstance {},
	shine_ray: class extends self.ISpriteInstance {},
	guess: class extends self.ISpriteInstance {},
	word: class extends self.ISpriteInstance {},
	ceiling: class extends self.ISpriteInstance {},
	pathway: class extends self.ISpriteInstance {},
	flat_letters: class extends self.ISpriteInstance {},
	orange_box: class extends self.ISpriteInstance {},
	purple_box: class extends self.ISpriteInstance {},
	rays: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	randomWords: class extends self.IInstance {},
	sRandomDart: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	rShineReward: class extends self.IInstance {},
	sRandomReward: class extends self.IInstance {},
	sRandomBgColor: class extends self.IInstance {},
	tut_popBoard: class extends self.ISpriteInstance {},
	tut_boardTxt: class extends self.ITextInstance {},
	tut_board: class extends self.ISpriteInstance {},
	tut_popBoardTxt: class extends self.ITextInstance {},
	tutorialtext: class extends self.ISpriteInstance {},
	rulesBoard: class extends self.ISpriteInstance {},
	find_result: class extends self.IButtonInstance {},
	GREEN: class extends self.IButtonInstance {},
	grids: class extends self.IButtonInstance {},
	show_word: class extends self.IButtonInstance {},
	YELLOW: class extends self.IButtonInstance {},
	debugText: class extends self.ITextInstance {},
	debug_green: class extends self.IArrayInstance {},
	debug_greenYellow: class extends self.IArrayInstance {},
	debug_yellow: class extends self.IArrayInstance {},
	_9patch: class extends self.IWorldInstance {},
	debug_notMatching: class extends self.IArrayInstance {},
	scoreboard: class extends self.ISpriteInstance {},
	taptoreveal: class extends self.ISpriteInstance {},
	TheWordWas: class extends self.ISpriteInstance {},
	game: class extends self.ISpriteInstance {},
	over: class extends self.ISpriteInstance {},
	playAgain: class extends self.ISpriteInstance {},
	rewardstext: class extends self.ISpriteInstance {},
	rewards_rays: class extends self.ISpriteInstance {},
	reward_icon: class extends self.ISpriteInstance {},
	playtutorial: class extends self.ISpriteInstance {},
	crossButton: class extends self.ISpriteInstance {},
	claim: class extends self.ISpriteInstance {},
	score: class extends self.ISpriteFontInstance {},
	debug_Text: class extends self.ITextInstance {},
	feature_text: class extends self.ITextInstance {},
	scoreSTATUS: class extends self.ITextInstance {},
	reveal_Text: class extends self.ITextInstance {},
	hint_txt: class extends self.ITextInstance {},
	grid_txt: class extends self.ITextInstance {},
	keys_txt: class extends self.ITextInstance {},
	adboard: class extends self.ISpriteInstance {},
	msg: class extends self.ISpriteInstance {},
	no: class extends self.ISpriteInstance {},
	yes: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	TimelineController: class extends self.IInstance {},
	rotate: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	glow: class extends self.ISpriteInstance {},
	done: class extends self.ISpriteInstance {},
	cpl_conf: class extends self.ISpriteInstance {},
	confetti: class extends self.IParticlesInstance {},
	Audio: class extends self.IInstance {},
	hand2: class extends self.ISpriteInstance {},
	level_txt: class extends self.ITextInstance {},
	fxlogo: class extends self.ISpriteInstance {},
	bar: class extends self.ISpriteInstance {},
	loadingtext: class extends self.ITextInstance {},
	camm: class extends self.ISpriteInstance {},
	Textlicense: class extends self.ITextInstance {},
	Client_Error: class extends self.IInstance {},
	adicon: class extends self.ISpriteInstance {},
	flying_boxes: class extends self.ISpriteInstance {},
	ui_buttons: class extends self.ISpriteInstance {},
	TWEEN_SPRITE: class extends self.ISpriteInstance {},
	TWEEN_TXT: class extends self.ITextInstance {},
	disable: class extends self.ISpriteInstance {},
	all_images: class extends self.ISpriteInstance {}
}