const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.LOS,
		C3.Behaviors.EightDir,
		C3.Behaviors.Timer,
		C3.Behaviors.Pin,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.TiledBg,
		C3.Plugins.NinePatch,
		C3.Behaviors.Tween,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Anchor,
		C3.Behaviors.solid,
		C3.Plugins.Tilemap,
		C3.Behaviors.Bullet,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.AJAX,
		C3.Plugins.Dictionary,
		C3.Plugins.Date,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Json,
		C3.Behaviors.Rotate,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.BinaryData,
		C3.Behaviors.destroy,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.LOS.Acts.AddObstacle,
		C3.Behaviors.LOS.Acts.SetRange,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.AdvancedRandom.Acts.SetProbabilityTable,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.AdvancedRandom.Exps.Weighted,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.RotateTowardAngle,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Behaviors.Bullet.Acts.SetAcceleration,
		C3.Plugins.System.Exps.anglelerp,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.Sprite.Cnds.AngleWithin,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Audio.Acts.PlayAtObject,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Particles.Acts.SetOpacity,
		C3.Plugins.Particles.Acts.SetInitSpeed,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Bullet.Cnds.OnStep,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.Tilemap.Exps.SnapX,
		C3.Plugins.Tilemap.Exps.SnapY,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.EightDir.Acts.SetVectorX,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.LOS.Acts.CastRay,
		C3.Behaviors.LOS.Cnds.RayIntersected,
		C3.Behaviors.LOS.Exps.HitX,
		C3.Behaviors.LOS.Exps.HitY,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.TiledBg.Exps.Count,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Exps.roundtodp,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Behaviors.LOS.Exps.Range,
		C3.Behaviors.Bullet.Acts.SetBounceOffSolids,
		C3.Behaviors.EightDir.Exps.Speed,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Acts.SetCharacterSpacing,
		C3.Plugins.Spritefont2.Acts.SetHAlign,
		C3.Plugins.Spritefont2.Acts.SetWidth,
		C3.Plugins.Spritefont2.Exps.TextWidth,
		C3.Plugins.Spritefont2.Acts.SetHeight,
		C3.Plugins.Spritefont2.Exps.TextHeight,
		C3.Behaviors.Tween.Acts.SetEnabled,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Spritefont2.Acts.AppendText,
		C3.Plugins.System.Exps.time,
		C3.Plugins.System.Exps.mid,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.NinePatch.Exps.BBoxLeft,
		C3.Plugins.NinePatch.Exps.BBoxRight,
		C3.Plugins.NinePatch.Exps.BBoxTop,
		C3.Plugins.NinePatch.Exps.BBoxBottom,
		C3.Plugins.Particles.Acts.SetEffectParam,
		C3.Plugins.Particles.Acts.SetInitSize,
		C3.Plugins.Particles.Acts.SetSizeRandomiser,
		C3.Plugins.Particles.Acts.SetGrowRate,
		C3.Plugins.Particles.Acts.SetSpeedRandomiser,
		C3.Plugins.Particles.Acts.SetLifeSpeedRandomiser,
		C3.Plugins.Particles.Acts.SetTimeout,
		C3.Plugins.Particles.Acts.SetSprayCone,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Touch.Exps.TouchCount,
		C3.Plugins.Touch.Exps.XAt,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.YAt,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Cnds.AngleWithin,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Touch.Exps.TouchID,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Behaviors.EightDir.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.Audio.Cnds.AdvancedAudioSupported,
		C3.Plugins.Audio.Acts.SetListenerObject,
		C3.Plugins.Audio.Acts.SetListenerZ,
		C3.Behaviors.EightDir.Exps.MovingAngle,
		C3.Plugins.NinePatch.Cnds.CompareWidth,
		C3.Plugins.NinePatch.Acts.SetEffectParam,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.NinePatch.Exps.LayerName,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.TiledBg.Cnds.IsOnScreen,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Browser.Exps.Language,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.TiledBg.Exps.LayerName,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Dictionary.Cnds.ForEachKey,
		C3.Plugins.AdvancedRandom.Acts.CreateProbabilityTableFromJSON,
		C3.Plugins.Dictionary.Exps.CurrentKey,
		C3.Plugins.Dictionary.Exps.CurrentValue,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Exps.LayerName,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.BinaryData.Acts.SetFromText,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.BinaryData.Acts.Compress,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.BinaryData.Exps.GetBase64,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Arr.Exps.Depth,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.Arr.Acts.Insert,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Spritefont2.Exps.IID,
		C3.Plugins.Spritefont2.Acts.SetAngle,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Rotate.Acts.SetAcceleration,
		C3.Plugins.System.Exps.zeropad,
		C3.Behaviors.Rotate.Exps.Speed,
		C3.Plugins.Spritefont2.Cnds.PickDistance,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.Spritefont2.Acts.SetX,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.IsSuspended,
		C3.Plugins.System.Cnds.OnResume,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Text.Acts.SetHAlign,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.Text.Acts.Destroy,
		C3.JavaScriptInEvents.Esglobal_Event48_Act1,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.JavaScriptInEvents.Esglobal_Event56_Act2,
		C3.JavaScriptInEvents.Esglobal_Event57_Act2,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.JavaScriptInEvents.Esglobal_Event91_Act1,
		C3.JavaScriptInEvents.Esglobal_Event92_Act2,
		C3.JavaScriptInEvents.Esglobal_Event93_Act2,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.JavaScriptInEvents.Esglobal_Event94_Act2,
		C3.JavaScriptInEvents.Esglobal_Event94_Act3,
		C3.JavaScriptInEvents.Esglobal_Event95_Act1,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.BinaryData.Acts.SetFromBase64,
		C3.Plugins.BinaryData.Acts.Decompress,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.BinaryData.Exps.GetAllText,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData
	];
};
self.C3_JsPropNameTable = [
	{weapon: 0},
	{wepname: 0},
	{firerate: 0},
	{damage: 0},
	{shoot: 0},
	{recoil: 0},
	{autoaim: 0},
	{LineOfSight: 0},
	{player_top: 0},
	{health: 0},
	{a: 0},
	{d: 0},
	{overlap: 0},
	{burning: 0},
	{corroded: 0},
	{shield: 0},
	{"8Direction": 0},
	{Timer: 0},
	{player_base: 0},
	{player_shadow: 0},
	{spawn_player: 0},
	{ready: 0},
	{spawn_enemy: 0},
	{tankID: 0},
	{Pin: 0},
	{en_health: 0},
	{en_health_bg: 0},
	{pinned: 0},
	{state: 0},
	{enemy_base: 0},
	{enemy_shadow: 0},
	{startX: 0},
	{startY: 0},
	{targetX: 0},
	{targetY: 0},
	{enemy_top: 0},
	{aidID: 0},
	{aid_icon: 0},
	{enemyID: 0},
	{en_icon: 0},
	{radar: 0},
	{player_crush: 0},
	{Fade: 0},
	{gunfire_all: 0},
	{hit_shell: 0},
	{part_en_smoke: 0},
	{part_rocket: 0},
	{ScrollTo: 0},
	{camera: 0},
	{phaserfire: 0},
	{hit_simple: 0},
	{pl_shock_hit: 0},
	{part_pl_smoke: 0},
	{debris_block: 0},
	{debris_explosive: 0},
	{fow_view: 0},
	{bang: 0},
	{enemy_crush: 0},
	{hit_bang: 0},
	{hit_phaser: 0},
	{hit_flame: 0},
	{part_bang: 0},
	{harmful: 0},
	{fire: 0},
	{corrosion: 0},
	{bang_light: 0},
	{part_corrosion: 0},
	{debris_corrosion: 0},
	{debris_aidcrate: 0},
	{debris_crate: 0},
	{part_pl_burn: 0},
	{part_en_burn: 0},
	{part_pl_corr: 0},
	{part_en_corr: 0},
	{flashing: 0},
	{Flash: 0},
	{emit: 0},
	{em_fire: 0},
	{emitterID: 0},
	{em_beam: 0},
	{pl_shock_light: 0},
	{en_shock_light: 0},
	{en_shock_hit: 0},
	{hit_flash: 0},
	{shooter: 0},
	{bullet: 0},
	{targetUID: 0},
	{follow: 0},
	{bul_rocket: 0},
	{lastX: 0},
	{lastY: 0},
	{bul_phaser: 0},
	{Tween: 0},
	{bul_phaser_trail: 0},
	{bul_flame: 0},
	{bul_gren: 0},
	{mine: 0},
	{topID: 0},
	{en_shock: 0},
	{pl_shock: 0},
	{btn_fscrn: 0},
	{level: 0},
	{btn_level: 0},
	{btn_fight: 0},
	{logo: 0},
	{Anchor: 0},
	{scorefont: 0},
	{popupUpgrades: 0},
	{aim: 0},
	{price: 0},
	{ammo: 0},
	{price_ammo: 0},
	{intensity: 0},
	{btn_upg_wep: 0},
	{ico_tank: 0},
	{scorelabel: 0},
	{pop_close: 0},
	{left: 0},
	{btn_gunswitch: 0},
	{btn_add_lvl: 0},
	{btn_add_ammo: 0},
	{ind_lvl: 0},
	{loader_bar: 0},
	{btn_any: 0},
	{upgrade: 0},
	{btn_upg_tank: 0},
	{color: 0},
	{content: 0},
	{effect: 0},
	{font_10px: 0},
	{prize: 0},
	{font_7px: 0},
	{part_ui: 0},
	{player_hp: 0},
	{player_hp_bg: 0},
	{ind_lvl2: 0},
	{level_bar_bg: 0},
	{level_bar: 0},
	{ammo_bar: 0},
	{ammo_bar_bg: 0},
	{loader_bg: 0},
	{loader_icon: 0},
	{font_10x16px: 0},
	{ico_ammo: 0},
	{btn_confirm: 0},
	{btn_play: 0},
	{help_desktop: 0},
	{btn_lvl_end: 0},
	{popupStats: 0},
	{btn_shop: 0},
	{pop_stats_line: 0},
	{level_group: 0},
	{btn_next_prev: 0},
	{btn_switcher: 0},
	{dist: 0},
	{ang: 0},
	{tmbstickbase: 0},
	{TouchID: 0},
	{tmbstick: 0},
	{shop_item: 0},
	{shopitem: 0},
	{shop_buy_btn: 0},
	{coin_sparks: 0},
	{btn_pause: 0},
	{btn_lang: 0},
	{btn_spin: 0},
	{part_coins: 0},
	{pop_lang: 0},
	{shop_item_bg: 0},
	{"9lives_logo": 0},
	{loader_spinner: 0},
	{icon_warn: 0},
	{part_wheel: 0},
	{rotate: 0},
	{home_btn: 0},
	{popupUpgrades2: 0},
	{btn_gunshot: 0},
	{bg_cammo: 0},
	{bg_fade: 0},
	{bg_loader: 0},
	{ui_wep_bg: 0},
	{resist: 0},
	{resistMax: 0},
	{Solid: 0},
	{block_fragile: 0},
	{blockID: 0},
	{block_flash: 0},
	{clouds: 0},
	{floorQty: 0},
	{tm_landscape: 0},
	{block_shadow: 0},
	{menu_bg_tank: 0},
	{bg_menu: 0},
	{tb_palms: 0},
	{bg_rocks: 0},
	{stuff: 0},
	{qty: 0},
	{aid: 0},
	{Bullet: 0},
	{coin: 0},
	{emitter: 0},
	{arrLevels: 0},
	{arrPlayerGuns: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{probTables: 0},
	{arrEnemyTank: 0},
	{arrPlayerTank: 0},
	{arrEnemyGuns: 0},
	{AJAX: 0},
	{dictProb: 0},
	{arrGunDB: 0},
	{Date: 0},
	{arrWheel: 0},
	{dictGameData: 0},
	{PlatformInfo: 0},
	{JSON: 0},
	{spin_point: 0},
	{rotating: 0},
	{Rotate: 0},
	{spin_wheel: 0},
	{play_text: 0},
	{dailyBonus_text: 0},
	{speenTheWheel_text: 0},
	{textUpgrade: 0},
	{weapons_text: 0},
	{upgrades_text: 0},
	{fight_text: 0},
	{settings_text: 0},
	{sound_text: 0},
	{music_text: 0},
	{fullscreen_text: 0},
	{autoAim_text: 0},
	{moreCoins_text: 0},
	{done_text: 0},
	{smallCaliber_text: 0},
	{sec_text: 0},
	{damage_text: 0},
	{infAmmo_text: 0},
	{ammo_text: 0},
	{shotgun_text: 0},
	{minigun_text: 0},
	{canon_text: 0},
	{flamethrower_text: 0},
	{phaser_text: 0},
	{missles_text: 0},
	{grenades_text: 0},
	{emitter_text: 0},
	{victory_text: 0},
	{tanksDestroyed_text: 0},
	{objDestroyed_text: 0},
	{ammoPicked_text: 0},
	{coinsEarned_text: 0},
	{defeat_text: 0},
	{moneyhack: 0},
	{unlock: 0},
	{langBack: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{JSON2: 0},
	{gunType: 0},
	{gunPrice: 0},
	{btnad: 0},
	{btnX2ad: 0},
	{BinaryData: 0},
	{f_mob_controls: 0},
	{f_pl_tank: 0},
	{DestroyOutsideLayout: 0},
	{f_bullets: 0},
	{DestroyOutsideLayout2: 0},
	{f_destroy: 0},
	{f_radar: 0},
	{f_upg_gui: 0},
	{f_ind_lvls: 0},
	{f_game_gui: 0},
	{f_particles: 0},
	{f_enemies: 0},
	{f_debris: 0},
	{f_en_tank: 0},
	{f_bul_hits: 0},
	{f_pushed: 0},
	{f_hp_gui: 0},
	{f_tilemaps: 0},
	{f_emitters: 0},
	{f_menu_gui: 0},
	{Family1: 0},
	{spawnerUID: 0},
	{topUID: 0},
	{enqty: 0},
	{stop: 0},
	{free_spawner: 0},
	{tankUID: 0},
	{tankState: 0},
	{tankAccel: 0},
	{tankSpeed: 0},
	{ignore_input: 0},
	{music_track: 0},
	{hp_bar: 0},
	{en_count: 0},
	{aid_count: 0},
	{fight_range: 0},
	{add_coins: 0},
	{shield_time: 0},
	{tanks_destroyed: 0},
	{obj_destroyed: 0},
	{ammo_collected: 0},
	{coins_collected: 0},
	{GetTileX: 0},
	{GetTileY: 0},
	{plays: 0},
	{patrolOff: 0},
	{pause: 0},
	{GlobalWon: 0},
	{debrisAmount: 0},
	{blockUID: 0},
	{hitX: 0},
	{hitY: 0},
	{bulletAnimation: 0},
	{bulletUID: 0},
	{stuffUID: 0},
	{speed: 0},
	{coinsInCrate: 0},
	{tweenTime: 0},
	{won: 0},
	{NumRewardAd: 0},
	{aaAngle: 0},
	{viewAngle: 0},
	{mag: 0},
	{dur: 0},
	{control_mode: 0},
	{first_time: 0},
	{all_sounds: 0},
	{adblock: 0},
	{MaxAchievedLevel: 0},
	{SelectedLevel: 0},
	{CurrentPage: 0},
	{NumberPages: 0},
	{PageWidth: 0},
	{coins: 0},
	{firerateLag: 0},
	{damageLag: 0},
	{speedLag: 0},
	{armorLag: 0},
	{aimLag: 0},
	{soundOff: 0},
	{musicOff: 0},
	{autoAim: 0},
	{dailyTime: 0},
	{bonusTimer: 0},
	{bonusInterval: 0},
	{rewTime: 0},
	{justUpdate: 0},
	{weaponName: 0},
	{weaponLevel: 0},
	{weaponPrice: 0},
	{ammoQty: 0},
	{ammoPrice: 0},
	{soundVolume: 0},
	{musicVolume: 0},
	{IsFirst: 0},
	{mute: 0},
	{param: 0},
	{rewardAd: 0},
	{reward: 0},
	{Score: 0},
	{Level: 0},
	{DataJson: 0},
	{keyName: 0},
	{Key: 0},
	{Languages: 0}
];

self.InstanceType = {
	player_top: class extends self.ISpriteInstance {},
	player_base: class extends self.ISpriteInstance {},
	player_shadow: class extends self.ISpriteInstance {},
	spawn_player: class extends self.ISpriteInstance {},
	spawn_enemy: class extends self.ISpriteInstance {},
	en_health: class extends self.ISpriteInstance {},
	en_health_bg: class extends self.ISpriteInstance {},
	enemy_base: class extends self.ISpriteInstance {},
	enemy_shadow: class extends self.ISpriteInstance {},
	enemy_top: class extends self.ISpriteInstance {},
	aid_icon: class extends self.ISpriteInstance {},
	en_icon: class extends self.ISpriteInstance {},
	radar: class extends self.ISpriteInstance {},
	player_crush: class extends self.ISpriteInstance {},
	gunfire_all: class extends self.ISpriteInstance {},
	hit_shell: class extends self.ISpriteInstance {},
	part_en_smoke: class extends self.IParticlesInstance {},
	part_rocket: class extends self.IParticlesInstance {},
	camera: class extends self.ISpriteInstance {},
	phaserfire: class extends self.ISpriteInstance {},
	hit_simple: class extends self.ISpriteInstance {},
	pl_shock_hit: class extends self.ISpriteInstance {},
	part_pl_smoke: class extends self.IParticlesInstance {},
	debris_block: class extends self.ISpriteInstance {},
	debris_explosive: class extends self.ISpriteInstance {},
	fow_view: class extends self.ISpriteInstance {},
	bang: class extends self.ISpriteInstance {},
	enemy_crush: class extends self.ISpriteInstance {},
	hit_bang: class extends self.ISpriteInstance {},
	hit_phaser: class extends self.ISpriteInstance {},
	hit_flame: class extends self.ISpriteInstance {},
	part_bang: class extends self.IParticlesInstance {},
	bang_light: class extends self.ISpriteInstance {},
	part_corrosion: class extends self.IParticlesInstance {},
	debris_corrosion: class extends self.ISpriteInstance {},
	debris_aidcrate: class extends self.ISpriteInstance {},
	debris_crate: class extends self.ISpriteInstance {},
	part_pl_burn: class extends self.IParticlesInstance {},
	part_en_burn: class extends self.IParticlesInstance {},
	part_pl_corr: class extends self.IParticlesInstance {},
	part_en_corr: class extends self.IParticlesInstance {},
	shield: class extends self.ISpriteInstance {},
	em_fire: class extends self.ISpriteInstance {},
	em_beam: class extends self.ITiledBackgroundInstance {},
	pl_shock_light: class extends self.ISpriteInstance {},
	en_shock_light: class extends self.ISpriteInstance {},
	en_shock_hit: class extends self.ISpriteInstance {},
	hit_flash: class extends self.I9PatchInstance {},
	bullet: class extends self.ISpriteInstance {},
	bul_rocket: class extends self.ISpriteInstance {},
	bul_phaser: class extends self.ISpriteInstance {},
	bul_phaser_trail: class extends self.ISpriteInstance {},
	bul_flame: class extends self.ISpriteInstance {},
	bul_gren: class extends self.ISpriteInstance {},
	mine: class extends self.ISpriteInstance {},
	en_shock: class extends self.ITiledBackgroundInstance {},
	pl_shock: class extends self.ITiledBackgroundInstance {},
	btn_fscrn: class extends self.ISpriteInstance {},
	btn_level: class extends self.ISpriteInstance {},
	btn_fight: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	scorefont: class extends self.ISpriteFontInstance {},
	popupUpgrades: class extends self.I9PatchInstance {},
	aim: class extends self.ISpriteInstance {},
	btn_upg_wep: class extends self.ISpriteInstance {},
	ico_tank: class extends self.ISpriteInstance {},
	scorelabel: class extends self.ISpriteInstance {},
	pop_close: class extends self.ISpriteInstance {},
	btn_gunswitch: class extends self.ISpriteInstance {},
	btn_add_lvl: class extends self.ISpriteInstance {},
	btn_add_ammo: class extends self.ISpriteInstance {},
	ind_lvl: class extends self.ISpriteInstance {},
	loader_bar: class extends self.I9PatchInstance {},
	btn_any: class extends self.ISpriteInstance {},
	btn_upg_tank: class extends self.ISpriteInstance {},
	font_10px: class extends self.ISpriteFontInstance {},
	font_7px: class extends self.ISpriteFontInstance {},
	part_ui: class extends self.IParticlesInstance {},
	player_hp: class extends self.I9PatchInstance {},
	player_hp_bg: class extends self.I9PatchInstance {},
	ind_lvl2: class extends self.ISpriteInstance {},
	level_bar_bg: class extends self.I9PatchInstance {},
	level_bar: class extends self.I9PatchInstance {},
	ammo_bar: class extends self.I9PatchInstance {},
	ammo_bar_bg: class extends self.ISpriteInstance {},
	loader_bg: class extends self.I9PatchInstance {},
	loader_icon: class extends self.ISpriteInstance {},
	font_10x16px: class extends self.ISpriteFontInstance {},
	ico_ammo: class extends self.ISpriteInstance {},
	btn_confirm: class extends self.ISpriteInstance {},
	btn_play: class extends self.ISpriteInstance {},
	help_desktop: class extends self.ISpriteInstance {},
	btn_lvl_end: class extends self.ISpriteInstance {},
	popupStats: class extends self.I9PatchInstance {},
	btn_shop: class extends self.ISpriteInstance {},
	pop_stats_line: class extends self.I9PatchInstance {},
	level_group: class extends self.ITiledBackgroundInstance {},
	btn_next_prev: class extends self.ISpriteInstance {},
	btn_switcher: class extends self.ISpriteInstance {},
	tmbstickbase: class extends self.ISpriteInstance {},
	tmbstick: class extends self.ISpriteInstance {},
	shop_item: class extends self.ISpriteInstance {},
	shop_buy_btn: class extends self.ISpriteInstance {},
	coin_sparks: class extends self.ISpriteInstance {},
	btn_pause: class extends self.ISpriteInstance {},
	btn_lang: class extends self.ISpriteInstance {},
	btn_spin: class extends self.ISpriteInstance {},
	part_coins: class extends self.IParticlesInstance {},
	pop_lang: class extends self.I9PatchInstance {},
	shop_item_bg: class extends self.I9PatchInstance {},
	_9lives_logo: class extends self.ISpriteInstance {},
	loader_spinner: class extends self.ISpriteInstance {},
	icon_warn: class extends self.ISpriteInstance {},
	part_wheel: class extends self.IParticlesInstance {},
	rotate: class extends self.ISpriteInstance {},
	home_btn: class extends self.ISpriteInstance {},
	popupUpgrades2: class extends self.I9PatchInstance {},
	btn_gunshot: class extends self.ISpriteInstance {},
	bg_cammo: class extends self.ITiledBackgroundInstance {},
	bg_fade: class extends self.ITiledBackgroundInstance {},
	bg_loader: class extends self.ITiledBackgroundInstance {},
	ui_wep_bg: class extends self.ISpriteInstance {},
	block_fragile: class extends self.ISpriteInstance {},
	block_flash: class extends self.ISpriteInstance {},
	clouds: class extends self.ITiledBackgroundInstance {},
	tm_landscape: class extends self.ITilemapInstance {},
	block_shadow: class extends self.ISpriteInstance {},
	menu_bg_tank: class extends self.ISpriteInstance {},
	bg_menu: class extends self.ITiledBackgroundInstance {},
	tb_palms: class extends self.ITiledBackgroundInstance {},
	bg_rocks: class extends self.ISpriteInstance {},
	stuff: class extends self.ISpriteInstance {},
	aid: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	emitter: class extends self.ISpriteInstance {},
	arrLevels: class extends self.IArrayInstance {},
	arrPlayerGuns: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	probTables: class extends self.IInstance {},
	arrEnemyTank: class extends self.IArrayInstance {},
	arrPlayerTank: class extends self.IArrayInstance {},
	arrEnemyGuns: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	dictProb: class extends self.IDictionaryInstance {},
	arrGunDB: class extends self.IArrayInstance {},
	Date: class extends self.IInstance {},
	arrWheel: class extends self.IArrayInstance {},
	dictGameData: class extends self.IDictionaryInstance {},
	PlatformInfo: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	spin_point: class extends self.ISpriteInstance {},
	spin_wheel: class extends self.ISpriteInstance {},
	play_text: class extends self.ITextInstance {},
	dailyBonus_text: class extends self.ITextInstance {},
	speenTheWheel_text: class extends self.ITextInstance {},
	weapons_text: class extends self.ITextInstance {},
	upgrades_text: class extends self.ITextInstance {},
	fight_text: class extends self.ITextInstance {},
	settings_text: class extends self.ITextInstance {},
	sound_text: class extends self.ITextInstance {},
	music_text: class extends self.ITextInstance {},
	fullscreen_text: class extends self.ITextInstance {},
	autoAim_text: class extends self.ITextInstance {},
	moreCoins_text: class extends self.ITextInstance {},
	done_text: class extends self.ITextInstance {},
	smallCaliber_text: class extends self.ITextInstance {},
	sec_text: class extends self.ITextInstance {},
	damage_text: class extends self.ITextInstance {},
	infAmmo_text: class extends self.ITextInstance {},
	ammo_text: class extends self.ITextInstance {},
	shotgun_text: class extends self.ITextInstance {},
	minigun_text: class extends self.ITextInstance {},
	canon_text: class extends self.ITextInstance {},
	flamethrower_text: class extends self.ITextInstance {},
	phaser_text: class extends self.ITextInstance {},
	missles_text: class extends self.ITextInstance {},
	grenades_text: class extends self.ITextInstance {},
	emitter_text: class extends self.ITextInstance {},
	victory_text: class extends self.ITextInstance {},
	tanksDestroyed_text: class extends self.ITextInstance {},
	objDestroyed_text: class extends self.ITextInstance {},
	ammoPicked_text: class extends self.ITextInstance {},
	coinsEarned_text: class extends self.ITextInstance {},
	defeat_text: class extends self.ITextInstance {},
	moneyhack: class extends self.IButtonInstance {},
	unlock: class extends self.IButtonInstance {},
	langBack: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	JSON2: class extends self.IJSONInstance {},
	btnad: class extends self.ISpriteInstance {},
	btnX2ad: class extends self.ISpriteInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	f_mob_controls: class extends self.ISpriteInstance {},
	f_pl_tank: class extends self.ISpriteInstance {},
	f_bullets: class extends self.ISpriteInstance {},
	f_destroy: class extends self.ISpriteInstance {},
	f_radar: class extends self.ISpriteInstance {},
	f_upg_gui: class extends self.ISpriteInstance {},
	f_ind_lvls: class extends self.ISpriteInstance {},
	f_game_gui: class extends self.ISpriteInstance {},
	f_particles: class extends self.IParticlesInstance {},
	f_enemies: class extends self.ISpriteInstance {},
	f_debris: class extends self.ISpriteInstance {},
	f_en_tank: class extends self.ISpriteInstance {},
	f_bul_hits: class extends self.ISpriteInstance {},
	f_pushed: class extends self.ISpriteInstance {},
	f_hp_gui: class extends self.I9PatchInstance {},
	f_tilemaps: class extends self.ITilemapInstance {},
	f_emitters: class extends self.ISpriteInstance {},
	f_menu_gui: class extends self.ISpriteInstance {},
	Family1: class extends self.ITextInstance {}
}