/*
 Platform.js <https://mths.be/platform>
 Copyright 2014-2018 Benjamin Tan <https://bnjmnt4n.now.sh/>
 Copyright 2011-2013 John-David Dalton
 Available under MIT license <https://mths.be/mit>
*/
(function(){function a(r){r=String(r);return r.charAt(0).toUpperCase()+r.slice(1)}function d(r,x){var n=-1,l=r?r.length:0;if("number"==typeof l&&-1<l&&l<=y)for(;++n<l;)x(r[n],n,r);else f(r,x)}function e(r){r=String(r).replace(/^ +| +$/g,"");return/^(?:webOS|i(?:OS|P))/.test(r)?r:a(r)}function f(r,x){for(var n in r)z.call(r,n)&&x(r[n],n,r)}function m(r){return null==r?a(r):H.call(r).slice(8,-1)}function h(r,x){var n=null!=r?typeof r[x]:"number";return!/^(?:boolean|number|string|undefined)$/.test(n)&&
("object"==n?!!r[x]:!0)}function p(r){return String(r).replace(/([ -])(?!$)/g,"$1?")}function g(r,x){var n=null;d(r,function(l,B){n=x(n,l,B,r)});return n}function c(r){function x(P){return g(P,function(O,M){var T=M.pattern||p(M);!O&&(O=RegExp("\\b"+T+" *\\d+[.\\w_]*","i").exec(r)||RegExp("\\b"+T+" *\\w+-[\\w]*","i").exec(r)||RegExp("\\b"+T+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(r))&&((O=String(M.label&&!RegExp(T,"i").test(M.label)?M.label:O).split("/"))[1]&&!/[\d.]+/.test(O[0])&&(O[0]+=
" "+O[1]),M=M.label||M,O=e(O[0].replace(RegExp(T,"i"),M).replace(RegExp("; *(?:"+M+"[_-])?","i")," ").replace(RegExp("("+M+")[-_.]?(\\w)","i"),"$1 $2")));return O})}function n(P){return g(P,function(O,M){return O||(RegExp(M+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(r)||0)[1]||null})}var l=t,B=r&&"object"==typeof r&&"String"!=m(r);B&&(l=r,r=null);var I=l.navigator||{},C=I.userAgent||"";r||(r=C);var X=B?!!I.likeChrome:/\bChrome\b/.test(r)&&!/internal|\n/i.test(H.toString()),
R=B?"Object":"ScriptBridgingProxyObject",N=B?"Object":"Environment",Q=B&&l.java?"JavaPackage":m(l.java),V=B?"Object":"RuntimeObject";N=(Q=/\bJava/.test(Q)&&l.java)&&m(l.environment)==N;var Z=Q?"a":"\u03b1",Y=Q?"b":"\u03b2",aa=l.document||{},S=l.operamini||l.opera,k=F.test(k=B&&S?S["[[Class]]"]:m(S))?k:S=null,b,A=r;B=[];var u=null,G=r==C;C=G&&S&&"function"==typeof S.version&&S.version();var J=function(P){return g(P,function(O,M){return O||RegExp("\\b"+(M.pattern||p(M))+"\\b","i").exec(r)&&(M.label||
M)})}([{label:"EdgeHTML",pattern:"Edge"},"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),D=function(P){return g(P,function(O,M){return O||RegExp("\\b"+(M.pattern||p(M))+"\\b","i").exec(r)&&(M.label||M)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"Edge"},"Midori","Nook Browser",
"PaleMoon","PhantomJS","Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Waterfox","WebPositive","Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chrome",{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",pattern:"FxiOS"},
{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),L=x([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV","Lumia","iPad",
"iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),U=function(P){return g(P,function(O,M,T){return O||(M[L]||M[/^[a-z]+(?: +[a-z]+\b)*/i.exec(L)]||RegExp("\\b"+p(T)+"(?:\\b|\\w*\\d)","i").exec(r))&&T})}({Apple:{iPad:1,iPhone:1,iPod:1},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},Asus:{Transformer:1},
"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1}}),E=function(P){return g(P,function(O,M){var T=M.pattern||p(M);if(!O&&(O=RegExp("\\b"+T+"(?:/[\\d.]+|[ \\w.]*)","i").exec(r))){var W=O,ba=M.label||M,ca={"10.0":"10","6.4":"10 Technical Preview",
"6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};T&&ba&&/^Win/i.test(W)&&!/^Windows Phone /i.test(W)&&(ca=ca[/[\d.]+$/.exec(W)])&&(W="Windows "+ca);W=String(W);T&&ba&&(W=W.replace(RegExp(T,"i"),ba));O=W=e(W.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,
"$1").replace(/\/(\d)/," $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return O})}(["Windows Phone","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian","Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X",
"Macintosh","Mac","Windows 98;","Windows "]);J&&(J=[J]);U&&!L&&(L=x([U]));if(b=/\bGoogle TV\b/.exec(L))L=b[0];/\bSimulator\b/i.test(r)&&(L=(L?L+" ":"")+"Simulator");"Opera Mini"==D&&/\bOPiOS\b/.test(r)&&B.push("running in Turbo/Uncompressed mode");"IE"==D&&/\blike iPhone OS\b/.test(r)?(b=c(r.replace(/like iPhone OS/,"")),U=b.manufacturer,L=b.product):/^iP/.test(L)?(D||(D="Safari"),E="iOS"+((b=/ OS ([\d_]+)/i.exec(r))?" "+b[1].replace(/_/g,"."):"")):"Konqueror"!=D||/buntu/i.test(E)?U&&"Google"!=U&&
(/Chrome/.test(D)&&!/\bMobile Safari\b/i.test(r)||/\bVita\b/.test(L))||/\bAndroid\b/.test(E)&&/^Chrome/.test(D)&&/\bVersion\//i.test(r)?(D="Android Browser",E=/\bAndroid\b/.test(E)?E:"Android"):"Silk"==D?(/\bMobi/i.test(r)||(E="Android",B.unshift("desktop mode")),/Accelerated *= *true/i.test(r)&&B.unshift("accelerated")):"PaleMoon"==D&&(b=/\bFirefox\/([\d.]+)\b/.exec(r))?B.push("identifying as Firefox "+b[1]):"Firefox"==D&&(b=/\b(Mobile|Tablet|TV)\b/i.exec(r))?(E||(E="Firefox OS"),L||(L=b[1])):!D||
(b=!/\bMinefield\b/i.test(r)&&/\b(?:Firefox|Safari)\b/.exec(D))?(D&&!L&&/[\/,]|^[^(]+?\)/.test(r.slice(r.indexOf(b+"/")+8))&&(D=null),(b=L||U||E)&&(L||U||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(E))&&(D=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(E)?E:b)+" Browser")):"Electron"==D&&(b=(/\bChrome\/([\d.]+)\b/.exec(r)||0)[1])&&B.push("Chromium "+b):E="Kubuntu";C||(C=n(["(?:Cloud9|CriOS|CrMo|Edge|FxiOS|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$))","Version",p(D),
"(?:Firefox|Minefield|NetFront)"]));if(b="iCab"==J&&3<parseFloat(C)&&"WebKit"||/\bOpera\b/.test(D)&&(/\bOPR\b/.test(r)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(r)&&!/^(?:Trident|EdgeHTML)$/.test(J)&&"WebKit"||!J&&/\bMSIE\b/i.test(r)&&("Mac OS"==E?"Tasman":"Trident")||"WebKit"==J&&/\bPlayStation\b(?! Vita\b)/i.test(D)&&"NetFront")J=[b];"IE"==D&&(b=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(r)||0)[1])?(D+=" Mobile",E="Windows Phone "+(/\+$/.test(b)?b:b+".x"),B.unshift("desktop mode")):/\bWPDesktop\b/i.test(r)?
(D="IE Mobile",E="Windows Phone 8.x",B.unshift("desktop mode"),C||(C=(/\brv:([\d.]+)/.exec(r)||0)[1])):"IE"!=D&&"Trident"==J&&(b=/\brv:([\d.]+)/.exec(r))&&(D&&B.push("identifying as "+D+(C?" "+C:"")),D="IE",C=b[1]);if(G){if(h(l,"global"))if(Q&&(b=Q.lang.System,A=b.getProperty("os.arch"),E=E||b.getProperty("os.name")+" "+b.getProperty("os.version")),N){try{C=l.require("ringo/engine").version.join("."),D="RingoJS"}catch(P){(b=l.system)&&b.global.system==l.system&&(D="Narwhal",E||(E=b[0].os||null))}D||
(D="Rhino")}else"object"==typeof l.process&&!l.process.browser&&(b=l.process)&&("object"==typeof b.versions&&("string"==typeof b.versions.electron?(B.push("Node "+b.versions.node),D="Electron",C=b.versions.electron):"string"==typeof b.versions.nw&&(B.push("Chromium "+C,"Node "+b.versions.node),D="NW.js",C=b.versions.nw)),D||(D="Node.js",A=b.arch,E=b.platform,C=(C=/[\d.]+/.exec(b.version))?C[0]:null));else m(b=l.runtime)==R?(D="Adobe AIR",E=b.flash.system.Capabilities.os):m(b=l.phantom)==V?(D="PhantomJS",
C=(b=b.version||null)&&b.major+"."+b.minor+"."+b.patch):"number"==typeof aa.documentMode&&(b=/\bTrident\/(\d+)/i.exec(r))?(C=[C,aa.documentMode],(b=+b[1]+4)!=C[1]&&(B.push("IE "+C[1]+" mode"),J&&(J[1]=""),C[1]=b),C="IE"==D?String(C[1].toFixed(1)):C[0]):"number"==typeof aa.documentMode&&/^(?:Chrome|Firefox)\b/.test(D)&&(B.push("masking as "+D+" "+C),D="IE",C="11.0",J=["Trident"],E="Windows");E=E&&e(E)}C&&(b=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(C)||/(?:alpha|beta)(?: ?\d)?/i.exec(r+";"+(G&&
I.appMinorVersion))||/\bMinefield\b/i.test(r)&&"a")&&(u=/b/i.test(b)?"beta":"alpha",C=C.replace(RegExp(b+"\\+?$"),"")+("beta"==u?Y:Z)+(/\d+\+?/.exec(b)||""));if("Fennec"==D||"Firefox"==D&&/\b(?:Android|Firefox OS)\b/.test(E))D="Firefox Mobile";else if("Maxthon"==D&&C)C=C.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(L))"Xbox 360"==L&&(E=null),"Xbox 360"==L&&/\bIEMobile\b/.test(r)&&B.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(D)&&(!D||L||/Browser|Mobi/.test(D))||"Windows CE"!=
E&&!/Mobi/i.test(r))if("IE"==D&&G)try{null===l.external&&B.unshift("platform preview")}catch(P){B.unshift("embedded")}else(/\bBlackBerry\b/.test(L)||/\bBB10\b/.test(r))&&(b=(RegExp(L.replace(/ +/g," *")+"/([.\\d]+)","i").exec(r)||0)[1]||C)?(b=[b,/BB10/.test(r)],E=(b[1]?(L=null,U="BlackBerry"):"Device Software")+" "+b[0],C=null):this!=f&&"Wii"!=L&&(G&&S||/Opera/.test(D)&&/\b(?:MSIE|Firefox)\b/i.test(r)||"Firefox"==D&&/\bOS X (?:\d+\.){2,}/.test(E)||"IE"==D&&(E&&!/^Win/.test(E)&&5.5<C||/\bWindows XP\b/.test(E)&&
8<C||8==C&&!/\bTrident\b/.test(r)))&&!F.test(b=c.call(f,r.replace(F,"")+";"))&&b.name&&(b="ing as "+b.name+((b=b.version)?" "+b:""),F.test(D)?(/\bIE\b/.test(b)&&"Mac OS"==E&&(E=null),b="identify"+b):(b="mask"+b,D=k?e(k.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(b)&&(E=null),G||(C=null)),J=["Presto"],B.push(b));else D+=" Mobile";if(b=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(r)||0)[1]){b=[parseFloat(b.replace(/\.(\d)$/,".0$1")),b];if("Safari"==D&&"+"==b[1].slice(-1))D="WebKit Nightly",u="alpha",
C=b[1].slice(0,-1);else if(C==b[1]||C==(b[2]=(/\bSafari\/([\d.]+\+?)/i.exec(r)||0)[1]))C=null;b[1]=(/\bChrome\/([\d.]+)/i.exec(r)||0)[1];537.36==b[0]&&537.36==b[2]&&28<=parseFloat(b[1])&&"WebKit"==J&&(J=["Blink"]);G&&(X||b[1])?(J&&(J[1]="like Chrome"),b=b[1]||(b=b[0],530>b?1:532>b?2:532.05>b?3:533>b?4:534.03>b?5:534.07>b?6:534.1>b?7:534.13>b?8:534.16>b?9:534.24>b?10:534.3>b?11:535.01>b?12:535.02>b?"13+":535.07>b?15:535.11>b?16:535.19>b?17:536.05>b?18:536.1>b?19:537.01>b?20:537.11>b?"21+":537.13>b?
23:537.18>b?24:537.24>b?25:537.36>b?26:"Blink"!=J?"27":"28")):(J&&(J[1]="like Safari"),b=(b=b[0],400>b?1:500>b?2:526>b?3:533>b?4:534>b?"4+":535>b?5:537>b?6:538>b?7:601>b?8:"8"));J&&(J[1]+=" "+(b+="number"==typeof b?".x":/[.+]/.test(b)?"":"+"));"Safari"==D&&(!C||45<parseInt(C))&&(C=b)}"Opera"==D&&(b=/\bzbov|zvav$/.exec(E))?(D+=" ",B.unshift("desktop mode"),"zvav"==b?(D+="Mini",C=null):D+="Mobile",E=E.replace(RegExp(" *"+b+"$"),"")):"Safari"==D&&/\bChrome\b/.exec(J&&J[1])&&(B.unshift("desktop mode"),
D="Chrome Mobile",C=null,/\bOS X\b/.test(E)?(U="Apple",E="iOS 4.3+"):E=null);C&&0==C.indexOf(b=/[\d.]+$/.exec(E))&&-1<r.indexOf("/"+b+"-")&&(E=String(E.replace(b,"")).replace(/^ +| +$/g,""));J&&!/\b(?:Avant|Nook)\b/.test(D)&&(/Browser|Lunascape|Maxthon/.test(D)||"Safari"!=D&&/^iOS/.test(E)&&/\bSafari\b/.test(J[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|Web)/.test(D)&&J[1])&&(b=J[J.length-1])&&B.push(b);B.length&&(B=["("+B.join("; ")+")"]);U&&L&&0>L.indexOf(U)&&
B.push("on "+U);L&&B.push((/^on /.test(B[B.length-1])?"":"on ")+L);if(E){var da=(b=/ ([\d.+]+)$/.exec(E))&&"/"==E.charAt(E.length-b[0].length-1);E={architecture:32,family:b&&!da?E.replace(b[0],""):E,version:b?b[1]:null,toString:function(){var P=this.version;return this.family+(P&&!da?" "+P:"")+(64==this.architecture?" 64-bit":"")}}}(b=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(A))&&!/\bi686\b/i.test(A)?(E&&(E.architecture=64,E.family=E.family.replace(RegExp(" *"+b),"")),D&&(/\bWOW64\b/i.test(r)||G&&
/\w(?:86|32)$/.test(I.cpuClass||I.platform)&&!/\bWin64; x64\b/i.test(r))&&B.unshift("32-bit")):E&&/^OS X/.test(E.family)&&"Chrome"==D&&39<=parseFloat(C)&&(E.architecture=64);r||(r=null);l={};l.description=r;l.layout=J&&J[0];l.manufacturer=U;l.name=D;l.prerelease=u;l.product=L;l.ua=r;l.version=D&&C;l.os=E||{architecture:null,family:null,version:null,toString:function(){return"null"}};l.parse=c;l.toString=function(){return this.description||""};l.version&&B.unshift(C);l.name&&B.unshift(D);E&&D&&(E!=
String(E).split(" ")[0]||E!=D.split(" ")[0]&&!L)&&B.push(L?"("+E+")":"on "+E);B.length&&(l.description=B.join(" "));return l}var q={"function":!0,object:!0},t=q[typeof window]&&window||this,v=q[typeof exports]&&exports;q=q[typeof module]&&module&&!module.nodeType&&module;var w=v&&q&&"object"==typeof global&&global;!w||w.global!==w&&w.window!==w&&w.self!==w||(t=w);var y=Math.pow(2,53)-1,F=/\bOpera/;w=Object.prototype;var z=w.hasOwnProperty,H=w.toString,K=c();"function"==typeof define&&"object"==typeof define.amd&&
define.amd?(t.platform=K,define(function(){return K})):v&&q?f(K,function(r,x){v[x]=r}):t.platform=K}).call(this);
function buildIOSMeta(){for(var a=[{name:"viewport",content:"width=device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"},{name:"apple-mobile-web-app-capable",content:"yes"},{name:"apple-mobile-web-app-status-bar-style",content:"black"}],d=0;d<a.length;d++){var e=document.createElement("meta");e.name=a[d].name;e.content=a[d].content;var f=window.document.head.querySelector('meta[name="'+e.name+'"]');f&&f.parentNode.removeChild(f);window.document.head.appendChild(e)}}
function hideIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","none");jQuery(".xxx-ios-fullscreen-scroll").css("display","none");jQuery(".xxx-game-iframe-full").removeClass("xxx-game-iframe-iphone-se")}function buildIOSFullscreenPanel(){jQuery("body").append('<div class="xxx-ios-fullscreen-message"><div class="xxx-ios-fullscreen-swipe"></div></div><div class="xxx-ios-fullscreen-scroll"></div>')}
function showIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","block");jQuery(".xxx-ios-fullscreen-scroll").css("display","block")}
function __iosResize(){window.scrollTo(0,0);console.log(window.devicePixelRatio);console.log(window.innerWidth);console.log(window.innerHeight);if("iPhone"===platform.product)switch(window.devicePixelRatio){case 2:switch(window.innerWidth){case 568:320!==window.innerHeight&&jQuery(".xxx-game-iframe-full").addClass("xxx-game-iframe-iphone-se");break;case 667:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();
break;default:hideIOSFullscreenPanel()}break;case 3:switch(window.innerWidth){case 736:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 724:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;default:hideIOSFullscreenPanel()}}function iosResize(){__iosResize();setTimeout(function(){__iosResize()},500)}
function iosInIframe(){try{return window.self!==window.top}catch(a){return!0}}function isIOSLessThen13(){var a=platform.os,d=a.family.toLowerCase();a=parseFloat(a.version);return"ios"===d&&13>a?!0:!1}$(document).ready(function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&(buildIOSFullscreenPanel(),buildIOSMeta())});
jQuery(window).resize(function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&iosResize()});
(function(){var a="undefined"!==typeof window&&"undefined"!==typeof window.document?window.document:{},d="undefined"!==typeof module&&module.exports,e=function(){for(var h,p=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),
"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],g=0,c=p.length,q={};g<c;g++)if((h=p[g])&&h[1]in a){for(g=0;g<h.length;g++)q[p[0][g]]=h[g];return q}return!1}(),f={change:e.fullscreenchange,error:e.fullscreenerror},m={request:function(h){return new Promise(function(p,g){var c=function(){this.off("change",
c);p()}.bind(this);this.on("change",c);h=h||a.documentElement;Promise.resolve(h[e.requestFullscreen]())["catch"](g)}.bind(this))},exit:function(){return new Promise(function(h,p){if(this.isFullscreen){var g=function(){this.off("change",g);h()}.bind(this);this.on("change",g);Promise.resolve(a[e.exitFullscreen]())["catch"](p)}else h()}.bind(this))},toggle:function(h){return this.isFullscreen?this.exit():this.request(h)},onchange:function(h){this.on("change",h)},onerror:function(h){this.on("error",h)},
on:function(h,p){var g=f[h];g&&a.addEventListener(g,p,!1)},off:function(h,p){var g=f[h];g&&a.removeEventListener(g,p,!1)},raw:e};e?(Object.defineProperties(m,{isFullscreen:{get:function(){return!!a[e.fullscreenElement]}},element:{enumerable:!0,get:function(){return a[e.fullscreenElement]}},isEnabled:{enumerable:!0,get:function(){return!!a[e.fullscreenEnabled]}}}),d?module.exports=m:window.screenfull=m):d?module.exports={isEnabled:!1}:window.screenfull={isEnabled:!1}})();
var s_iScaleFactor=1,s_bIsIphone=!1,s_iOffsetX,s_iOffsetY,s_bFocus=!0;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}function isIpad(){var a=-1!==navigator.userAgent.toLowerCase().indexOf("ipad");return!a&&navigator.userAgent.match(/Mac/)&&navigator.maxTouchPoints&&2<navigator.maxTouchPoints?!0:a}function isMobile(){return isIpad()?!0:jQuery.browser.mobile}
function isIOS(){var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");if(-1!==navigator.userAgent.toLowerCase().indexOf("iphone"))return s_bIsIphone=!0;for(;a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}
function getSize(a){var d=a.toLowerCase(),e=window.document,f=e.documentElement;if(void 0===window["inner"+a])a=f["client"+a];else if(window["inner"+a]!=f["client"+a]){var m=e.createElement("body");m.id="vpw-test-b";m.style.cssText="overflow:scroll";var h=e.createElement("div");h.id="vpw-test-d";h.style.cssText="position:absolute;top:-1000px";h.innerHTML="<style>@media("+d+":"+f["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+d+":7px!important}}</style>";m.appendChild(h);f.insertBefore(m,e.head);
a=7==h["offset"+a]?f["client"+a]:window["inner"+a];f.removeChild(m)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=null!==platform.name&&"safari"===platform.name.toLowerCase()?getIOSWindowHeight():getSize("Height");var d=getSize("Width");s_bFocus&&_checkOrientation(d,a);var e=Math.min(a/CANVAS_HEIGHT,d/CANVAS_WIDTH),f=Math.round(CANVAS_WIDTH*e);e=Math.round(CANVAS_HEIGHT*e);if(e<a){var m=a-e;e+=m;f+=CANVAS_WIDTH/CANVAS_HEIGHT*m}else f<d&&(m=d-f,f+=m,e+=CANVAS_HEIGHT/CANVAS_WIDTH*m);m=a/2-e/2;var h=d/2-f/2,p=CANVAS_WIDTH/f;if(h*p<-EDGEBOARD_X||
m*p<-EDGEBOARD_Y)e=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),d/(CANVAS_WIDTH-2*EDGEBOARD_X)),f=Math.round(CANVAS_WIDTH*e),e=Math.round(CANVAS_HEIGHT*e),m=(a-e)/2,h=(d-f)/2,p=CANVAS_WIDTH/f;s_iOffsetX=-1*h*p;s_iOffsetY=-1*m*p;0<=m&&(s_iOffsetY=0);0<=h&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oLevelMenu&&s_oLevelMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_oStage.canvas.width=f;
s_oStage.canvas.height=e;0>m||(m=(a-e)/2);$("#canvas").css("top",m+"px");$("#canvas").css("left",h+"px");fullscreenHandler();s_iScaleFactor=Math.min(f/CANVAS_WIDTH,e/CANVAS_HEIGHT);s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor}}
function _checkOrientation(a,d){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>d?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function createBitmap(a,d,e){var f=new createjs.Bitmap(a),m=new createjs.Shape;d&&e?m.graphics.beginFill("#fff").drawRect(0,0,d,e):m.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);f.hitArea=m;return f}function createSprite(a,d,e,f,m,h){a=null!==d?new createjs.Sprite(a,d):new createjs.Sprite(a);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-e,-f,m,h);a.hitArea=d;return a}
function randomFloatBetween(a,d,e){"undefined"===typeof e&&(e=2);return parseFloat(Math.min(a+Math.random()*(d-a),d).toFixed(e))}function shuffle(a){for(var d=a.length,e,f;0!==d;)f=Math.floor(Math.random()*d),--d,e=a[d],a[d]=a[f],a[f]=e;return a}function formatTime(a){a/=1E3;var d=Math.floor(a/60);a=parseFloat(a-60*d).toFixed(1);var e="";e=10>d?e+("0"+d+":"):e+(d+":");return 10>a?e+("0"+a):e+a}
function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var d=a.length,e,f;0<d;)f=Math.floor(Math.random()*d),d--,e=a[d],a[d]=a[f],a[f]=e;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);a.dispatchEvent(d)}}};
(function(){function a(e){var f={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};e=e||window.event;e.type in f?document.body.className=f[e.type]:(document.body.className=this[d]?"hidden":"visible","hidden"===document.body.className?(s_oMain.stopUpdate(),s_bFocus=!1):(s_oMain.startUpdate(),s_bFocus=!0))}var d="hidden";d in document?document.addEventListener("visibilitychange",a):(d="mozHidden")in document?document.addEventListener("mozvisibilitychange",
a):(d="webkitHidden")in document?document.addEventListener("webkitvisibilitychange",a):(d="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var d=window.location.search.substring(1).split("&"),e=0;e<d.length;e++){var f=d[e].split("=");if(f[0]==a)return f[1]}}function playSound(a,d,e){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(d),s_aSounds[a].loop(e),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}function setVolume(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(d)}
function setMute(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(d)}function saveItem(a,d){s_bStorageAvailable&&localStorage.setItem(a,d)}function getItem(a){return s_bStorageAvailable?localStorage.getItem(a):null}
function fullscreenHandler(){ENABLE_FULLSCREEN&&!1!==screenfull.isEnabled&&(s_bFullscreen=screenfull.isFullscreen,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut(),null!==s_oLevelMenu&&s_oLevelMenu.resetFullscreenBut())}if(screenfull.isEnabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut();null!==s_oLevelMenu&&s_oLevelMenu.resetFullscreenBut()});
function CSpriteLibrary(){var a={},d,e,f,m,h,p;this.init=function(g,c,q){d={};f=e=0;m=g;h=c;p=q};this.addSprite=function(g,c){if(!a.hasOwnProperty(g)){var q=new Image;a[g]=d[g]={szPath:c,oSprite:q,bLoaded:!1};e++}};this.getSprite=function(g){return a.hasOwnProperty(g)?a[g].oSprite:null};this._onSpritesLoaded=function(){e=0;h.call(p)};this._onSpriteLoaded=function(){m.call(p);++f===e&&this._onSpritesLoaded()};this.loadSprites=function(){for(var g in d)d[g].oSprite.oSpriteLibrary=this,d[g].oSprite.szKey=
g,d[g].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},d[g].oSprite.onerror=function(c){var q=c.currentTarget;setTimeout(function(){d[q.szKey].oSprite.src=d[q.szKey].szPath},500)},d[g].oSprite.src=d[g].szPath};this.setLoaded=function(g){a[g].bLoaded=!0};this.isLoaded=function(g){return a[g].bLoaded};this.getNumSprites=function(){return e}}
var CANVAS_WIDTH=960,CANVAS_HEIGHT=540,EDGEBOARD_X=128,EDGEBOARD_Y=42,FPS=35,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,FONT_GAME="Chewy",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_MSG_BOX_LEFT_BUT=6,ON_MSG_BOX_CENTER_BUT=7,ON_MSG_BOX_RIGHT_BUT=8,STATE_GAME_ROLL_IN=0,STATE_GAME_BALL_MOVE=1,STATE_GAME_ROLL_OUT=2,STATE_GAME_SHOOTING=3,STATE_GAME_ATTRACT_BALLS=4,PATH_COLOR_STROKE="#a04c00",PATH_COLOR=
"#221910",STEP_LENGTH=1.8,BALL_COLORS=5,BALL_ROLLING_IN,BALL_SHOOTED_SPEED=24,NUM_LEVELS,COMBO_VALUE,EXTRA_SCORE,BALL_DIAMETER,BALL_RADIUS,BALL_DIAMETER_SQUARE,NUM_ROWS_PAGE_LEVEL=3,NUM_COLS_PAGE_LEVEL=5,SOUNDTRACK_VOLUME_IN_GAME=1,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION,TEXT_GAMEOVER="GAME OVER",TEXT_CONGRATS="CONGRATULATIONS",TEXT_PLAY="PLAY",TEXT_SCORE="SCORE",TEXT_LEVEL="LEVEL",TEXT_FINAL_SCORE="FINAL SCORE",TEXT_SELECT_LEVEL="SELECT A LEVEL",TEXT_DELETE_SAVINGS="ALL YOUR PROGRESS WILL BE CANCELLED! ARE YOU SURE?",
TEXT_NO="NO",TEXT_YES="YES",TEXT_ERR_LS="YOUR WEB BROWSER DOES NOT SUPPORT STORING SETTING LOCALLY. IN SAFARI, THE MOST COMMON CAUSE OF THIS IS USING 'PRIVATE BROWSING MODE'. SOME INFO MAY NOT SAVE OR SOME FEATURE MAY NOT WORK PROPERLY.",TEXT_CREDITS_DEVELOPED="DEVELOPED BY",TEXT_PRELOADER_CONTINUE="START",TEXT_SHARE_IMAGE="200x200.jpg",TEXT_SHARE_TITLE="Congratulations!",TEXT_SHARE_MSG1="You collected <strong>",TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!",TEXT_SHARE_SHARE1=
"My score is ",TEXT_SHARE_SHARE2=" points! Can you do better";
function CPreloader(){var a,d,e,f,m,h,p,g,c,q;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.addSprite("but_start","./sprites/but_start.png");s_oSpriteLibrary.loadSprites();q=new createjs.Container;s_oStage.addChild(q)};this.unload=function(){q.removeAllChildren();c.unload()};this._onImagesLoaded=function(){};
this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var t=new createjs.Shape;t.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);q.addChild(t);t=s_oSpriteLibrary.getSprite("200x200");p=createBitmap(t);p.regX=.5*t.width;p.regY=.5*t.height;p.x=CANVAS_WIDTH/2;p.y=CANVAS_HEIGHT/2-150;q.addChild(p);g=new createjs.Shape;g.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(p.x-100,p.y-100,200,200,10);q.addChild(g);p.mask=g;
t=s_oSpriteLibrary.getSprite("progress_bar");f=createBitmap(t);f.x=CANVAS_WIDTH/2-t.width/2;f.y=CANVAS_HEIGHT/2+50;q.addChild(f);a=t.width;d=t.height;m=new createjs.Shape;m.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(f.x,f.y,1,d);q.addChild(m);f.mask=m;e=new createjs.Text("","30px "+FONT_GAME,"#fff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2+100;e.textBaseline="alphabetic";e.textAlign="center";q.addChild(e);t=s_oSpriteLibrary.getSprite("but_start");c=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/
2,t,TEXT_PRELOADER_CONTINUE,"Arial","#000","bold 40",q);c.addEventListener(ON_MOUSE_UP,this._onButStartRelease,this);c.setVisible(!1);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);q.addChild(h);createjs.Tween.get(h).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(h);q.removeChild(h)})};this._onButStartRelease=function(){s_oMain._onRemovePreloader()};this.refreshLoader=function(t){e.text=t+"%";100===t&&(s_oMain._onRemovePreloader(),e.visible=
!1,f.visible=!1);m.graphics.clear();t=Math.floor(t*a/100);m.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(f.x,f.y,t,d)};this._init()}
function CMain(a){var d,e=0,f=0,m=STATE_LOADING,h,p;this.initContainer=function(){var c=document.getElementById("canvas");s_oStage=new createjs.Stage(c);createjs.Touch.enable(s_oStage,!0);s_bMobile=isMobile();!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.framerate=FPS;createjs.Ticker.on("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;seekAndDestroy()?h=new CPreloader:window.location.href=
"http://www.codethislab.com/contact-us.html"};this.setLocalStorageLevel=function(c){s_iLastLevel<c&&(s_iLastLevel=c,saveItem("sorcerer_level",s_iLastLevel))};this.setLocalStorageScore=function(c,q,t){saveItem("score_level_"+t,c)};this.clearLocalStorage=function(){s_iLastLevel=1;s_bStorageAvailable&&localStorage.clear()};this.getScoreTillLevel=function(c){if(!s_bStorageAvailable)return 0;for(var q=0,t=0;t<c-1;t++)q+=parseInt(getItem("score_level_"+(t+1)));return q};this.preloaderReady=function(){this._loadImages();
!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();d=!0};this.soundLoaded=function(){e++;h.refreshLoader(Math.floor(e/f*100))};this._initSounds=function(){Howler.mute(!s_bAudioActive);s_aSoundsInfo=[];s_aSoundsInfo.push({path:"./sounds/",filename:"win",loop:!1,volume:1,ingamename:"win"});s_aSoundsInfo.push({path:"./sounds/",filename:"press_but",loop:!1,volume:1,ingamename:"press_but"});s_aSoundsInfo.push({path:"./sounds/",filename:"game_over",loop:!1,volume:1,ingamename:"game_over"});s_aSoundsInfo.push({path:"./sounds/",
filename:"combo",loop:!1,volume:1,ingamename:"combo"});s_aSoundsInfo.push({path:"./sounds/",filename:"shot",loop:!1,volume:1,ingamename:"shot"});s_aSoundsInfo.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});f+=s_aSoundsInfo.length;s_aSounds=[];for(var c=0;c<s_aSoundsInfo.length;c++)this.tryToLoadSound(s_aSoundsInfo[c],!1)};this.tryToLoadSound=function(c,q){setTimeout(function(){s_aSounds[c.ingamename]=new Howl({src:[c.path+c.filename+".mp3"],autoplay:!1,preload:!0,
loop:c.loop,volume:c.volume,onload:s_oMain.soundLoaded,onloaderror:function(t,v){for(var w=0;w<s_aSoundsInfo.length;w++)if(t===s_aSounds[s_aSoundsInfo[w].ingamename]._sounds[0]._id){s_oMain.tryToLoadSound(s_aSoundsInfo[w],!0);break}},onplayerror:function(t){for(var v=0;v<s_aSoundsInfo.length;v++)if(t===s_aSounds[s_aSoundsInfo[v].ingamename]._sounds[0]._id){s_aSounds[s_aSoundsInfo[v].ingamename].once("unlock",function(){s_aSounds[s_aSoundsInfo[v].ingamename].play();"soundtrack"===s_aSoundsInfo[v].ingamename&&
null!==s_oGame&&setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME)});break}}})},q?200:0)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_bg","./sprites/but_play_bg.png");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_continue","./sprites/but_continue.png");s_oSpriteLibrary.addSprite("but_generic_small","./sprites/but_generic_small.png");s_oSpriteLibrary.addSprite("but_exit",
"./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("hero","./sprites/hero.png");s_oSpriteLibrary.addSprite("hit_area","./sprites/hit_area.png");s_oSpriteLibrary.addSprite("explosion","./sprites/explosion.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("extra_score","./sprites/extra_score.png");s_oSpriteLibrary.addSprite("end_path",
"./sprites/end_path.png");s_oSpriteLibrary.addSprite("but_level","./sprites/but_level.png");s_oSpriteLibrary.addSprite("bg_menu_level","./sprites/bg_menu_level.jpg");s_oSpriteLibrary.addSprite("arrow_left","./sprites/arrow_left.png");s_oSpriteLibrary.addSprite("arrow_right","./sprites/arrow_right.png");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("but_exit_small","./sprites/but_exit_small.png");
s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");for(var c=0;c<BALL_COLORS;c++)s_oSpriteLibrary.addSprite("ball_"+c,"./sprites/ball_"+c+".png");s_oSpriteLibrary.addSprite("bg_game_1","./sprites/bg_game_1.jpg");s_oSpriteLibrary.addSprite("bg_game_2","./sprites/bg_game_2.jpg");s_oSpriteLibrary.addSprite("bg_game_3","./sprites/bg_game_3.jpg");s_oSpriteLibrary.addSprite("bg_game_4","./sprites/bg_game_4.jpg");f+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};
this._onImagesLoaded=function(){e++;h.refreshLoader(Math.floor(e/f*100))};this._onAllImagesLoaded=function(){};this._onRemovePreloader=function(){h.unload();this.onLoadedJSON(LEVELS)};this.onLoadedJSON=function(c){try{saveItem("ls_available","ok")}catch(q){s_bStorageAvailable=!1}s_oLevelSettings=new CLevelSettings(c);s_oSoundTrack=playSound("soundtrack",1,!0);s_oMain.gotoMenu()};this.stopUpdate=function(){d=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();d=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this.gotoMenu=function(){new CMenu;m=STATE_MENU};this.gotoLevelMenu=function(){new CLevelMenu};this.gotoGame=function(c,q){p=new CGame(g,c,q);m=STATE_GAME};this.gotoHelp=function(){new CHelp;m=STATE_HELP};this.levelSelected=function(c){c>=s_iLastLevel&&(s_iLastLevel=
c);var q=this.getScoreTillLevel(c);this.gotoGame(c,q)};this._update=function(c){if(!1!==d){var q=(new Date).getTime();s_iTimeElaps=q-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=q;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);m===STATE_GAME&&p.update();void 0!==s_oStage&&s_oStage.update(c)}};s_oMain=this;var g=a;ENABLE_FULLSCREEN=a.fullscreen;ENABLE_CHECK_ORIENTATION=a.check_orientation;s_bAudioActive=a.audio_enable_on_startup;this.initContainer()}
var s_bMobile,s_bAudioActive=!1,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oSoundTrack=null,s_oDrawLayer,s_oStage,s_oMain=null,s_oSpriteLibrary,s_oLevelSettings,s_iLastLevel=1,s_bFullscreen=!1,s_bStorageAvailable=!0,s_aSounds,s_aSoundsInfo;
function CTextButton(a,d,e,f,m,h,p,g){var c,q,t,v,w,y,F,z,H,K;this._init=function(r,x,n,l,B,I,C){c=!1;q=1;t=[];v=[];K=createBitmap(n);z=new createjs.Container;z.x=r;z.y=x;z.regX=n.width/2;z.regY=n.height/2;s_bMobile||(z.cursor="pointer");z.addChild(K,H);g.addChild(z);H=new CTLText(z,10,12,n.width-20,n.height-20,C,"center",I,B,1.1,0,0,l,!0,!0,!1,!1);this._initListener()};this.unload=function(){z.off("mousedown",w);z.off("pressup",y);g.removeChild(z)};this.setVisible=function(r){z.visible=r};this.setAlign=
function(r){H.textAlign=r};this.setTextX=function(r){H.x=r};this.setScale=function(r){q=z.scaleX=z.scaleY=r};this.enable=function(){c=!1};this.disable=function(){c=!0};this._initListener=function(){w=z.on("mousedown",this.buttonDown);y=z.on("pressup",this.buttonRelease)};this.addEventListener=function(r,x,n){t[r]=x;v[r]=n};this.addEventListenerWithParams=function(r,x,n,l){t[r]=x;v[r]=n;F=l};this.buttonRelease=function(){c||(playSound("press_but",1,!1),z.scaleX=q,z.scaleY=q,t[ON_MOUSE_UP]&&t[ON_MOUSE_UP].call(v[ON_MOUSE_UP],
F))};this.buttonDown=function(){c||(z.scaleX=.9*q,z.scaleY=.9*q,t[ON_MOUSE_DOWN]&&t[ON_MOUSE_DOWN].call(v[ON_MOUSE_DOWN]))};this.setPosition=function(r,x){z.x=r;z.y=x};this.tweenPosition=function(r,x,n,l,B,I,C){createjs.Tween.get(z).wait(l).to({x:r,y:x},n,B).call(function(){void 0!==I&&I.call(C)})};this.changeText=function(r){H.refreshText(r)};this.setX=function(r){z.x=r};this.setY=function(r){z.y=r};this.getButtonImage=function(){return z};this.getX=function(){return z.x};this.getY=function(){return z.y};
this.getSprite=function(){return z};this.getScale=function(){return z.scaleX};this._init(a,d,e,f,m,h,p)}
function CGfxButton(a,d,e){var f,m,h=[],p,g,c;this._init=function(q,t,v){f=[];m=[];c=createBitmap(v);c.x=q;c.y=t;c.regX=v.width/2;c.regY=v.height/2;c.cursor="pointer";s_oStage.addChild(c);this._initListener()};this.unload=function(){c.off("mousedown",p);c.off("pressup",g);s_oStage.removeChild(c)};this.setVisible=function(q){c.visible=q};this._initListener=function(){p=c.on("mousedown",this.buttonDown);g=c.on("pressup",this.buttonRelease)};this.addEventListener=function(q,t,v){f[q]=t;m[q]=v};this.addEventListenerWithParams=
function(q,t,v,w){f[q]=t;m[q]=v;h=w};this.buttonRelease=function(){playSound("press_but",1,!1);c.scaleX=1;c.scaleY=1;f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(m[ON_MOUSE_UP],h)};this.buttonDown=function(){c.scaleX=.9;c.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(m[ON_MOUSE_DOWN],h)};this.setPosition=function(q,t){c.x=q;c.y=t};this.setX=function(q){c.x=q};this.setY=function(q){c.y=q};this.getButtonImage=function(){return c};this.getX=function(){return c.x};this.getY=function(){return c.y};this._init(a,
d,e);return this}
function CToggle(a,d,e,f){var m,h,p,g,c,q;this._init=function(t,v,w,y){h=[];p=[];var F=new createjs.SpriteSheet({images:[w],frames:{width:w.width/2,height:w.height,regX:w.width/2/2,regY:w.height/2},animations:{state_true:[0],state_false:[1]}});m=y;q=createSprite(F,"state_"+m,w.width/2/2,w.height/2,w.width/2,w.height);q.x=t;q.y=v;q.stop();q.cursor="pointer";s_oStage.addChild(q);this._initListener()};this.unload=function(){q.off("mousedown",g);q.off("pressup",c);s_oStage.removeChild(q)};this._initListener=
function(){g=q.on("mousedown",this.buttonDown);c=q.on("pressup",this.buttonRelease)};this.addEventListener=function(t,v,w){h[t]=v;p[t]=w};this.setActive=function(t){m=t;q.gotoAndStop("state_"+m)};this.buttonRelease=function(){q.scaleX=1;q.scaleY=1;playSound("press_but",1,!1);m=!m;q.gotoAndStop("state_"+m);h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(p[ON_MOUSE_UP],m)};this.buttonDown=function(){q.scaleX=.9;q.scaleY=.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(p[ON_MOUSE_DOWN])};this.setPosition=function(t,v){q.x=
t;q.y=v};this._init(a,d,e,f)}
function CMenu(){var a,d,e,f,m,h,p,g,c=null,q,t,v,w,y=null,F=null;this._init=function(){p=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(p);if(s_bStorageAvailable){var z=getItem("sorcerer_level");null!==z&&void 0!==z?s_iLastLevel=parseInt(getItem("sorcerer_level")):saveItem("sorcerer_level",1)}else new CAlertSavingBox(TEXT_ERR_LS,s_oStage);1===s_iLastLevel?(g=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-120,s_oSpriteLibrary.getSprite("but_play"),!0),g.addEventListener(ON_MOUSE_UP,
this._onButPlayRelease,this)):(g=new CGfxButton(CANVAS_WIDTH/2-150,CANVAS_HEIGHT-120,s_oSpriteLibrary.getSprite("but_play"),!0),g.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this),c=new CGfxButton(CANVAS_WIDTH/2+150,CANVAS_HEIGHT-120,s_oSpriteLibrary.getSprite("but_continue"),!0),c.addEventListener(ON_MOUSE_UP,this._onButContinueRelease,this));if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)z=s_oSpriteLibrary.getSprite("audio_icon"),m=CANVAS_WIDTH-z.height/2-6,h=z.height/2+6,q=new CToggle(m,
h,z,s_bAudioActive),q.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);z=s_oSpriteLibrary.getSprite("but_credits");e=z.width/2+6;f=z.height/2+6;t=new CGfxButton(e,f,z,s_oStage);t.addEventListener(ON_MOUSE_UP,this._onButCreditsRelease,this);z=window.document;var H=z.documentElement;y=H.requestFullscreen||H.mozRequestFullScreen||H.webkitRequestFullScreen||H.msRequestFullscreen;F=z.exitFullscreen||z.mozCancelFullScreen||z.webkitExitFullscreen||z.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(y=!1);
y&&screenfull.isEnabled&&(z=s_oSpriteLibrary.getSprite("but_fullscreen"),a=e+z.width/2,d=f,w=new CToggle(a,d,z,s_bFullscreen,s_oStage),w.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));v=new createjs.Shape;v.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(v);createjs.Tween.get(v).to({alpha:0},400).call(function(){v.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){g.unload();g=null;t.unload();null!==c&&c.unload();
if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q.unload(),q=null;y&&screenfull.isEnabled&&w.unload();s_oStage.removeChild(p);p=null;s_oStage.removeChild(v);s_oMenu=v=null};this.refreshButtonPos=function(z,H){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||q.setPosition(m-z,H+h);y&&screenfull.isEnabled&&w.setPosition(a+z,d+H);t.setPosition(e+z,f+H)};this._exitFromMenu=function(){this.unload();s_oMain.gotoLevelMenu();$(s_oMain).trigger("start_session")};this._onButPlayRelease=function(){if(1<s_iLastLevel){var z=
new CMsgBox(TEXT_DELETE_SAVINGS,TEXT_NO,"",TEXT_YES);z.addEventListener(ON_MSG_BOX_LEFT_BUT,function(){z.hide()},this);z.addEventListener(ON_MSG_BOX_RIGHT_BUT,function(){z.hide();s_oMain.clearLocalStorage();s_oMenu._exitFromMenu()},this)}else s_oMenu._exitFromMenu()};this._onButContinueRelease=function(){s_oMenu._exitFromMenu()};this._onButCreditsRelease=function(){new CCreditsPanel};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=
function(){y&&screenfull.isEnabled&&w.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?F.call(window.document):y.call(window.document.documentElement);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a,d,e){var f=!1,m,h,p,g,c,q,t,v,w=-1,y,F,z,H,K,r,x,n,l,B,I,C=null,X=null,R=null,N,Q,V,Z,Y,aa,S;this._init=function(k,b){x=k;g=b;s_oBezier=new CBezier;S=new createjs.Container;Q=createBitmap(s_oSpriteLibrary.getSprite(s_oLevelSettings.getBgForLevel(x)));S.addChild(Q);s_oStage.addChild(S);Q.cache(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);N=new CHero;Y=new createjs.Container;Z=new createjs.Container;aa=new createjs.Container;s_oStage.addChild(Y);s_oStage.addChild(Z);s_oStage.addChild(aa);V=new CInterface(g);
this.reset();if(!1===s_bMobile){var A=this;s_oStage.addEventListener("stagemousemove",function(u){A._onMouseMove(u.stageX,u.stageY)})}f=!0};this.unload=function(){f=!1;clearInterval(z);V.unload();N.unload();s_oStage.removeAllChildren()};this.reset=function(){m=!0;p=h=!1;v=s_oLevelSettings.getBallSpeedForLevel(x);t=s_oLevelSettings.getBallNumberForLevel(x);K=s_oLevelSettings.getBallColorsForLevel(x);BALL_ROLLING_IN=Math.floor(.33*t);y=0;q=F=1;c=r=0;N.reset(s_oLevelSettings.getHeroPosForLevel(x),K);
null!==X&&(Y.removeChild(X),Y.removeChild(R));this._initCurve();this._initBall();V.refreshLevel(x);$(s_oMain).trigger("start_level",x)};this._normalize=function(k){var b=this._length(k);return 0<b?{x:k.x/b,y:k.y/b}:k};this._length=function(k){return Math.sqrt(k.x*k.x+k.y*k.y)};this._dotProductV2=function(k,b){return k.x*b.x+k.y*b.y};this._angleBetweenVectors=function(k,b){var A=Math.acos(this._dotProductV2(k,b)/(this._length(k)*this._length(b)));return!0===isNaN(A)?0:A};this._rot90CW=function(k){return{x:k.y,
y:-k.x}};this._rot90CCW=function(k){return{x:-k.y,y:k.x}};this._rotateVector2D=function(k,b){return{x:b.x*Math.cos(k)+b.y*Math.sin(k),y:b.x*-Math.sin(k)+b.y*Math.cos(k)}};this._initCurve=function(){var k;var b=s_oLevelSettings.getCurveForLevel(x);var A=new createjs.Graphics;l=[];for(k=0;k<b.length-2;++k){var u=0===k?new createjs.Point(b[0][0],b[0][1]):new createjs.Point((b[k][0]+b[k+1][0])/2,(b[k][1]+b[k+1][1])/2),G=new createjs.Point(b[k+1][0],b[k+1][1]),J=k<=b.length-4?new createjs.Point((b[k+1][0]+
b[k+2][0])/2,(b[k+1][1]+b[k+2][1])/2):new createjs.Point(b[k+2][0],b[k+2][1]);u=s_oBezier.init(u,G,J,STEP_LENGTH);for(G=1;G<=u;++G)J=s_oBezier.getAnchorPoint(G),l.push(J)}A.setStrokeStyle(4);A.beginStroke(PATH_COLOR_STROKE);A.beginFill(PATH_COLOR);u={x:l[1][0]-l[0][0],y:l[1][1]-l[0][1]};u=this._normalize(u);u=this._rot90CW(u);u.x*=15;u.y*=15;u.x+=l[0][0];u.y+=l[0][1];b=u.x;k=u.y;A.moveTo(u.x,u.y);for(G=1;G<l.length-1;G++)u={x:l[G+1][0]-l[G][0],y:l[G+1][1]-l[G][1]},u=this._normalize(u),u=this._rot90CW(u),
u.x*=15,u.y*=15,u.x+=l[G][0],u.y+=l[G][1],A.lineTo(u.x,u.y);A.lineTo(u.x,u.y);u={x:l[l.length-1][0]-l[l.length-2][0],y:l[l.length-1][1]-l[l.length-2][1]};u=this._normalize(u);u=this._rot90CCW(u);u.x*=15;u.y*=15;u.x+=l[l.length-1][0];u.y+=l[l.length-1][1];A.lineTo(u.x,u.y);for(G=l.length-2;1<G;G--)u={x:l[G][0]-l[G-1][0],y:l[G][1]-l[G-1][1]},u=this._normalize(u),u=this._rot90CCW(u),u.x*=15,u.y*=15,u.x+=l[G][0],u.y+=l[G][1],A.lineTo(u.x,u.y);A.lineTo(b,k);A.endFill();X=new createjs.Shape(A);Y.addChild(X);
A=l.length;b=s_oSpriteLibrary.getSprite("end_path");R=createBitmap(b);R.x=l[A-9][0];R.y=l[A-9][1];R.regX=b.width/2;R.regY=b.height/2;Y.addChild(R);Y.cache(0,0,CANVAS_WIDTH,CANVAS_HEIGHT)};this._initBall=function(){n=[];var k=this.getRandomBall();n.unshift(k);k.setPos(16,l);w=STATE_GAME_ROLL_IN};this.getRandomBall=function(){t--;return new CBall(Math.floor(Math.random()*K),Z)};this._pushNextBall=function(k,b){var A=[];A.push(n[k]);for(var u=k;u<n.length-1;++u)if(16>=n[u+1].getFotogram()-n[u].getFotogram())16>
n[u+1].getFotogram()-n[u].getFotogram()&&n[u+1].setPos(n[u].getFotogram()+16,l),A.push(n[u+1]);else break;for(u=0;u<A.length;++u)A[u].increasePos(b,l);if(n[n.length-1].getFotogram()>=l.length-17){m=!1;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_aSounds.soundtrack.pause(),playSound("game_over",1,!1).on("end",this._onSoundGameOverComplete);s_oStage.removeEventListener("stagemousemove");p=h=!1;q=1;n[n.length-1].unload();n.splice(n.length-1,1);w=STATE_GAME_ROLL_OUT}};this.onIntroduceBall=function(){if(0!==
n.length&&(s_oGame._pushNextBall(0,1),32===n[0].getFotogram()&&0!==t)){var k=s_oGame.getRandomBall();n.unshift(k);k.setPos(16,l)}};this.shoot=function(){playSound("shot",1,!1);var k=(N.getRotation()+90)*Math.PI/180,b=N.getCurrentBall();b.changePos(N.getX()+60*Math.cos(k),N.getY()+60*Math.sin(k));Z.addChild(b.getSprite());b.setContainer(Z);B.push([b,k]);w=STATE_GAME_SHOOTING};this._checkCollision=function(k){k=k[0];for(var b=0;b<n.length;++b)if((n[b].getX()-k.getX())*(n[b].getX()-k.getX())+(n[b].getY()-
k.getY())*(n[b].getY()-k.getY())<=BALL_DIAMETER_SQUARE)return b;return-1};this._insertBall=function(k,b,A){if("next"===A){var u=n[b].getFotogram()+16;n[b+1]&&32>n[b+1].getFotogram()-n[b].getFotogram()&&(I.push([k,n[b+1]]),h=!0)}else n[b-1]&&32>n[b].getFotogram()-n[b-1].getFotogram()?(u=n[b-1].getFotogram()+16,I.push([k,n[b]]),h=!0):u=n[b].getFotogram()-16;b=l[u][0];A=l[u][1];var G=this;createjs.Tween.get(k.getSprite()).to({x:b,y:A},200).call(function(){G.motionFinished(k,u)})};this.motionFinished=
function(k,b){for(var A,u=0;u<n.length;++u){if(n[u].getFotogram()>b){A=u;break}u===n.length-1&&(A=u+1)}I.splice(I.indexOf(k),1);k.setPos(b,l);n.splice(A,0,k);n[A-1]&&n[A-1].getIndex()===n[A].getIndex()&&17<n[A].getFotogram()-n[A-1].getFotogram()&&this._addToBallAttracted(n[A]);n[A+1]&&n[A+1].getIndex()===n[A].getIndex()&&17<n[A+1].getFotogram()-n[A].getFotogram()&&this._addToBallAttracted(n[A+1]);this._clearCheck(A,!0)};this._addToBallAttracted=function(k){null===C&&(C=[]);C.push(k);setTimeout(function(){p=
!0},400)};this._clearCheck=function(k,b){var A=[];A.push(n[k]);for(var u=n[k].getIndex(),G=k+1;n[G];)if(n[G].getIndex()===u)if(17>=n[G].getFotogram()-n[G-1].getFotogram())A.push(n[G]),++G;else if(b)break;else A.push(n[G]),++G;else break;for(G=k-1;n[G];)if(n[G].getIndex()===u)if(17>=n[G+1].getFotogram()-n[G].getFotogram())A.push(n[G]),--G;else if(b)break;else A.push(n[G]),--G;else break;++G;2<A.length&&b&&this._clearBall(G,A);return A.length};this._attract=function(){if(0!==C.length)for(var k=0;k<
C.length;++k){var b=n.indexOf(C[k]);if(-1!==b&&n[b-1])if(C[k].getIndex()===n[b-1].getIndex()){var A=19<C[k].getFotogram()-n[b-1].getFotogram()?3:C[k].getFotogram()-n[b-1].getFotogram()-16;this._pushNextBall(b,-A);16>=C[k].getFotogram()-n[b-1].getFotogram()&&(q++,C.splice(k,1),this._clearCheck(b-1,!0),0===C.length&&(p=!1,q=1))}else C.splice(k,1),y>F&&(F=y),y=0}else p=!1,q=1};this._checkPushCollision=function(){if(0!==I.length)for(var k=0;k<I.length;++k){var b=(I[k][0].getX()-I[k][1].getX())*(I[k][0].getX()-
I[k][1].getX())+(I[k][0].getY()-I[k][1].getY())*(I[k][0].getY()-I[k][1].getY());b=b<BALL_DIAMETER_SQUARE?!0:!1;for(var A=0;b;)++A,b=(I[k][0].getX()-l[I[k][1].getFotogram()+A][0])*(I[k][0].getX()-l[I[k][1].getFotogram()+A][0])+(I[k][0].getY()-l[I[k][1].getFotogram()+A][1])*(I[k][0].getY()-l[I[k][1].getFotogram()+A][1]),b=b<BALL_DIAMETER_SQUARE?!0:!1;b=n.indexOf(I[k][1]);-1!==b&&this._pushNextBall(b,A)}else h=!1};this._clearBall=function(k,b){++y;playSound("combo",1,!1);for(var A=0,u=0;u<b.length;++u)b[u].explode(),
A+=COMBO_VALUE;A*=q;g+=A;c+=A;V.refreshScore(g);n.length===b.length&&(m=!1,H=n[n.length-1].getFotogram(),setTimeout(this._gamePass,600),!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&(s_aSounds.soundtrack.pause(),playSound("win",1,!1).on("end",this._onSoundGameOverComplete));n.splice(k,b.length);0===t&&this._checkColor(b[0].getIndex());n[k-1]&&n[k]&&n[k-1].getIndex()===n[k].getIndex()?(3>this._clearCheck(k,!1)&&(y>F&&(F=y),y=0),this._addToBallAttracted(n[k])):(y>F&&(F=y),y=0)};this._gamePass=function(){z=
setInterval(s_oGame._extraScore,v)};this._extraScore=function(){H+16<l.length-17?(H+=16,new CExtraScore(l[H][0],l[H][1],aa),g+=EXTRA_SCORE,c+=EXTRA_SCORE,V.refreshScore(g)):($(s_oMain).trigger("end_level",x),clearInterval(z),s_oStage.removeEventListener("stagemousemove"),m=!1,s_oMain.setLocalStorageScore(c,g,x),x++,x>s_oLevelSettings.getNumLevels()?(x--,V.win(g)):(s_oMain.setLocalStorageLevel(x),V.nextLevel(x,g)))};this._checkColor=function(k){for(var b=0;b<n.length;++b)if(n[b].getIndex()===k)return;
for(b=0;b<B.length;++b)if(B[b].getIndex()===k)return;N.colorCleared(k)};this.nextLevel=function(){S.removeChild(Q);Q=createBitmap(s_oSpriteLibrary.getSprite(s_oLevelSettings.getBgForLevel(x)));S.addChild(Q);this.reset();f=!0};this.onShot=function(k,b){if(m&&N.canShoot()){if(s_bMobile){var A=k-N.getX()*s_iScaleFactor,u=b-N.getY()*s_iScaleFactor;N.rotate(180*Math.atan2(u,A)/Math.PI-90)}this.shoot()}};this._onMouseMove=function(k,b){var A=k-N.getX()*s_iScaleFactor,u=b-N.getY()*s_iScaleFactor;N.rotate(180*
Math.atan2(u,A)/Math.PI-90)};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_session");$(s_oMain).trigger("share_event",g)};this._onSoundGameOverComplete=function(){playSound("soundtrack",1,!0)};this._updateMove=function(){r+=s_iTimeElaps;r>v&&(r=0,this.onIntroduceBall())};this._updateRollOut=function(){for(var k=n.length-1;0<=k;--k)n[k].getFotogram()>l.length-17?(n[k].unload(),n.splice(k,1),0===n.length&&(w=-1,V.gameOver(g))):n[k].increasePos(8,l)};this._updateRollIn=
function(){if(n.length<BALL_ROLLING_IN){for(var k=0;k<n.length;++k)n[k].increasePos(4,l);32===n[0].getFotogram()&&(k=this.getRandomBall(),n.unshift(k),k.setPos(16,l))}else w=-1,B=[],I=[],N.start(),w=STATE_GAME_BALL_MOVE};this._updateShooting=function(){if(0!==B.length)for(var k=0;k<B.length;++k)if(0<B[k][0].getX()&&B[k][0].getX()<CANVAS_WIDTH&&0<B[k][0].getY()&&B[k][0].getY()<CANVAS_HEIGHT){var b=this._checkCollision(B[k]);if(-1===b)B[k][0].increasePosWithNumbers(Math.cos(B[k][1])*BALL_SHOOTED_SPEED,
Math.sin(B[k][1])*BALL_SHOOTED_SPEED);else{var A=B[k][0],u=B[k][1],G=Math.sqrt((n[b].getX()-A.getX())*(n[b].getX()-A.getX())+(n[b].getY()-A.getY())*(n[b].getY()-A.getY()));B[k][0].decreasePos((BALL_DIAMETER-G)*Math.cos(u),(BALL_DIAMETER-G)*Math.sin(u));u=l[n[b].getFotogram()-BALL_RADIUS][0];G=l[n[b].getFotogram()-BALL_RADIUS][1];u=Math.sqrt((A.getX()-u)*(A.getX()-u)+(A.getY()-G)*(A.getY()-G));G=l[n[b].getFotogram()+BALL_RADIUS][0];var J=l[n[b].getFotogram()+BALL_RADIUS][1];A=Math.sqrt((A.getX()-G)*
(A.getX()-G)+(A.getY()-J)*(A.getY()-J));this._insertBall(B[k][0],b,u>A?"next":"previous");B.splice(k,1)}}else B[k][0].unload(),B.splice(k,1);else w=-1};this.update=function(){if(!1!==f)switch(!0===p&&this._attract(),!0===h&&this._checkPushCollision(),w){case STATE_GAME_ROLL_IN:this._updateRollIn();break;case STATE_GAME_ROLL_OUT:this._updateRollOut();break;case STATE_GAME_SHOOTING:this._updateShooting();this._updateMove();break;default:this._updateMove()}};s_oGame=this;COMBO_VALUE=a.combo_value;EXTRA_SCORE=
a.extra_score;this._init(d,e)}var s_oGame,s_oBezier;
function CInterface(a){var d,e,f,m,h,p,g,c,q,t,v,w,y,F,z,H,K,r,x=null,n=null;this._init=function(l){c=g=10;w=new createjs.Text(TEXT_SCORE+" "+l,"38px "+FONT_GAME,"#fff");w.x=g;w.y=c;w.textAlign="left";s_oStage.addChild(w);h=10;p=50;v=new createjs.Text(TEXT_LEVEL+" "+s_iLastLevel,"30px "+FONT_GAME,"#fff");v.x=h;v.y=p;v.textAlign="left";s_oStage.addChild(v);var B=this;F=createBitmap(s_oSpriteLibrary.getSprite("hit_area"));s_oStage.addChild(F);F.on("pressup",function(C){B._onTapScreen(C.stageX,C.stageY)});
l=s_oSpriteLibrary.getSprite("but_exit");d=CANVAS_WIDTH-l.width/2-6;e=l.height/2+6;y=new CGfxButton(d,e,l,!0);y.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q=d-l.width,t=l.height/2+6,l=s_oSpriteLibrary.getSprite("audio_icon"),z=new CToggle(q,t,l,s_bAudioActive),z.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);l=window.document;var I=l.documentElement;x=I.requestFullscreen||I.mozRequestFullScreen||I.webkitRequestFullScreen||I.msRequestFullscreen;
n=l.exitFullscreen||l.mozCancelFullScreen||l.webkitExitFullscreen||l.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(x=!1);x&&screenfull.isEnabled&&(l=s_oSpriteLibrary.getSprite("but_fullscreen"),f=d,m=CANVAS_HEIGHT-l.height/2,r=new CToggle(f,m,l,s_bFullscreen,s_oStage),r.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));K=new CNextLevel;H=new CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){y.unload();y=null;!1===DISABLE_SOUND_MOBILE&&
(z.unload(),z=null);x&&screenfull.isEnabled&&r.unload();s_oStage.removeAllChildren();s_oInterface=null};this.refreshButtonPos=function(l,B){w.x=g+l;w.y=c+B;v.x=h+l;v.y=p+B;y.setPosition(d-l,e+B);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||z.setPosition(q-l,B+t);x&&screenfull.isEnabled&&r.setPosition(f-l,m-B)};this._onTapScreen=function(l,B){s_oGame.onShot(l,B)};this.gameOver=function(l){H.show(l,!1)};this.win=function(l){H.show(l,!0)};this.nextLevel=function(l,B){K.show(l,B)};this.refreshScore=function(l){w.text=
TEXT_SCORE+" "+l};this.refreshLevel=function(l){v.text=TEXT_LEVEL+" "+l};this._onExit=function(){s_oGame.onExit()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=function(){x&&screenfull.isEnabled&&r.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?n.call(window.document):x.call(window.document.documentElement);sizeHandler()};s_oInterface=this;this._init(a);return this}var s_oInterface=null;
function CEndPanel(a){var d,e,f,m,h,p;this._init=function(g){p=new createjs.Container;p.alpha=0;p.visible=!1;s_oStage.addChild(p);d=createBitmap(g);p.addChild(d);h=new CTLText(p,CANVAS_WIDTH/2-80,CANVAS_HEIGHT/2-68,210,30,50,"center","#000",FONT_GAME,1.1,0,0,TEXT_CONGRATS,!0,!0,!0,!1);m=new CTLText(p,CANVAS_WIDTH/2-80,CANVAS_HEIGHT/2-68,210,30,50,"center","#fff",FONT_GAME,1.1,0,0,TEXT_CONGRATS,!0,!0,!0,!1);e=new CTLText(p,CANVAS_WIDTH/2-80,CANVAS_HEIGHT/2-15,200,70,50,"center","#000",FONT_GAME,1.1,
0,0,TEXT_FINAL_SCORE+"\n99999",!0,!0,!0,!1);f=new CTLText(p,CANVAS_WIDTH/2-80,CANVAS_HEIGHT/2-15,200,70,50,"center","#fff",FONT_GAME,1.1,0,0,TEXT_FINAL_SCORE+"\n99999",!0,!0,!0,!1)};this.unload=function(){p.off("mousedown",this._onExit);s_oStage.removeChild(p)};this._initListener=function(){p.on("mousedown",this._onExit);$(s_oMain).trigger("show_interlevel_ad")};this.show=function(g,c){c?(h.refreshText(TEXT_CONGRATS),m.refreshText(TEXT_CONGRATS)):(h.refreshText(TEXT_GAMEOVER),m.refreshText(TEXT_GAMEOVER));
e.refreshText(TEXT_FINAL_SCORE+"\n "+g);f.refreshText(TEXT_FINAL_SCORE+"\n "+g);p.visible=!0;var q=this;createjs.Tween.get(p).to({alpha:1},500).call(function(){q._initListener()});$(s_oMain).trigger("save_score",g)};this._onExit=function(){p.off("mousedown");s_oGame.onExit()};this._init(a);return this}
function CTweenController(){this.tweenValue=function(a,d,e){return a+e*(d-a)};this.easeLinear=function(a,d,e,f){return e*a/f+d};this.easeInCubic=function(a,d,e,f){f=(a/=f)*a*a;return d+e*f};this.easeBackInQuart=function(a,d,e,f){f=(a/=f)*a;return d+e*(2*f*f+2*f*a+-3*f)};this.easeInBack=function(a,d,e,f){return e*(a/=f)*a*(2.70158*a-1.70158)+d};this.easeOutCubic=function(a,d,e,f){return e*((a=a/f-1)*a*a+1)+d}}
function CLevelSettings(a){var d,e,f,m,h,p,g;this._init=function(c){d=c;NUM_LEVELS=Object.keys(d).length;this._initBallSpeed();this._initBallNumber();this._initBallColors();this._initHeroPos();this._initCurveLevel();this._initBgLevel()};this._initBallSpeed=function(){e=[];for(var c=0;c<NUM_LEVELS;c++)e[c]=d[c].ball_speed};this._initBallNumber=function(){f=[];for(var c=0;c<NUM_LEVELS;c++)f[c]=d[c].ball_number};this._initBallColors=function(){m=[];for(var c=0;c<NUM_LEVELS;c++)m[c]=d[c].num_colors};
this._initHeroPos=function(){h=[];for(var c=0;c<NUM_LEVELS;c++)h[c]=new createjs.Point(d[c].hero_pos.x,d[c].hero_pos.y)};this._initCurveLevel=function(){p=[];for(var c=0;c<NUM_LEVELS;c++){p[c]=[];for(var q=d[c].curve_point,t=0;t<q.length;t++)p[c].push([q[t].x,q[t].y])}};this._initBgLevel=function(){g=[];for(var c=0;c<NUM_LEVELS;c++)g[c]=d[c].bg_image};this.getBallSpeedForLevel=function(c){return e[c-1]};this.getBallNumberForLevel=function(c){return f[c-1]};this.getBallColorsForLevel=function(c){return m[c-
1]};this.getHeroPosForLevel=function(c){return h[c-1]};this.getCurveForLevel=function(c){return p[c-1]};this.getNumLevels=function(){return p.length};this.getBgForLevel=function(c){return g[c-1]};this._init(a)}
function CHero(){var a=!1,d,e,f,m,h,p,g,c,q,t;this._init=function(){var v=s_oSpriteLibrary.getSprite("hero");t=new createjs.Container;t.regX=v.width/2;t.regY=v.height/2;s_oStage.addChild(t);g=createBitmap(v);g.x=0;g.y=0;t.addChild(g);c=new createjs.Shape;c.graphics.beginFill("rgba(255,0,0,0.01)").drawCircle(40,110,16);t.addChild(c);q=new createjs.Shape;q.graphics.beginFill("rgba(255,0,0,0.01)").drawCircle(120,60,6);t.addChild(q);d=v.width;e=v.height};this.reset=function(v,w){f=w;void 0!==h&&null!==
h&&h.unload();void 0!==p&&null!==p&&p.unload();t.x=v.x;t.y=v.y;m=[];for(var y=0;y<f;y++)m[y]=!0};this.unload=function(){};this.rotate=function(v){t.rotation=v};this.start=function(){h=this._getRandomBall();h.changePos(d/2-25,e/2+20);h.getSprite().mask=c;p=this._getRandomBall();p.changePos(120,e/2-12);p.getSprite().mask=q;var v=this;createjs.Tween.get(h.getSprite()).to({y:h.getY()+25},300).call(function(){v._onBallReady()});createjs.Tween.get(p.getSprite()).to({y:p.getY()+16},300)};this._getRandomBall=
function(){if(!0===this._checkIfAllColorsNotAvailable())return null;do{var v=Math.floor(Math.random()*f),w=!1;if(!0===m[v]){var y=new CBall(v,t);break}}while(!1===w);return y};this._checkIfAllColorsNotAvailable=function(){for(var v=!0,w=0;w<m.length;w++)!0===m[w]&&(v=!1);return v};this._nextShoot=function(){null!==h&&h.unload();h=p;h.changePos(d/2-25,e/2+20);h.getSprite().mask=c;p=this._getRandomBall();p.changePos(120,e/2-12);p.getSprite().mask=q;var v=this;createjs.Tween.get(h.getSprite()).to({y:h.getY()+
25},300).call(function(){v._onBallReady()});createjs.Tween.get(p.getSprite()).to({y:p.getY()+16},300)};this.colorCleared=function(v){m[v]=!1;h.getIndex()===v&&(h.unload(),h=this._getRandomBall(),null!==h&&(h.changePos(d/2-25,e/2+45),h.getSprite().mask=c));p.getIndex()===v&&(p.unload(),p=this._getRandomBall(),null!==p&&(p.changePos(120,e/2+4),p.getSprite().mask=q))};this._onBallReady=function(){a=!0};this.getCurrentBall=function(){a=!1;var v=h;this._nextShoot();return v};this.getX=function(){return t.x};
this.getY=function(){return t.y};this.getRotation=function(){return t.rotation};this.canShoot=function(){return a};this._init()}
function CBezier(){var a,d,e,f,m,h,p,g,c,q,t,v;this.init=function(w,y,F,z){a=w;d=y;e=F;m=a.x-2*d.x+e.x;h=a.y-2*d.y+e.y;p=2*d.x-2*a.x;g=2*d.y-2*a.y;c=4*(m*m+h*h);q=4*(m*p+h*g);t=p*p+g*g;v=this._length(1);f=Math.floor(v/z);v%z>z/2&&f++;return f};this._speed=function(w){return Math.sqrt(c*w*w+q*w+t)};this._length=function(w){var y=Math.sqrt(t+w*(q+c*w));return(2*Math.sqrt(c)*(2*c*w*y+q*(y-Math.sqrt(t)))+(q*q-4*c*t)*(Math.log(q+2*Math.sqrt(c)*Math.sqrt(t))-Math.log(q+2*c*w+2*Math.sqrt(c)*y)))/(8*Math.pow(c,
1.5))};this.invertL=function(w,y){var F=w;do{var z=F-(this._length(F)-y)/this._speed(F);if(1E-6>Math.abs(F-z))break;F=z}while(1);return z};this.getAnchorPoint=function(w){if(0<=w&&w<=f){var y=w/f;y=this.invertL(y,y*v);w=(1-y)*(1-y)*a.x+2*(1-y)*y*d.x+y*y*e.x;var F=(1-y)*(1-y)*a.y+2*(1-y)*y*d.y+y*y*e.y,z=new createjs.Point((1-y)*a.x+y*d.x,(1-y)*a.y+y*d.y);y=new createjs.Point((1-y)*d.x+y*e.x,(1-y)*d.y+y*e.y);return[w,F,180*Math.atan2(y.y-z.y,y.x-z.x)/Math.PI]}return[]}}
function CBall(a,d){var e,f,m,h,p;this._init=function(g,c){e=g;f=0;p=c;var q=s_oSpriteLibrary.getSprite("ball_"+e);BALL_DIAMETER=q.width;BALL_DIAMETER_SQUARE=BALL_DIAMETER*BALL_DIAMETER;BALL_RADIUS=BALL_DIAMETER/2;q=new createjs.SpriteSheet({images:[q],frames:{width:BALL_DIAMETER,height:BALL_DIAMETER,regX:BALL_RADIUS,regY:BALL_RADIUS},animations:{move:[0,49]}});m=createSprite(q,null,BALL_RADIUS,BALL_RADIUS,BALL_DIAMETER,BALL_DIAMETER);m.stop();p.addChild(m)};this.unload=function(){p.removeChild(h);
p.removeChild(m)};this.nextFrame=function(){m.gotoAndStop(50===m.currentFrame+1?0:m.currentFrame+1)};this.prevFrame=function(){m.gotoAndStop(0>m.currentFrame-1?49:m.currentFrame-1)};this.setPos=function(g,c){g>f?this.nextFrame():g<f&&this.prevFrame();f=g;m.x=c[f][0];m.y=c[f][1];m.rotation=c[f][2]-90};this.changePos=function(g,c){m.x=g;m.y=c};this.increasePosWithNumbers=function(g,c){m.x+=g;m.y+=c};this.decreasePos=function(g,c){m.x-=g;m.y-=c};this.increasePos=function(g,c){this.setPos(f+g,c)};this.setContainer=
function(g){m.mask=null;p=g};this.explode=function(){var g={images:[s_oSpriteLibrary.getSprite("explosion")],frames:{width:30,height:30,regX:15,regY:15},animations:{show:[0,19],hide:[20]}},c=this;g=new createjs.SpriteSheet(g,"show");h=new createjs.Sprite(g);p.addChild(h);h.x=m.x;h.y=m.y;h.gotoAndPlay("show");createjs.Tween.get(m).to({alpha:0},1E3,createjs.Ease.cubicOut).call(function(){m.visible=!1});createjs.Tween.get(h).to({alpha:0},1200,createjs.Ease.cubicOut).call(function(){c.onExplosionEnd()})};
this.onExplosionEnd=function(){p.removeChild(h);p.removeChild(m)};this.rollInStage=function(){};this.getFotogram=function(){return f};this.getSprite=function(){return m};this.getIndex=function(){return e};this.getX=function(){return m.x};this.getY=function(){return m.y};this._init(a,d)}
function CNextLevel(){var a,d,e,f,m,h;this._init=function(){h=new createjs.Container;h.alpha=0;h.visible=!1;s_oStage.addChild(h);a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));h.addChild(a);e=new CTLText(h,CANVAS_WIDTH/2-80,CANVAS_HEIGHT/2-68,210,30,50,"center","#000",FONT_GAME,1.1,0,0,TEXT_CONGRATS,!0,!0,!0,!1);d=new CTLText(h,CANVAS_WIDTH/2-80,CANVAS_HEIGHT/2-68,210,30,50,"center","#fff",FONT_GAME,1.1,0,0,TEXT_CONGRATS,!0,!0,!0,!1);m=new CTLText(h,CANVAS_WIDTH/2-80,CANVAS_HEIGHT/2-15,200,
70,50,"center","#000",FONT_GAME,1.1,0,0,TEXT_FINAL_SCORE+"\n99999",!0,!0,!0,!1);f=new CTLText(h,CANVAS_WIDTH/2-80,CANVAS_HEIGHT/2-15,200,70,50,"center","#fff",FONT_GAME,1.1,0,0,TEXT_FINAL_SCORE+"\n99999",!0,!0,!0,!1)};this.show=function(p,g){e.refreshText(TEXT_LEVEL+" "+p);d.refreshText(TEXT_LEVEL+" "+p);m.refreshText(TEXT_SCORE+" "+g);f.refreshText(TEXT_SCORE+" "+g);h.visible=!0;var c=this;createjs.Tween.get(h).to({alpha:1},500).call(function(){c._initListener()});$(s_oMain).trigger("save_score",
g)};this._initListener=function(){h.on("mousedown",this._onExit);$(s_oMain).trigger("show_interlevel_ad")};this._onExit=function(){h.off("mousedown");h.alpha=0;h.visible=!1;s_oGame.nextLevel()};this._init()}function CExtraScore(a,d,e){var f;this._init=function(m,h,p){var g=s_oSpriteLibrary.getSprite("extra_score");f=createBitmap(g);f.x=m;f.y=h;f.regX=g.width/2;f.regY=g.height/2;f.alpha=0;p.addChild(f);createjs.Tween.get(f).to({alpha:1},1E3).call(function(){p.removeChild(f)})};this._init(a,d,e)}
function CLevelMenu(){var a,d,e,f,m,h,p,g,c,q,t,v,w,y=null,F=null,z,H,K=null,r=null;this._init=function(){p=0;z=new createjs.Container;s_oStage.addChild(z);var x=createBitmap(s_oSpriteLibrary.getSprite("bg_menu_level"));z.addChild(x);new CTLText(s_oStage,230,90,500,60,100,"center","#fff",FONT_GAME,1.1,0,0,TEXT_SELECT_LEVEL,!0,!0,!0,!1);x=s_oSpriteLibrary.getSprite("but_exit");m=CANVAS_WIDTH-x.width/2-6;h=x.height/2+6;v=new CGfxButton(m,h,x,!0);v.addEventListener(ON_MOUSE_UP,this._onExit,this);g=x.height;
if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e=v.getX()-x.width,f=x.height/2+6,w=new CToggle(e,f,s_oSpriteLibrary.getSprite("audio_icon"),s_bAudioActive),w.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);x=window.document;var n=x.documentElement;K=n.requestFullscreen||n.mozRequestFullScreen||n.webkitRequestFullScreen||n.msRequestFullscreen;r=x.exitFullscreen||x.mozCancelFullScreen||x.webkitExitFullscreen||x.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(K=!1);K&&screenfull.isEnabled&&(x=s_oSpriteLibrary.getSprite("but_fullscreen"),
a=x.width/4+6,d=x.height/2+6,H=new CToggle(a,d,x,s_bFullscreen,s_oStage),H.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));this._checkBoundLimits();q=[];x=Math.floor((CANVAS_WIDTH-2*EDGEBOARD_X)/NUM_COLS_PAGE_LEVEL)/2;for(var l=n=0;l<NUM_COLS_PAGE_LEVEL;l++)q.push(n),n+=2*x;t=[];this._createNewLevelPage(0,NUM_LEVELS);if(1<t.length){for(x=1;x<t.length;x++)t[x].visible=!1;y=new CGfxButton(CANVAS_WIDTH/2+280,CANVAS_HEIGHT-80,s_oSpriteLibrary.getSprite("arrow_right"),!0);y.addEventListener(ON_MOUSE_UP,
this._onRight,this);F=new CGfxButton(CANVAS_WIDTH/2-280,CANVAS_HEIGHT-80,s_oSpriteLibrary.getSprite("arrow_left"),!0);F.addEventListener(ON_MOUSE_UP,this._onLeft,this)}this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){for(var x=0;x<c.length;x++)c[x].unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||w.unload();K&&screenfull.isEnabled&&H.unload();v.unload();null!==F&&(F.unload(),y.unload());s_oLevelMenu=null};this.refreshButtonPos=function(x,n){v.setPosition(m-x,h+n);!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||w.setPosition(e-x,n+f);K&&screenfull.isEnabled&&H.setPosition(a+x,d+n)};this._checkBoundLimits=function(){for(var x=s_oSpriteLibrary.getSprite("but_level"),n=0,l=CANVAS_HEIGHT-2*EDGEBOARD_Y-2*g,B=0;n<l;)n+=x.height+20,B++;NUM_ROWS_PAGE_LEVEL>B&&(NUM_ROWS_PAGE_LEVEL=B);l=n=0;B=CANVAS_WIDTH-2*EDGEBOARD_X;for(x=s_oSpriteLibrary.getSprite("but_level");l<B;)l+=x.width/2+5,n++;NUM_COLS_PAGE_LEVEL>n&&(NUM_COLS_PAGE_LEVEL=n)};this._createNewLevelPage=function(x,n){var l=new createjs.Container;
z.addChild(l);t.push(l);c=[];for(var B=0,I=0,C=1,X=!1,R=s_oSpriteLibrary.getSprite("but_level"),N=x;N<n;N++){var Q=new CLevelBut(q[B]+R.width/4,I+R.height/2,N+1,R,N+1>s_iLastLevel?!1:!0,l);Q.addEventListenerWithParams(ON_MOUSE_UP,this._onButLevelRelease,this,N);c.push(Q);B++;if(B===q.length&&(B=0,I+=R.height+20,C++,C>NUM_ROWS_PAGE_LEVEL)){X=!0;break}}l.x=CANVAS_WIDTH/2;l.y=CANVAS_HEIGHT/2;l.regX=l.getBounds().width/2;l.regY=l.getBounds().height/2;X&&this._createNewLevelPage(N+1,n)};this._onRight=
function(){t[p].visible=!1;p++;p>=t.length&&(p=0);t[p].visible=!0};this._onLeft=function(){t[p].visible=!1;p--;0>p&&(p=t.length-1);t[p].visible=!0};this._onButLevelRelease=function(x){s_oMain.levelSelected(x+1)};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=function(){K&&screenfull.isEnabled&&H.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?r.call(window.document):K.call(window.document.documentElement);
sizeHandler()};this._onExit=function(){s_oMain.gotoMenu()};s_oLevelMenu=this;this._init()}var s_oLevelMenu=null;
function CLevelBut(a,d,e,f,m,h){var p,g,c,q=[],t=[],v,w,y,F;this._init=function(H,K,r,x,n){g=[];c=[];F=new createjs.Container;z.addChild(F);var l=new createjs.SpriteSheet({images:[x],frames:{width:x.width/2,height:x.height,regX:x.width/2/2,regY:x.height/2},animations:{state_true:[0],state_false:[1]}});p=n;y=createSprite(l,"state_"+p,x.width/2/2,x.height/2,x.width/2,x.height);y.mouseEnabled=n;y.x=H;y.y=K;y.stop();s_bMobile||(F.cursor="pointer");F.addChild(y);q.push(y);v=new createjs.Text(r,"60px "+
FONT_GAME,"#004e6f");v.x=H;v.y=K+20;v.textAlign="center";v.textBaseline="alphabetic";v.lineWidth=200;v.outline=6;F.addChild(v);w=new createjs.Text(r,"60px "+FONT_GAME,"#fff");w.x=H;w.y=K+20;w.textAlign="center";w.textBaseline="alphabetic";w.lineWidth=200;F.addChild(w);n||(w.color="#b4b4b4",v.color="#606161");this._initListener()};this.unload=function(){F.off("mousedown",this.buttonDown);F.off("pressup",this.buttonRelease);F.removeChild(y)};this._initListener=function(){F.on("mousedown",this.buttonDown);
F.on("pressup",this.buttonRelease)};this.viewBut=function(H){F.addChild(H)};this.addEventListener=function(H,K,r){g[H]=K;c[H]=r};this.addEventListenerWithParams=function(H,K,r,x){g[H]=K;c[H]=r;t=x};this.ifClickable=function(){return!0===F.mouseEnabled?1:0};this.setActive=function(H,K){p=K;q[H].gotoAndStop("state_"+p);q[H].mouseEnabled=!0;p?(w.color="#69b8d5",v.color="#004e6f"):(w.color="#b4b4b4",v.color="#606161")};this.buttonRelease=function(){p&&(playSound("press_but",1,!1),g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(c[ON_MOUSE_UP],
t))};this.buttonDown=function(){g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(c[ON_MOUSE_DOWN],t)};this.setPosition=function(H,K){F.x=H;F.y=K};this.setVisible=function(H){F.visible=H};var z=h;this._init(a,d,e,f,m,h)}
function CMsgBox(a,d,e,f){var m,h,p,g,c,q,t;this._init=function(v,w,y,F){m=[];h=[];t=new createjs.Container;s_oStage.addChild(t);var z=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));t.addChild(z);p=new CTLText(t,CANVAS_WIDTH/2-80,CANVAS_HEIGHT/2-80,210,130,50,"center","#fff",FONT_GAME,1.1,0,0,"",!0,!0,!0,!1);g=new CTextButton(CANVAS_WIDTH/2-100,CANVAS_HEIGHT-150,s_oSpriteLibrary.getSprite("but_generic_small"),"LEFT",FONT_GAME,"#ffffff",50,t);g.addEventListener(ON_MOUSE_UP,this._onButLeftDownRelease,
this);c=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-150,s_oSpriteLibrary.getSprite("but_generic_small"),"CENTER",FONT_GAME,"#ffffff",50,t);c.addEventListener(ON_MOUSE_UP,this._onButCenterDownRelease,this);q=new CTextButton(CANVAS_WIDTH/2+90,CANVAS_HEIGHT-150,s_oSpriteLibrary.getSprite("but_generic_small"),"LEFT",FONT_GAME,"#ffffff",50,t);q.addEventListener(ON_MOUSE_UP,this._onButRightDownRelease,this);this.show(v,w,y,F)};this.show=function(v,w,y,F){p.refreshText(v);""!==w?(g.changeText(w),g.setVisible(!0)):
g.setVisible(!1);""!==y?(c.changeText(y),c.setVisible(!0)):c.setVisible(!1);""!==F?(q.changeText(F),q.setVisible(!0)):q.setVisible(!1)};this.hide=function(){this.unload();s_oStage.removeChild(t)};this.unload=function(){g.unload();c.unload();q.unload()};this.addEventListener=function(v,w,y){m[v]=w;h[v]=y};this._onButLeftDownRelease=function(){m[ON_MSG_BOX_LEFT_BUT]&&(m[ON_MSG_BOX_LEFT_BUT].call(h[ON_MSG_BOX_LEFT_BUT]),t.visible=!1)};this._onButCenterDownRelease=function(){m[ON_MSG_BOX_CENTER_BUT]&&
(m[ON_MSG_BOX_CENTER_BUT].call(h[ON_MSG_BOX_CENTER_BUT]),t.visible=!1)};this._onButRightDownRelease=function(){m[ON_MSG_BOX_RIGHT_BUT]&&(m[ON_MSG_BOX_RIGHT_BUT].call(h[ON_MSG_BOX_RIGHT_BUT]),t.visible=!1)};this._init(a,d,e,f)}
function CCreditsPanel(){var a,d,e,f,m,h,p,g;this._init=function(){g=new createjs.Container;g.alpha=0;s_oStage.addChild(g);var c=new createjs.Shape;c.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.addChild(c);d=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));g.addChild(d);h=new createjs.Shape;h.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=.01;a=h.on("click",this._onLogoButRelease);g.addChild(h);c=s_oSpriteLibrary.getSprite("but_exit_small");
f=new CGfxButton(620,180,c,g);f.addEventListener(ON_MOUSE_UP,this.unload,this);m=new CTLText(g,400,214,200,30,50,"center","#000",FONT_GAME,1.1,0,0,TEXT_CREDITS_DEVELOPED,!0,!0,!0,!1);m.setOutline(2);new CTLText(g,400,214,200,30,50,"center","#fff",FONT_GAME,1.1,0,0,TEXT_CREDITS_DEVELOPED,!0,!0,!0,!1);c=s_oSpriteLibrary.getSprite("logo_ctl");e=createBitmap(c);e.regX=c.width/2;e.regY=c.height/2;e.x=CANVAS_WIDTH/2+20;e.y=265;g.addChild(e);p=new CTLText(g,400,286,200,30,50,"center","#000",FONT_GAME,1.1,
0,0,"www.codethislab.com",!0,!0,!0,!1);p.setOutline(2);new CTLText(g,400,286,200,30,50,"center","#fff",FONT_GAME,1.1,0,0,"www.codethislab.com",!0,!0,!0,!1);createjs.Tween.get(g).to({alpha:1},600,createjs.Ease.cubicOut);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(c,q){};this.unload=function(){h.off("click",a);f.unload();f=null;s_oStage.removeChild(g)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en","_blank")};this._init()}
function CAlertSavingBox(a,d){var e,f;this._init=function(p){f=new createjs.Container;h.addChild(f);var g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=.5;g.on("click",function(){});f.addChild(g);g=s_oSpriteLibrary.getSprite("msg_box");var c=createBitmap(g);c.x=.5*CANVAS_WIDTH;c.y=.5*CANVAS_HEIGHT;c.regX=.5*g.width;c.regY=.5*g.height;f.addChild(c);new CTLText(f,400,190,200,130,50,"center","#fff",FONT_GAME,1.1,0,0,p,!0,!0,!0,!1);e=new CGfxButton(CANVAS_WIDTH/
2,430,s_oSpriteLibrary.getSprite("but_exit"),f);e.addEventListener(ON_MOUSE_UP,this._onButOk,this)};this._onButOk=function(){m.unload()};this.unload=function(){e.unload();h.removeChild(f)};var m=this;var h=d;this._init(a)}
CTLText.prototype={constructor:CTLText,__autofit:function(){if(this._bFitText){for(var a=this._iFontSize;(this._oText.getBounds().height>this._iHeight-2*this._iPaddingV||this._oText.getBounds().width>this._iWidth-2*this._iPaddingH)&&!(a--,this._oText.font=a+"px "+this._szFont,this._oText.lineHeight=Math.round(a*this._fLineHeightFactor),this.__updateY(),this.__verticalAlign(),8>a););this._iFontSize=a}},__verticalAlign:function(){if(this._bVerticalAlign){var a=this._oText.getBounds().height;this._oText.y-=
(a-this._iHeight)/2+this._iPaddingV}},__updateY:function(){this._oText.y=this._y+this._iPaddingV;switch(this._oText.textBaseline){case "middle":this._oText.y+=this._oText.lineHeight/2+(this._iFontSize*this._fLineHeightFactor-this._iFontSize)}},__createText:function(a){this._bDebug&&(this._oDebugShape=new createjs.Shape,this._oDebugShape.graphics.beginFill("rgba(255,0,0,0.5)").drawRect(this._x,this._y,this._iWidth,this._iHeight),this._oContainer.addChild(this._oDebugShape));this._oText=new createjs.Text(a,
this._iFontSize+"px "+this._szFont,this._szColor);this._oText.textBaseline="middle";this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this._oText.textAlign=this._szAlign;this._oText.lineWidth=this._bMultiline?this._iWidth-2*this._iPaddingH:null;switch(this._szAlign){case "center":this._oText.x=this._x+this._iWidth/2;break;case "left":this._oText.x=this._x+this._iPaddingH;break;case "right":this._oText.x=this._x+this._iWidth-this._iPaddingH}this._oContainer.addChild(this._oText);
this.refreshText(a)},setVerticalAlign:function(a){this._bVerticalAlign=a},setOutline:function(a){null!==this._oText&&(this._oText.outline=a)},setShadow:function(a,d,e,f){null!==this._oText&&(this._oText.shadow=new createjs.Shadow(a,d,e,f))},setColor:function(a){this._oText.color=a},setAlpha:function(a){this._oText.alpha=a},removeTweens:function(){createjs.Tween.removeTweens(this._oText)},getText:function(){return this._oText},getY:function(){return this._y},getFontSize:function(){return this._iFontSize},
refreshText:function(a){""===a&&(a=" ");null===this._oText&&this.__createText(a);this._oText.text=a;this._oText.font=this._iFontSize+"px "+this._szFont;this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this.__autofit();this.__updateY();this.__verticalAlign()}};
function CTLText(a,d,e,f,m,h,p,g,c,q,t,v,w,y,F,z,H){this._oContainer=a;this._x=d;this._y=e;this._iWidth=f;this._iHeight=m;this._bMultiline=z;this._iFontSize=h;this._szAlign=p;this._szColor=g;this._szFont=c;this._iPaddingH=t;this._iPaddingV=v;this._bVerticalAlign=F;this._bFitText=y;this._bDebug=H;this._oDebugShape=null;this._fLineHeightFactor=q;this._oText=null;w&&this.__createText(w)}
var LEVELS=[{ball_speed:50,ball_number:60,num_colors:4,hero_pos:{x:450,y:270},bg_image:"bg_game_1",curve_point:[{x:-25.2,y:262.4},{x:24.8,y:221.4},{x:64.8,y:191.4},{x:105.1,y:167.25},{x:152.1,y:144.4},{x:181.65,y:131},{x:213.9,y:118.45},{x:245.75,y:106.5},{x:277.65,y:95.6},{x:310.4,y:85.35},{x:343.3,y:76.95},{x:376.85,y:70.7},{x:410.75,y:66.55},{x:444.85,y:63.2},{x:479.25,y:60.85},{x:513.35,y:59.35},{x:547.6,y:59.85},{x:581.35,y:63.2},{x:614.9,y:71.55},{x:646.85,y:82.35},{x:677.05,y:99.45},{x:704.4,
y:118.95},{x:731.25,y:141.3},{x:753.1,y:167.1},{x:771,y:196.1},{x:782.3,y:228.05},{x:783.6,y:262.1},{x:769.4,y:292.45},{x:738.8,y:305.9},{x:706.9,y:295},{x:687.1,y:267.3},{x:673.65,y:236.3},{x:657.7,y:206.05},{x:640.1,y:176.35},{x:615.55,y:152.45},{x:587.05,y:134.85},{x:554.85,y:121.4},{x:521.2,y:116.4},{x:487.65,y:116.4},{x:453.6,y:122.3},{x:420.2,y:129},{x:386.6,y:135.7},{x:353.05,y:144.1},{x:321.15,y:155.2},{x:289.25,y:167.45},{x:258.7,y:183.05},{x:230.5,y:201.7},{x:203.5,y:222.65},{x:183.15,y:250.25},
{x:171.2,y:282.05},{x:167.2,y:315.7},{x:170.55,y:349.9},{x:178.45,y:383.3},{x:193.9,y:413.7},{x:215.05,y:440.75},{x:242.25,y:460.5},{x:274.15,y:472.25},{x:307.85,y:478.3},{x:342.5,y:481.5},{x:374.35,y:483.2},{x:414.65,y:484.2},{x:454.95,y:484.2},{x:488.55,y:482.7},{x:522.05,y:479.85},{x:557.35,y:474.95},{x:594.25,y:467.9},{x:627.9,y:458.85},{x:661.4,y:446.8},{x:688.3,y:435.2},{x:718.5,y:416.75},{x:735.3,y:394.85},{x:735.3,y:366.35},{x:715.1,y:347.9},{x:689.95,y:335.65},{x:663.1,y:335.65},{x:636.2,
y:345.9},{x:614.45,y:360.15},{x:589.2,y:378.6},{x:559,y:398.75},{x:530.5,y:412.5},{x:503.6,y:421.6},{x:476.75,y:426.65},{x:448.2,y:428.3},{x:416.3,y:425.95},{x:387.8,y:420.9},{x:360.95,y:413.5},{x:332.05,y:402.25},{x:303.8,y:385.5},{x:283.35,y:363.7},{x:270.45,y:335.15}]},{ball_speed:40,ball_number:80,num_colors:5,hero_pos:{x:450,y:280},bg_image:"bg_game_2",curve_point:[{x:271.65,y:-62.1},{x:381.65,y:-26.1},{x:464.35,y:2.85},{x:547.1,y:35.6},{x:583.25,y:51.8},{x:617.75,y:67.8},{x:650.5,y:85.05},{x:679.8,
y:102.3},{x:709.1,y:121.25},{x:734.95,y:141.6},{x:765.45,y:169.7},{x:790.6,y:200.7},{x:804.75,y:227.05},{x:809.9,y:254.8},{x:803.55,y:283.45},{x:788,y:309.8},{x:766.3,y:333.9},{x:740.3,y:355.8},{x:711,y:376.15},{x:676.5,y:396.85},{x:646.85,y:412.35},{x:615.85,y:427},{x:577.95,y:441.8},{x:545.2,y:453},{x:505.55,y:464.9},{x:469.35,y:473.35},{x:424.55,y:481.1},{x:378,y:485.75},{x:326.3,y:484.05},{x:286.65,y:477.15},{x:251.7,y:463.35},{x:218.95,y:439.25},{x:193.6,y:408.2},{x:178.1,y:375.45},{x:167.9,
y:343.05},{x:162.25,y:306.85},{x:161.55,y:263.8},{x:165.7,y:227.6},{x:173.6,y:194.85},{x:185,y:162.1},{x:203.25,y:129.35},{x:223.95,y:103},{x:248.05,y:83.15},{x:275.65,y:69.35},{x:308.4,y:64.2},{x:341.15,y:65.95},{x:373.9,y:70.95},{x:403.15,y:76.25},{x:453.15,y:88.7},{x:501.4,y:103.35},{x:541.05,y:117.1},{x:608.25,y:146.6},{x:656.35,y:172.8},{x:700.1,y:205.55},{x:722.35,y:239.65},{x:717.55,y:266.7},{x:701.35,y:292.55},{x:673.75,y:316.7},{x:640.85,y:339.1},{x:609.8,y:355.65},{x:539.15,y:383.4},{x:485.75,
y:398.9},{x:435.75,y:407.85},{x:382.3,y:409.6},{x:354.75,y:403.7},{x:327.15,y:384.75},{x:311.65,y:357.2},{x:303.05,y:327.9},{x:299.6,y:291.7},{x:302.85,y:252.05},{x:309.6,y:221.05},{x:321.65,y:188.3},{x:340.6,y:162.95},{x:361.3,y:150.55},{x:385.4,y:149.35},{x:416.45,y:154.7},{x:456.75,y:166.4},{x:503.5,y:183.65},{x:556.9,y:206.2}]},{ball_speed:30,ball_number:100,num_colors:5,hero_pos:{x:500,y:200},bg_image:"bg_game_3",curve_point:[{x:-88,y:300.9},{x:-48,y:266.9},{x:2,y:229.9},{x:52,y:193.9},{x:92,
y:168.9},{x:141.75,y:135.95},{x:183.15,y:114.2},{x:253.25,y:88.25},{x:304.1,y:75.65},{x:367.2,y:63.9},{x:421.55,y:58.95},{x:460.1,y:58.95},{x:505.7,y:59.65},{x:542.5,y:62.65},{x:582.85,y:68.8},{x:619.65,y:77.05},{x:658.2,y:88.95},{x:695.05,y:104.75},{x:731.65,y:125.75},{x:759.55,y:149.25},{x:781.1,y:175.55},{x:795.15,y:203.4},{x:803,y:236.75},{x:804.95,y:271.8},{x:800.9,y:305.1},{x:791.1,y:338.05},{x:772.85,y:368.4},{x:750.4,y:394.85},{x:719.05,y:419.75},{x:689.25,y:437.8},{x:657.7,y:451.3},{x:624.4,
y:462.15},{x:592.3,y:469.55},{x:560.55,y:475.3},{x:523.75,y:478.8},{x:490.45,y:480.25},{x:453.65,y:479.9},{x:414,y:476.55},{x:380.7,y:471.8},{x:347.4,y:465.5},{x:312.35,y:455.85},{x:279.05,y:443.75},{x:249.05,y:428.5},{x:212.25,y:402.2},{x:184.2,y:368.9},{x:167.2,y:337.35},{x:159.15,y:302.3},{x:158.6,y:268.45},{x:167.55,y:240.4},{x:193.85,y:222.35},{x:222.75,y:226.55},{x:241.35,y:251.8},{x:238.9,y:281.6},{x:245.2,y:311.6},{x:262.05,y:343.15},{x:284.8,y:366.1},{x:311.1,y:384},{x:353.2,y:401.5},{x:407.55,
y:413.8},{x:458.35,y:418.85},{x:509.2,y:418.85},{x:558.3,y:415.2},{x:609.3,y:404.3},{x:647.85,y:387.85},{x:684.7,y:361.9},{x:708,y:332.1},{x:722,y:298.8},{x:725.55,y:269},{x:715,y:240.95},{x:688.7,y:226.9},{x:658.75,y:232.15},{x:645.95,y:260.2},{x:642.8,y:290.35},{x:627,y:317},{x:600.9,y:337.2},{x:571.1,y:350},{x:538.3,y:357.7},{x:505,y:360.5},{x:459.4,y:360.15},{x:420.85,y:355.05},{x:387.55,y:345.6},{x:355.45,y:329.1},{x:332,y:305.8},{x:318.85,y:274.4},{x:317.1,y:246.35}]}];
function extractHostname(a){a=-1<a.indexOf("://")?a.split("/")[2]:a.split("/")[0];a=a.split(":")[0];return a=a.split("?")[0]}function extractRootDomain(a){a=extractHostname(a);var d=a.split("."),e=d.length;2<e&&(a=d[e-2]+"."+d[e-1]);return a}
var getClosestTop=function(){var a=window,d=!1;try{for(;a.parent.document!==a.document;)if(a.parent.document)a=a.parent;else{d=!0;break}}catch(e){d=!0}return{topFrame:a,err:d}},getBestPageUrl=function(a){var d=a.topFrame,e="";if(a.err)try{try{e=window.top.location.href}catch(m){var f=window.location.ancestorOrigins;e=f[f.length-1]}}catch(m){e=d.document.referrer}else e=d.location.href;return e},TOPFRAMEOBJ=getClosestTop(),PAGE_URL=getBestPageUrl(TOPFRAMEOBJ);
function seekAndDestroy(){for(var a=extractRootDomain(PAGE_URL),d=[String.fromCharCode(99,111,100,101,116,104,105,115,108,97,98,46,99,111,109),String.fromCharCode(101,110,118,97,116,111,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,110,101,116)],e=0;e<d.length;e++)if(d[e]===a)return!0;return!1};