/*
 Platform.js <https://mths.be/platform>
 Copyright 2014-2018 Benjamin Tan <https://bnjmnt4n.now.sh/>
 Copyright 2011-2013 John-David Dalton
 Available under MIT license <https://mths.be/mit>
*/
(function(){var a="undefined"!==typeof window&&"undefined"!==typeof window.document?window.document:{},c="undefined"!==typeof module&&module.exports,b=function(){for(var k,m=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),
"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],g=0,r=m.length,q={};g<r;g++)if((k=m[g])&&k[1]in a){for(g=0;g<k.length;g++)q[m[0][g]]=k[g];return q}return!1}(),d={change:b.fullscreenchange,error:b.fullscreenerror},l={request:function(k){return new Promise(function(m,g){var r=function(){this.off("change",
r);m()}.bind(this);this.on("change",r);k=k||a.documentElement;Promise.resolve(k[b.requestFullscreen]())["catch"](g)}.bind(this))},exit:function(){return new Promise(function(k,m){if(this.isFullscreen){var g=function(){this.off("change",g);k()}.bind(this);this.on("change",g);Promise.resolve(a[b.exitFullscreen]())["catch"](m)}else k()}.bind(this))},toggle:function(k){return this.isFullscreen?this.exit():this.request(k)},onchange:function(k){this.on("change",k)},onerror:function(k){this.on("error",k)},
on:function(k,m){var g=d[k];g&&a.addEventListener(g,m,!1)},off:function(k,m){var g=d[k];g&&a.removeEventListener(g,m,!1)},raw:b};b?(Object.defineProperties(l,{isFullscreen:{get:function(){return!!a[b.fullscreenElement]}},element:{enumerable:!0,get:function(){return a[b.fullscreenElement]}},isEnabled:{enumerable:!0,get:function(){return!!a[b.fullscreenEnabled]}}}),c?module.exports=l:window.screenfull=l):c?module.exports={isEnabled:!1}:window.screenfull={isEnabled:!1}})();
function buildIOSMeta(){for(var a=[{name:"viewport",content:"width=device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"},{name:"apple-mobile-web-app-capable",content:"yes"},{name:"apple-mobile-web-app-status-bar-style",content:"black"}],c=0;c<a.length;c++){var b=document.createElement("meta");b.name=a[c].name;b.content=a[c].content;var d=window.document.head.querySelector('meta[name="'+b.name+'"]');d&&d.parentNode.removeChild(d);window.document.head.appendChild(b)}}
function hideIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","none");jQuery(".xxx-ios-fullscreen-scroll").css("display","none");jQuery(".xxx-game-iframe-full").removeClass("xxx-game-iframe-iphone-se")}function buildIOSFullscreenPanel(){jQuery("body").append('<div class="xxx-ios-fullscreen-message"><div class="xxx-ios-fullscreen-swipe"></div></div><div class="xxx-ios-fullscreen-scroll"></div>')}
function showIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","block");jQuery(".xxx-ios-fullscreen-scroll").css("display","block")}
function __iosResize(){window.scrollTo(0,0);console.log(window.devicePixelRatio);console.log(window.innerWidth);console.log(window.innerHeight);if("iPhone"===platform.product)switch(window.devicePixelRatio){case 2:switch(window.innerWidth){case 568:320!==window.innerHeight&&jQuery(".xxx-game-iframe-full").addClass("xxx-game-iframe-iphone-se");break;case 667:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();
break;default:hideIOSFullscreenPanel()}break;case 3:switch(window.innerWidth){case 736:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 724:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;default:hideIOSFullscreenPanel()}}function iosResize(){__iosResize();setTimeout(function(){__iosResize()},500)}
function iosInIframe(){try{return window.self!==window.top}catch(a){return!0}}function isIOSLessThen13(){var a=platform.os,c=a.family.toLowerCase();a=parseFloat(a.version);return"ios"===c&&13>a?!0:!1}$(document).ready(function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&(buildIOSFullscreenPanel(),buildIOSMeta())});
jQuery(window).resize(function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&iosResize()});
(function(){function a(h){h=String(h);return h.charAt(0).toUpperCase()+h.slice(1)}function c(h,G){var A=-1,B=h?h.length:0;if("number"==typeof B&&-1<B&&B<=z)for(;++A<B;)G(h[A],A,h);else d(h,G)}function b(h){h=String(h).replace(/^ +| +$/g,"");return/^(?:webOS|i(?:OS|P))/.test(h)?h:a(h)}function d(h,G){for(var A in h)w.call(h,A)&&G(h[A],A,h)}function l(h){return null==h?a(h):t.call(h).slice(8,-1)}function k(h,G){var A=null!=h?typeof h[G]:"number";return!/^(?:boolean|number|string|undefined)$/.test(A)&&
("object"==A?!!h[G]:!0)}function m(h){return String(h).replace(/([ -])(?!$)/g,"$1?")}function g(h,G){var A=null;c(h,function(B,u){A=G(A,B,u,h)});return A}function r(h){function G(R){return g(R,function(P,K){var W=K.pattern||m(K);!P&&(P=RegExp("\\b"+W+" *\\d+[.\\w_]*","i").exec(h)||RegExp("\\b"+W+" *\\w+-[\\w]*","i").exec(h)||RegExp("\\b"+W+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(h))&&((P=String(K.label&&!RegExp(W,"i").test(K.label)?K.label:P).split("/"))[1]&&!/[\d.]+/.test(P[0])&&(P[0]+=
" "+P[1]),K=K.label||K,P=b(P[0].replace(RegExp(W,"i"),K).replace(RegExp("; *(?:"+K+"[_-])?","i")," ").replace(RegExp("("+K+")[-_.]?(\\w)","i"),"$1 $2")));return P})}function A(R){return g(R,function(P,K){return P||(RegExp(K+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(h)||0)[1]||null})}var B=p,u=h&&"object"==typeof h&&"String"!=l(h);u&&(B=h,h=null);var F=B.navigator||{},x=F.userAgent||"";h||(h=x);var L=u?!!F.likeChrome:/\bChrome\b/.test(h)&&!/internal|\n/i.test(t.toString()),
J=u?"Object":"ScriptBridgingProxyObject",M=u?"Object":"Environment",N=u&&B.java?"JavaPackage":l(B.java),S=u?"Object":"RuntimeObject";M=(N=/\bJava/.test(N)&&B.java)&&l(B.environment)==M;var T=N?"a":"\u03b1",Y=N?"b":"\u03b2",Z=B.document||{},Q=B.operamini||B.opera,v=f.test(v=u&&Q?Q["[[Class]]"]:l(Q))?v:Q=null,e,O=h;u=[];var U=null,V=h==x;x=V&&Q&&"function"==typeof Q.version&&Q.version();var D=function(R){return g(R,function(P,K){return P||RegExp("\\b"+(K.pattern||m(K))+"\\b","i").exec(h)&&(K.label||
K)})}([{label:"EdgeHTML",pattern:"Edge"},"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),C=function(R){return g(R,function(P,K){return P||RegExp("\\b"+(K.pattern||m(K))+"\\b","i").exec(h)&&(K.label||K)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"Edge"},"Midori","Nook Browser",
"PaleMoon","PhantomJS","Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Waterfox","WebPositive","Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chrome",{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",pattern:"FxiOS"},
{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),I=G([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV","Lumia","iPad",
"iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),X=function(R){return g(R,function(P,K,W){return P||(K[I]||K[/^[a-z]+(?: +[a-z]+\b)*/i.exec(I)]||RegExp("\\b"+m(W)+"(?:\\b|\\w*\\d)","i").exec(h))&&W})}({Apple:{iPad:1,iPhone:1,iPod:1},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},Asus:{Transformer:1},
"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1}}),E=function(R){return g(R,function(P,K){var W=K.pattern||m(K);if(!P&&(P=RegExp("\\b"+W+"(?:/[\\d.]+|[ \\w.]*)","i").exec(h))){var aa=P,ba=K.label||K,ca={"10.0":"10","6.4":"10 Technical Preview",
"6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};W&&ba&&/^Win/i.test(aa)&&!/^Windows Phone /i.test(aa)&&(ca=ca[/[\d.]+$/.exec(aa)])&&(aa="Windows "+ca);aa=String(aa);W&&ba&&(aa=aa.replace(RegExp(W,"i"),ba));P=aa=b(aa.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,
"$1").replace(/\/(\d)/," $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return P})}(["Windows Phone","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian","Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X",
"Macintosh","Mac","Windows 98;","Windows "]);D&&(D=[D]);X&&!I&&(I=G([X]));if(e=/\bGoogle TV\b/.exec(I))I=e[0];/\bSimulator\b/i.test(h)&&(I=(I?I+" ":"")+"Simulator");"Opera Mini"==C&&/\bOPiOS\b/.test(h)&&u.push("running in Turbo/Uncompressed mode");"IE"==C&&/\blike iPhone OS\b/.test(h)?(e=r(h.replace(/like iPhone OS/,"")),X=e.manufacturer,I=e.product):/^iP/.test(I)?(C||(C="Safari"),E="iOS"+((e=/ OS ([\d_]+)/i.exec(h))?" "+e[1].replace(/_/g,"."):"")):"Konqueror"!=C||/buntu/i.test(E)?X&&"Google"!=X&&
(/Chrome/.test(C)&&!/\bMobile Safari\b/i.test(h)||/\bVita\b/.test(I))||/\bAndroid\b/.test(E)&&/^Chrome/.test(C)&&/\bVersion\//i.test(h)?(C="Android Browser",E=/\bAndroid\b/.test(E)?E:"Android"):"Silk"==C?(/\bMobi/i.test(h)||(E="Android",u.unshift("desktop mode")),/Accelerated *= *true/i.test(h)&&u.unshift("accelerated")):"PaleMoon"==C&&(e=/\bFirefox\/([\d.]+)\b/.exec(h))?u.push("identifying as Firefox "+e[1]):"Firefox"==C&&(e=/\b(Mobile|Tablet|TV)\b/i.exec(h))?(E||(E="Firefox OS"),I||(I=e[1])):!C||
(e=!/\bMinefield\b/i.test(h)&&/\b(?:Firefox|Safari)\b/.exec(C))?(C&&!I&&/[\/,]|^[^(]+?\)/.test(h.slice(h.indexOf(e+"/")+8))&&(C=null),(e=I||X||E)&&(I||X||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(E))&&(C=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(E)?E:e)+" Browser")):"Electron"==C&&(e=(/\bChrome\/([\d.]+)\b/.exec(h)||0)[1])&&u.push("Chromium "+e):E="Kubuntu";x||(x=A(["(?:Cloud9|CriOS|CrMo|Edge|FxiOS|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$))","Version",m(C),
"(?:Firefox|Minefield|NetFront)"]));if(e="iCab"==D&&3<parseFloat(x)&&"WebKit"||/\bOpera\b/.test(C)&&(/\bOPR\b/.test(h)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(h)&&!/^(?:Trident|EdgeHTML)$/.test(D)&&"WebKit"||!D&&/\bMSIE\b/i.test(h)&&("Mac OS"==E?"Tasman":"Trident")||"WebKit"==D&&/\bPlayStation\b(?! Vita\b)/i.test(C)&&"NetFront")D=[e];"IE"==C&&(e=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(h)||0)[1])?(C+=" Mobile",E="Windows Phone "+(/\+$/.test(e)?e:e+".x"),u.unshift("desktop mode")):/\bWPDesktop\b/i.test(h)?
(C="IE Mobile",E="Windows Phone 8.x",u.unshift("desktop mode"),x||(x=(/\brv:([\d.]+)/.exec(h)||0)[1])):"IE"!=C&&"Trident"==D&&(e=/\brv:([\d.]+)/.exec(h))&&(C&&u.push("identifying as "+C+(x?" "+x:"")),C="IE",x=e[1]);if(V){if(k(B,"global"))if(N&&(e=N.lang.System,O=e.getProperty("os.arch"),E=E||e.getProperty("os.name")+" "+e.getProperty("os.version")),M){try{x=B.require("ringo/engine").version.join("."),C="RingoJS"}catch(R){(e=B.system)&&e.global.system==B.system&&(C="Narwhal",E||(E=e[0].os||null))}C||
(C="Rhino")}else"object"==typeof B.process&&!B.process.browser&&(e=B.process)&&("object"==typeof e.versions&&("string"==typeof e.versions.electron?(u.push("Node "+e.versions.node),C="Electron",x=e.versions.electron):"string"==typeof e.versions.nw&&(u.push("Chromium "+x,"Node "+e.versions.node),C="NW.js",x=e.versions.nw)),C||(C="Node.js",O=e.arch,E=e.platform,x=(x=/[\d.]+/.exec(e.version))?x[0]:null));else l(e=B.runtime)==J?(C="Adobe AIR",E=e.flash.system.Capabilities.os):l(e=B.phantom)==S?(C="PhantomJS",
x=(e=e.version||null)&&e.major+"."+e.minor+"."+e.patch):"number"==typeof Z.documentMode&&(e=/\bTrident\/(\d+)/i.exec(h))?(x=[x,Z.documentMode],(e=+e[1]+4)!=x[1]&&(u.push("IE "+x[1]+" mode"),D&&(D[1]=""),x[1]=e),x="IE"==C?String(x[1].toFixed(1)):x[0]):"number"==typeof Z.documentMode&&/^(?:Chrome|Firefox)\b/.test(C)&&(u.push("masking as "+C+" "+x),C="IE",x="11.0",D=["Trident"],E="Windows");E=E&&b(E)}x&&(e=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(x)||/(?:alpha|beta)(?: ?\d)?/i.exec(h+";"+(V&&F.appMinorVersion))||
/\bMinefield\b/i.test(h)&&"a")&&(U=/b/i.test(e)?"beta":"alpha",x=x.replace(RegExp(e+"\\+?$"),"")+("beta"==U?Y:T)+(/\d+\+?/.exec(e)||""));if("Fennec"==C||"Firefox"==C&&/\b(?:Android|Firefox OS)\b/.test(E))C="Firefox Mobile";else if("Maxthon"==C&&x)x=x.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(I))"Xbox 360"==I&&(E=null),"Xbox 360"==I&&/\bIEMobile\b/.test(h)&&u.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(C)&&(!C||I||/Browser|Mobi/.test(C))||"Windows CE"!=E&&!/Mobi/i.test(h))if("IE"==
C&&V)try{null===B.external&&u.unshift("platform preview")}catch(R){u.unshift("embedded")}else(/\bBlackBerry\b/.test(I)||/\bBB10\b/.test(h))&&(e=(RegExp(I.replace(/ +/g," *")+"/([.\\d]+)","i").exec(h)||0)[1]||x)?(e=[e,/BB10/.test(h)],E=(e[1]?(I=null,X="BlackBerry"):"Device Software")+" "+e[0],x=null):this!=d&&"Wii"!=I&&(V&&Q||/Opera/.test(C)&&/\b(?:MSIE|Firefox)\b/i.test(h)||"Firefox"==C&&/\bOS X (?:\d+\.){2,}/.test(E)||"IE"==C&&(E&&!/^Win/.test(E)&&5.5<x||/\bWindows XP\b/.test(E)&&8<x||8==x&&!/\bTrident\b/.test(h)))&&
!f.test(e=r.call(d,h.replace(f,"")+";"))&&e.name&&(e="ing as "+e.name+((e=e.version)?" "+e:""),f.test(C)?(/\bIE\b/.test(e)&&"Mac OS"==E&&(E=null),e="identify"+e):(e="mask"+e,C=v?b(v.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(e)&&(E=null),V||(x=null)),D=["Presto"],u.push(e));else C+=" Mobile";if(e=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(h)||0)[1]){e=[parseFloat(e.replace(/\.(\d)$/,".0$1")),e];if("Safari"==C&&"+"==e[1].slice(-1))C="WebKit Nightly",U="alpha",x=e[1].slice(0,-1);else if(x==
e[1]||x==(e[2]=(/\bSafari\/([\d.]+\+?)/i.exec(h)||0)[1]))x=null;e[1]=(/\bChrome\/([\d.]+)/i.exec(h)||0)[1];537.36==e[0]&&537.36==e[2]&&28<=parseFloat(e[1])&&"WebKit"==D&&(D=["Blink"]);V&&(L||e[1])?(D&&(D[1]="like Chrome"),e=e[1]||(e=e[0],530>e?1:532>e?2:532.05>e?3:533>e?4:534.03>e?5:534.07>e?6:534.1>e?7:534.13>e?8:534.16>e?9:534.24>e?10:534.3>e?11:535.01>e?12:535.02>e?"13+":535.07>e?15:535.11>e?16:535.19>e?17:536.05>e?18:536.1>e?19:537.01>e?20:537.11>e?"21+":537.13>e?23:537.18>e?24:537.24>e?25:537.36>
e?26:"Blink"!=D?"27":"28")):(D&&(D[1]="like Safari"),e=(e=e[0],400>e?1:500>e?2:526>e?3:533>e?4:534>e?"4+":535>e?5:537>e?6:538>e?7:601>e?8:"8"));D&&(D[1]+=" "+(e+="number"==typeof e?".x":/[.+]/.test(e)?"":"+"));"Safari"==C&&(!x||45<parseInt(x))&&(x=e)}"Opera"==C&&(e=/\bzbov|zvav$/.exec(E))?(C+=" ",u.unshift("desktop mode"),"zvav"==e?(C+="Mini",x=null):C+="Mobile",E=E.replace(RegExp(" *"+e+"$"),"")):"Safari"==C&&/\bChrome\b/.exec(D&&D[1])&&(u.unshift("desktop mode"),C="Chrome Mobile",x=null,/\bOS X\b/.test(E)?
(X="Apple",E="iOS 4.3+"):E=null);x&&0==x.indexOf(e=/[\d.]+$/.exec(E))&&-1<h.indexOf("/"+e+"-")&&(E=String(E.replace(e,"")).replace(/^ +| +$/g,""));D&&!/\b(?:Avant|Nook)\b/.test(C)&&(/Browser|Lunascape|Maxthon/.test(C)||"Safari"!=C&&/^iOS/.test(E)&&/\bSafari\b/.test(D[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|Web)/.test(C)&&D[1])&&(e=D[D.length-1])&&u.push(e);u.length&&(u=["("+u.join("; ")+")"]);X&&I&&0>I.indexOf(X)&&u.push("on "+X);I&&u.push((/^on /.test(u[u.length-
1])?"":"on ")+I);if(E){var da=(e=/ ([\d.+]+)$/.exec(E))&&"/"==E.charAt(E.length-e[0].length-1);E={architecture:32,family:e&&!da?E.replace(e[0],""):E,version:e?e[1]:null,toString:function(){var R=this.version;return this.family+(R&&!da?" "+R:"")+(64==this.architecture?" 64-bit":"")}}}(e=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(O))&&!/\bi686\b/i.test(O)?(E&&(E.architecture=64,E.family=E.family.replace(RegExp(" *"+e),"")),C&&(/\bWOW64\b/i.test(h)||V&&/\w(?:86|32)$/.test(F.cpuClass||F.platform)&&!/\bWin64; x64\b/i.test(h))&&
u.unshift("32-bit")):E&&/^OS X/.test(E.family)&&"Chrome"==C&&39<=parseFloat(x)&&(E.architecture=64);h||(h=null);B={};B.description=h;B.layout=D&&D[0];B.manufacturer=X;B.name=C;B.prerelease=U;B.product=I;B.ua=h;B.version=C&&x;B.os=E||{architecture:null,family:null,version:null,toString:function(){return"null"}};B.parse=r;B.toString=function(){return this.description||""};B.version&&u.unshift(x);B.name&&u.unshift(C);E&&C&&(E!=String(E).split(" ")[0]||E!=C.split(" ")[0]&&!I)&&u.push(I?"("+E+")":"on "+
E);u.length&&(B.description=u.join(" "));return B}var q={"function":!0,object:!0},p=q[typeof window]&&window||this,n=q[typeof exports]&&exports;q=q[typeof module]&&module&&!module.nodeType&&module;var y=n&&q&&"object"==typeof global&&global;!y||y.global!==y&&y.window!==y&&y.self!==y||(p=y);var z=Math.pow(2,53)-1,f=/\bOpera/;y=Object.prototype;var w=y.hasOwnProperty,t=y.toString,H=r();"function"==typeof define&&"object"==typeof define.amd&&define.amd?(p.platform=H,define(function(){return H})):n&&
q?d(H,function(h,G){n[G]=h}):p.platform=H}).call(this);var s_bLandscape=!0,s_iScaleFactor=1,s_bIsIphone=!1,s_iOffsetX,s_iOffsetY;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}function isIpad(){var a=-1!==navigator.userAgent.toLowerCase().indexOf("ipad");return!a&&navigator.userAgent.match(/Mac/)&&navigator.maxTouchPoints&&2<navigator.maxTouchPoints?!0:a}function isMobile(){return isIpad()?!0:jQuery.browser.mobile}
function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}
function getSize(a){var c=a.toLowerCase(),b=window.document,d=b.documentElement;if(void 0===window["inner"+a])a=d["client"+a];else if(window["inner"+a]!=d["client"+a]){var l=b.createElement("body");l.id="vpw-test-b";l.style.cssText="overflow:scroll";var k=b.createElement("div");k.id="vpw-test-d";k.style.cssText="position:absolute;top:-1000px";k.innerHTML="<style>@media("+c+":"+d["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+c+":7px!important}}</style>";l.appendChild(k);d.insertBefore(l,b.head);
a=7==k["offset"+a]?d["client"+a]:window["inner"+a];d.removeChild(l)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=null!==platform.name&&"safari"===platform.name.toLowerCase()?getIOSWindowHeight():getSize("Height");var c=getSize("Width"),b=Math.min(a/CANVAS_HEIGHT,c/CANVAS_WIDTH);c>a?(EDGEBOARD_X=0,EDGEBOARD_Y=380,s_bLandscape=!0):(EDGEBOARD_X=400,EDGEBOARD_Y=0,s_bLandscape=!1);var d=Math.round(CANVAS_WIDTH*b);b=Math.round(CANVAS_HEIGHT*b);if(b<a){var l=a-b;b+=l;d+=CANVAS_WIDTH/CANVAS_HEIGHT*l}else d<c&&(l=c-d,d+=l,b+=CANVAS_HEIGHT/CANVAS_WIDTH*
l);l=a/2-b/2;var k=c/2-d/2,m=CANVAS_WIDTH/d;if(k*m<-EDGEBOARD_X||l*m<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),c/(CANVAS_WIDTH-2*EDGEBOARD_X)),d=Math.round(CANVAS_WIDTH*b),b=Math.round(CANVAS_HEIGHT*b),l=(a-b)/2,k=(c-d)/2,m=CANVAS_WIDTH/d;s_iOffsetX=-1*k*m;s_iOffsetY=-1*l*m;0<=l&&(s_iOffsetY=0);0<=k&&(s_iOffsetX=0);null!==s_oGame&&s_oGame.refreshButtonPos();null!==s_oMenu&&s_oMenu.refreshButtonPos();null!==s_oChooseCharacterMenu&&s_oChooseCharacterMenu.refreshButtonPos();s_iScaleFactor=
Math.min(d/CANVAS_WIDTH,b/CANVAS_HEIGHT);s_bIsIphone&&s_oStage?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*d,s_oStage.canvas.height=2*b,canvas.style.width=d+"px",canvas.style.height=b+"px",s_iScaleFactor=2*Math.min(d/CANVAS_WIDTH,b/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor):s_bMobile||isChrome()?($("#canvas").css("width",d+"px"),$("#canvas").css("height",b+"px")):s_oStage&&(s_oStage.canvas.width=d,s_oStage.canvas.height=b,s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);
0>l||(l=(a-b)/2);$("#canvas").css("top",l+"px");$("#canvas").css("left",k+"px");fullscreenHandler()}}function createBitmap(a,c,b){var d=new createjs.Bitmap(a),l=new createjs.Shape;c&&b?l.graphics.beginFill("#fff").drawRect(0,0,c,b):l.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);d.hitArea=l;return d}
function createSprite(a,c,b,d,l,k){a=null!==c?new createjs.Sprite(a,c):new createjs.Sprite(a);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-b,-d,l,k);a.hitArea=c;return a}function randomFloatBetween(a,c,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(c-a),c).toFixed(b))}function rotateVector2D(a,c){var b=c.getX()*Math.cos(a)+c.getY()*Math.sin(a),d=c.getX()*-Math.sin(a)+c.getY()*Math.cos(a);c.set(b,d)}function tweenVectorsOnX(a,c,b){return a+b*(c-a)}
this.tweenVectors=function(a,c,b){var d=new CVector2;d.set(a.getX()+b*(c.getX()-a.getX()),a.getY()+b*(c.getY()-a.getY()));return d};function distance(a,c){return Math.sqrt((c.x-a.x)*(c.x-a.x)+(c.y-a.y)*(c.y-a.y))}function shuffle(a){for(var c=a.length,b,d;0!==c;)d=Math.floor(Math.random()*c),--c,b=a[c],a[c]=a[d],a[d]=b;return a}function bubbleSort(a){do{var c=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(c=a[b],a[b]=a[b+1],a[b+1]=c,c=!0)}while(c)}
function compare(a,c){return a.index>c.index?-1:a.index<c.index?1:0}function easeLinear(a,c,b,d){return b*a/d+c}function easeInQuad(a,c,b,d){return b*(a/=d)*a+c}function easeInSine(a,c,b,d){return-b*Math.cos(a/d*(Math.PI/2))+b+c}function easeInCubic(a,c,b,d){return b*(a/=d)*a*a+c}function getTrajectoryPoint(a,c){var b=new createjs.Point,d=(1-a)*(1-a),l=a*a;b.x=d*c.start.x+2*(1-a)*a*c.traj.x+l*c.end.x;b.y=d*c.start.y+2*(1-a)*a*c.traj.y+l*c.end.y;return b}
function formatTime(a){a/=1E3;var c=Math.floor(a/60);a=Math.floor(a-60*c);var b="";b=10>c?b+("0"+c+":"):b+(c+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,c){var b=getBounds(a,.9);var d=getBounds(c,.98);return calculateIntersection(b,d)}function collisionWithCircle(a,c,b){var d=a.getX()-c.getX();a=a.getY()-c.getY();return Math.sqrt(d*d+a*a)<PLAYER_RADIUS*b+CELL_SIZE*b?!0:!1}
function calculateIntersection(a,c){var b,d,l,k;var m=a.x+(b=a.width/2);var g=a.y+(d=a.height/2);var r=c.x+(l=c.width/2);var q=c.y+(k=c.height/2);m=Math.abs(m-r)-(b+l);g=Math.abs(g-q)-(d+k);return 0>m&&0>g?(m=Math.min(Math.min(a.width,c.width),-m),g=Math.min(Math.min(a.height,c.height),-g),{x:Math.max(a.x,c.x),y:Math.max(a.y,c.y),width:m,height:g,rect1:a,rect2:c}):null}
function getBounds(a,c){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var d=a.children,l=d.length,k;for(k=0;k<l;k++){var m=getBounds(d[k],1);m.x<b.x&&(b.x=m.x);m.y<b.y&&(b.y=m.y);m.x+m.width>b.x2&&(b.x2=m.x+m.width);m.y+m.height>b.y2&&(b.y2=m.y+m.height)}Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{if(a instanceof createjs.Bitmap){l=
a.sourceRect||a.image;k=l.width*c;var g=l.height*c}else if(a instanceof createjs.Sprite)if(a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image){l=a.spriteSheet.getFrame(a.currentFrame);k=l.rect.width;g=l.rect.height;d=l.regX;var r=l.regY}else b.x=a.x||0,b.y=a.y||0;else b.x=a.x||0,b.y=a.y||0;d=d||0;k=k||0;r=r||0;g=g||0;b.regX=d;b.regY=r;l=a.localToGlobal(0-d,0-r);m=a.localToGlobal(k-d,g-r);k=a.localToGlobal(k-d,0-r);d=a.localToGlobal(0-d,g-r);b.x=
Math.min(Math.min(Math.min(l.x,m.x),k.x),d.x);b.y=Math.min(Math.min(Math.min(l.y,m.y),k.y),d.y);b.width=Math.max(Math.max(Math.max(l.x,m.x),k.x),d.x)-b.x;b.height=Math.max(Math.max(Math.max(l.y,m.y),k.y),d.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var c=a.length,b,d;0<c;)d=Math.floor(Math.random()*c),c--,b=a[c],a[c]=a[d],a[d]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);a.dispatchEvent(c)}}};
(function(){function a(b){var d={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};b=b||window.event;b.type in d?document.body.className=d[b.type]:(document.body.className=this[c]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var c="hidden";c in document?document.addEventListener("visibilitychange",a):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(c="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(c="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var c=window.location.search.substring(1).split("&"),b=0;b<c.length;b++){var d=c[b].split("=");if(d[0]==a)return d[1]}}function playSound(a,c,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(c),s_aSounds[a].loop(b),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}function setVolume(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(c)}
function setMute(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(c)}function saveItem(a,c){s_bStorageAvailable&&localStorage.setItem(a,c)}function getItem(a){return s_bStorageAvailable?localStorage.getItem(a):null}
function fullscreenHandler(){ENABLE_FULLSCREEN&&screenfull.isEnabled&&(s_bFullscreen=screenfull.isFullscreen,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut(),null!==s_oChooseCharacterMenu&&s_oChooseCharacterMenu.resetFullscreenBut())}
if(screenfull.isEnabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut();null!==s_oChooseCharacterMenu&&s_oChooseCharacterMenu.resetFullscreenBut()});
function CSpriteLibrary(){var a={},c,b,d,l,k,m;this.init=function(g,r,q){c={};d=b=0;l=g;k=r;m=q};this.addSprite=function(g,r){if(!a.hasOwnProperty(g)){var q=new Image;a[g]=c[g]={szPath:r,oSprite:q,bLoaded:!1};b++}};this.getSprite=function(g){return a.hasOwnProperty(g)?a[g].oSprite:null};this._onSpritesLoaded=function(){b=0;k.call(m)};this._onSpriteLoaded=function(){l.call(m);++d===b&&this._onSpritesLoaded()};this.loadSprites=function(){for(var g in c)c[g].oSprite.oSpriteLibrary=this,c[g].oSprite.szKey=
g,c[g].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},c[g].oSprite.onerror=function(r){var q=r.currentTarget;setTimeout(function(){c[q.szKey].oSprite.src=c[q.szKey].szPath},500)},c[g].oSprite.src=c[g].szPath};this.setLoaded=function(g){a[g].bLoaded=!0};this.isLoaded=function(g){return a[g].bLoaded};this.getNumSprites=function(){return b}}
var CANVAS_WIDTH=1920,CANVAS_HEIGHT=1920,EDGEBOARD_X=0,EDGEBOARD_Y=0,FONT="comiquita_sansmedium",FPS=30,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_LEVEL=2,STATE_GAME=3,STATE_CHOOSE_CHARACTER_MENU=4,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_BUT_YES_DOWN=4,ON_BUT_NO_DOWN=5,ON_BACK_MENU=6,ON_RESTART=7,ON_NEXT=8,ON_ITEM_DIE=9,ON_ITEM_FALL=10,ON_END_READYGO_ANIM=11,ON_EXIT_FROM_HELP=12,DIR_RIGHT=0,DIR_LEFT=1,MATERIALS=["glass","organic","paper","plastic"],ANIM_IDLE=
"idle",ANIM_WALK="walk",ANIM_CATCH="catch",PREFIX_LOCAL_STORAGE="twin_the_bin",ENABLE_FULLSCREEN,LEFT_DIR=37,RIGHT_DIR=39,TIME_LOGO_OFF=8E3,TIME_LOGO_BLINK=2E3,HERO_LIMIT_LEFT=480,HERO_LIMIT_RIGHT=1488,ITEM_LIMIT_LEFT=484,ITEM_LIMIT_RIGHT=1438,PERC_FALL_ITEM=70,MAX_PERC_FALL_ITEM=90,ITEM_FALLING_SPEED=.5,PISTON_WIDTH=242,PISTON_HEIGHT=276,PISTON_Y=438-PISTON_HEIGHT/4,CONVEYOR_SPEED=9,TOP_CONVEYOR_Y=438,BOTTOM_CONVEYOR_Y=1505,NUM_ITEM_TYPES_PER_MATERIAL=5,START_ITEM_Y=400,START_SPAWN_ITEM_TIME=1400,
FLOOR_Y=1350,HERO_ACCELERATION,MAX_HERO_SPEED,HERO_FRICTION,MALUS_PERC,MALUS_POINTS,ITEM_POINTS,TIME_LEVEL,CHANGE_DELAY,SOUNDTRACK_VOLUME_IN_GAME=.5;
function CMain(a){var c,b=0,d=0,l=STATE_LOADING,k,m;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage,!0);s_oStage.preventSelection=!1;s_bMobile=isMobile();!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.framerate=FPS;navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;
seekAndDestroy()?k=new CPreloader:window.location.href="https://www.codethislab.com/contact-us.html"};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();c=!0};this.soundLoaded=function(){b++;k.refreshLoader(Math.floor(b/d*100))};this._initSounds=function(){Howler.mute(!s_bAudioActive);s_aSoundsInfo=[];s_aSoundsInfo.push({path:"./sounds/",filename:"catch_item",loop:!1,volume:1,ingamename:"catch_item"});s_aSoundsInfo.push({path:"./sounds/",
filename:"catch_malus",loop:!1,volume:1,ingamename:"catch_malus"});s_aSoundsInfo.push({path:"./sounds/",filename:"time_over",loop:!1,volume:1,ingamename:"time_over"});s_aSoundsInfo.push({path:"./sounds/",filename:"click",loop:!1,volume:1,ingamename:"click"});s_aSoundsInfo.push({path:"./sounds/",filename:"ready",loop:!1,volume:1,ingamename:"ready"});s_aSoundsInfo.push({path:"./sounds/",filename:"go",loop:!1,volume:1,ingamename:"go"});s_aSoundsInfo.push({path:"./sounds/",filename:"soundtrack",loop:!0,
volume:1,ingamename:"soundtrack"});d+=s_aSoundsInfo.length;s_aSounds=[];for(var g=0;g<s_aSoundsInfo.length;g++)this.tryToLoadSound(s_aSoundsInfo[g],!1)};this.tryToLoadSound=function(g,r){setTimeout(function(){s_aSounds[g.ingamename]=new Howl({src:[g.path+g.filename+".mp3"],autoplay:!1,preload:!0,loop:g.loop,volume:g.volume,onload:s_oMain.soundLoaded,onloaderror:function(q,p){for(var n=0;n<s_aSoundsInfo.length;n++)if(q===s_aSounds[s_aSoundsInfo[n].ingamename]._sounds[0]._id){s_oMain.tryToLoadSound(s_aSoundsInfo[n],
!0);break}},onplayerror:function(q){for(var p=0;p<s_aSoundsInfo.length;p++)if(q===s_aSounds[s_aSoundsInfo[p].ingamename]._sounds[0]._id){s_aSounds[s_aSoundsInfo[p].ingamename].once("unlock",function(){s_aSounds[s_aSoundsInfo[p].ingamename].play();"soundtrack"===s_aSoundsInfo[p].ingamename&&null!==s_oGame&&setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME)});break}}})},r?200:0)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);for(var g="female",r=
0;2>r;r++){for(var q=0;4>q;q++)for(var p=0;28>=p;p++)s_oSpriteLibrary.addSprite(g+"_"+MATERIALS[q]+"_"+p,"./sprites/character_"+g+"/"+MATERIALS[q]+"/"+g+"_"+MATERIALS[q]+"_"+p+".png");g="male"}for(p=0;33>=p;p++)s_oSpriteLibrary.addSprite("compactor_bottom_"+p,"./sprites/compactor_bottom/compactor_bottom_"+p+".png"),s_oSpriteLibrary.addSprite("compactor_top_"+p,"./sprites/compactor_top/compactor_top_0_"+p+".png");for(p=0;59>=p;p++)s_oSpriteLibrary.addSprite("conveyor_"+p,"./sprites/conveyor/conveyor_"+
p+".jpg");for(p=0;14>=p;p++)s_oSpriteLibrary.addSprite("piston_"+p,"./sprites/piston/piston_"+p+".png");for(p=0;4>p;p++)for(q=0;4>=q;q++)s_oSpriteLibrary.addSprite(MATERIALS[p]+"_"+q,"./sprites/items/"+MATERIALS[p]+"_"+q+".png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_exit",
"./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("but_female","./sprites/but_female.png");s_oSpriteLibrary.addSprite("but_male","./sprites/but_male.png");s_oSpriteLibrary.addSprite("but_help","./sprites/but_help.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("but_left","./sprites/but_left.png");s_oSpriteLibrary.addSprite("but_right","./sprites/but_right.png");s_oSpriteLibrary.addSprite("but_next",
"./sprites/but_next.png");s_oSpriteLibrary.addSprite("but_no","./sprites/but_no.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_settings","./sprites/but_settings.png");s_oSpriteLibrary.addSprite("but_start","./sprites/but_start.png");s_oSpriteLibrary.addSprite("best_score_panel","./sprites/best_score_panel.png");s_oSpriteLibrary.addSprite("hand_indicate",
"./sprites/hand_indicate.png");s_oSpriteLibrary.addSprite("glass","./sprites/glass.png");s_oSpriteLibrary.addSprite("paper","./sprites/paper.png");s_oSpriteLibrary.addSprite("plastic","./sprites/plastic.png");s_oSpriteLibrary.addSprite("organic","./sprites/organic.png");s_oSpriteLibrary.addSprite("collect","./sprites/collect.png");s_oSpriteLibrary.addSprite("avoid","./sprites/avoid.png");s_oSpriteLibrary.addSprite("alert","./sprites/alert.png");s_oSpriteLibrary.addSprite("keyboard_left","./sprites/keyboard_left.png");
s_oSpriteLibrary.addSprite("keyboard_right","./sprites/keyboard_right.png");s_oSpriteLibrary.addSprite("logo_menu","./sprites/logo_menu.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("msg_box_big","./sprites/msg_box_big.png");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("time_panel","./sprites/time_panel.png");s_oSpriteLibrary.addSprite("score_panel","./sprites/score_panel.png");s_oSpriteLibrary.addSprite("swipe",
"./sprites/swipe.png");s_oSpriteLibrary.addSprite("ctl_logo","./sprites/ctl_logo.png");d+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;k.refreshLoader(Math.floor(b/d*100))};this._onRemovePreloader=function(){try{saveItem("ls_available","ok")}catch(g){s_bStorageAvailable=!1}k.unload();s_oSoundTrack=playSound("soundtrack",1,!0);"false"==getItem(PREFIX_LOCAL_STORAGE+"_first_game")&&(s_iNumHelpFirstGame=0);this.gotoMenu()};this._onAllImagesLoaded=
function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;l=STATE_MENU};this.gotoChooseCharacterMenu=function(){new CChooseCharacterMenu;l=STATE_CHOOSE_CHARACTER_MENU};this.gotoGame=function(g){m=new CGame(g);l=STATE_GAME};this.stopUpdateNoBlock=function(){c=!1;createjs.Ticker.paused=!0};this.startUpdateNoBlock=function(){s_iPrevTime=(new Date).getTime();c=!0;createjs.Ticker.paused=!1};this.stopUpdate=function(){c=!1;createjs.Ticker.paused=!0;$("#block_game").css("display",
"block");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();c=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(g){if(!1!==c){var r=(new Date).getTime();s_iTimeElaps=r-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=r;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);l===STATE_GAME&&
m.update();s_oStage.update(g)}};s_oMain=this;HERO_ACCELERATION=a.hero_acceleration;HERO_FRICTION=a.hero_friction;MAX_HERO_SPEED=a.max_hero_speed;MALUS_PERC=a.malus_percentage;TIME_LEVEL=a.time_level;ITEM_POINTS=a.item_point;MALUS_POINTS=a.malus_point;ENABLE_FULLSCREEN=a.fullscreen;CHANGE_DELAY=TIME_LEVEL/4;s_bAudioActive=a.audio_enable_on_startup;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack=null,s_oCanvas,s_bFullscreen=!1,s_aSounds,s_bStorageAvailable=!0,s_iBestScore=0,s_iNumHelpFirstGame=1,s_aSoundsInfo;
function CPreloader(){var a,c,b,d,l,k,m,g,r,q;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.addSprite("but_start","./sprites/but_start.png");s_oSpriteLibrary.loadSprites();q=new createjs.Container;s_oStage.addChild(q)};this.unload=function(){q.removeAllChildren();r.unload()};this._onImagesLoaded=function(){};
this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var p=new createjs.Shape;p.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);q.addChild(p);p=s_oSpriteLibrary.getSprite("200x200");m=createBitmap(p);m.regX=.5*p.width;m.regY=.5*p.height;m.x=CANVAS_WIDTH/2;m.y=CANVAS_HEIGHT/2-180;q.addChild(m);g=new createjs.Shape;g.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(m.x-100,m.y-100,200,200,10);q.addChild(g);m.mask=g;
p=s_oSpriteLibrary.getSprite("progress_bar");d=createBitmap(p);d.x=CANVAS_WIDTH/2-p.width/2;d.y=CANVAS_HEIGHT/2+50;q.addChild(d);a=p.width;c=p.height;l=new createjs.Shape;l.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(d.x,d.y,1,c);q.addChild(l);d.mask=l;b=new createjs.Text("","30px "+FONT,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2+100;b.textBaseline="alphabetic";b.textAlign="center";q.addChild(b);p=s_oSpriteLibrary.getSprite("but_start");r=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2,p,TEXT_PRELOADER_CONTINUE,
"Arial","#000","bold 50",q);r.addEventListener(ON_MOUSE_UP,this._onButStartRelease,this);r.setVisible(!1);k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);q.addChild(k);createjs.Tween.get(k).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(k);q.removeChild(k)})};this._onButStartRelease=function(){s_oMain._onRemovePreloader()};this.refreshLoader=function(p){b.text=p+"%";100===p&&(s_oMain._onRemovePreloader(),b.visible=!1,d.visible=!1);l.graphics.clear();
p=Math.floor(p*a/100);l.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(d.x,d.y,p,c)};this._init()}var MS_ROLLING_SCORE=750;
function CRollingScore(){var a=null,c=null;this.rolling=function(b,d,l){l>parseInt(b.text)?b.color="#fff":l<parseInt(b.text)&&(b.color="#ae0000");a=createjs.Tween.get(b).to({text:l},MS_ROLLING_SCORE,createjs.Ease.cubicOut).call(function(){createjs.Tween.removeTweens(a);b.color="#fff"}).addEventListener("change",function(){b.text=Math.floor(b.text)});null!==d&&(c=createjs.Tween.get(d).to({text:l},MS_ROLLING_SCORE,createjs.Ease.cubicOut).call(function(){createjs.Tween.removeTweens(c)}).addEventListener("change",
function(){d.text=Math.floor(d.text)}))};return this}
function CTextButton(a,c,b,d,l,k,m,g){var r,q,p,n,y,z,f,w,t,H;this._init=function(h,G,A,B,u,F,x,L){r=!1;n=[];y=[];H=createBitmap(A);q=A.width;p=A.height;var J=Math.ceil(x/20);w=new createjs.Text(B,x+"px "+u,"#000000");var M=w.getBounds();w.textAlign="center";w.lineWidth=.9*q;w.textBaseline="alphabetic";w.x=A.width/2+J;w.y=Math.floor(A.height/2)+M.height/3+J;t=new createjs.Text(B,x+"px "+u,F);t.textAlign="center";t.textBaseline="alphabetic";t.lineWidth=.9*q;t.x=A.width/2;t.y=Math.floor(A.height/2)+
M.height/3;f=new createjs.Container;f.x=h;f.y=G;f.regX=A.width/2;f.regY=A.height/2;s_bMobile||(f.cursor="pointer");f.addChild(H,w,t);!1!==L&&s_oStage.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown");f.off("pressup");s_oStage.removeChild(f)};this.setVisible=function(h){f.visible=h};this.setAlign=function(h){t.textAlign=h;w.textAlign=h};this.enable=function(){r=!1;H.filters=[];H.cache(0,0,q,p)};this.disable=function(){r=!0;var h=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);
H.filters=[new createjs.ColorMatrixFilter(h)];H.cache(0,0,q,p)};this._initListener=function(){f.on("mousedown",this.buttonDown);f.on("pressup",this.buttonRelease)};this.addEventListener=function(h,G,A){n[h]=G;y[h]=A};this.addEventListenerWithParams=function(h,G,A,B){n[h]=G;y[h]=A;z=B};this.buttonRelease=function(){r||(playSound("click",1,!1),f.scaleX=1,f.scaleY=1,n[ON_MOUSE_UP]&&n[ON_MOUSE_UP].call(y[ON_MOUSE_UP],z))};this.buttonDown=function(){r||(f.scaleX=.9,f.scaleY=.9,n[ON_MOUSE_DOWN]&&n[ON_MOUSE_DOWN].call(y[ON_MOUSE_DOWN]))};
this.setPosition=function(h,G){f.x=h;f.y=G};this.changeText=function(h){t.text=h;w.text=h};this.setX=function(h){f.x=h};this.setY=function(h){f.y=h};this.getButtonImage=function(){return f};this.getX=function(){return f.x};this.getY=function(){return f.y};this.getSprite=function(){return f};this._init(a,c,b,d,l,k,m,g);return this}
function CToggle(a,c,b,d,l){var k,m,g,r=[],q,p,n;this._init=function(y,z,f,w){m=[];g=[];var t=new createjs.SpriteSheet({images:[f],frames:{width:f.width/2,height:f.height,regX:f.width/2/2,regY:f.height/2},animations:{state_true:[0],state_false:[1]}});k=w;n=createSprite(t,"state_"+k,f.width/2/2,f.height/2,f.width/2,f.height);n.mouseEnabled=!0;n.x=y;n.y=z;n.stop();l.addChild(n);n.cursor="pointer";this._initListener()};this.unload=function(){n.off("mousedown",q);n.off("pressup",p);n.mouseEnabled=!1;
l.removeChild(n)};this._initListener=function(){q=n.on("mousedown",this.buttonDown);p=n.on("pressup",this.buttonRelease)};this.addEventListener=function(y,z,f){m[y]=z;g[y]=f};this.addEventListenerWithParams=function(y,z,f,w){m[y]=z;g[y]=f;r=w};this.setActive=function(y){k=y;n.gotoAndStop("state_"+k)};this.buttonRelease=function(){n.scaleX=1;n.scaleY=1;playSound("click",1,!1);k=!k;n.gotoAndStop("state_"+k);m[ON_MOUSE_UP]&&m[ON_MOUSE_UP].call(g[ON_MOUSE_UP],r)};this.buttonDown=function(){n.scaleX=.9;
n.scaleY=.9;m[ON_MOUSE_DOWN]&&m[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN],r)};this.setPosition=function(y,z){n.x=y;n.y=z};this.setVisible=function(y){n.visible=y};this.getButtonImage=function(){return n};this._init(a,c,b,d)}
function CGfxButton(a,c,b,d){var l,k,m,g,r,q,p=[],n;this._init=function(z,f,w){l=!0;k=1;r=[];q=[];n=createBitmap(w);n.x=z;n.y=f;n.regX=w.width/2;n.regY=w.height/2;y.addChild(n);n.cursor="pointer";this._initListener()};this.unload=function(){n.off("mousedown",m);n.off("pressup",g);createjs.Tween.removeTweens(n);y.removeChild(n)};this.setVisible=function(z){n.visible=z};this.setScale=function(z){k=z;n.scaleX=n.scaleY=k};this._initListener=function(){m=n.on("mousedown",this.buttonDown);g=n.on("pressup",
this.buttonRelease)};this.addEventListener=function(z,f,w){r[z]=f;q[z]=w};this.addEventListenerWithParams=function(z,f,w,t){r[z]=f;q[z]=w;p=t};this.buttonRelease=function(){l&&(n.scaleX=k,n.scaleY=k,r[ON_MOUSE_UP]&&r[ON_MOUSE_UP].call(q[ON_MOUSE_UP],p))};this.buttonDown=function(){l&&(n.scaleX=.9*k,n.scaleY=.9*k,playSound("click",1,!1),r[ON_MOUSE_DOWN]&&r[ON_MOUSE_DOWN].call(q[ON_MOUSE_DOWN],p))};this.setScale=function(z){k=z;n.scaleX=z;n.scaleY=z};this.setPosition=function(z,f){n.x=z;n.y=f};this.pulseAnimation=
function(){createjs.Tween.get(n,{loop:-1}).to({scaleX:1.1*k,scaleY:1.1*k},850,createjs.Ease.quadOut).to({scaleX:k,scaleY:k},650,createjs.Ease.quadIn)};this.setX=function(z){n.x=z};this.setY=function(z){n.y=z};this.setActive=function(z){l=z;n.cursor=l?"pointer":"arrow"};this.getButtonImage=function(){return n};this.getX=function(){return n.x};this.getY=function(){return n.y};var y=d;this._init(a,c,b);return this}
function CMenu(){var a,c,b,d,l,k,m,g,r=null,q=null,p,n,y,z;this._init=function(){p=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(p);var f=s_oSpriteLibrary.getSprite("but_play");m=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+300,f,s_oStage);m.pulseAnimation();m.addEventListener(ON_MOUSE_UP,this._onStart,this,0);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f=s_oSpriteLibrary.getSprite("audio_icon"),l=CANVAS_WIDTH-f.height/2-10,k=f.height/2+10,n=new CToggle(l,k,f,s_bAudioActive,
s_oStage),n.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);f=s_oSpriteLibrary.getSprite("but_credits");b=f.width/2+10;d=f.height/2+10;g=new CGfxButton(b,d,f,s_oStage);g.addEventListener(ON_MOUSE_UP,this._onCreditsBut,this);f=window.document;var w=f.documentElement;r=w.requestFullscreen||w.mozRequestFullScreen||w.webkitRequestFullScreen||w.msRequestFullscreen;q=f.exitFullscreen||f.mozCancelFullScreen||f.webkitExitFullscreen||f.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(r=!1);r&&screenfull.isEnabled&&
(f=s_oSpriteLibrary.getSprite("but_fullscreen"),a=b+f.width/2+10,c=f.height/2+10,y=new CToggle(a,c,f,s_bFullscreen,s_oStage),y.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));f=s_oSpriteLibrary.getSprite("logo_menu");z=createBitmap(f);z.regX=f.width/2;z.regY=f.height/2;z.x=CANVAS_WIDTH/2;z.y=830;z.scale=.1;s_oStage.addChild(z);createjs.Tween.get(z).to({scale:1},1E3,createjs.Ease.elasticOut);f=new createjs.Text(""," 60px "+FONT,"#fff");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2+520;f.textAlign=
"center";f.textBaseline="alphabetic";s_oStage.addChild(f);this.refreshButtonPos();s_bStorageAvailable?(w=getItem(PREFIX_LOCAL_STORAGE+"_best_score"),null!==w&&(s_iBestScore=w)):new CMsgBox;f.text=TEXT_BEST_SCORE+": "+s_iBestScore;var t=new createjs.Shape;t.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(t);createjs.Tween.get(t).to({alpha:0},1E3).call(function(){t.visible=!1})};this.unload=function(){_bUpdate=!1;m.unload();g.unload();if(!1===DISABLE_SOUND_MOBILE||
!1===s_bMobile)n.unload(),n=null;r&&screenfull.isEnabled&&y.unload();s_oMenu=null;s_oStage.removeAllChildren()};this.refreshButtonPos=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||n.setPosition(l-s_iOffsetX,s_iOffsetY+k);r&&screenfull.isEnabled&&y.setPosition(a+s_iOffsetX,c+s_iOffsetY);g.setPosition(b+s_iOffsetX,s_iOffsetY+d)};this._onStart=function(){$(s_oMain).trigger("start_session");s_oMenu.unload();s_oMain.gotoChooseCharacterMenu()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);
s_bAudioActive=!s_bAudioActive};this._onCreditsBut=function(){new CCreditsPanel};this.resetFullscreenBut=function(){r&&screenfull.isEnabled&&y.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?q.call(window.document):r.call(window.document.documentElement);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){var c,b,d,l,k,m,g,r,q,p,n,y,z,f,w,t,H,h,G,A,B,u,F,x,L,J,M,N,S,T,Y,Z,Q;this._init=function(v){setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME);f=[];this._initBg();this._initHero(v);T=new CInterface;B=new CReadyGoAnim({x:CANVAS_WIDTH/2,y:-250},{x:CANVAS_WIDTH/2,y:-250},120,"#fff",s_oStage);B.addEventListener(ON_END_READYGO_ANIM,this._startGame,this);this.reset();Y=new CHelpPanel(H,h.slice(),v);Y.addEventListener(ON_EXIT_FROM_HELP,this._onExitFromHelp,this);Z=new CAreYouSurePanel(s_oStage);
Z.addEventListener(ON_BUT_YES_DOWN,this.onConfirmExit,this);Q=new CEndPanel;Q.addEventListener(ON_BACK_MENU,this.onConfirmExit,this);Q.addEventListener(ON_RESTART,this._restartLevel,this);this.refreshButtonPos();this.showHelpPanel()};this.unload=function(){T.unload();Q.unload();Y.unload();s_oGame=null;createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.refreshButtonPos=function(){T.refreshButtonPos()};this.reset=function(v){d=b=c=!1;m=0;g=TIME_LEVEL;k=0;p=START_SPAWN_ITEM_TIME;y=PERC_FALL_ITEM;
z=(MAX_PERC_FALL_ITEM-PERC_FALL_ITEM)/(TIME_LEVEL/1E3);r=1;q=Math.floor(TIME_LEVEL/CHANGE_DELAY)-1;w=[];h=[];G=shuffle(MATERIALS.slice());v?this._changeMaterialToCollect():this._setMaterialToCollect();A.setMaterial(H);A.reset();T.reset(k);for(v=0;v<f.length;v++)f[v].unload();f=[]};this._initBg=function(){var v=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(v);u=new createjs.Container;s_oStage.addChild(u);v=[];for(var e=0;33>=e;e++)v.push(s_oSpriteLibrary.getSprite("compactor_bottom_"+
e));e={framerate:FPS,images:v,frames:{width:v[0].width,height:v[0].height,regX:v[0].width,regY:v[0].height},animations:{anim:[0,v.length-1]}};e=new createjs.SpriteSheet(e);J=createSprite(e,"anim",v[0].width,v[0].height,v[0].width,v[0].height);J.x=CANVAS_WIDTH;J.y=CANVAS_HEIGHT;u.addChild(J);v=[];for(e=0;59>=e;e++)v.push(s_oSpriteLibrary.getSprite("conveyor_"+e));e={framerate:FPS,images:v,frames:{width:v[0].width,height:v[0].height,regX:v[0].width/2,regY:0},animations:{anim:[0,v.length-1]}};e=new createjs.SpriteSheet(e);
M=createSprite(e,"anim",v[0].width/2,0,v[0].width,v[0].height);M.x=CANVAS_WIDTH/2;M.y=TOP_CONVEYOR_Y;u.addChild(M);N=createSprite(e,"anim",v[0].width/2,0,v[0].width,v[0].height);N.x=CANVAS_WIDTH/2;N.y=BOTTOM_CONVEYOR_Y;u.addChild(N);v=[];for(e=0;33>=e;e++)v.push(s_oSpriteLibrary.getSprite("compactor_top_"+e));e={framerate:FPS,images:v,frames:{width:v[0].width,height:v[0].height,regX:v[0].width,regY:v[0].height},animations:{anim:[22,33],animDispose:[0,21,"anim"]}};e=new createjs.SpriteSheet(e);S=createSprite(e,
"anim",v[0].width,v[0].height,v[0].width,v[0].height);S.x=CANVAS_WIDTH;S.y=CANVAS_HEIGHT;u.addChild(S);t=[];v=CANVAS_WIDTH/2-2*(PISTON_WIDTH-30);var O=PISTON_Y;for(e=0;5>e;e++){var U=new CPiston(v,O,u);t.push(U);v+=PISTON_WIDTH-30}x=new createjs.Container;u.addChild(x);x.visible=!1;x.alpha=0;e=s_oSpriteLibrary.getSprite("alert");v=createBitmap(e);x.addChild(v);U=e.width+120;v=(U-e.width)/-2;O=e.height+5;new CTLText(x,v,O,U,120,80,"center","#fff",FONT,1,0,0,TEXT_ALERT_CHANGE_MATERIAL,!0,!0,!0,!1);
x.x=CANVAS_WIDTH/2;x.y=CANVAS_HEIGHT/2;x.regX=x.getBounds().width/2;x.regY=x.getBounds().height/2;L=createjs.Tween.get(x,{loop:-1,bounce:!0}).to({scale:1.4},400,createjs.Ease.cubicOut)};this._initHero=function(v){F=new createjs.Container;s_oStage.addChild(F);s_oStage.setChildIndex(F,1);A=new CHero(CANVAS_WIDTH/2,FLOOR_Y,v,F)};this.showHelpPanel=function(){this.stopUpdate();Y.refresh(H,h.slice());Y.show()};this._onExitFromHelp=function(){T.isPaused()||this.prepareStartLevel()};this.prepareStartLevel=
function(){T.disableGUIExpandible();B.showFade();l||B.show(H)};this._startGame=function(){this.startUpdate();T.enableGUIExpandible();T.collapseGUIButtons()};this._restartLevel=function(){this.reset(!0)};this._spawnItem=function(){var v=Math.floor(100*Math.random())>=MALUS_PERC?H:h[Math.floor(3*Math.random())];var e=Math.floor(Math.random()*NUM_ITEM_TYPES_PER_MATERIAL),O=!1;if(Math.floor(101*Math.random())<y){var U=Math.floor(5*Math.random());var V=t[U].getX();0<s_iNumHelpFirstGame&&v==H&&(O=!0,s_iNumHelpFirstGame--)}else V=
-1;y<=MAX_PERC_FALL_ITEM&&(y+=z);v=new CItem(0,TOP_CONVEYOR_Y,V,v,e,O,u);u.setChildIndex(S,u.numChildren-1);v.addEventListener(ON_ITEM_DIE,this._onItemDie,this);-1<V&&v.addEventListenerWithParams(ON_ITEM_FALL,this._onItemFall,this,U);f.push(v)};this._onItemDie=function(v){for(var e=0;e<f.length;e++)if(f[e]===v){w.push(v);break}"anim"==S.currentAnimation&&v.getY()>CANVAS_HEIGHT/2&&v.getX()>=CANVAS_WIDTH&&S.gotoAndPlay("animDispose")};this._onItemFall=function(v){t[v].push()};this._setMaterialToCollect=
function(){H=G.pop();h=[];MATERIALS.forEach(function(v){v!=H&&h.push(v)})};this._changeMaterialToCollect=function(){this._setMaterialToCollect();this.showHelpPanel()};this.onKeyDown=function(v){if(!1===c||l)return v.preventDefault(),!1;v||(v=window.event);switch(v.keyCode){case LEFT_DIR:return A.moveLeft(!0),v.preventDefault(),!1;case RIGHT_DIR:return A.moveRight(!0),v.preventDefault(),!1}};this.onKeyUp=function(v){if(b||l)return v.preventDefault(),!1;v||(v=window.event);switch(v.keyCode){case 37:return A.moveLeft(!1),
v.preventDefault(),!1;case 39:return A.moveRight(!1),v.preventDefault(),!1}};this.moveLeft=function(v){!1!==c&&A.moveLeft(v)};this.moveRight=function(v){!1!==c&&A.moveRight(v)};this.onExit=function(){Z.show(TEXT_ARE_YOU_SURE,90)};this.onConfirmExit=function(){this.unload();$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("end_session");s_oMain.gotoMenu()};this.gameOver=function(){this.stopUpdate();this._stopAlertChangeMaterialToCollect();k>s_iBestScore&&(s_iBestScore=k,T.refreshBestScore());
Q.show(k);A.setIdle();saveItem(PREFIX_LOCAL_STORAGE+"_best_score",s_iBestScore);saveItem(PREFIX_LOCAL_STORAGE+"_first_game",!1)};this._refreshScore=function(v){k+=v;0>k&&(k=0);T.refreshScore(k)};this.playAlertTween=function(){x.visible&&L.gotoAndPlay()};this.pauseAlertTween=function(){x.visible&&L.gotoAndStop()};this._alertChangeMaterialToCollect=function(){d=!0;x.visible=!0;x.alpha=.8;x.scale=1;this.playAlertTween()};this._stopAlertChangeMaterialToCollect=function(){this.pauseAlertTween();x.alpha=
0;d=x.visible=!1};this._checkCollision=function(){for(var v=A.getRectCollision(),e=0;e<f.length;e++){var O=f[e].getRectCollision();O&&v.intersects(O)&&(f[e].getMaterial()!=H?(playSound("catch_malus",1,!1),A.collectBad(),O=-MALUS_POINTS):(playSound("catch_item",1,!1),A.collectGood(),O=ITEM_POINTS),f[e].die(),new CScoreText(O,f[e].getX(),f[e].getY(),u),this._refreshScore(O))}};this.stopUpdate=function(){c=!1;s_oInterface.isPaused()&&(J.stop(),M.stop(),N.stop(),S.stop(),f.forEach(function(v){v.stopUpdate()}))};
this.startUpdate=function(){c=!0;J.play();M.play();N.play();S.play();f.forEach(function(v){v.startUpdate()})};this.update=function(){g!=TIME_LEVEL&&(A.update(),l)&&((1==A.getCheckLimit()&&A.setCheckLimit(!1),A.getX()<CANVAS_WIDTH+100&&!_bHeroLeftTheGame)?A.moveRight(!0):_bHeroLeftTheGame?A.getX()>n?A.moveLeft(!0):A.getX()<n&&(A.moveLeft(!1),A.setCheckLimit(!0),A.setIdle(),l=!1,0==Y.isShowing()&&B.show(H)):(_bHeroLeftTheGame=!0,A.moveRight(!1),A.setMaterial(H)));for(var v=0;v<f.length;v++)f[v].update();
if(c){m+=s_iTimeElaps;m>p&&(m=0,this._spawnItem());this._checkCollision();for(v=0;v<w.length;v++)for(var e=0;e<f.length;e++)if(w[v]===f[e]){f.splice(e,1);break}w=[];g-=s_iTimeElaps;r+=s_iTimeElaps;r>=CHANGE_DELAY-3E3&&0==d&&0<q&&this._alertChangeMaterialToCollect();r>=CHANGE_DELAY&&0<q&&(r=0,l=!0,A.moveLeft(!1),n=A.getX(),_bHeroLeftTheGame=!1,this._stopAlertChangeMaterialToCollect(),this._changeMaterialToCollect(),q--);0>g&&(g=0,this.gameOver());T.refreshTime(g)}};s_oGame=this;this._init(a)}
var s_oGame=null;
function CInterface(){var a,c,b,d,l,k,m,g,r,q,p,n,y,z,f,w,t=null,H=null,h,G,A,B,u,F,x,L,J,M,N,S,T,Y,Z,Q,v,e,O,U,V;this._init=function(){L=new createjs.Container;L.visible=!1;s_oStage.addChild(L);var D=new createjs.Shape;D.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);D.alpha=.5;L.addChild(D);D=new createjs.Text(TEXT_PAUSE,"120px "+FONT,"#fff");D.textAlign="center";D.textBaseline="alphabetic";D.x=CANVAS_WIDTH/2;D.y=CANVAS_HEIGHT/2;L.addChild(D);s_bMobile?(D=s_oSpriteLibrary.getSprite("but_left"),
r=D.width/2+50,q=CANVAS_HEIGHT-D.height/2-20,B=new CGfxButton(r,q,D,s_oStage),B.addEventListener(ON_MOUSE_DOWN,this._onLeftDown,this),B.addEventListener(ON_MOUSE_UP,this._onLeftUp,this),D=s_oSpriteLibrary.getSprite("but_right"),m=CANVAS_WIDTH-D.width/2-50,g=CANVAS_HEIGHT-D.height/2-20,u=new CGfxButton(m,g,D,s_oStage),u.addEventListener(ON_MOUSE_DOWN,this._onRightDown,this),u.addEventListener(ON_MOUSE_UP,this._onRightUp,this),Q=new createjs.Shape,Q.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(10,
0,CANVAS_WIDTH/2-10,CANVAS_HEIGHT),s_oStage.addChild(Q),v=Q.on("mousedown",B.buttonDown),e=Q.on("pressup",B.buttonRelease),O=new createjs.Shape,O.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(CANVAS_WIDTH/2+10,0,CANVAS_WIDTH/2-10,CANVAS_HEIGHT),s_oStage.addChild(O),U=O.on("mousedown",u.buttonDown),V=O.on("pressup",u.buttonRelease)):(document.onkeydown=s_oGame.onKeyDown,document.onkeyup=s_oGame.onKeyUp);w=f=10;M=new createjs.Container;M.x=f;M.y=w;s_oStage.addChild(M);D=s_oSpriteLibrary.getSprite("score_panel");
var C=createBitmap(D);M.addChild(C);Y=new CTLText(M,100,24,200,54,54,"left","#fff",FONT,1,0,0,"0",!0,!0,!1,!1);y=10;z=D.height+10;N=new createjs.Container;N.x=y;N.y=z;s_oStage.addChild(N);D=s_oSpriteLibrary.getSprite("best_score_panel");C=createBitmap(D);N.addChild(C);Z=new CTLText(N,100,24,200,54,54,"left","#fff",FONT,1,0,0,s_iBestScore.toString(),!0,!0,!1,!1);p=10;n=N.y+D.height;J=new createjs.Container;J.x=p;J.y=n;s_oStage.addChild(J);D=createBitmap(s_oSpriteLibrary.getSprite("time_panel"));J.addChild(D);
T=new CTLText(J,100,19,200,64,64,"center","#fff",FONT,1,0,0,formatTime(TIME_LEVEL),!0,!0,!1,!1);D=s_oSpriteLibrary.getSprite("but_exit");l=CANVAS_WIDTH-D.height/2-10;k=D.height/2+10;A=new CGfxButton(l,k,D,s_oStage);A.addEventListener(ON_MOUSE_UP,this._onExit,this);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(D=s_oSpriteLibrary.getSprite("audio_icon"),b=A.getX()-D.width/2-10,d=D.height/2+10,h=new CToggle(b,d,D,s_bAudioActive,s_oStage),h.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),D=s_oSpriteLibrary.getSprite("but_fullscreen"),
a=b-D.width/2-10):(D=s_oSpriteLibrary.getSprite("but_fullscreen"),a=A.getX()-D.width/2-10);c=D.height/2+10;C=window.document;var I=C.documentElement;t=I.requestFullscreen||I.mozRequestFullScreen||I.webkitRequestFullScreen||I.msRequestFullscreen;H=C.exitFullscreen||C.mozCancelFullScreen||C.webkitExitFullscreen||C.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(t=!1);t&&screenfull.isEnabled&&(G=new CToggle(a,c,D,s_bFullscreen,s_oStage),G.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));F=new CGfxButton(100,
100,s_oSpriteLibrary.getSprite("but_help"),s_oStage);F.addEventListener(ON_MOUSE_UP,this._onHelp,this);D=s_oSpriteLibrary.getSprite("but_settings");x=new CGUIExpandible(l,k,D,s_oStage);x.addButton(A);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||x.addButton(h);t&&screenfull.isEnabled&&x.addButton(G);x.addButton(F);S=new CRollingScore};this.unload=function(){x.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h.unload(),h=null;t&&screenfull.isEnabled&&G.unload();s_bMobile?(B.unload(),u.unload(),Q.off("mousedown",
v),Q.off("pressup",e),O.off("mousedown",U),O.off("pressup",V)):(document.onkeydown=null,document.onkeyup=null);A.unload();s_oInterface=null};this.refreshButtonPos=function(){x.refreshPos();M.x=f+s_iOffsetX;M.y=w+s_iOffsetY;N.x=y+s_iOffsetX;N.y=z+s_iOffsetY;s_bLandscape?(p=10,n=N.y+N.getBounds().height-s_iOffsetY):(p=M.getBounds().width+20,n=M.y);J.x=p+s_iOffsetX;J.y=n+s_iOffsetY;s_bMobile&&(B.setPosition(r+s_iOffsetX,q-s_iOffsetY),u.setPosition(m-s_iOffsetX,g-s_iOffsetY))};this.reset=function(D){this.refreshTime(TIME_LEVEL);
this.refreshScore(D);x.reset()};this.refreshTime=function(D){T.refreshText(formatTime(D))};this.refreshScore=function(D){S.rolling(Y.getText(),null,D)};this.refreshBestScore=function(){Z.refreshText(s_iBestScore)};this.onPause=function(){1==L.visible?(L.visible=!1,s_oGame.playAlertTween()):(L.visible=!0,s_oGame.pauseAlertTween())};this.collapseGUIButtons=function(){x.isExpanded()&&(x._onMenu(),this.onPause())};this.disableGUIExpandible=function(){x.disable()};this.enableGUIExpandible=function(){x.enable()};
this._onLeftDown=function(){s_oGame.moveLeft(!0)};this._onRightDown=function(){s_oGame.moveRight(!0)};this._onLeftUp=function(){s_oGame.moveLeft(!1)};this._onRightUp=function(){s_oGame.moveRight(!1)};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){s_oGame.onExit()};this._onHelp=function(){s_oGame.showHelpPanel()};this.isPaused=function(){return L.visible};this.resetFullscreenBut=function(){t&&screenfull.isEnabled&&G.setActive(s_bFullscreen)};
this._onFullscreenRelease=function(){s_bFullscreen?H.call(window.document):t.call(window.document.documentElement);sizeHandler()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CEndPanel(){var a,c,b,d,l,k,m,g,r,q,p,n,y,z=this;this._init=function(){b=[];d=[];n=new createjs.Container;n.visible=!1;s_oStage.addChild(n);m=new createjs.Shape;m.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);m.alpha=.5;l=m.on("click",function(){});n.addChild(m);k=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));y=new createjs.Container;y.x=CANVAS_WIDTH/2;n.addChild(y);var f=s_oSpriteLibrary.getSprite("msg_box"),w=createBitmap(f);y.addChild(w);new CTLText(y,f.width/
2-250,f.height/2-200,500,80,80,"center","#fff",FONT,1,0,0,TEXT_GAMEOVER,!0,!0,!1,!1);g=new CTLText(y,f.width/2-250,f.height/2-70,500,50,50,"center","#fff",FONT,1,0,0,TEXT_BEST_SCORE,!0,!0,!1,!1);r=new CTLText(y,f.width/2-250,f.height/2,500,50,50,"center","#fff",FONT,1,0,0,TEXT_SCORE,!0,!0,!1,!1);q=new CGfxButton(f.width/2-250,f.height/2+180,s_oSpriteLibrary.getSprite("but_home"),y);q.addEventListener(ON_MOUSE_UP,this._onHome,this);p=new CGfxButton(f.width/2+250,f.height/2+180,s_oSpriteLibrary.getSprite("but_restart"),
y);p.addEventListener(ON_MOUSE_UP,this._onRestart,this);a=-f.height/2;y.regX=f.width/2;y.regY=f.height/2};this.unload=function(){q.unload();p.unload();m.off("click",l)};this.addEventListener=function(f,w,t){b[f]=w;d[f]=t};this.show=function(f){$(s_oMain).trigger("save_score",f);$(s_oMain).trigger("share_event",f);playSound("time_over",1,!1);r.refreshText(TEXT_SCORE+": "+f);g.refreshText(TEXT_BEST_SCORE+": "+s_iBestScore);k.alpha=0;m.alpha=0;y.y=a;n.visible=!0;createjs.Tween.get(k).to({alpha:1},500);
createjs.Tween.get(m).to({alpha:.7},500);createjs.Tween.get(y).wait(400).to({y:CANVAS_HEIGHT/2},800,createjs.Ease.bounceOut)};this.hide=function(){createjs.Tween.get(y).to({y:a},800,createjs.Ease.backIn).call(function(){createjs.Tween.get(k).to({alpha:0},400,createjs.Ease.cubicOut).call(function(){n.visible=!1;b[c]&&b[c].call(d[c])})})};this._onHome=function(){c=ON_BACK_MENU;z.hide()};this._onRestart=function(){$(s_oMain).trigger("show_interlevel_ad");c=ON_RESTART;z.hide()};this._init()}
function CCreditsPanel(){var a,c,b,d,l,k,m;this._init=function(){b=new createjs.Shape;b.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);b.alpha=0;b.on("mousedown",function(){});s_oStage.addChild(b);createjs.Tween.get(b).to({alpha:.7},500);d=new createjs.Container;s_oStage.addChild(d);var g=s_oSpriteLibrary.getSprite("msg_box");m=createBitmap(g);m.regX=g.width/2;m.regY=g.height/2;d.addChild(m);c=m.on("click",this._onLogoButRelease);d.x=CANVAS_WIDTH/2;d.y=-g.height/2;a=d.y;createjs.Tween.get(d).to({y:CANVAS_HEIGHT/
2},1E3,createjs.Ease.bounceOut);g=new createjs.Text(TEXT_DEVELOPED," 50px "+FONT,"#fff");g.y=-70;g.textAlign="center";g.textBaseline="alphabetic";d.addChild(g);g=new createjs.Text("www.codethislab.com"," 56px "+FONT,"#fff");g.y=106;g.textAlign="center";g.textBaseline="middle";g.lineWidth=320;d.addChild(g);g=s_oSpriteLibrary.getSprite("ctl_logo");k=createBitmap(g);k.regX=g.width/2;k.regY=g.height/2;k.y=0;d.addChild(k);g=s_oSpriteLibrary.getSprite("but_exit");l=new CGfxButton(320,-210,g,d);l.addEventListener(ON_MOUSE_UP,
this.unload,this)};this.unload=function(){createjs.Tween.get(b).to({alpha:0},500);createjs.Tween.get(d).to({y:a},400,createjs.Ease.backIn).call(function(){s_oStage.removeChild(b);s_oStage.removeChild(d);l.unload()});b.off("mousedown",function(){});m.off("mousedown",c)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._init()}
function CAreYouSurePanel(a){var c,b,d,l,k,m,g,r,q,p,n,y=this;this._init=function(){b=[];d=[];q=new createjs.Container;q.visible=!1;z.addChild(q);p=new createjs.Shape;p.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);p.alpha=.5;l=p.on("click",function(){});q.addChild(p);n=new createjs.Container;q.addChild(n);var f=s_oSpriteLibrary.getSprite("msg_box");k=createBitmap(f);k.regX=.5*f.width;k.regY=.5*f.height;n.addChild(k);n.x=CANVAS_WIDTH/2;n.y=c=-f.height/2;m=new CTLText(n,-250,
-130,500,200,90,"center","#fff",FONT,1,0,0," ",!0,!0,!0,!1);g=new CGfxButton(250,170,s_oSpriteLibrary.getSprite("but_yes"),n);g.addEventListener(ON_MOUSE_UP,this._onButYes,this);r=new CGfxButton(-250,170,s_oSpriteLibrary.getSprite("but_exit"),n);r.addEventListener(ON_MOUSE_UP,this._onButNo,this)};this.addEventListener=function(f,w,t){b[f]=w;d[f]=t};this.show=function(f,w){m.refreshText(f);n.y=c;q.visible=!0;createjs.Tween.get(n).to({y:CANVAS_HEIGHT/2},1E3,createjs.Ease.bounceOut).call(function(){})};
this.hide=function(){q.visible=!1};this.unload=function(){r.unload();g.unload();p.off("click",l)};this._onButYes=function(){y.hide();b[ON_BUT_YES_DOWN]&&b[ON_BUT_YES_DOWN].call(d[ON_BUT_YES_DOWN])};this._onButNo=function(){b[ON_BUT_NO_DOWN]&&b[ON_BUT_NO_DOWN].call(d[ON_BUT_NO_DOWN]);y.hide()};var z=a;this._init()}
function CMsgBox(){var a,c,b,d,l;this._init=function(){l=new createjs.Container;s_oStage.addChild(l);b=new createjs.Shape;b.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);b.alpha=.5;a=b.on("click",function(){});l.addChild(b);d=new createjs.Container;l.addChild(d);var k=s_oSpriteLibrary.getSprite("msg_box"),m=createBitmap(k);m.regX=.5*k.width;m.regY=.5*k.height;d.addChild(m);d.x=CANVAS_WIDTH/2;d.y=-k.height/2;new CTLText(d,-280,-220,560,270,40,"center","#fff",FONT,1,0,0,TEXT_ERR_LS,
!0,!0,!0,!1);c=new CGfxButton(0,160,s_oSpriteLibrary.getSprite("but_yes"),d);c.addEventListener(ON_MOUSE_UP,this._onButYes,this);createjs.Tween.get(d).to({y:CANVAS_HEIGHT/2},1E3,createjs.Ease.bounceOut)};this._onButYes=function(){c.unload();b.off("click",a);s_oStage.removeChild(l)};this._init()}
function CHelpPanel(a,c,b){var d,l,k,m,g,r,q,p,n,y,z=[],f,w,t,H=this;this._init=function(h,G,A){l=[];k=[];w=new createjs.Container;w.visible=!1;s_oStage.addChild(w);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=.5;m=g.on("click",function(){});w.addChild(g);t=new createjs.Container;t.x=CANVAS_WIDTH/2;w.addChild(t);var B=s_oSpriteLibrary.getSprite("msg_box_big"),u=createBitmap(B);t.addChild(u);q=new CTLText(t,B.width/2-(B.width-150)/2,50,B.width-
150,100,70,"center","#fff",FONT,1,0,0,TEXT_HELP_PANEL_COLLECT+" "+TEXT_MATERIALS[h],!0,!0,!0,!1);var F=s_oSpriteLibrary.getSprite(h);r=createBitmap(F);r.x=310;r.y=B.height/2-F.height-50;t.addChild(r);u=createBitmap(s_oSpriteLibrary.getSprite("collect"));u.x=550;u.y=B.height/2-F.height-50;t.addChild(u);var x=310;for(u=0;3>u;u++){F=s_oSpriteLibrary.getSprite(G.pop());var L=createBitmap(F);L.x=x;L.y=B.height/2-F.height+130;t.addChild(L);z.push(L);x-=125}u=createBitmap(s_oSpriteLibrary.getSprite("avoid"));
u.x=550;u.y=B.height/2-F.height+130;t.addChild(u);s_bMobile?(u=s_oSpriteLibrary.getSprite("but_left"),p=createBitmap(u),p.regX=u.width/2,p.regY=u.height/2,p.x=B.width/2-300,p.y=B.height-180,p.scale=.65,t.addChild(p),u=s_oSpriteLibrary.getSprite("but_right"),n=createBitmap(u),n.regX=u.width/2,n.regY=u.height/2,n.x=B.width/2+300,n.y=B.height-180,n.scale=.65):(u=s_oSpriteLibrary.getSprite("keyboard_left"),p=createBitmap(u),p.regX=u.width/2,p.regY=u.height/2,p.x=B.width/2-300,p.y=B.height-180,t.addChild(p),
u=s_oSpriteLibrary.getSprite("keyboard_right"),n=createBitmap(u),n.regX=u.width/2,n.regY=u.height/2,n.x=B.width/2+300,n.y=B.height-180);t.addChild(n);G=A?"male":"female";A=[];for(u=0;4>u;u++)for(F=6;24>=F;F++)A.push(s_oSpriteLibrary.getSprite(G+"_"+MATERIALS[u]+"_"+F));u=new createjs.SpriteSheet({images:A,frames:{width:A[0].width,height:A[0].height,regX:A[0].width/2,regY:A[0].height/2},animations:{walk_glass:[0,18],walk_organic:[19,37],walk_paper:[38,56],walk_plastic:[57,75]}});y=createSprite(u,"walk_"+
h,A[0].width/2,A[0].height/2,A[0].width,A[0].height);y.scale=.4;y.x=B.width/2-150;y.y=B.height-180;t.addChild(y);this._addHelpMoveTween();f=new CGfxButton(B.width/2,B.height-10,s_oSpriteLibrary.getSprite("but_next"),t);f.addEventListener(ON_MOUSE_UP,this._onStart,this);d=-B.height;t.regX=B.width/2;t.regY=B.height/2};this.unload=function(){g.off("click",m);f.unload();createjs.Tween.removeTweens(y);s_oStage.removeChild(w)};this.refresh=function(h,G){this._refreshContainerPanel(h,G)};this._refreshContainerPanel=
function(h,G){r.image=s_oSpriteLibrary.getSprite(h);q.refreshText(TEXT_HELP_PANEL_COLLECT+" "+TEXT_MATERIALS[h]);for(var A=0;3>A;A++)z[A].image=s_oSpriteLibrary.getSprite(G[A]);y.gotoAndPlay("walk_"+h)};this._addHelpMoveTween=function(){createjs.Tween.get(y,{loop:-1}).to({x:t.getBounds().width/2+150},1E3).call(function(){this.scaleX*=-1;H._pressKey(!0)}).to({x:t.getBounds().width/2-150},1E3).call(function(){this.scaleX*=-1;H._pressKey(!1)})};this._pressKey=function(h){var G=.1;s_bMobile&&(G=.1);h?
(n.scale=p.scale,p.scale-=G):(p.scale=n.scale,n.scale-=G)};this.addEventListener=function(h,G,A){l[h]=G;k[h]=A};this.show=function(){g.alpha=0;t.y=d;w.visible=!0;f.setActive(!1);createjs.Tween.get(g).to({alpha:.5},500);createjs.Tween.get(t).wait(400).to({y:CANVAS_HEIGHT/2},800,createjs.Ease.bounceOut).call(function(){f.setActive(!0)})};this.hide=function(){f.setActive(!1);createjs.Tween.get(t).to({y:d},800,createjs.Ease.backIn).call(function(){g.alpha=0;l[ON_EXIT_FROM_HELP]&&l[ON_EXIT_FROM_HELP].call(k[ON_EXIT_FROM_HELP])})};
this.isShowing=function(){return t.y==CANVAS_HEIGHT/2?!0:!1};this._onStart=function(){H.hide()};this._init(a,c,b)}
function CHero(a,c,b,d){var l,k,m=!1,g=!1,r=!0,q,p,n,y,z,f,w;this._init=function(t,H,h){l=t;k=H;q=0;p=HERO_ACCELERATION;n=MAX_HERO_SPEED;y=new createjs.Rectangle(0,0,100,100);z=MATERIALS[0];w=new createjs.Container;w.x=t;w.y=H;d.addChild(w);H=h?"male":"female";t=[];for(h=0;4>h;h++)for(var G=0;28>=G;G++)t.push(s_oSpriteLibrary.getSprite(H+"_"+MATERIALS[h]+"_"+G));H=new createjs.SpriteSheet({images:t,frames:{width:t[0].width,height:t[0].height,regX:t[0].width/2,regY:t[0].height/2},animations:{idle_glass:0,
catch_good_glass:[1,5,"idle_glass"],walk_glass:[6,24],catch_bad_glass:[25,28,"idle_glass"],idle_organic:29,catch_good_organic:[30,34,"idle_organic"],walk_organic:[35,53],catch_bad_organic:[54,57,"idle_organic"],idle_paper:58,catch_good_paper:[59,63,"idle_paper"],walk_paper:[64,82],catch_bad_paper:[83,86,"idle_paper"],idle_plastic:87,catch_good_plastic:[88,92,"idle_plastic"],walk_plastic:[93,111],catch_bad_plastic:[112,115,"idle_plastic"]}});f=createSprite(H,"idle_"+z,t[0].width/2,t[0].height/2,t[0].width,
t[0].height);w.addChild(f)};this.reset=function(){q=0;g=m=!1;f.gotoAndStop("idle_"+z);f.framerate=30;w.x=l;w.y=k};this.setIdle=function(){f.gotoAndStop("idle_"+z)};this.collectGood=function(){f.currentAnimation==="idle_"+z&&(f.framerate=15,f.gotoAndPlay("catch_good_"+z))};this.collectBad=function(){f.currentAnimation==="idle_"+z&&(f.framerate=15,f.gotoAndPlay("catch_bad_"+z))};this.moveLeft=function(t){m=t;m?f.currentAnimation!=="walk_"+z&&(f.framerate=30,f.gotoAndPlay("walk_"+z),w.scaleX=-1):(f.gotoAndStop("idle_"+
z),w.scaleX=1)};this.moveRight=function(t){g=t;g?f.currentAnimation!=="walk_"+z&&(f.framerate=30,f.gotoAndPlay("walk_"+z),w.scaleX=1):(f.gotoAndStop("idle_"+z),w.scaleX=1)};this.getRectCollision=function(){return y};this.getX=function(){return w.x};this.getCheckLimit=function(){return r};this.setCheckLimit=function(t){r=t};this.setMaterial=function(t){z=t;f.gotoAndStop("idle_"+z)};this._updateRectCollision=function(){f.currentAnimation==="walk_"+z?1===w.scaleX?y.setValues(w.x+15,w.y-10,110,40):y.setValues(w.x-
125,w.y-10,110,40):y.setValues(w.x-55,w.y-0,110,40)};this.update=function(){m&&(q-=p);g&&(q+=p);w.x+=q;q*=HERO_FRICTION;q>n&&(q=n);q<-n&&(q=-n);.1>Math.abs(q)&&(q=0);w.x+q>HERO_LIMIT_RIGHT&&1==r&&(w.x=HERO_LIMIT_RIGHT-q);w.x-q<HERO_LIMIT_LEFT&&1==r&&(w.x=HERO_LIMIT_LEFT+q);this._updateRectCollision()};this._init(a,c,b)}
function CGUIExpandible(a,c,b,d){var l,k,m,g,r,q,p,n,y;this._init=function(f,w,t,H){m=!0;r=[];p=new createjs.Container;p.x=f;p.y=w;H.addChild(p);n=new createjs.Container;p.addChild(n);y=new createjs.Container;p.addChild(y);g=!1;q=new CGfxButton(0,0,t,y);q.addEventListener(ON_MOUSE_UP,this._onMenu,this);k=l=130};this.unload=function(){q.unload();d.removeChild(p)};this.refreshPos=function(){p.x=a-s_iOffsetX;p.y=c+s_iOffsetY};this.reset=function(){g&&this._onMenu()};this.addButton=function(f){f=f.getButtonImage();
f.x=0;f.y=0;f.visible=0;n.addChildAt(f,0);r.push(f)};this._onMenu=function(){m&&((g=!g)?z._expand():z._collapse())};this._expand=function(){s_oInterface.onPause();s_oGame.stopUpdate();for(var f=0;f<r.length;f++)r[f].visible=!0,createjs.Tween.get(r[f],{override:!0}).wait(300*f/2).to({y:l+f*k},300,createjs.Ease.cubicOut)};this._collapse=function(){for(var f=0;f<r.length;f++){var w=r[r.length-1-f];createjs.Tween.get(w,{override:!0}).wait(300*f/2).to({y:0},300,createjs.Ease.cubicOut).call(function(t){t.visible=
!1},[w])}s_oInterface.onPause();s_oGame.startUpdate()};this.enable=function(){m=!0;q.setActive(!0)};this.disable=function(){m=!1;q.setActive(!1)};this.isExpanded=function(){return g};var z=this;this._init(a,c,b,d)}
function CItem(a,c,b,d,l,k,m){var g,r,q,p,n,y,z,f,w,t,H,h,G,A=[],B,u,F;this._init=function(x,L,J,M,N,S){q=S;r=!1;p=M;n=N;w=J;y=0;z=.5<Math.random()?1:-1;h=[];G=[];0<w&&(B=new createjs.Rectangle(0,0,100,100),w+=Math.floor(50*Math.random())*(1==Math.floor(2*Math.random())?-1:1));F=new createjs.Container;m.addChild(F);J=s_oSpriteLibrary.getSprite(p+"_"+n);t=J.width;H=J.height;J=createBitmap(J);F.addChild(J);f=BOTTOM_CONVEYOR_Y+30-H/2;F.x=x-t;F.y=L+30;F.regY=H;F.regX=t/2;u={x:0};q&&(J=s_oSpriteLibrary.getSprite("hand_indicate"),
u=createBitmap(J),m.addChild(u),u.x=F.x,u.y=F.y+50,u.regX=36,createjs.Tween.get(u,{loop:-1,bounce:!0}).to({y:F.y},300,createjs.Ease.cubicOut));g=!0};this.addEventListener=function(x,L,J){h[x]=L;G[x]=J};this.addEventListenerWithParams=function(x,L,J,M){h[x]=L;G[x]=J;A=M};this.unload=function(){m.removeChild(F);createjs.Tween.removeTweens(F);createjs.Tween.removeTweens(u)};this.die=function(){this.unload();h[ON_ITEM_DIE]&&h[ON_ITEM_DIE].call(G[ON_ITEM_DIE],this)};this._fall=function(){r=!0;F.regY/=
2;F.y-=F.regY;h[ON_ITEM_FALL]&&h[ON_ITEM_FALL].call(G[ON_ITEM_FALL],A)};this.getRectCollision=function(){return B};this.getMaterial=function(){return p};this.getItemType=function(){return n};this.getX=function(){return F.x};this.getY=function(){return F.y};this.isFalling=function(){return r};this._updateRectCollision=function(){B.setValues(F.x-t/2,F.y-70*H/100/2,t,70*H/100)};this.stopUpdate=function(){g=!1};this.startUpdate=function(){g=!0};this.update=function(){g&&(-1<w&&this._updateRectCollision(),
r?(y+=ITEM_FALLING_SPEED,F.y+=y,30>F.rotation&&-30<F.rotation&&(F.rotation+=.5*z),F.y>f&&(F.y=f,r=!1,createjs.Tween.get(F).to({rotation:t>H?0:90*z,y:t<H?BOTTOM_CONVEYOR_Y+30-t/2:f},p==MATERIALS[0]?400:p==MATERIALS[3]?600:100,p==MATERIALS[0]||p==MATERIALS[3]?createjs.Ease.bounceOut:createjs.Ease.linear))):(F.x+=CONVEYOR_SPEED,u.x+=CONVEYOR_SPEED,F.x>=w&&F.y<f&&0<w&&(this._fall(),q&&(q=!1,u.visible=!1,createjs.Tween.removeTweens(u))),F.x>CANVAS_WIDTH+t&&this.die()))};this._init(a,c,b,d,l,k)}
function CScoreText(a,c,b,d){var l;this._init=function(k,m,g){var r="#fff";0>k?r="#ae0000":k="+"+k;l=new createjs.Text(k," 80px "+FONT,r);l.textAlign="center";l.x=m;l.y=g;l.alpha=0;l.shadow=new createjs.Shadow("#000",1,1,1);d.addChild(l);var q=this;createjs.Tween.get(l).to({alpha:1},200,createjs.Ease.quadIn).call(function(){q.moveUp()})};this.moveUp=function(){var k=l.y-400,m=this;createjs.Tween.get(l).to({y:k},1500,createjs.Ease.sineIn).call(function(){m.unload()});createjs.Tween.get(l).wait(800).to({alpha:0},
500)};this.unload=function(){d.removeChild(l)};this._init(a,c,b)}
function CReadyGoAnim(a,c,b,d,l){var k,m,g,r,q,p=this;this._init=function(n,y){k=[];m=[];g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=.5;g.visible=!1;l.addChild(g);q=new createjs.Container;q.x=a.x;q.y=a.y;l.addChild(q);r=new createjs.Text(TEXT_READY,n+"px "+FONT,y);r.textAlign="center";r.textBaseline="alphabetic";q.addChild(r)};this.addEventListener=function(n,y,z){k[n]=y;m[n]=z};this.showFade=function(){g.visible=!0};this.hideFade=function(){g.visible=
!1};this.show=function(n){q.y=a.y;r.text=TEXT_COLLECT+"\n"+TEXT_MATERIALS[n];createjs.Tween.get(q).wait(1E3).to({y:CANVAS_HEIGHT/2},400,createjs.Ease.backOut).wait(700).to({y:c.y},200,createjs.Ease.cubicOut).call(function(){p._showReady()})};this._showReady=function(){setTimeout(function(){playSound("ready",1,!1)},500);q.y=a.y;r.text=TEXT_READY;createjs.Tween.get(q).wait(500).to({y:CANVAS_HEIGHT/2},400,createjs.Ease.backOut).wait(700).to({y:c.y},200,createjs.Ease.cubicOut).call(function(){p._showGo()})};
this._showGo=function(){setTimeout(function(){playSound("go",1,!1)},500);q.y=a.y;r.text=TEXT_GO;createjs.Tween.get(q).wait(500).to({y:CANVAS_HEIGHT/2},400,createjs.Ease.backOut).wait(700).to({y:c.y},200,createjs.Ease.cubicOut).call(function(){p.hideFade();k[ON_END_READYGO_ANIM]&&k[ON_END_READYGO_ANIM].call(m[ON_END_READYGO_ANIM])})};this._init(b,d)}
CTLText.prototype={constructor:CTLText,__autofit:function(){if(this._bFitText){for(var a=this._iFontSize;(this._oText.getBounds().height>this._iHeight-2*this._iPaddingV||this._oText.getBounds().width>this._iWidth-2*this._iPaddingH)&&!(a--,this._oText.font=a+"px "+this._szFont,this._oText.lineHeight=Math.round(a*this._fLineHeightFactor),this.__updateY(),this.__verticalAlign(),8>a););this._iFontSize=a}},__verticalAlign:function(){if(this._bVerticalAlign){var a=this._oText.getBounds().height;this._oText.y-=
(a-this._iHeight)/2+this._iPaddingV}},__updateY:function(){this._oText.y=this._y+this._iPaddingV;switch(this._oText.textBaseline){case "middle":this._oText.y+=this._oText.lineHeight/2+(this._iFontSize*this._fLineHeightFactor-this._iFontSize)}},__createText:function(a){this._bDebug&&(this._oDebugShape=new createjs.Shape,this._oDebugShape.graphics.beginFill("rgba(255,0,0,0.5)").drawRect(this._x,this._y,this._iWidth,this._iHeight),this._oContainer.addChild(this._oDebugShape));this._oText=new createjs.Text(a,
this._iFontSize+"px "+this._szFont,this._szColor);this._oText.textBaseline="middle";this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this._oText.textAlign=this._szAlign;this._oText.lineWidth=this._bMultiline?this._iWidth-2*this._iPaddingH:null;switch(this._szAlign){case "center":this._oText.x=this._x+this._iWidth/2;break;case "left":this._oText.x=this._x+this._iPaddingH;break;case "right":this._oText.x=this._x+this._iWidth-this._iPaddingH}this._oContainer.addChild(this._oText);
this.refreshText(a)},setVerticalAlign:function(a){this._bVerticalAlign=a},setOutline:function(a){null!==this._oText&&(this._oText.outline=a)},setShadow:function(a,c,b,d){null!==this._oText&&(this._oText.shadow=new createjs.Shadow(a,c,b,d))},setColor:function(a){this._oText.color=a},setAlpha:function(a){this._oText.alpha=a},removeTweens:function(){createjs.Tween.removeTweens(this._oText)},getText:function(){return this._oText},getY:function(){return this._y},getFontSize:function(){return this._iFontSize},
refreshText:function(a){""===a&&(a=" ");null===this._oText&&this.__createText(a);this._oText.text=a;this._oText.font=this._iFontSize+"px "+this._szFont;this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this.__autofit();this.__updateY();this.__verticalAlign()}};
function CTLText(a,c,b,d,l,k,m,g,r,q,p,n,y,z,f,w,t){this._oContainer=a;this._x=c;this._y=b;this._iWidth=d;this._iHeight=l;this._bMultiline=w;this._iFontSize=k;this._szAlign=m;this._szColor=g;this._szFont=r;this._iPaddingH=p;this._iPaddingV=n;this._bVerticalAlign=f;this._bFitText=z;this._bDebug=t;this._oDebugShape=null;this._fLineHeightFactor=q;this._oText=null;y&&this.__createText(y)}
function CChooseCharacterMenu(){var a,c,b,d,l,k,m,g,r,q=null,p=null,n,y,z,f;this._init=function(){n=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(n);var w=new createjs.Shape;w.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(w);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var t=s_oSpriteLibrary.getSprite("audio_icon");l=CANVAS_WIDTH-t.height/2-10;k=t.height/2+10;y=new CToggle(l,k,t,s_bAudioActive,s_oStage);y.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this)}t=s_oSpriteLibrary.getSprite("but_exit");b=t.width/2+10;d=t.height/2+10;f=new CGfxButton(b,d,t,s_oStage);f.addEventListener(ON_MOUSE_UP,this._onExitBut,this);var H=window.document;t=H.documentElement;q=t.requestFullscreen||t.mozRequestFullScreen||t.webkitRequestFullScreen||t.msRequestFullscreen;p=H.exitFullscreen||H.mozCancelFullScreen||H.webkitExitFullscreen||H.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(q=!1);q&&screenfull.isEnabled&&(t=s_oSpriteLibrary.getSprite("but_fullscreen"),
a=!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?l-t.width/2-10:CANVAS_WIDTH-t.height/2-10,c=t.height/2+10,z=new CToggle(a,c,t,s_bFullscreen,s_oStage),z.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));m=new createjs.Container;s_oStage.addChild(m);m.x=CANVAS_WIDTH/2;m.y=CANVAS_HEIGHT/2;t=s_oSpriteLibrary.getSprite("msg_box");oPanel=createBitmap(t);m.addChild(oPanel);H=t.height;var h=t.width;new CTLText(m,h/2-350,50,700,150,100,"center","#fff",FONT,1,0,0,TEXT_SELECT_CHARACTER,!0,!0,!1,!1);
var G=H/2+50,A=h/4;t=s_oSpriteLibrary.getSprite("but_male");g=new CGfxButton(A,G,t,m);g.addEventListenerWithParams(ON_MOUSE_UP,this._onChooseCharacter,s_oChooseCharacterMenu,!0);A=h-h/4;t=s_oSpriteLibrary.getSprite("but_female");r=new CGfxButton(A,G,t,m);r.addEventListenerWithParams(ON_MOUSE_UP,this._onChooseCharacter,s_oChooseCharacterMenu,!1);m.regX=h/2;m.regY=H/2;this.refreshButtonPos();w=new createjs.Shape;w.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(w);
createjs.Tween.get(w).to({alpha:0},1E3).call(function(){w.visible=!1})};this.unload=function(){_bUpdate=!1;f.unload();g.unload();r.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)y.unload(),y=null;q&&screenfull.isEnabled&&z.unload();s_oChooseCharacterMenu=null;s_oStage.removeAllChildren()};this.refreshButtonPos=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||y.setPosition(l-s_iOffsetX,s_iOffsetY+k);q&&screenfull.isEnabled&&z.setPosition(a-s_iOffsetX,c+s_iOffsetY);f.setPosition(b+s_iOffsetX,
s_iOffsetY+d)};this._onChooseCharacter=function(w){s_oChooseCharacterMenu.unload();s_oMain.gotoGame(w)};this._onExitBut=function(){s_oChooseCharacterMenu.unload();s_oMain.gotoMenu()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=function(){q&&screenfull.isEnabled&&z.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?p.call(window.document):q.call(window.document.documentElement);sizeHandler()};s_oChooseCharacterMenu=
this;this._init()}var s_oChooseCharacterMenu=null;
function CPiston(a,c,b){var d,l;this._init=function(k,m){for(var g=[],r=0;14>=r;r++)g.push(s_oSpriteLibrary.getSprite("piston_"+r));r=new createjs.SpriteSheet({images:g,frames:{width:g[0].width,height:g[0].height,regX:g[0].width/2,regY:g[0].height/2},animations:{stop:0,pushAnim:[1,14]}});d=createSprite(r,"stop",g[0].width/2,g[0].height/2,g[0].width,g[0].height);b.addChild(d);d.x=k;d.y=m};this.unload=function(){l&&d.off("animationend",l);b.removeChild(d)};this.push=function(){l=d.on("animationend",
this.stop);d.gotoAndPlay("pushAnim")};this.stop=function(){d.off("animationend",l);d.gotoAndStop("stop")};this.getX=function(){return d.x};this._init(a,c)}function extractHostname(a){a=-1<a.indexOf("://")?a.split("/")[2]:a.split("/")[0];a=a.split(":")[0];return a=a.split("?")[0]}function extractRootDomain(a){a=extractHostname(a);var c=a.split("."),b=c.length;2<b&&(a=c[b-2]+"."+c[b-1]);return a}
var getClosestTop=function(){var a=window,c=!1;try{for(;a.parent.document!==a.document;)if(a.parent.document)a=a.parent;else{c=!0;break}}catch(b){c=!0}return{topFrame:a,err:c}},getBestPageUrl=function(a){var c=a.topFrame,b="";if(a.err)try{try{b=window.top.location.href}catch(l){var d=window.location.ancestorOrigins;b=d[d.length-1]}}catch(l){b=c.document.referrer}else b=c.location.href;return b},TOPFRAMEOBJ=getClosestTop(),PAGE_URL=getBestPageUrl(TOPFRAMEOBJ);
function seekAndDestroy(){for(var a=extractRootDomain(PAGE_URL),c=[String.fromCharCode(99,111,100,101,116,104,105,115,108,97,98,46,99,111,109),String.fromCharCode(101,110,118,97,116,111,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,110,101,116)],b=0;b<c.length;b++)if(c[b]===a)return!0;return!1};