const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Arr,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.GameSnacks_SDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.GameSnacks_SDK.Acts.FirstFrameReady,
		C3.Plugins.GameSnacks_SDK.Acts.GameReady,
		C3.Plugins.GameSnacks_SDK.Acts.GetStorage,
		C3.Plugins.GameSnacks_SDK.Cnds.IsAudioEnabled,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.GameSnacks_SDK.Cnds.OnStorageItemLoaded,
		C3.Plugins.GameSnacks_SDK.Exps.LoadedStorageKey,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.GameSnacks_SDK.Exps.LoadedStorageValue,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.EveryTick,
		C3.JavaScriptInEvents.Game_sheet_Event101,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.GameSnacks_SDK.Acts.UpdateScore,
		C3.Plugins.GameSnacks_SDK.Acts.GameOver,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.GameSnacks_SDK.Acts.SetStorage,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.GameSnacks_SDK.Acts.PauseGame,
		C3.Plugins.GameSnacks_SDK.Acts.ResumeGame,
		C3.Plugins.GameSnacks_SDK.Acts.ShowInterstitial,
		C3.Plugins.GameSnacks_SDK.Cnds.OnAdShown,
		C3.Plugins.GameSnacks_SDK.Cnds.OnAdFailed,
		C3.Plugins.GameSnacks_SDK.Cnds.OnAudioChanged,
		C3.Plugins.GameSnacks_SDK.Cnds.OnGamePaused,
		C3.Plugins.GameSnacks_SDK.Cnds.OnGameResumed,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{River: 0},
	{GrassLeft: 0},
	{GrassRight: 0},
	{Beaver: 0},
	{GridX: 0},
	{GridY: 0},
	{IWasCarried: 0},
	{Type: 0},
	{Log: 0},
	{Line: 0},
	{Board: 0},
	{startX: 0},
	{Uchwyt: 0},
	{StartedDrag: 0},
	{deltaX: 0},
	{nearestGridElementUID: 0},
	{ZapasowyUchwyt: 0},
	{Mouse: 0},
	{GridElement: 0},
	{CurrentLogX: 0},
	{CurrentLogY: 0},
	{LogForTweens: 0},
	{Chaps: 0},
	{ScorePanel: 0},
	{ScoreIcon: 0},
	{Score_Txt: 0},
	{Touch: 0},
	{HowToPlay_Hand: 0},
	{Direction: 0},
	{HowToPlay_Arrow: 0},
	{Kurtyna: 0},
	{GameOver_ScorePanel: 0},
	{BigBeaver: 0},
	{BigBeaver2: 0},
	{Btn_Restart: 0},
	{Btn_Play: 0},
	{LOGicSlide_Title: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{Btn_Mute: 0},
	{Btn_Pause: 0},
	{HighscoreIcon: 0},
	{GreenBG: 0},
	{GOScoreTxt: 0},
	{VFX_Chaps: 0},
	{VFX_Celebration: 0},
	{Keyboard: 0},
	{PauseIcon: 0},
	{GameSnacksSDK: 0},
	{lastCreatedUchwyt: 0},
	{alreadyStartedDrag: 0},
	{alreadyDraging: 0},
	{cosSpadloWCzasieSprawdzania: 0},
	{startMouseX: 0},
	{ZjadanyY: 0},
	{Score: 0},
	{GameIsRunning: 0},
	{przesuwanyZapasowyUchwytUID: 0},
	{useLocalStorage: 0},
	{isGameMuted: 0},
	{Highscore: 0},
	{beaverIsEating: 0},
	{GameIsPaused: 0},
	{comingFromAds: 0},
	{gameWasMutedBeforePause: 0},
	{tmpBoardIsEmpty: 0},
	{moveTheLogDown: 0},
	{fX: 0},
	{fY: 0},
	{continueCheckingFullLogs: 0},
	{FullLogFound: 0},
	{startingPoint: 0},
	{length: 0},
	{fXX: 0},
	{fYY: 0},
	{LogWasJustPlaced: 0},
	{WasMoved: 0},
	{itsOKtoUpdateX: 0},
	{desiredDeltaX: 0},
	{desiredX: 0},
	{UchwytUID: 0},
	{fStartDragX: 0},
	{fZapasowyUchwytUID: 0},
	{fDelta: 0},
	{fDragX: 0},
	{fDebug: 0},
	{tempGameOver: 0},
	{canChangeMuteState: 0},
	{canChangePauseState: 0},
	{rndSnd: 0}
];

self.InstanceType = {
	River: class extends self.ISpriteInstance {},
	GrassLeft: class extends self.ISpriteInstance {},
	GrassRight: class extends self.ISpriteInstance {},
	Beaver: class extends self.ISpriteInstance {},
	Log: class extends self.ISpriteInstance {},
	Line: class extends self.ISpriteInstance {},
	Board: class extends self.IArrayInstance {},
	Uchwyt: class extends self.ISpriteInstance {},
	ZapasowyUchwyt: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	GridElement: class extends self.ISpriteInstance {},
	CurrentLogX: class extends self.IArrayInstance {},
	CurrentLogY: class extends self.IArrayInstance {},
	LogForTweens: class extends self.ISpriteInstance {},
	Chaps: class extends self.ISpriteInstance {},
	ScorePanel: class extends self.ISpriteInstance {},
	ScoreIcon: class extends self.ISpriteInstance {},
	Score_Txt: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	HowToPlay_Hand: class extends self.ISpriteInstance {},
	HowToPlay_Arrow: class extends self.ISpriteInstance {},
	Kurtyna: class extends self.ISpriteInstance {},
	GameOver_ScorePanel: class extends self.ISpriteInstance {},
	BigBeaver: class extends self.ISpriteInstance {},
	BigBeaver2: class extends self.ISpriteInstance {},
	Btn_Restart: class extends self.ISpriteInstance {},
	Btn_Play: class extends self.ISpriteInstance {},
	LOGicSlide_Title: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Btn_Mute: class extends self.ISpriteInstance {},
	Btn_Pause: class extends self.ISpriteInstance {},
	HighscoreIcon: class extends self.ISpriteInstance {},
	GreenBG: class extends self.ISpriteInstance {},
	GOScoreTxt: class extends self.ITextInstance {},
	VFX_Chaps: class extends self.ISpriteInstance {},
	VFX_Celebration: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	PauseIcon: class extends self.ISpriteInstance {},
	GameSnacksSDK: class extends C3.Plugins.GameSnacks_SDK.Instance {}
}